### ISSUE TITLE
Philips Hue Still 3261348P7

### ISSUE THREAD

**Issue by meyland** [sebbebebbe/com.philips.hue.zigbee#10]
Hey
First thank you for your great job, I just bought a Philips Hue Still 3261348P7 do you think it's possible to make it connect?

**Comment by sebbebebbe** [comment]
Hi @meyland, plase send me a link to the Philips official page and i will have a look at adding it to the definitions.

**Comment by meyland** [comment]
Thank you
i hope this is good enough?
https://www.philips.co.uk/c-p/3261348P7/hue-white-ambiance-still-ceiling-light

**Comment by meyland** [comment]
https://www2.meethue.com/en-gb/p/hue-white-ambiance-still-ceiling-light/3261348P7/specifications

**Comment by sebbebebbe** [comment]
I have added it to the TODO for next release.

**Comment by meyland** [comment]
Thank you!

**Comment by JohanBendz** [comment]
@meyland
Can you please add the device as a generic Zigbee unit and get back to us with the info below?
Product ID:
Device ID:
Profile ID:

(bump)
