### ISSUE TITLE
[Request] Add support for Aurelle Panel Square

### ISSUE THREAD

**Issue by Blacksmit82** [sebbebebbe/com.philips.hue.zigbee#100]
Hi 
Could you please add support for Aurelle Panel Square?

Product ID:  LTC014
Device ID: 544
Profile ID: 49246

**Comment by JohanBendz** [comment]
Hi @Blacksmit82, I added it to our todo list.

**Comment by csejer** [comment]
I have the Aurelle Square (30x30 cm) and it identifies as this:

Product ID: LTC013
Device ID: 544
Profile ID: 49246

Could that be added as well?

**Comment by ThijsvanEssen** [comment]
Hi! It would be amazing if the circular (normal?) one could be added to! I saw the square one is already present :))

Product ID: LTC016
Service ID: 544
Profile ID: 4926

**Comment by sebbebebbe** [comment]
All are now added to my todo-list.

**Comment by Gemeni123** [comment]
@sebbebebbe 
It looks like all are similar models ...
LTC012, 015, 013, 016 are added in app.json under LTC015

013, 014 and 016 should be able to be added to that product array. Only thins is that they actually look different. Only way to manage that is to create seperate ID entries?

**Comment by sebbebebbe** [comment]
Yepp, different folders and drivers and so on. For the sake of getting support fast i bundled all the aurelle panels under one rectangular driver.

But you are free to rearrange them as you see fit :)

**Comment by Gemeni123** [comment]
Won't it break anything for the ones already using them in flows etc? Or will they only get nicer icons for the devices?

**Comment by sebbebebbe** [comment]
Added to the upcoming release. We might need to merge or split them depending on how it looks.
