### ISSUE TITLE
Motion sensitivity adjustment missing on Hue Outdoor Sensor

### ISSUE THREAD

**Issue by ghost** [sebbebebbe/com.philips.hue.zigbee#101]
The outdoor motion sensor is triggering ALL THE TIME, without any humans or animals in front of the sensor. In the Philips Hue mobile app it is possible to set the sensitivity on motion, but not in the Homey Philips Hue Zigbee app.
It makes the sensor useless for motion detection which is the main and sole purpose for me.

Please add possibility to change sensitivity on the motion sensor.

**Comment by sebbebebbe** [comment]
Hi, right now I can´t set any values with the current ZigBee implementation. I get no answer back at all from my lights, so I first need to sort out that issue. However I cannot currently put time into this project im afraid. If someone else with the knowledge out there is willing to pitch in, feel free to do so.

**Comment by antoniob10** [comment]
Hello. Does't work Outdoor Sensor. Motion alarm, temperature and luminance shows like "-".

**Comment by sebbebebbe** [comment]
Hi, please report to support@athom.com since the issue is in their ZigBee implementation.

There is no other logic for these devices in the app itself.

**Comment by 6zXo8aMn2TRXOs** [comment]
Think it would be nice if this issue could be reopened again? Think this would be an 'Enhancement'. Not saying that you should fix it, but maybe easier for someone else as well who could do a PR if the issue is open?
