### ISSUE TITLE
Hue motion sensor problem if meshing trough other Hue devices

### ISSUE THREAD

**Issue by Blacksmit82** [sebbebebbe/com.philips.hue.zigbee#102]
I have for some time had only a Hue motion sensor added with some Ikea devices, without problems or hangs. Then I added a bunch of Hue e27 bulbs. Right after that my motion sensor have started to hang all the time. I have then tested several things and looked at the zigbee mesh and the route the motion sensor takes.. 
It seems like for me that if the motion sensor takes a route via other Hue devices then it hangs, and if it directly connect to homey or via the Ikea devices then it works straight away.

Can this be the actual problem to this? That it is maybe meshing trough other Hue devices that is the actual problem with the motion sensor?

**Comment by 6zXo8aMn2TRXOs** [comment]
Sorry to say, but I guess not. I have three motion sensors and two outdoor motion sensors (none of them work). Four of them route through an Ikea bulb, the fifth through an Innr plug. See any patterns there, hehe?

**Comment by Blacksmit82** [comment]
Okey. Then it is probably just a coincidence that it suddenly worked for me for a time.
