### ISSUE TITLE
[Request] add hue adore series

### ISSUE THREAD

**Issue by dajojonl** [sebbebebbe/com.philips.hue.zigbee#103]
Please add hue adore series.
Ceilinglight 3435011P7 
ProductID LTC021 
DeviceID 544 
ProfileID 49246 
Network 0x0017...

4 white tints and dimming.

**Comment by dajojonl** [comment]
https://www.bol.com/nl/p/philips-hue-adore-plafondlamp-warm-tot-koelwit-licht-chroom/9200000097039931/

https://www.bol.com/nl/s/algemeen/zoekresultaten/Ntt/adore%2Bhue/N/0/Nty/1/search/true/searchType/qck/suggestedFor/adore/defaultSearchContext/media_all/index.html

**Comment by sebbebebbe** [comment]
Added to my todo-list.

**Comment by kof** [comment]
Just in case it's useful info, happy to provide anything you need or test it to get this lamp added.

![2019-09-01 10 22 25](https://user-images.githubusercontent.com/52824/64073756-74ed7c80-cca2-11e9-88c9-b33267001870.jpg)
