### ISSUE TITLE
After Homey 2.4 update philips app crashes

### ISSUE THREAD

**Issue by Mastersdt** [sebbebebbe/com.philips.hue.zigbee#104]
Hello, after the new homey update I don’t have response from the indoor hue sensors. And a lot of flows works with this sensors.😭

Is there any way to remedy that ?

**Comment by 6zXo8aMn2TRXOs** [comment]
Is the app really crashing or is it "just" the sensors which stop send values? If it is the latter, it is probably related to #61 which won't be fixed until Homey zigbee core update.

**Comment by Mastersdt** [comment]
It’s look like the sensors which stop send values. 
But if I want to reconnect the sensor It look like the app are freeze.

**Comment by sebbebebbe** [comment]
There is no logic in the app for the sensors, everything relies on Athom implementation. Please report to support@athom.com
