### ISSUE TITLE
[Request] support for Aurelle Panel Circular

### ISSUE THREAD

**Issue by ThijsvanEssen** [sebbebebbe/com.philips.hue.zigbee#105]
Hi! It would be amazing if the circular Aurelle Panel could be added too!

Product ID: LTC016
Service ID: 544
Profile ID: 4926

**Comment by sebbebebbe** [comment]
Added to my todo-list.

**Comment by sebbebebbe** [comment]
Will be included in next release, grouped together with the other rectangular aurelle panels
