### ISSUE TITLE
Support for Philips Hue Lucca

### ISSUE THREAD

**Issue by plavelle62** [sebbebebbe/com.philips.hue.zigbee#106]
Please add support for Philips Hue Lucca LED Smart Outdoor Garden Wall Lantern.

Thanks in advance,

**Comment by sebbebebbe** [comment]
Hi,

Please provide me with the ID:s for these devices so that i can add them.

**Comment by plavelle62** [comment]
Sebbe,

Apologises but where would I find this data?

Regards
Paul

**Comment by sebbebebbe** [comment]
Add the device as a generic zigbee device.
Go into devices and then on the device choose show properties.

//Sebastian

**Comment by plavelle62** [comment]
Here you go;

Product ID: LWW001

Device ID:256

Profile ID: 49246

Thanks.

**Comment by sebbebebbe** [comment]
Thx. Added to the TODO-list.

**Comment by sebbebebbe** [comment]
Will be included in the next release
