### ISSUE TITLE
Hue dimmer switch

### ISSUE THREAD

**Issue by Hirostil** [sebbebebbe/com.philips.hue.zigbee#107]
Hi,

I just bought 2 Hue dimmer switch (RWL021) and it doesn't work with any Flow :(

Do you have an idea?

My version is: 1.4.5
And my Homey (early 2019) is on: 2.5.1

Thanks

**Comment by sebbebebbe** [comment]
Hi,

This has been an issue for some users. Please report to support@athom.com because the issue is in their core libraries.

**Comment by Hirostil** [comment]
Hi,

Since update 2.5.2 it's works! 🙂

**Comment by Hirostil** [comment]
Hello,

After a power failure, it does not work anymore ☹️

**Comment by sebbebebbe** [comment]
Please report it to Athom, they need to know that their ZigBee implementation is not working properly.

**Comment by Hirostil** [comment]
They asked me to contact you...
I try again...
