### ISSUE TITLE
Hue GU10 not found

### ISSUE THREAD

**Issue by rgerr** [sebbebebbe/com.philips.hue.zigbee#108]
Hi, I tried to add this GU10 spot to Homey. It is being added, but as an unknown ZigBee device. Then it will only be able to turn on and off, no dimming functions.

http://i66.tinypic.com/mtwld3.jpg

**Comment by sebbebebbe** [comment]
Hi,
Image does not work, I need the model number inorder to add it.
Add as generic zigbee device and send the properties info.

**Comment by rgerr** [comment]
Not sure what you exactly need, I removed the GU10 from Homey and installed it as a generic ZigBee device. However, the information in properties does not change.

**Comment by sebbebebbe** [comment]
I can see the screenshot you linked now, the link didnt work yesterday.

You can just paste the image in Github.

There is another request for this device to be added.

**Comment by rgerr** [comment]
Alright, anything else you need from me then?

**Comment by rgerr** [comment]
Have you been able to implement this yet?

**Comment by sebbebebbe** [comment]
Hi, im sorry I have not been able to look at it and I do not knwo when I will be able to.

**Comment by sebbebebbe** [comment]
Added to dev branch. Will be included in next release.

**Comment by rgerr** [comment]
Thank you, when will the next release be?
