### ISSUE TITLE
Request adding LCG002   GU10 spot

### ISSUE THREAD

**Issue by zee-eend** [sebbebebbe/com.philips.hue.zigbee#109]
Hi,

Can someone please help to add the LCG002. It’s the new white&color gu10 with richer colors and perfect fit

Thanks in advance 🙃

**Comment by zee-eend** [comment]
Oh and why can’t I find anything at the zigbee alliance page about the LCG002?

**Comment by sebbebebbe** [comment]
I have this one on my list

**Comment by sebbebebbe** [comment]
Added to dev branch. Will be included in next release

**Comment by zee-eend** [comment]
Thank thanks thanks!!!! :D
