### ISSUE TITLE
[Request] Could you add the Philips Hue Beyond Pendant to the app

### ISSUE THREAD

**Issue by Marc1979** [sebbebebbe/com.philips.hue.zigbee#11]
Great app, running it for almost two weeks without any trouble. (exept the reset of the bulbs was a nightmare, but fixed that with a Hue dimmer)

Could you please add the Philips Hue Beyond Pendant to you're app (LLM001)?

**Comment by sebbebebbe** [comment]
Hi @Marc1979,

I have added it to my TODO list.

**Comment by JohanBendz** [comment]
Added in app v.1.4.0
