### ISSUE TITLE
Hue outdoor sensor

### ISSUE THREAD

**Issue by henkhuppelschoten** [sebbebebbe/com.philips.hue.zigbee#110]
Hi,

Often a signal from the Phillips Hue outdoor sensor won't be spotted by Homey.
The update frequentie is set to the minimum but a update of the sensor is several hours before now.

For example if its dark the outdoor sensor needs to turn te outdoor lights on. The sensor become's red (he spotted me) but the lights stay dark.
A look at homey tells me the last update on the sensor was 10 hours before.

**Comment by henrikrox** [comment]
#61
