### ISSUE TITLE
Would love to help with testing

### ISSUE THREAD

**Issue by kof** [sebbebebbe/com.philips.hue.zigbee#111]
I got these hue lamps and can help testing them:

Work as expected:
- Fair
- Still 

Isn't on the list, but works as a basic zigbee device:
- Adore

Is on the list but shows error (no compatible app) and adds it as a basic zigbee device:
- Cher

**Comment by sebbebebbe** [comment]
Adore will be added.

Can you provide me with the generic zigbee details for the Adore and Cher ones?
