### ISSUE TITLE
Hue white fair pendant is not recognised! Only as a basic zigbee device but the hue fair is recognised perfectly 

### ISSUE THREAD

**Issue by dimitrisraptis** [sebbebebbe/com.philips.hue.zigbee#113]

**Comment by sebbebebbe** [comment]
Will be identified in next release.

**Comment by ncickc** [comment]
When can we expect the next release?

**Comment by sebbebebbe** [comment]
I cannot give any estimates, but it has now been merged into dev and will be included in the upcoming release.
