### ISSUE TITLE
[Request] Support for Philips Hue Filament

### ISSUE THREAD

**Issue by Emile86** [sebbebebbe/com.philips.hue.zigbee#115]
Hi,
Is there any chance to add support for Philips Hue Filament lamps?

**Comment by sebbebebbe** [comment]
Hi,
Send me the generic zigbee device information and I will eventualy add it.

thx

**Comment by Emile86** [comment]
Product ID: LWA004
Device ID: 257
Profile ID: 260

Single Filament bulb A60 E27 (Zigbee and bluetooth versions)

Thanks in advance

**Comment by HarlandT** [comment]
Product ID: LWO001
Device ID: 257
Profile ID: 260

Philips Hue White Filament E27 BT and Zigbee  / G93

Thanks in advance!

**Comment by Gemeni123** [comment]
Did a pull request to add G93 based on above info. Tested ok on my homey and G93 :)

**Comment by HarlandT** [comment]
Is it coming a update? Or What does this mean?:)

**Comment by sebbebebbe** [comment]
Will be included in next release shortly.
