### ISSUE TITLE
Remove Dimmer

### ISSUE THREAD

**Issue by Radiotechniman** [sebbebebbe/com.philips.hue.zigbee#12]
For some reason my Dimmer is not "seen" after inclusion, yes I even restarted
I thought to exclude and try again but there is no way to exclude the DImmer..

**Comment by sebbebebbe** [comment]
Hi @Radiotechniman,
I have had some reports of devices not wanting to be deleted from the mesh. One last resort might be to reset entire mesh and add everything again.

Do you have other ZigBee devices connected to your Homey than Philips Hue?

**Comment by Radiotechniman** [comment]
Hi @sebbebebbe 
Yes I have multiple Aqara sensors as well, so resetting is not really an option..

**Comment by sebbebebbe** [comment]
Hi again @Radiotechniman,

I have these sensors aswell, although no problem with my dimmer switches.
Please send me you app logfile go to Settings -> Apps, then press Alt button and hover over the App names until a button appears.

Thanks

**Comment by Radiotechniman** [comment]
thanks @sebbebebbe i've had some issues with homey and had to restart several times 
the dimmer is gone now but I plan to add it at one point (since I want to get rid of the Hue app) 
If it happens again i'll send you a log file
