### ISSUE TITLE
Add Philips Hue LTC012 lamp

### ISSUE THREAD

**Issue by vmswtje** [sebbebebbe/com.philips.hue.zigbee#13]
Is it possible to request support for the LTC012 lamp?

I've already purchased/installed the lamp, but it's now an "Unknown ZigBee device". It can only turn on and off using Homey, but it isn't possible to use the dimming functions nor different white/yellow-colours that this lamp (led strip) supports. In case I can help by providing data and/or test your software, please let me know.

https://www2.meethue.com/en-gb/p/connected-luminaires-white-ambiance-struana-ceiling-light/3306431P7

**Comment by sebbebebbe** [comment]
Should be possible, im adding it to the list.

**Comment by JohanBendz** [comment]
@vmswtje Can you please add below information to your request?
Manufacturer ID:
Product ID:
Device ID:
Profile  ID:

**Comment by vmswtje** [comment]
Hi! Thanks for your follow-up!!!

Manufacturer ID: Philips
Product ID: LTC012
Device ID: 544
Profile ID: 49246

As for now, shows up as "Unknown ZigBee device" (Z-wave device)

I'm quite sure it has (almost) the same options as the:
Philips Hue Being Ceiling Lamp
(Philips Hue Fair Ceiling Lamp)

**Comment by JohanBendz** [comment]
Added to app v1.4.4

**Comment by vmswtje** [comment]
Thank you very much for your efforts! It seems to work and I'm very happy with this new device in Homey :)
