### ISSUE TITLE
hue being/ ambiaance

### ISSUE THREAD

**Issue by axelne** [sebbebebbe/com.philips.hue.zigbee#134]
Hue being/ambiance pendant not included in device list.

https://www.webhallen.com/se/product/287755-Philips-Hue-Being-Ambiance-Pendant-Aluminium

**Comment by Goliath2000** [comment]
Is the philips hue being pendant not supported!? 
I’m planning to buy that lamp!

**Comment by Goliath2000** [comment]
Hue being ceiling lamp is on the other hand in the support list, but isn’t this the same lamp as being pendant?

**Comment by sebbebebbe** [comment]
Please add the id and modelnumber so that it can be added.

Add as Generic ZigBee device and go to properties for the device to find the information.

**Comment by JohanBendz** [comment]
Without Generic Zigbee device info we are unable to add a new device, will close this request.
