### ISSUE TITLE
Support philips smart plug Bluetooth/zigbee EU

### ISSUE THREAD

**Issue by KrakenTyio** [sebbebebbe/com.philips.hue.zigbee#137]
PLS add support EU Philips smart plug bluetooth/zigbee

https://homekitnews.com/2019/09/15/philips-hue-smart-plug-eu-version-review/

Manufacture id: Philips
Product id: LOM002
Device id: 266
Profile id: 260

Thx

**Comment by sebbebebbe** [comment]
Will be included in v1.4.7 release.
