### ISSUE TITLE
Philips Filament Bulb ST64 E27

### ISSUE THREAD

**Issue by lenwar** [sebbebebbe/com.philips.hue.zigbee#138]
Hi,

Can you please add support for the Philips Filament Bulb ST64 E27
I tried adding it as another Filament bulb, but it shows as a generic Zigbee device.

Product ID is LWV001

**Comment by KrakenTyio** [comment]
Perform pls:
Product ID: xyz
Device ID: xyz
Profile ID: xyz

**Comment by lenwar** [comment]
Product ID LWV001
Device ID 257
Profile ID 260

**Comment by jeroendew** [comment]
I would love to see this supported as well :-)

**Comment by sebbebebbe** [comment]
Will be included in v1.4.7
