### ISSUE TITLE
Adding a lamp

### ISSUE THREAD

**Issue by dkduck** [sebbebebbe/com.philips.hue.zigbee#14]
A litlle request for adding this Hue lamp and thanks in Advance: Philips Hue - Connected Being 

https://www2.meethue.com/da-dk/p/hue-white-ambiance-being-loftslys/3261048P7

Regards
Erik

**Comment by sebbebebbe** [comment]
@dkduck 

It is already in the TODO list.

**Comment by dkduck** [comment]
Hi Sebastian

Ok, sounds great, but I don´t see the icon for the lamp model when I try
add it?

Thanks in advance
Erik

2018-05-07 11:34 GMT+02:00 Sebastian Johansson <notifications@github.com>:

**Comment by sebbebebbe** [comment]
@dkduck 

Sorry, I didn´t specify which list at first when commenting.
I have added it to my TODO List.

//Sebastian

**Comment by dkduck** [comment]
That´s OK :-)

Sounds great Sebastian, looking forward to hopefully a fast add ;-)
If you need info at any kind, just let me know.

//Erik

2018-05-07 12:46 GMT+02:00 Sebastian Johansson <notifications@github.com>:

**Comment by dkduck** [comment]
Any ETA hopefully :-)

**Comment by sebbebebbe** [comment]
Hi @dkduck, as i have mentioned before i have no ETA at present.

**Comment by JohanBendz** [comment]
Added to app v.1.4.0
