### ISSUE TITLE
Philips Hue Fugato Support

### ISSUE THREAD

**Issue by ChappIO** [sebbebebbe/com.philips.hue.zigbee#140]
I bought new hue lamps without checking the compatibility with your app (since everything has just been working out-of-the-box, nice job!). But this time the lamps were not recognised.

I am talking about the Philips Hue Fugato. Here is some information:

**Product Info**
https://www2.meethue.com/nl-nl/p/hue-white-and-color-ambiance-fugato-2-lichts-spotbalk/5063231P7

**Zigbee Info**
Manufacturer ID: Philips
Product ID: 5063230P7
Device ID: 269
Profile ID: 260

The lamps should support color and white, so I'd expect similar capabilities as the regular E28 bulbs with color support.

Is there anything I can do to help you? (I am a dev myself.)

**Comment by Sjnaaf** [comment]
@ChappIO I will try to add support for this one as well when I will be adding support for other lamps as well. In the meantime you could take a look at PR #135 to see what is necessary to add support for a certain type of lamp.

**Comment by JohanBendz** [comment]
Now in test version.
https://homey.app/sv-se/app/com.philips.hue.zigbee/Philips-Hue-ZigBee/test/
