### ISSUE TITLE
Support Homey v3.0 energy consumption estimates

### ISSUE THREAD

**Issue by DiedB** [sebbebebbe/com.philips.hue.zigbee#141]
Homey v3.0 supports energy measurements. For most lights, this can be added to `app.json` as an estimation based on standby power and power consumption at 100%. 

https://apps.developer.athom.com/tutorial-Drivers-Energy.html

Most power consumption figures can be found in Philips product brochures.

**Comment by sebbebebbe** [comment]
This has been added and will be included inte the upcoming release.
