### ISSUE TITLE
Hue Go LCT026 not recognized to Philips hue zigbee app

### ISSUE THREAD

**Issue by jeroenvano** [sebbebebbe/com.philips.hue.zigbee#142]
Adding the Hue Go LCT026 lamp results in an error that no app has been found for this device. Results in added as a simple zigbee device, only on and off.

**Comment by Sjuul70** [comment]
Same here. Product ID: LCT026, Device ID: 269, Profile ID: 260. Could it be added to the app?

**Comment by Sjnaaf** [comment]
@Sjuul70 Unfortunately I don't own these types of lamps. Could you provide links to a webshop for the LCT026 so I have a visual representation and full specs of the capabilities of these type of lamps? Then I will add them

**Comment by jeroenvano** [comment]
Hi Patrick,

See
https://www.bol.com/nl/p/philips-hue-go-tafellamp-white-and-color-ambiance-v2-bluetooth/9200000117474511/


It is the new version of the Hue Go so I would imagine the same capacity as
the current Hue Go supported in your app. Difference is that the new
version also has bluetooth enabled but that is not needed in your zigbee
driven app.

Regards,
Jeroen

Op do 5 dec. 2019 13:02 schreef Patrick Savelberg <notifications@github.com

**Comment by Sjuul70** [comment]
[ODLI20170713-001-UPD-en_AA-hue-go-emea.pdf](https://github.com/sebbebebbe/com.philips.hue.zigbee/files/3932244/ODLI20170713-001-UPD-en_AA-hue-go-emea.pdf)

**Comment by Sjuul70** [comment]
Hi Patrick, 
Quick start manual. Describes all the capabilities of the Hue Go.
Regards,
Julian

**Comment by sebbebebbe** [comment]
This device will be added in the next release.
