### ISSUE TITLE
Philips hue signe floor lamp

### ISSUE THREAD

**Issue by Goliath2000** [sebbebebbe/com.philips.hue.zigbee#144]
Hi.

It seems that this philips hue signe floor lamp is not supported. Any plans to implement this?

https://www2.meethue.com/en-us/p/hue-white-and-color-ambiance-signe-floor-light/4080248U7

**Comment by Sjnaaf** [comment]
@Goliath2000 please add the device as a simple zigbee and go into the advanced config of this added device and post details here (Producent ID, Product ID, Apparaat ID, Profiel ID) so they can be added as well.

Product ID: xyz
Device ID: xyz
Profile ID: xyz

**Comment by Kvasy123** [comment]
> Product ID: LCF003
> Device ID: 528
> Profile ID: 49246

Here u go @sebbebebbe @Schnaaf

**Comment by JohanBendz** [comment]
Thanks @Kvasy123, added to list of devices to be added.

**Comment by JohanBendz** [comment]
https://github.com/sebbebebbe/com.philips.hue.zigbee/issues/174
