### ISSUE TITLE
Hue Dimmer switches non-functional - Homey 3.1.0 app version 1.4.6

### ISSUE THREAD

**Issue by DocAliS** [sebbebebbe/com.philips.hue.zigbee#147]
Hi there,

I'm running, four Hue Dimmer switches on 4 groups of LifX downlights without any issues for the past 8 months but ever since upgrading to 3.1 it seems remotes and button presses trigger no actions or flows anymore.

I've tried it all.. rebooting, restarting Homey and apps. If adding remotes via Hue hub and then to homey, desired flows work but with a huge delay compared with previously.

I've concluded the app, running v1.4.6 btw, somehow isn't registering input since Homey firmware version 3.1.0.

I'd be extremely grateful if somebody with know-how investigated and solved the issue.

Thanks 🙏

**Comment by sebbebebbe** [comment]
Hi this is however a known issue with the dimmers, for alot of people including myself they work fine. Let´s wait for the zigbee rewrite and see if it helps.
