### ISSUE TITLE
Motion Sensor Default min report interval

### ISSUE THREAD

**Issue by mapulu** [sebbebebbe/com.philips.hue.zigbee#148]
Hello,

I think the default min Report Interval for motion (s) is to low. Other zigbee hubs use at least 5 seconds (also the hue hub?)
When I leave the default settings it hangs up and does not report anymore after a short time.
If I set the report min report interval for motion to 10 seconds it works well.
I think no one needs such a low report interval and it cause trouble so I would recommend to set the default min motion report value to 10 s or something like that.

**Comment by sebbebebbe** [comment]
Thx for the input. We can try and raise the interval and see if the motion sensor failure reports dissapear.
