### ISSUE TITLE
Hue Motion

### ISSUE THREAD

**Issue by HenricAsk** [sebbebebbe/com.philips.hue.zigbee#149]
Hi

I added a second Homey to my house and now my Hue Motions stopped working.
I have tried to exclude them then include them again. Then they work for a couple of hours (max) then they stops working again. They works fine if I include them in the Hue Bridge but I want them connected directly to Homey (less delay). Is there something that interferes when using 2 or more Homeys?
Other Zigbee devices are working fine.

Homey version: 3.1.0
App version: 1.4.6

**Comment by sebbebebbe** [comment]
This is a known issue with Athoms ZigBee implementation. There is no code inte the app for the sensors more than settings and registering the listeners.
