### ISSUE TITLE
Feature request: harmonized random color.

### ISSUE THREAD

**Issue by gvdijnsen** [sebbebebbe/com.philips.hue.zigbee#15]
I found a action card that sets my lamp to a random color which is great, but it sets every lamp to a different color when called. It would be nice to have some kind of global randomized color that changes with a set frequency or for which a color change can be triggered and possibly an accompanying trigger so that the color of all lamps in the house can be harmonized.

A way to set a lamp to an rgb value in a variable could also work, so it can be programmed by a user using some flows or a script of course, but I have not been able to find out how to do this yet...

**Comment by sebbebebbe** [comment]
I have solved this personally by creating a flow that syncs all lamps with the same color and dim level. Would that solve your problem?

**Comment by gvdijnsen** [comment]
Perhaps, but only if it can the color en dim level are not hard coded, since I want to set a level throughout the house and then when change it all the lights should follow... Dint find how to do that yet.

**Comment by sebbebebbe** [comment]
Ah ok for the whole house it would be a bit cumbersome. I have 1 lamp that has 3 A19 bulbs, where i set a variable when one of the lamps start and then I have a flow that triggers when changing the variable. That variable then sets the other two lights temperature.

**Comment by sebbebebbe** [comment]
I have added this function to my list of added features, however i have not had any luck with communicating with my devices at all. Might give it another go soon.
