### ISSUE TITLE
Turn off Hue motion sensor LED

### ISSUE THREAD

**Issue by 6zXo8aMn2TRXOs** [sebbebebbe/com.philips.hue.zigbee#151]
Hello Sebastian! Know that you are busy with life.

Anyway, do you think it would be possible to turn off the red light when the motion sensor detects motion (and the bridge cannot be reached)? 

Obviously they solved for zigbee2mqtt like this https://github.com/Koenkk/zigbee2mqtt/issues/897#issuecomment-536764802 . Don't know if anything similar would be possible with Homey?

**Comment by sebbebebbe** [comment]
I will have a look at it some time, i have issues with issuing commands to the zigbee devices overall. The devices does not seem to answer when i send on off messages. Will have a look at it again eventually.

**Comment by 6zXo8aMn2TRXOs** [comment]
@JohanBendz Would it be possible that you'd have a look on this? Know that you are busy with all your apps, but this is a deal breaker for me moving my Hue motion sensors to Homey, getting rid of the bridge. Like mentioned in https://github.com/JohanBendz/com.philips.hue.zigbee/issues/151#issue-532314466 it was solved in zigbee2mqtt with posting a reply to the sensor, in some way.

**Comment by JohanBendz** [comment]
Hi @rindlerblabla What firmware do you use? On firmware 5 / app version 2.0.14 my sensors do not blink the LED.

**Comment by 6zXo8aMn2TRXOs** [comment]
Ah, cool! I am still on 4.2. Think I am still waiting for stable. Closing this issue then!
