### ISSUE TITLE
Can you add the Natural Dynamic Effects to the Hue Go?

### ISSUE THREAD

**Issue by Jansrt** [sebbebebbe/com.philips.hue.zigbee#16]
Can you add the Natural Dynamic Effects to the Hue Go?

**Comment by sebbebebbe** [comment]
Im not sure if this is something that the current implementation of ZigBee for Homey supports.

**Comment by Jansrt** [comment]
OK. Thanks. It would be nice to have though.

**Comment by Jansrt** [comment]
OK. Thanks. It would be nice to have though.
