### ISSUE TITLE
Hue Smart plug with different produkt id

### ISSUE THREAD

**Issue by iamberg** [sebbebebbe/com.philips.hue.zigbee#162]
Hi, 
It appears that Hue Smart Plug might have both LOM001 and LOM002 as Product ID:
![Screenshot_20191222-171457](https://user-images.githubusercontent.com/46677534/71325348-cfc61080-24eb-11ea-8ba8-6b564ceb17e7.jpg)

Could you include that one too?

**Comment by jacobalexanderkarlsson** [comment]
Would love support for this one too

**Comment by kingofkobjer** [comment]
Please add support for LOM001

**Comment by kingofkobjer** [comment]
patch available but I don't have access to push and create pull request.

```
commit 339ffa252eac5a6f4490a7d77ce634588e05f2d7 (HEAD -> dev)
Author: kingofkobjer <kingofkobjer@gmail.com>
Date:   Fri Mar 20 16:45:32 2020 +0100

    Bug fix #162:Hue Smart plug with different produkt id

diff --git app.json app.json
index 28857e1..b9f26b7 100644
--- app.json
+++ app.json
@@ -212,7 +212,7 @@
       },
       "zigbee": {
         "manufacturerName": "Philips",
-        "productId": "LOM002",
+        "productId": ["LOM001", "LOM002"],
         "deviceId": 266,
         "profileId": 260,
         "learnmode": {

```

**Comment by JohanBendz** [comment]
Thanks, will add on next update.

**Comment by cyppe** [comment]
Hi, when will you do official release with this change? In the homey app store it's still 1.4.9 that seems a bit old. Thanks!

**Comment by JohanBendz** [comment]
Hi @cyppe, next live version will be released when Homey firmware v5 has been released.
