### ISSUE TITLE
Support Hue Econic light #93 (reopen?)

### ISSUE THREAD

**Issue by RonaldNeed** [sebbebebbe/com.philips.hue.zigbee#163]
Hi, I tried to connect (pairs) my new ordered Philips Hue Econic(s) (4x). Unfortunately, the only that  is working is a basic Zigbee device. (all my other hue devices are working perfectly with your app. Thanks for that.
Following your proposal for a request for a new hue device here is the information”
Producer: Philips
Product ID: 1743830P7
Device ID 269
Profile ID 260
Note  issue #93 is  a request for the same device. The product id is different: 174383oP7 the last 0 is an o. typo?
Hopefully you can add this device.
Regards,
Ronald

**Comment by JohanBendz** [comment]
Hi @RonaldNeed, the device in the app have the correct Product ID with a 0 (not a o).
Your Device ID and Profile ID is however totally different. Is this the information you got when adding your device as a generic Zigbee unit?

Looks like your info can be correct and the current is wrong.. wonder if this have ever worked for anyone...

**Comment by RonaldNeed** [comment]
Hi @JohanBendz, thanks for your reply. 
Today I checked again the ProductID, DeviceID and ProfileIDs. Two Philips Hue Econic devices I removed and added to the system. They again working as basic Zigbee devices with the above-mentioned profile. Basic functions are working (On|Off) as basic ZigBee device. I checked on all lights the ProductID = 1743830P7, DeviceID = 269 and ProfileID = 260. on all 4 of them.

Furthermore, I like to contribute on this App. Testing devices, code reading, other help, if needed.

**Comment by JohanBendz** [comment]
Hi again @RonaldNeed.
I have corrected the info in the app and released a test version.
https://homey.app/sv-se/app/com.philips.hue.zigbee/Philips-Hue-ZigBee/test/

I would be very happy if you can test it and get back to me with your findings! :)

**Comment by RonaldNeed** [comment]
Hello Johan Bendz,

 

To be short: it works great!

 

I was not able to do the test earlier unfortunately. But today I tried the Philips-Hue-ZigBee/test/ Version 1.5.7. 

Thanks for the work! It’s wonderful Hue devices working with Homey.

If I can help with other devices on Hue or testing, I’m here to help. Let me know.

 

Regards,

Ronald Need

 

 

 

Van: Johan Bendz <notifications@github.com> 
Verzonden: zaterdag 16 mei 2020 16:21
Aan: sebbebebbe/com.philips.hue.zigbee <com.philips.hue.zigbee@noreply.github.com>
CC: RonaldNeed <ronaldneed@icloud.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [sebbebebbe/com.philips.hue.zigbee] Support Hue Econic light #93 (reopen?) (#163)

 

Hi again @RonaldNeed <https://github.com/RonaldNeed> .
I have corrected the info in the app and released a test version.
https://homey.app/sv-se/app/com.philips.hue.zigbee/Philips-Hue-ZigBee/test/

I would be very happy if you can test it and get back to me with your findings! :)

**Comment by JohanBendz** [comment]
Great, thanks for letting me know :)
