### ISSUE TITLE
New Typ Gu10 color ambiance to add. 

### ISSUE THREAD

**Issue by Pim65** [sebbebebbe/com.philips.hue.zigbee#166]
Hi Sebastian,

Can you please add the latest gu10 type ambiance colour Bluetooth bulb to Homey ?

The product ID is LCG002
The rest I can not find as I can not add it to homey. 

Can you work with this? 

![15793845366593118377086045553058](https://user-images.githubusercontent.com/40526333/72671115-cb870780-3a45-11ea-964e-8f648fd26c02.jpg)
Thanks!

**Comment by JohanBendz** [comment]
Hi @Pim65, are you able to add it to Hoemy as a generic device and post the Zigbee Info?

Manufacturer ID: Philips
Product ID: 
Device ID: 
Profile ID:

**Comment by Pim65** [comment]
Hi, it is seen as a screen, I use 3T motors and bought them. On ebay.
They work fantastic with the Brel app and homey

Pim

________________________________

**Comment by Pim65** [comment]
It is a 433 MHz application by the way

Pim

________________________________

**Comment by JohanBendz** [comment]
OK, I have added it to our to do list. Same request as https://github.com/sebbebebbe/com.philips.hue.zigbee/issues/182.

**Comment by Pim65** [comment]
Hi,



I can't add it as a generic zigbee device in homey...
The device ID is LCG002 the rest I can't give you.

Can you work with that?

My homey is on V5rc34 and the philips app is the experimental version.

**Comment by Pim65** [comment]
At least it is not visible as Icon with BT in the experimental app on homey

**Comment by JohanBendz** [comment]
Hi @Pim65. If you are unable to pair it with Homey as a generic Zigbee device the problem is not in the app but in the device or Homey core. Athom is currently looking into an issue with pairing.

If you can pair the device as generic but not as a device under the app I would like to get the data from an interview sent to me in mail or pm.

**Comment by Pim65** [comment]
Hi Johan,

I contacted Athom and they adviced to reset the zigbee and add routers first.
So I did.
Works flawless now.
The only thing a bit confusing is that the gu10 ambiance color BT is not showing in the app, but you need to use the E27 button.

Now u know and I can work with that.

Thanks!

Pim

________________________________

**Comment by Pim65** [comment]
Hi Johan,

What i am very much missing is the option "start colorloop" in Homey
Something I could do using the philips HUB app but not in yours.

Maybe something to think about and add.

Many thanks by the way for your contribution!!

Pim

________________________________
Van: pim ooms <pim.ooms@hotmail.com>
Verzonden: donderdag 15 oktober 2020 07:36
Aan: JohanBendz/com.philips.hue.zigbee <com.philips.hue.zigbee@noreply.github.com>; JohanBendz/com.philips.hue.zigbee <reply@reply.github.com>
CC: Mention <mention@noreply.github.com>
Onderwerp: Re: [JohanBendz/com.philips.hue.zigbee] New Typ Gu10 color ambiance to add. (#166)

Hi Johan,

I contacted Athom and they adviced to reset the zigbee and add routers first.
So I did.
Works flawless now.
The only thing a bit confusing is that the gu10 ambiance color BT is not showing in the app, but you need to use the E27 button.

Now u know and I can work with that.

Thanks!

Pim

________________________________

**Comment by JohanBendz** [comment]
Hi @Pim65, good to hear you got it working.
Thanks for your request, I have color loop on my todo list. :)
