### ISSUE TITLE
Hue dimmer switch battery level

### ISSUE THREAD

**Issue by zsoltharkay** [sebbebebbe/com.philips.hue.zigbee#168]
Hi,
Battery status of Hue dimmer switch device can not be seen.
Please add battery status for Hue dimmer switch devices, as well.

**Comment by JohanBendz** [comment]
Hi and thanks for your request, I will look into if this can be done and if so add the function to the app.

**Comment by JohanBendz** [comment]
Battery information will be added to the firmware v5 version of the app.
