### ISSUE TITLE
Change colour using HTML values?

### ISSUE THREAD

**Issue by matt20v** [sebbebebbe/com.philips.hue.zigbee#169]
Hi I have been trying to work out of there is a way to enable the feature where we could put a HTML value in as the colour rather then using the colour Selection wheel like we used to ? 

I can’t remember how many versions ago this was enabled but it used to make setting the exact colour across multiple devices much easier. 

As below we now have the wheel where as before we had a value generated when you selected the colour which you could copy to other devices. 
![799D7ED7-9FC0-4354-AF1F-4D6892F32291](https://user-images.githubusercontent.com/31461639/73872049-15277d00-48a3-11ea-89cc-7bf8ad3e391f.png)

Thanks !

**Comment by JohanBendz** [comment]
Hi @matt20v, this is sadly not possible after the change to the new color wheel. (I too miss it :( )

**Comment by matt20v** [comment]
@JohanBendz  Thank you for the confirmation, That is very unfortunate as it did seem much easier to be able to get consistent colours across all devices.

If any one see this and has a way to easily set the same custom colours across multiple devices please do let me know.

Thanks!

**Comment by JohanBendz** [comment]
@matt20v You can use Homeyscript to achieve that, but it takes a bit of work to set up and manage.

**Comment by matt20v** [comment]
@JohanBendz  thank you for the information. It does sound like a lot more work and i am no coder :).. I will try and look into how this could be setup. 

Thanks again i do appreciate the information!

**Comment by JohanBendz** [comment]
@matt20v Sometimes the brain is stuck in a pattern.. I was stuck at html.. and forgot that you can solve your need by using tags in the Hue card. Not html but still usable across multiple bulbs.
