### ISSUE TITLE
Philips Hue Sensors are not found by the app

### ISSUE THREAD

**Issue by ghost** [sebbebebbe/com.philips.hue.zigbee#17]
After adding 25 sensors to Homey with your application, Philips Hue ZigBee, all of a sudden Homey cannot find the sensors anymore.
In theory the Homey has an unlimited capacity so this shouldn't be the issue. Is there anything that can be fixed in the app?

Thanks in advance!

**Comment by sebbebebbe** [comment]
Hi @RobertvdVeen,

There is no limitation in the app itself, it relies on the Athom Code mesh driver. The functionality of the app right now is mostly mapping device id:s to the correct type of bulbs i.e. color or white ambiance.

I know there are users with more sensors than 25 that are fine and those with less that have problems. :(

**Comment by ghost** [comment]
Hi @sebbebebbe , thanks for the answer but it isn't really clear to me yet if there is anything I can do to add more sensors at the moment. From within the app there is nothing you can do I understand? So then something in the Homey would need fixing?

**Comment by sebbebebbe** [comment]
Hi @RobertvdVeen i do not know if there is anything you can do to make it work, try asking on the forum or contacting their support.

I cannot do anything in the app since i rely on athoms implementation of the ZigBee driver.

**Comment by ghost** [comment]
@sebbebebbe In the last couple of days I managed to make it work; I added additional smart plugs so I could add more sensors. However I now face another problem. After I added all my sensors I changed the wifi network to which the Homey is connected through a reset. After this the sensors don't respond like they did before the change, e.g. they say motion is detected while there is nothing to detect, almost continuously. Or sensor don't detect motion while there is something to detect. Any experience with this?

**Comment by sebbebebbe** [comment]
@RobertvdVeen Nice to see you got some of it working. I know there has been some discussions about changing the Wifi-network in the Athom forums.

**Comment by ghost** [comment]
So changing the wifi network doesn't affect your app? @sebbebebbe

**Comment by sebbebebbe** [comment]
Correct

**Comment by sebbebebbe** [comment]
Issues with sensors should be solved in upcoming v2.0.5 or later
