### ISSUE TITLE
Animation/Fading functionality

### ISSUE THREAD

**Issue by robinator90** [sebbebebbe/com.philips.hue.zigbee#170]
It would be great to have some light animation functionality. Maybe a new tab, with presets, ability to create own sets, test button. This sets should also be usable in flows.

I'm not sure if this is even possible. But this would be awesome :)

**Comment by JohanBendz** [comment]
Hi and thanks for your request and creative idea! :)
I'll look into if this can be done and if so add it to the roadmap.

**Comment by jamesbryant** [comment]
+1 

Every other light I have (Aeotec Nano Dimmers) smoothly transitions as you adjust the dim level. Using the two hue lights that I have feel janky as they instantly jump to each dim level adjustment. Would be perfect to mimic the transition you get when you turn the lights off.

**Comment by JohanBendz** [comment]
Some animations has been added in already available updates. The option to dim over time works in flows. I'm looking to add default dim time to lights as standard. closing the issue.
