### ISSUE TITLE
Flourish Hue pendant white color support

### ISSUE THREAD

**Issue by kingofkobjer** [sebbebebbe/com.philips.hue.zigbee#173]
**Product Info**
https://www2.meethue.com/en-us/p/hue-white-and-color-ambiance-flourish-pendant-light/4090631U7 

**Zigbee Info**
Manufacturer ID: Philips
Product ID: 4090631P9
Device ID: 269
Profile ID: 260

**Comment by JohanBendz** [comment]
Thanks for your contribution, I have added this to the list of units to be added.

**Comment by JohanBendz** [comment]
Added to next release of the app.
