### ISSUE TITLE
New device: Signe WCA Floor Lamp - Info provided

### ISSUE THREAD

**Issue by Kvasy123** [sebbebebbe/com.philips.hue.zigbee#174]
Hi, can you add this device:

Signe WCA Floor Lamp
https://www2.meethue.com/en-us/p/hue-white-and-color-ambiance-signe-floor-light/4080248U7

Product ID: LCF003
Device ID: 528
Profile ID: 49246

Thanks in advance! ❤️

**Comment by JohanBendz** [comment]
Thanks for your request, the device is on the list of units to be added.

**Comment by JohanBendz** [comment]
Device added to test version of the app, going live on next update.
