### ISSUE TITLE
Philips Hue Econic Outdoor wall lamp Classic no support

### ISSUE THREAD

**Issue by vjmikey** [sebbebebbe/com.philips.hue.zigbee#177]
Hii,

i am trying to add the Philips Hue Econic Outdoor wall lamp Classic.

after try to add to says to set it up as a simple zigbee device where i only can turn it on or off.

![1382465](https://user-images.githubusercontent.com/54313436/77224732-d99df500-6b68-11ea-92e4-003b2776ad9b.jpeg)

Thankss

**Comment by JohanBendz** [comment]
Hi and thanks for your interest in the app, I would however need more information to be able to add this device to the app.

Here is a short guide when you want to request a new device to be added.

1. Add the device to Homey as a Generic Zigbee device
2. Tap and hold the device in the Homey app
3. When in the device tap properties in the upper right corner
4. Take a screenshot of the properties which will contain the info needed, see example below
5. Link to the device on www.meethue.com

Example:
Product ID: LTC016
Service ID: 544
Profile ID: 4926

**Comment by JohanBendz** [comment]
@vjmikey, just posting a friendly reminder to get back with device info.
