### ISSUE TITLE
Add Philips hue Calla outdoor lamp

### ISSUE THREAD

**Issue by schildsoft** [sebbebebbe/com.philips.hue.zigbee#179]
Can you add the Calla outdoor Lamp? 

https://www2.meethue.com/nl-nl/p/hue-white-and-color-ambiance-calla-sokkellamp/1742030P7

Product id: LCF002
Service id: 528
profile id: 49246

after try to add to says to set it up as a simple zigbee device where i only can turn it on or off.
Homey user

**Comment by JohanBendz** [comment]
Thanks for the information, I will add this to the list of devices to be added.

**Comment by JohanBendz** [comment]
Now in test version.
https://homey.app/sv-se/app/com.philips.hue.zigbee/Philips-Hue-ZigBee/test/
