### ISSUE TITLE
[Request] Being ceiling light

### ISSUE THREAD

**Issue by Jugge72** [sebbebebbe/com.philips.hue.zigbee#18]
[https://www2.meethue.com/en-us/p/hue-white-ambiance-being-ceiling-light/4100448U7](url)

**Comment by sebbebebbe** [comment]
@Jugge72 saw your post in the forum. The being light is added to my todo list and first out for next release.

In the mean time you can add it as a generic zigbee device.

//Sebastian

**Comment by Jugge72** [comment]
Hi, tried to add as generic zigbee device but no response.
But thanks for feedback.

**Comment by Jugge72** [comment]
After a reset i manage to add it as a generic device.

/Jugge

**Comment by gjefsjo** [comment]
It would be nice to get all the features working- will there soon be a new release with Being support?

**Comment by sebbebebbe** [comment]
Soonish :)
