### ISSUE TITLE
Bulb status after power failure

### ISSUE THREAD

**Issue by ZimoSka** [sebbebebbe/com.philips.hue.zigbee#180]
after power outage, all bulbs turn on (LCT01, LWB010).
However they are reported to homey (which is on UPS) as - off.

**Comment by JohanBendz** [comment]
Thank you for the feedback, I will have a look at it.

**Comment by JohanBendz** [comment]
I'm closing this issue. If you still have problems after upgrading to firmware 5 please create a new issue.
