### ISSUE TITLE
Add support for Philips Hue Impress Path Light?

### ISSUE THREAD

**Issue by mmuksis** [sebbebebbe/com.philips.hue.zigbee#181]
Hi there, 

thank you for providing this great app for Homey. I have many Philips Hue lights already installed and everything works flawlessly. However, would it be possible for you to please add Hue Impress Pathlight: 

https://www.amazon.de/dp/B07MFQXMMZ/ref=cm_sw_em_r_mt_dp_U_nh8REbVPQ7KNZ 

Product ID: 1743230P7
Device ID: 269
Profile ID: 260

It seems that currently only the "shorter version" of the lamp called Impress Post is supported by the app.

Thanks a lot,
Mikael

![Screenshot_20200504-100936_Homey](https://user-images.githubusercontent.com/64771080/80944070-591e1580-8df1-11ea-8ae5-aff2142e1045.jpg)

**Comment by JohanBendz** [comment]
Hi @mmuksis, thanks for your request and kind words. :)

I add this to our list of devices to be added, the information provided is much appreciated! 👍

**Comment by JohanBendz** [comment]
Now in test version.
https://homey.app/sv-se/app/com.philips.hue.zigbee/Philips-Hue-ZigBee/test/
