### ISSUE TITLE
Philips GU10 White and Color Ambiance

### ISSUE THREAD

**Issue by sizarkamar** [sebbebebbe/com.philips.hue.zigbee#182]
Can you please add support for the GU10 White and Color Ambiance.
Thank you in advance.

this is the product link: https://www2.meethue.com/nl-nl/p/hue-white-and-color-ambiance-2-pack-gu10/8718699629250

And this is the zigbee info from Homey when adding it as a normal zigbee device:
Producent ID: philips
Product ID: 5045131P7
Device/apparaat/service ID: 269
Profile ID: 260

**Comment by JohanBendz** [comment]
Thanks for your request, I have added it to our to do list.

**Comment by JohanBendz** [comment]
Now in test version.
https://homey.app/sv-se/app/com.philips.hue.zigbee/Philips-Hue-ZigBee/test/

**Comment by sizarkamar** [comment]
thank you very much for the fast replay and add to the lamp!
I'll test it as soon as possible!

Op za 16 mei 2020 om 10:40 schreef Johan Bendz <notifications@github.com>:

**Comment by Pim65** [comment]
This one is not added, at least I do not see the correct bulp in the app?
