### ISSUE TITLE
Please add Hue e27 W&C Ambiance BT variant

### ISSUE THREAD

**Issue by ech0-sj** [sebbebebbe/com.philips.hue.zigbee#183]
Hi, 
please add lamp, it's product ID is4090431p9. I have seen you've already added 40903x 40905x, 40906x :) 
![hue lamp](https://user-images.githubusercontent.com/10262946/81478903-7b17fd80-9220-11ea-93b6-29f2d7cc9214.jpeg)

Thanks a lot! You're doing a great job

**Comment by JohanBendz** [comment]
Hi @ech0-sj and thanks for your request, I have added it to our to do list.

**Comment by JohanBendz** [comment]
Now in test version.
https://homey.app/sv-se/app/com.philips.hue.zigbee/Philips-Hue-ZigBee/test/
