### ISSUE TITLE
Hue outdoor Fuza Wall Latern

### ISSUE THREAD

**Issue by Marcel1024** [sebbebebbe/com.philips.hue.zigbee#184]
I've got 2 Hue outdoor Fuza Wall Latern, 1 working correctly, the other couldn't be recognized.
It can be turned on and off while using it as an Unknown ZigBee device tho.

Not working:
ProductID: 174430P7
DeviceID: 257
ProfileID: 260 

Working:
ProductID: 1744430P7
DeviceID: 256
ProfileID: 49246

I guess the deviceID has to be added to the app.

**Comment by JohanBendz** [comment]
Hi @Marcel1024 and thanks for your request, it's added to our list of things to do.

**Comment by JohanBendz** [comment]
Now in test version.
https://homey.app/sv-se/app/com.philips.hue.zigbee/Philips-Hue-ZigBee/test/

**Comment by Marcel1024** [comment]
Hi johan! Tested the app and it works!

Thanks

________________________________
Van: Johan Bendz <notifications@github.com>
Verzonden: Saturday, May 16, 2020 10:39:12 AM
Aan: sebbebebbe/com.philips.hue.zigbee <com.philips.hue.zigbee@noreply.github.com>
CC: M. Mulder / 1024 Solutions <m.mulder@1024solutions.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [sebbebebbe/com.philips.hue.zigbee] Hue outdoor Fuza Wall Latern (#184)


Closed #184<https://github.com/sebbebebbe/com.philips.hue.zigbee/issues/184>.
