### ISSUE TITLE
Adding Philips Hue Daylo

### ISSUE THREAD

**Issue by andtor84** [sebbebebbe/com.philips.hue.zigbee#186]
Could you please add Philips Hue Daylo outdoor wall light:

Product ID: 1746530P7
Service ID: 269
Profile ID: 260

![Screenshot_20200513_174053](https://user-images.githubusercontent.com/48864995/81834393-2981b280-9541-11ea-857d-8e37a854c0c7.jpg)

![received_943292946123177](https://user-images.githubusercontent.com/48864995/81835098-1fac7f00-9542-11ea-9bf2-b818949ad3dd.jpeg)

**Comment by JohanBendz** [comment]
Hi @andtor84 and thanks for your request, it has been added to the To Do list :)

**Comment by JohanBendz** [comment]
Now in test version
https://homey.app/sv-se/app/com.philips.hue.zigbee/Philips-Hue-ZigBee/test/

**Comment by andtor84** [comment]
Seems to work perfect, @JohanBendz! Thx. 😊
