### ISSUE TITLE
Philips Hue White en Color Ambiance Econic oudste wall lamp

### ISSUE THREAD

**Issue by arnodejong2307** [sebbebebbe/com.philips.hue.zigbee#187]
Dear, 

I have a problem with a new outdoor lamp from philips the Philips Hue White and Color Ambiance Econic. When I add the lamp it comes with standard zigbee device. And I can only turn on and off. Unfortunately I can't dim and change color.

![IMG_5550](https://user-images.githubusercontent.com/65450954/82120076-e4998e00-9783-11ea-91dd-d1205d8b74d7.png)
![LPH01450_big1](https://user-images.githubusercontent.com/65450954/82120018-6f2dbd80-9783-11ea-9b4c-abcadabb1e0e.jpg)

**Comment by JohanBendz** [comment]
Hi @arnodejong2307, thanks for your feedback. I have corrected the info in the app. There was a typo making this device unable to pair correctly.

A test version with this update is available here: https://homey.app/sv-se/app/com.philips.hue.zigbee/Philips-Hue-ZigBee/test/

**Comment by arnodejong2307** [comment]
Hey @JohanBendz, thanks for your super quick response, i am going to try again tonight i will let you know.

Thanks again for your quick response.

**Comment by arnodejong2307** [comment]
Hey @JohanBendz, thanks i have testing and working fine now, gr Arno
