### ISSUE TITLE
Philips Hue Smart Plug AU

### ISSUE THREAD

**Issue by matt20v** [sebbebebbe/com.philips.hue.zigbee#188]
Hi Just wondering if the Philips Hue Zigbee app has support for the Australian hue smart plug ? 

I tried to add mine a couple of times and it only comes up as a generic Zigbee devices it found the Outdoor Motion Sensor no problems along with the Hue Light Strip and the Hue Outdoor spot lights. 

Any help would be great 

See the device in the list as generic 
![image0](https://user-images.githubusercontent.com/31461639/82808170-c858c800-9ecc-11ea-9e93-bab49652805b.png)

When connected if i look at the advance settings you can see it detects with the correct model etc.  
![image1](https://user-images.githubusercontent.com/31461639/82808179-ce4ea900-9ecc-11ea-8c31-b6aa4c63c850.png)

Thanks Matt

**Comment by JohanBendz** [comment]
Hi @matt20v, the model LOM005 was not added to the app, I have now added it and it will be supported in the next version of the app.

Thanks for you help with the device information! :)

**Comment by matt20v** [comment]
@JohanBendz  Your a legend thanks soooo much :) 

Matt
