### ISSUE TITLE
Hue Dimmer Switch suddenly lost connection

### ISSUE THREAD

**Issue by BBEHannes** [sebbebebbe/com.philips.hue.zigbee#19]
Hello,

i have a problem that started yesterday (after adding door sensors with ZigBee connection). Suddenly, my Hue Dimmer switch is not working anymore. I have tried the following without good results;

-Removed the Hue Dimmer from Homey and re-added it
-Made sure that the dimmer is working by adding it to a HUE Bridge and seeing the Button presses coming in
-Reset the entire ZigBee devices and adding it back as first device, still nothing

Any idea what to do? It keeps adding the device without any problems but it doesn't register any of the button presses. I also see the device properly on the developer page.

Appreciate your thoughts..

**Comment by koktaildotcom** [comment]
I think this ticket is a duplicate, see https://github.com/sebbebebbe/com.philips.hue.zigbee/issues/8
@sebbebebbe is there any progress on this issue?

**Comment by BBEHannes** [comment]
Yep, same issue... I worked around it by pairing another hue dimmer switch and using the “broken” one to replace it since it works fine on the hue Brigde. Hope this won’t become a returning thing though

**Comment by sebbebebbe** [comment]
@BBEHannes  @koktaildotcom 
I am closely monitoring all of Athoms changes to their core ZigBee implementation.
But nothing has happened yet.

Their priority right now is the release of the new 2.0 mobile app. :(
