### ISSUE TITLE
Hue Outdoor Motion Sensitivite 

### ISSUE THREAD

**Issue by matt20v** [sebbebebbe/com.philips.hue.zigbee#190]
Hello,

I know this has been brought up before https://github.com/sebbebebbe/com.philips.hue.zigbee/issues/101#issue-457106571

but just wondering if there is any chance we can somehow look at this again to add the possibility for adjustment ?

I was testing notifications during the day when motion was detected and it seems that just the sunlight was making it trigger. 

Not sure how hard this would be to add the setting if there is anything i can do to help i am happy to try.

**Comment by JohanBendz** [comment]
Hi @matt20v I'll make some time to have a look at it again. 👍

**Comment by matt20v** [comment]
Thanks Mate do let me know if i can do anything to help!

**Comment by dirkg173** [comment]
Hello @JohanBendz,
unfortunately the possibility to adjust the sensitivity seems not to be included yet.
I know that you are currently spending a lot of time with the migration to Homey FW 5. But is it still possible to integrate this device setting? The missing of this device setting is the main reason that I still have 3 lamps and the outdoor motion sensor still running over the Philips Hue Bridge.
This information might be helpful:

https://github.com/dresden-elektronik/phoscon-app-beta/issues/100

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1815

**Comment by joka222** [comment]
Would be really great if sensitivity was added as a parameter! THX

**Comment by JohanBendz** [comment]
Hi @dirkg173 and thanks for the link, very informative! :)

I will look into adding parameter settings for:
  pirOccupiedToUnoccupiedDelay
  pirUnoccupiedToOccupiedDelay
  pirUnoccupiedToOccupiedThreshold
  sensititivty
  sensititivtyMax

I will however only be able to add this to the FW5 version of the app.

**Comment by ghost** [comment]
Any news on that?

**Comment by Ltek** [comment]
Would like this too. And the ability to set it in Phoscon UI!

**Comment by joka222** [comment]
Would be really nice if this could be integrated in near future! THX Johan

**Comment by CoderIllusionist** [comment]
Indeed, would be very nice to have ! Mine is currently detecting motion almost all day when it's after sunrise

**Comment by matt20v** [comment]
> Indeed, would be very nice to have ! Mine is currently detecting motion almost all day when it's after sunrise

Not sure if this helps but for how i use mine i just put in that motion is not active during daytime hours. Then on the device I covered the top half of the ball with black electrical tap to limit its field of vision to stop it picking up areas that kept causing false positives

**Comment by CoderIllusionist** [comment]
Thanks, that helped!

**Comment by oh2th** [comment]
Adjusting the sensitivity would be useful indeed, hope to see this available soon.

**Comment by thomaswitt** [comment]
Same problem here, motion detection all day!

**Comment by JohanBendz** [comment]
Motion sensitivity has been added to the occupancy driver in the test version of the app
