### ISSUE TITLE
Philips Hue Outdoor Wall light Fuzo (1744430P7) recognized as "Unknown ZigBee devices".

### ISSUE THREAD

**Issue by EricPiepers** [sebbebebbe/com.philips.hue.zigbee#191]
I recently bought 2 Fuzo outdoor lights, both lights seem not to be recognized by the app.
I'm also using the Hue Outdoor Lightstrip, Hue Lily Outdoor Spot, Hue ambience Candle (3) and Hue White Ambience GU10 BT (5) they work flawless. 
The Fuzo outdoor lights are recognized as "Unknown ZigBee devices".
I'm using "Philips Hue ZigBee app v1.4.9"
Can you help me getting this fixed? 

Below some screen shots.
(Note: they are in Dutch, I don't hope that's a problem)
![Fuzo specs](https://user-images.githubusercontent.com/66127842/83272446-744f2b80-a1cb-11ea-9607-57142aae2b36.jpg)
![Fuzo issue 1](https://user-images.githubusercontent.com/66127842/83272517-84670b00-a1cb-11ea-936a-6f71d787bb4d.jpg)
![Fuzo issue 2](https://user-images.githubusercontent.com/66127842/83272539-8a5cec00-a1cb-11ea-8d21-22093bfb9028.jpg)
![Fuzo issue 3](https://user-images.githubusercontent.com/66127842/83272545-9052cd00-a1cb-11ea-940d-e447144d25f7.jpg)
![Fuzo issue 4](https://user-images.githubusercontent.com/66127842/83272571-96e14480-a1cb-11ea-8dc3-2746ad0f341b.jpg)
![Fuzo issue 5](https://user-images.githubusercontent.com/66127842/83272582-9a74cb80-a1cb-11ea-99b7-7e12c0f88060.jpg)

Regards, Eric.

**Comment by JohanBendz** [comment]
Hi @EricPiepers, can you please try the Test version to see if your issue is resolved? I'm waiting for more feedback on the Test version before I release it as a Live version to everyone.

https://homey.app/a/com.philips.hue.zigbee/test

// Johan

**Comment by EricPiepers** [comment]
Hi Johan,




Thanks for your reply. I'll install the testversion today and report any issues asap.




Regards, Eric 




Verzonden vanuit Outlook Mobile







On Sun, May 31, 2020 at 8:45 AM +0200, "Johan Bendz" <notifications@github.com> wrote:















Hi @EricPiepers, can you please try the Test version to see if your issue is resolved? I'm waiting for more feedback on the Test version before I release it as a Live version to everyone.


https://homey.app/a/com.philips.hue.zigbee/test


// Johan

**Comment by EricPiepers** [comment]
Hi Johan,

 

Test version (1.5.7.) installed, problem with the Fuzo still exists ☹.

Until now no problems in using the other lamps. I’ll try to do some more testing this week.

 

Regards, Eric.

**Comment by JohanBendz** [comment]
Hi again @EricPiepers, I have now made some changes according to your information. Can you try the updated test version? https://homey.app/a/com.philips.hue.zigbee/test/

**Comment by EricPiepers** [comment]
Hi Johan,

 

Thanks for your prompt reply.

I’ll try to test either today or tomorrow.

 

Kind regards, Eric.

**Comment by EricPiepers** [comment]
Hi Johan,

 

Yes !!!! The problem fixed the Fuzo is recognized again and can be switched on/off and dimmed, works like a charm 😊.

Thanks a lot. Shall I continue testing this version (v.1.5.8)or revert back to v.1.5.7. ?

 

Regards, Eric.

**Comment by JohanBendz** [comment]
Hi again @EricPiepers
Great!! Stay on 1.5.8 :)

// Johan
