### ISSUE TITLE
Not responding

### ISSUE THREAD

**Issue by Mark25051969** [sebbebebbe/com.philips.hue.zigbee#192]
I have a hue lamp that sometimes not responding after the latest Homey update. After a restart it wil recognise the lamp an it wil work for fine 24 hours than I must restart again.

**Comment by JohanBendz** [comment]
Hi @Mark25051969, can you create a crash report and send it to me next time it happens?

**Comment by JohanBendz** [comment]
Hi again @Mark25051969, I have published a test version of the app that might work better for you, please try it out: https://homey.app/sv-se/app/com.philips.hue.zigbee/Philips-Hue-ZigBee/test/

**Comment by JohanBendz** [comment]
Get back to me if this is still an issue.
