### ISSUE TITLE
GU10 and E27  White Ambiance with BT, not recognized

### ISSUE THREAD

**Issue by jeroendew** [sebbebebbe/com.philips.hue.zigbee#194]
Today I got the GU10 Ambiance with BT but it's not recognized.
Could somebody add these to the app?

Product ID:  LGT002
Service ID: 268
Profile ID:  260

Edit:
And the E27 White Ambiance with BT isn't recognized either.
Product ID:  LTA001
Service ID: 268
Profile ID:  260

Thanks,
Jeroen

**Comment by JohanBendz** [comment]
Hi @jeroendew, I think the first product should be LTG002, correct?

If so, both products are already added to the test version of the app. Waiting for more testers to verify that everything works just fine before I publish it to everyone.

Fell free to try it out, I would love to get feedback on any issues :)

https://homey.app/a/com.philips.hue.zigbee/test/

**Comment by jeroendew** [comment]
Hello @JohanBendz ,

Sorry, yes it was the LTG002. I've installed the test version and now the lamps are recognized.

**Comment by JohanBendz** [comment]
Great, thanks for letting me know! :)
