### ISSUE TITLE
Philips Hue Outdoor Wall light Daylo

### ISSUE THREAD

**Issue by pngoosen** [sebbebebbe/com.philips.hue.zigbee#195]
Hi,
 
Yesterday I bought the Philips Hue Outdoor Wall light Daylo.
The product ID on the box is 1746547P7.

When connecting the wall light to my Homey Pro I couldn't select it.
The light is now installed as unknown Zigbee device.
The only available action is on/off.

Is it possible to add the product? Will I get more functionality like colors?

Productname  Philips Hue Outdoor Wall light Daylo
Product ID   1746547P7
Device ID    269
Profile ID   260 

Thanks in advance!

Kind regards,

Peter

**Comment by JohanBendz** [comment]
Hi @pngoosen, thanks for your request.
I will put this to my list of device to add.

**Comment by JohanBendz** [comment]
@pngoosen Now added to the test version.

https://homey.app/sv-se/app/com.philips.hue.zigbee/Philips-Hue-ZigBee/Test/

**Comment by pngoosen** [comment]
Hi Johan,
Thanks for your update.
I am new both in using Homey as using Philips Hue.
What will be my next step?
Testing the test-version and give feedback to you?

How do I test?
I assume:
- Delete Wall light from Homey
- Delete Philips Hue Zigbee app from Homey
- Install test-version Philips Hue Zigbee app
- Connect Wall light to Homey

Is this correct? Is there a better way?
I am using an Android mobile device.

Peter.

**Comment by JohanBendz** [comment]
Hi @pngoosen, that is an excellent plan :)

**Comment by pngoosen** [comment]
Hi Johan,
The test was successful!
All functionality is available now.

I assume that I continue using the test version and that I will get the new version automatically?

Thanx for your help!
