### ISSUE TITLE
Please add outdoor light

### ISSUE THREAD

**Issue by haroldbouwmeester** [sebbebebbe/com.philips.hue.zigbee#196]
Hi Can you please add this lamp 

Product ID: 1743930P7
Service ID: 528
Profile ID: 49246

https://www2.meethue.com/nl-nl/p/hue-white-and-color-ambiance-econic-buitenwandlamp/1743930P7

Thanks Harold

**Comment by JohanBendz** [comment]
Hi @haroldbouwmeester.
Sure I can, adding it to the list of devices to be added. :)

**Comment by JohanBendz** [comment]
Added to upcoming SDK3 version of the app
