### ISSUE TITLE
Philips Hue Lightstrip Outdoor 5m White and color ambiance

### ISSUE THREAD

**Issue by Borwil** [sebbebebbe/com.philips.hue.zigbee#197]
It only comes up as generic zigbee in the Homey app, even when I choose outdoor strip. Can you add it please 
https://www2.meethue.com/no-no/p/hue-white-og-farget-stemning-lightstrip-outdoor-5-meter/8718699709853

![Screenshot_20200622-190819_Homey](https://user-images.githubusercontent.com/67285312/85316322-d8a89680-b4bc-11ea-94dc-1f22cf820247.jpg)

**Comment by JohanBendz** [comment]
Hi @Borwil.
Sure, I put it on the list of devices to be added. :)

**Comment by spacecosmos** [comment]
I'm also waiting for this.

**Comment by JohanBendz** [comment]
Added to upcoming SDK3 version of the app.
