### ISSUE TITLE
Philips Hue Lightstrip Outdoor 2m - White and Color Ambiance

### ISSUE THREAD

**Issue by acaenepeel** [sebbebebbe/com.philips.hue.zigbee#198]
Hi,

Is it possible to add this device?
https://www2.meethue.com/nl-nl/p/hue-white-and-color-ambiance-lightstrip-outdoor--2-meter/8718699709839

Producent ID: Philips
Product ID: LCL002
Device ID: 269
Profile ID: 260

Kind regards,

Aaron

**Comment by JohanBendz** [comment]
Hi  @acaenepeel.
Absolutely,  I'm putting it on the todo list.

**Comment by JohanBendz** [comment]
Added to upcoming SDK3 version of the app.
