### ISSUE TITLE
Philips Hue Outdoor Nyro Sokkel

### ISSUE THREAD

**Issue by acaenepeel** [sebbebebbe/com.philips.hue.zigbee#199]
Hi,

Is it possible to add this device?
https://www2.meethue.com/nl-nl/p/hue-white-and-color-ambiance-nyro-sokkellamp/1745530P7

Producent ID: Philips
Product ID: 1745530P7
Device ID: 269
Profile ID: 260

Kind regards,

Aaron

**Comment by JohanBendz** [comment]
Hi again, sure. Adding it to the todo list.

**Comment by JohanBendz** [comment]
Added to upcoming SDK3 version of the app.
