### ISSUE TITLE
Philips Hue Outdoor Nyro muurlamp

### ISSUE THREAD

**Issue by acaenepeel** [sebbebebbe/com.philips.hue.zigbee#200]
Hi,

Is it possible to add this device?
https://www2.meethue.com/nl-be/p/hue-white-and-color-ambiance-nyro-muurlamp/1745630P7

Producent ID: Philips
Product ID: 1745630P7
Device ID: 269
Profile ID: 260

Kind regards,

Aaron

**Comment by JohanBendz** [comment]
Same with this one :)

Adding it to the todo list.

**Comment by JohanBendz** [comment]
Added to upcoming SDK3 version of the app
