### ISSUE TITLE
White and Color Ambiance

### ISSUE THREAD

**Issue by rolli00** [sebbebebbe/com.philips.hue.zigbee#201]
Please add support for homey.
https://www2.meethue.com/de-de/p/hue-white-and-color-ambiance-discover-flutlicht/1743530P7

Producer ID 1743530P7
Service ID 528
Profile ID 49246

Thank's a lot!

**Comment by JohanBendz** [comment]
Hi @rolli00.
This device is already added to the test version of the app, please try it and report if it works for you.

https://homey.app/sv-se/app/com.philips.hue.zigbee/Philips-Hue-ZigBee/test/

**Comment by rolli00** [comment]
Hi Johan,

Great work!
First tests are running very well.
I'll report if i have some trouble.

Thanks a lot.

Regards
Roland

Am Di., 30. Juni 2020 um 13:05 Uhr schrieb Johan Bendz <
notifications@github.com>:
