### ISSUE TITLE
New Philips Hue Aurelle panel lamp

### ISSUE THREAD

**Issue by Erwin-1234** [sebbebebbe/com.philips.hue.zigbee#205]
The new Aurelle lamp (large rectangle version) has been changed. It now has Bluetooth support. When adding the new model to the Homey it shows up as a simple Generic Zigbee Device in the Hue Zigbee Device App.

https://www.philips-hue.com/nl-nl/p/hue-white-ambiance-aurelle--rechthoekig--paneellamp/3216331P6

Producent ID: Philips
Product ID: 3216331P6
Device ID: 268
Profile ID: 260

Can you please add support for the new Philips Hue Aurelle panel lamp? Thank you!!

**Comment by JohanBendz** [comment]
Added to the upcoming SDK3 version of the app
