### ISSUE TITLE
Livingcolor gen-3 bloom

### ISSUE THREAD

**Issue by hfaas** [sebbebebbe/com.philips.hue.zigbee#207]
Hi,

I have a livingcolors gen-3 bloom (LLC005), that I'm trying to connect with Homey, but I can't seem to get it into zigbee pairing mode (I'm not able to connect it with the generic zigbee device setup).

Some methods to get the lamp into pairing mode that I found online seem to contradict each other. So therefor I was wondering if anyone here can enlighten me whether this lightbulb is even capable of connecting whith a generic zigbee network, and ifso how to get it done?

Any help is welcome.!

Thanks.

Spikey

**Comment by JohanBendz** [comment]
Hi @hfaas, while I do not have the device myself I'd say there is a very large chance it will connect to Homey.
Other Living Color devices of older versions have been verified to work so this is probably doable.

I'd start with following any of the guides and while doing so keeping the device very close to Homey. If no device is to be found, try pulling the plug on Homey for 15 minutes and then try again.

If you succeed to add it as generic, please get back to me with the zigbee data you have on it.

**Comment by JohanBendz** [comment]
I'm closing this issue. If you still have problems (after upgrading to firmware 5) please create a new issue.

**Comment by hfaas** [comment]
Hi Johan,

Just as a (late) follow-up. 

It looks like the LLC005 isn't fully supporting the zigbee standards or what ever.
I now have a couple of other Philips Hue devices which i was able to properly "reset" and "pair" with Homey, but I still fail to get the LLC005 to pair (resetting works fine, but it isn't recognised by Homey as a new/searching device).

This also seems to be confirmed in the "supported devices" context of Philips develop API of which the following document is a public shared PDF. There it states the LLC005, LLC006, LLC007 and LLC014 are not "Hue" or "Friends of Hue", although the 006 and 7 are detectable, but the 5 and 14 are not mentioned.
https://trianglebruins.com/hue/hue-api-16.pdf

Weirdly enough the device is properly being identified by the bridge, at the same channel (I do have to admit I have to use the touchlink method to do so). 
I was wondering (did not look at the code yet), but do you support/use a touchlink method in any way in Homey?
There is an example mentioning here, but I'm not sure if it is of any use:
https://www.zigbee2mqtt.io/information/touchlink

Anyway, if you have any tips I could still try, let me know, otherwise you can close this issue again, since I don't know any more options to get it paired.
