### ISSUE TITLE
Outdoor Wall light Fuzo shows up as generic. 

### ISSUE THREAD

**Issue by MartenWihlborg** [sebbebebbe/com.philips.hue.zigbee#208]
When trying to add https://www.philips-hue.com/sv-se/p/hue-white-fuzo-vagglampa-for-utomhusbruk/1744430P7 it shows up as generic device. 

![218C3870-6CB0-484E-8405-5AC72A6B2298](https://user-images.githubusercontent.com/68607019/88081442-aacc7580-cb80-11ea-874e-729a53225e84.jpeg)

>

**Comment by JohanBendz** [comment]
Added.
