### ISSUE TITLE
Work on homey 5.0.0+ (zigbee sdk 3)

### ISSUE THREAD

**Issue by zeppie** [sebbebebbe/com.philips.hue.zigbee#209]
Is this happening in the near future? Forgot to turn out experimental updates for homey and now all my zigbee devices stopped working :(  waiting for your update vs factory reset homey. Thx

**Comment by markhaehnel** [comment]
The maintainer is already working on it. 👍🏻

See #204

**Comment by zeppie** [comment]
A nice! Didn’t notice it, because issue was closed. Hopefully released soon.

**Comment by markhaehnel** [comment]
I think it would be a good idea to close the issue to keep the place tidy.

**Comment by bramoosterhuis** [comment]
I already did some work for SDK3 so at least I could control my bulbs again, https://github.com/sebbebebbe/com.philips.hue.zigbee/issues/204#issuecomment-664048195

**Comment by JohanBendz** [comment]
Hi everyone waiting for the update.

The prerelease to developers and now to experimental did perfectly allign with my summer vacation and it appears my family does not consider developing Homey apps as holiday ;) 

I am now back home after spending time with family and friends and expect to finish the update within a week or so.
