### ISSUE TITLE
Hue Motion Sensor - Motion Alarm is constantly on

### ISSUE THREAD

**Issue by pberden** [sebbebebbe/com.philips.hue.zigbee#21]
The problem I'm having is that the Motion Alarm is constantly on. I placed it in a cabinet for a while where, as far as I know, nothing moves. It seems to detect the darkness in the cabinet correctly.

Also under insights it shows that the alarm never goes off. What do you think? Is this a problem with the Motion Sensor? Or could it also be a problem with Homey / the Philips Hue Zigbee app?

**Comment by sebbebebbe** [comment]
Hi @pberden,

I would say it shouldn´t have anything to do with the app atleast. The app provides no logic for the motion sensor, it merely sets some parameters and then the Athom ZigBee code takes care of the rest.

**Comment by GitHubLuigi** [comment]
I have exactly the same issue.
The sensor did work great for a couple of days though.
It got stuck in detecting motion somewhere the past 24 hours.

How strange...
Restarting the app didn’t change anything and restarting Homey neither.
But somehow the sensor just fixed itself. It isn’t stuck in detecting motion anymore.

**Comment by PatrickvanD** [comment]
Same problem here with both of my motion sensors. Sometimes after a few days, sometime after a few hours the red light on the sensor turns on, but in Homey the device is a continue motion detected and nothing happens. 

Only removing and adding the sensor to Homey helps (for a few hours/days). 

After a update to Homey 1.5.13 the motion sensors are stuck in the motion detected mode.

Update 11-30: Send a mail to Athom but they send me back to the devolper of the app. For the time beeing i connected te sensors back to the Hue bridge and now its working again. (only slow reaction)

**Comment by sebbebebbe** [comment]
Please continue to send reports for this to Athom since it has to do with their ZigBee implementation
