### ISSUE TITLE
New Lightstrip Plus with BT

### ISSUE THREAD

**Issue by Erwin-1234** [sebbebebbe/com.philips.hue.zigbee#211]
Also the new Lightstrip Plus has changed, it now supports Bluetooth and is no longer recognised by the app.

https://www.philips-hue.com/nl-nl/p/hue-white-and-color-ambiance-lightstrip-plus-basispakket--2-meter/8718699703424

Producent: Philips
Product ID: LCL001
Device ID: 269
Profile: 260

regards,
Erwin

**Comment by Ekorrmage** [comment]
Can confirm that this is the case, have the same issue

**Comment by JohanBendz** [comment]
Hi @Erwin-1234, that's correct.. that model of the strip have a new Product ID and will have to be added to the app. Adding it to my todo list.

**Comment by JohanBendz** [comment]
Added to next release (SDK3)
