### ISSUE TITLE
New 1600 lumen A21 bulb support

### ISSUE THREAD

**Issue by suhajdab** [sebbebebbe/com.philips.hue.zigbee#214]
Please add support for the new 1600 lumen white bulb.
[Link](https://www.philips-hue.com/en-us/p/hue-white-1-pack-a21-e26/046677557805)

**Comment by JohanBendz** [comment]
Hi @suhajdab, thanks for your request. I will put it on the list of devices to be added.

**Comment by JohanBendz** [comment]
I need product ID for the device to be able to add it. If someone have this device, please add it as a generic device and get back to me with product information.

**Comment by suhajdab** [comment]
LWA009

**Comment by JohanBendz** [comment]
Thx @suhajdab, now added to next release.
