### ISSUE TITLE
Philips impress wall light small

### ISSUE THREAD

**Issue by EmielPijn** [sebbebebbe/com.philips.hue.zigbee#215]
Can you please add device Impress wall light **small**. The one in the app is the "normal/big" one not the small.
See attachment for details.
Device ID 1742930P7

Thnx!

![IMG_2229](https://user-images.githubusercontent.com/69204917/89303810-f85edd00-d66c-11ea-9a42-8bda9da4c410.jpeg)

**Comment by JohanBendz** [comment]
Hi @EmielPijn, thanks for your request. I put it on the todo list :)

**Comment by JohanBendz** [comment]
Added

**Comment by EmielPijn** [comment]
Wow, that was fast. Thnx!!

**Comment by EmielPijn** [comment]
Hi Johan, I tried adding the light today but it is not working. I get the message "There is no Homey app found for this device. The device is added as simple zigbee device." See attachment(it is in dutch but that's what it said). 
Did I something wrong? Or is there a bug or something?
![Impress](https://user-images.githubusercontent.com/69204917/90318778-2547a580-df33-11ea-85f4-698114b4ee27.png)
