### ISSUE TITLE
Philips Hue Smart button support

### ISSUE THREAD

**Issue by christian-ek** [sebbebebbe/com.philips.hue.zigbee#216]
Hello,
Please add support for the Philips Hue Smart button.

[Link to product](https://www.philips-hue.com/en-us/p/hue-smart-button/046677553715)

Product information from when i added it as generic zigbee device in homey.
![IMG_5924](https://user-images.githubusercontent.com/25098185/89392798-4aa20b80-d70a-11ea-884c-a7e55a172220.PNG)

**Comment by JohanBendz** [comment]
Hi @christian-ek, thanks for your request. It's already on my todo list and hopefully soon supported. : ) // Johan

**Comment by JohanBendz** [comment]
oops... closed by misstake :) Will keep the case open until device is added.

**Comment by JohanBendz** [comment]
Added to version v.2.0.11
