### ISSUE TITLE
LTW013 / GU10 - light is not reacting on light temperature change

### ISSUE THREAD

**Issue by shaarkys** [sebbebebbe/com.philips.hue.zigbee#217]
Hi,
I'm shocked to see how this app changed for last year ! Excellent work and thank you - I started to migrate from Hue Bridge however 1st light and it seems I can't change the hue / color temperature for LTW013 spot bulb (GU10), it seems it's stuck to cold white regardless of what I do. On-off and dimming works fine thought. If I shall provide more inputs, let me know please.

**Comment by JohanBendz** [comment]
Hi @shaarkys and thanks for those kind words! :)

Hmm, that sounds strange.. can you please provide the zigbee information for the device and a crash report from the app directly after trying to use it?

**Comment by shaarkys** [comment]
Hi @JohanBendz ,

is this info OK please  ?
Also "crash" report just sent - ec143aa8-9f79-4031-b922-3c8b32fa87fd

Thank you.

![obrazek](https://user-images.githubusercontent.com/14859895/89621071-02612580-d891-11ea-9bd7-ddf9686ce486.png)

**Comment by JohanBendz** [comment]
Hi @shaarkys, thanks. That's exactly what I needed.
Hmm, I don't see any issues with the code or your information.. can you try removing the device and pair it again? It can be a faulty pair process.

**Comment by shaarkys** [comment]
Interesting, I removed it and pair again - it works now. Thank you for your help, closing this "issue" for now then.
