### ISSUE TITLE
Update to new version

### ISSUE THREAD

**Issue by AvieNL** [sebbebebbe/com.philips.hue.zigbee#218]
Maybe very newbie...

Is there any knowledge when your app for Homey (Philips Hue Zigbee) will be updated in Homey? The last version doesn’t support the Lightstrip Plus and I saw that you coded everything already to version 1.5.10.
Or is there another way to force to add that driver?

**Comment by JohanBendz** [comment]
Hi @AvieNL, you can wait for the release of an version that support it or you can code the support yourself :)
I have it on my todo list and there is already an issue about it so I will close this issue.
