### ISSUE TITLE
Philips hue being pendant(?) support

### ISSUE THREAD

**Issue by daftwally** [sebbebebbe/com.philips.hue.zigbee#219]
It seems that the hue being light is supported but the other variant (the one that hangs down a bit, not sure what the English name is for this type of lamp) isn't yet supported.

Info:
Product ID: LTP008
Service ID: 544
Profile ID: 49246

Meethue.com link: https://www.philips-hue.com/nl-nl/p/hue-white-ambiance-being-hanglamp/4098430P7
(If I go to meethue.com I get redirected to there)

**Comment by daftwally** [comment]
And a quick question, if support is added down the line, will the lamp change to the correct one or doe I have to re-add it to homey to make it show up as the correct one?

**Comment by JohanBendz** [comment]
Hi @daftwally, thanks for your request. I will in time add all lights that are asked for but each and everyone needs to be added individually so they all end up in my todo list. Once a light (or other Hue device) has been added the device needs to be paired again using the new driver.

**Comment by JohanBendz** [comment]
Device added to upcoming SDK3 version of the app.
