### ISSUE TITLE
Hue motion sensor 1lx

### ISSUE THREAD

**Issue by GitHubLuigi** [sebbebebbe/com.philips.hue.zigbee#22]
Hi there, since this morning my Philips Hue motion sensor is stuck at measuring 1lx.
Restarting the app and restarting Homey both didn’t help.

**Comment by sebbebebbe** [comment]
Hi,

This is most likely an issue with the ZigBee implementation of Homey. In the latest Athom newsletter they mentioned that the ZigBee code will be redesigned eventually. Hopefully this will help.
