### ISSUE TITLE
Changing light temperature not working

### ISSUE THREAD

**Issue by jonasbkarlsson** [sebbebebbe/com.philips.hue.zigbee#220]
Hi! 
Had a bit of random problems with light temperature, using version 1.6.1.

After adding a new Philips Hue LCT012 (color candle E14) to Homey, change of light temperature did not work.
Removed it from Homey, and added it to Hue Bridge. Worked fine with Hue Bridge.
Updated firmware for the LCT012 from 1.29.0_r21169 to 1.50.2_r30933. Still worked fine with Hue Bridge. 
Removed from Hue Bridge, and added to Homey. 
Still not possible to change light temperature.
Restarted Homey. 
Change of light temperature worked.

Added another new Philips Hue LCT012 (color candle E14), change of light temperature worked.
Removed it from Homey, and added it to Hue Bridge. Worked fine with Hue Bridge.
Updated firmware for the LCT012 from 1.29.0_r21169 to 1.50.2_r30933. Still worked fine with Hue Bridge.
Removed from Hue Bridge, and added to Homey.
Now change of light temperature did not work any more.
Restarted Homey.
Change of light temperature did not work.
Restarted Philips Homey app.
Change of light temperature did not work.
Removed it from Homey, and added it back to Homey.
Change of light temperature worked.

All other functions, on/off, dimmer, setting light color (hue and saturation), worked fine. Only setting light temperature did not work.

I'm using Homey version: 4.2.0

**Comment by JohanBendz** [comment]
Hi @jonasbkarlsson and thanks for your feedback.
Can you please send me a crash log from the app? Comment it with your nickname, no need to send me the crash log code.

**Comment by jonasbkarlsson** [comment]
Crash log sent. Have restarted Homey at least once more after the trouble. Hope the log still contains information about yesterday.

**Comment by JohanBendz** [comment]
Hi @jonasbkarlsson, I will release a new test version with verbose zigbee logs enabled as I need more info to troubleshoot.

**Comment by jonasbkarlsson** [comment]
I can see that there is a test version 2.0.3. Do you want me to install that one, remove and add some lights to recreate the problem, and then send you a crash report? Before doing that, will the other devices that I have added with the current version 1.6.1, be unaffected by first installing 2.0.3, and then afterwards going back to 1.6.1? Or would you recommend me to stay on 2.0.3? (I'm using Homey version 4.2.0) Also, is it correct that removing a device and adding it back will give it a different ID, breaking all the flows that it was part of? That I have also seen with 1.6.1. (And after that I have started to use "< group >" to not break flows.)

**Comment by JohanBendz** [comment]
Ah, sorry jonasbkarlsson.. my fault! to many threads.. You should not go to v5 unless you really want to go to experimental.
I have no means to upgrade the current version 1.6.1 on the app store since I have a v5 compatible app in test phase.. so sadly you will have to wait until a stable v5 is out.

**Comment by JohanBendz** [comment]
I'm closing this issue. If you still have problems after upgrading to firmware 5 please create a new issue.
