### ISSUE TITLE
Australian Downlight Support

### ISSUE THREAD

**Issue by dzammit85** [sebbebebbe/com.philips.hue.zigbee#221]
Hi, was just wondering if the hue downlight would ever be getting added, Profuct id LTD011, Device id 268, It would be great if they were on there. appreciate all the work you’ve done already also, the this app works flawlessly for me. Thanks

**Comment by JohanBendz** [comment]
Hi @dzammit85, can you please provide a link to the device on Philips website or a store?

**Comment by dzammit85** [comment]
Yeah sure, here is the link to the Philips hue website
https://www.philips-hue.com/en-au/p/hue-white-ambiance-garnea-downlight/5110131H5

**Comment by JohanBendz** [comment]
OK, thx @dzammit85.
Now added to next release.
