### ISSUE TITLE
Philips garden light loses connection with homey 

### ISSUE THREAD

**Issue by pngoosen** [sebbebebbe/com.philips.hue.zigbee#222]
Since 2 weeks my Philips garden light Lucca (LWW001/256/49246) regularly loses connection with Homey . The Philips Hue Outdoor Sensor then sometimes also loses connection. The distance from the Lucca to the Homey is about 8 meters. The distance to the outdoor sensor is 9 meters (1 meter further away close to the Lucca). The Lucca operates as a router. Sometimes the Outdoor sensor which operates as end-device can hold the connection by connecting directly to the Homey. Why loses the router the connection? The distance shouldn't be the problem!
Restarting the Zigbee app and/or the Homey doesn't help. My solution is to open the Garden light remove the light bulb and place the bulb back again. Then after a few seconds the Lucca works fine again and the Outdoor sensor will also connect to the homey via the Lucca.

Any tips or a real solution? I read that more people experience the same problem. Some are hoping homey release 5 will solve this issue ......

**Comment by JohanBendz** [comment]
Hi @pngoosen, the new rewrite of Zigbee is handling routing better so hopefully your problem will not persist after the update.
Sadly I can do nothing to help you until then, your work around is the only one I know of too.

**Comment by pngoosen** [comment]
When will be the release of the new rewrite of Zigbee? I will note that date on my calendar and will monitor the problem after the update.

**Comment by JohanBendz** [comment]
Hi again @pngoosen, the stable version of firmware v5 from Athom will be released "when it's finished for release" ;)

There will likely not be any official date announced but one will have to find out it has been released when Athom so see fit.

**Comment by pngoosen** [comment]
I am using another work-around now. I created a flow that every 20 minutes switches the light off when it is off or switches the light on when it is already on. I hope this wake-up / keep awake flow forces communication between the Homey and the Garden light and as a result the Homey or the light bulb will not lose the connection. It seems to work!

**Comment by JohanBendz** [comment]
Hi @pngoosen. Thanks for the feedback, I have tried your "hack" and it looks like far away units actually stay connected better. I am looking into what can be done system wise to have units connect better, it might be an Athom issue though.

Closing the errand, feel free to start a new one if needed.

Thx // Johan
