### ISSUE TITLE
Hue Being detected as generic (new version?)

### ISSUE THREAD

**Issue by osauser** [sebbebebbe/com.philips.hue.zigbee#223]
I've read through the issue threads and see from the list that Hue Being is supported - however the one I installed yesterday is not detected properly. Performed an update of the lamp via Hue Bluetooth app before starting to integrate with Homey.
It appears as a generic device, with possibility of on/off. 

https://www.philips-hue.com/no-no/p/hue-white-ambiance-being-hue-taklys/3261031P6 (didn't find english version of product page - this is the Norwegian one :))

![IMG_A9AFE6712110-1](https://user-images.githubusercontent.com/70038233/90936348-50376b00-e405-11ea-8044-d8d36bf091e5.jpeg)
Screenshot from Homey app on iOS

Product id: 3261031P6

From the Athom dev page:

![image](https://user-images.githubusercontent.com/70038233/90938713-1d43a600-e40a-11ea-9603-604a90d7e5aa.png)

Tried repairing several times, upgrading from Homey 4.2 to 5.0 beta (and the corresponding 2.0.3 Phillips Hue Zigbee app)
(diagnostic report 19bcc1be-429d-4397-904f-5e27cc673cc8)

Downgrade of lamp next?

Best regards, Ola.

**Comment by JohanBendz** [comment]
Hi @osauser. Looks like I will have to add it to the app.. done! :) Will be supported in next release for Homey v.5.
