### ISSUE TITLE
Philips Hue Lightstrip Plus v4 - Unknown Zigbee device

### ISSUE THREAD

**Issue by nian66** [sebbebebbe/com.philips.hue.zigbee#224]
My Philips Hue Lightstup Plus v4 is an unknown Zigbee device. Can you please add it as a device so I can use it with my Homey.
Product ID: LCL001
Device ID: 269
Profile ID: 260

**Comment by SlyNL** [comment]
Same problem as nian66

**Comment by JohanBendz** [comment]
Hi @nian66 and @SlyNL. The Lightstrip has already been added to version 2 of the app (for Homey firmware 5).
I am however unable to uppgrade the current Stable version (for Homey firmware 4) since I already have a test app in there and I can only have one at a time.
