### ISSUE TITLE
Philips Hue Resonate - Unknown Zigbee device

### ISSUE THREAD

**Issue by ENdamOsionYS** [sebbebebbe/com.philips.hue.zigbee#225]
Hi,

I have a new Philips Hue Resonate outdoor lamp, but unfortunately it is not yet fully recognized in Homey.
Can you make this devices supported in the app?

Producent ID: Philips
Product ID: 1746447P7
Device ID: 269
Profile ID: 260

Thanks
Bart

**Comment by JohanBendz** [comment]
Added to version 2.0.4
