### ISSUE TITLE
LightStrips Plus added as generic ZigBee device

### ISSUE THREAD

**Issue by stba** [sebbebebbe/com.philips.hue.zigbee#228]
Is it the app or just me? 😬 Product id LCL001

**Comment by JohanBendz** [comment]
Hi @stba. LCL001 is supported by version 2.x of the app. This version only works on the experimental version 5.x of the Homey firmware. What firmware does your Homey run?

**Comment by suhajdab** [comment]
Same issue. I'm running Homey v4.2.0.
Is LCL001 not the same Lightstrip Plus one can choose in the app when adding the device?

**Comment by melkuier** [comment]
Also have the same problem. Also on 4.2.0. is there a chance it will be added to the 'old' version too?

**Comment by melkuier** [comment]
> Is it the app or just me? 😬 Product id LCL001

I dont kow how github works yet, but i have copied the lightstrip v1 files and changed the id's. loaded the files in my homey as a developper and it works here.  if u want i can send them..

**Comment by JohanBendz** [comment]
Hi  @suhajdab and @melkuier.
The lightstrip you guys want to add is not supported in the version for firmware 4.2.
Normally I would just add it over night but since I have uploaded a new version of the app for the upcoming firmware v5 I am unable to update the old version.

So sadly you guys will have to wait for the release of firmware v5 or install the experimental firmware (be aware of the risks and limitations).

**Comment by suhajdab** [comment]
@JohanBendz I'm not afraid to get my hands dirty. 😊
How do I go about updating the app files to make the required changes? From what I can tell the changes are rather minor, I just need to know how to make them in the app.

**Comment by suhajdab** [comment]
> > Is it the app or just me? 😬 Product id LCL001
> 
> I dont kow how github works yet, but i have copied the lightstrip v1 files and changed the id's. loaded the files in my homey as a developper and it works here. if u want i can send them..

So you essentially created your own version of Johan's Zigbee app and added that? If so, wouldn't that mean your devices will need to be re-added at some later point when you want to switch back to using Johan's original?

**Comment by melkuier** [comment]
> > > Is it the app or just me? 😬 Product id LCL001
> > 
> > 
> > I dont kow how github works yet, but i have copied the lightstrip v1 files and changed the id's. loaded the files in my homey as a developper and it works here. if u want i can send them..
> 
> So you essentially created your own version of Johan's Zigbee app and added that? If so, wouldn't that mean your devices will need to be re-added at some later point when you want to switch back to using Johan's original?

yes. i just looked what files changed with the latest added product. those files i copied from the older ligthstrip plus and gave it the specs from the new ligthstrip. then i updated the app under developper. 
here is an dutch video how that works. 
https://youtu.be/JnjAyWKSEIE
then the device is recognised as the lightstrip. 
works great.!
so if u want the working files, just ask. i can send them and u can use it till version 5.0 is out of beta

**Comment by JohanBendz** [comment]
Added to firmware 5 version
