### ISSUE TITLE
LightStrips outdoor 2M added as generic ZigBee device

### ISSUE THREAD

**Issue by kjaski** [sebbebebbe/com.philips.hue.zigbee#229]
Hi, have tried to add 2 ledstrip outdoor 2m. Both come up as generic ZigBee device, LCL002.

**Comment by JohanBendz** [comment]
Hi @kjaski . LCL001 is supported by version 2.x of the app. This version only works on the experimental version 5.x of the Homey firmware. What firmware does your Homey run?

**Comment by kjaski** [comment]
Philips v1.6.1
Homey 4.2.0

**Comment by JohanBendz** [comment]
@kjaski OK, then you will either have to upgrade to experimental firmware v5 or wait for it to be released to stable channel.
