### ISSUE TITLE
Add Philips Hue Outdoor Resonate

### ISSUE THREAD

**Issue by bjoo8931** [sebbebebbe/com.philips.hue.zigbee#230]
Hi Johan,

I’ve just bought a Philips Hue Outdoor Resonate and it would be great if I could control this directly via Homey. Do you think this is feasible?

Thanks!

Regards,

Bob

**Comment by JohanBendz** [comment]
Hi @bjoo8931. Hue Outdoor Resonate is supported by version 2.x of the app. This version only works on the experimental version 5.x of the Homey firmware.

**Comment by bjoo8931** [comment]
Hi Johan, thanks for the very fast reply and clarification! Will update the Homey firmware once its a stable build then.
    	
    	

    	
    
  




On Wed, Sep 2, 2020 at 10:14 PM +0200, "Johan Bendz" <notifications@github.com> wrote:















Hi @bjoo8931. Hue Outdoor Resonate is supported by version 2.x of the app. This version only works on the experimental version 5.x of the Homey firmware.
