### ISSUE TITLE
Dimmer switch - Short and long release triggers

### ISSUE THREAD

**Issue by SelfDestructor** [sebbebebbe/com.philips.hue.zigbee#231]
Hi!

Is it possible to implement short and long release triggers on all 4 buttons on the dimmer switch?

**Comment by JohanBendz** [comment]
Hi @SelfDestructor, only the dimmer buttons have Zigbee support for level control and this is what is needed to trigger on held and released. The dimmer buttons only support pressed and released, I could add long or short press to the app but you can also handle this in a flow with a counter that starts on held and stops on released.

**Comment by SelfDestructor** [comment]
Huh, I thought it was the switch that did long press detection.

If your app could detect short and long release, it would save me and perhaps others from creating multiple logic and flows for each switch to detect what button was pressed before release.
Assuming there are more people who likes to have different functions on short and long press. If it's a lot of work to implement, then perhaps throw it on the backlog for a feature suggestions for the future. I can work with a counting flow. :)

Also are you saying that the on and off buttons can't send a repeating signal when connected to the Homey?
They appear to do so when linked with the Hue hub with the green LED blinking when holding down ON or OFF.

**Comment by Vincent75b** [comment]
I was going to ask the same ;-)  After the v5 update my dimmer switches are finally working without the Hue hub so I am happy... the extra functionality would be awesome, since the Homey flows are not always working if you want to use the "double press" option for example. Thanks for your work btw!

**Comment by JohanBendz** [comment]
@SelfDestructor  On and Off does not send more than one command per press. Dim buttons send one command every .8 second (roughly). I have put "add a long and short press flow card" to my todo list. :)
