### ISSUE TITLE
Unreliable switching

### ISSUE THREAD

**Issue by DavidRCT** [sebbebebbe/com.philips.hue.zigbee#232]
Hi,

I’ve just installed the Homey Pro and looking to move 50+ Hue devices over to Homey. As a test I moved around 8 bulbs, 3 switches and 2 movement detectors. Over half the time bulbs are not responding or are not set Incorrectly, Hue dimmer switches will also sometimes not respond and flash red and green.

The Hue hub is sill running and works fine, as a test I’ve also added the Hue Hub to Homey. After some playing with the way Flows address the bulbs (send all dim then colour settings) it seems to work fine, the Hue Hub connected device work fine.

Have I missed some, has anyone got any ideas?
Thanks
David

**Comment by JohanBendz** [comment]
Hi @DavidRCT, sorry for late answer.
What Firmware are you using?

**Comment by DavidRCT** [comment]
Please see screen shot, the door sensor is intermittently working but more not than is. I don’t think it’s a range issue as I’ve moved the quad switch next to the door sensor and it works %100

**Comment by JohanBendz** [comment]
Hi again. I think you forgot to attach the screen shot :)

**Comment by DavidRCT** [comment]
Just checked I did send them but hopefully this time you’ll get them 😁

**Comment by JohanBendz** [comment]
Hmm, no.. sorry... not here and not in mail...
Perhaps you can mail me directly?

**Comment by JohanBendz** [comment]
OK, thanks! Got it now on email. :)
You run Homey firmware 4.2 and I guess the latest version of the app for that version of the firmware.

That's correct, I am not with Athom but a community developer. So Boas is right, as this app is done by me and not Athom he can't help you. But I will try! :)

Can you please send a crash report from the Philips Hue Zigbee app?

**Comment by DavidRCT** [comment]
Thanks Johan I appreciate your help. 

I’ve done a lot of testing and think I’ve found one of the problems. Initially everything was running fine but for some reason Homey totally crashed and ground to a halt z-wave and Zigbee just didn’t work and Homey itself was very slow to respond, this happened sometime after I installed the Aeotec App, however I can’t be sure that’s what caused it. After about a day it seemed to sort itself out and the Zigbee devices started to respond along with with Quad switch and Doorbell 6 (I’ve had to return this however).

Now it seems only the door contacts (Sensor 7) are very hit and miss if they work, I’ve now removed them from the doors and started to walk around the house testing them. If I’m within 10 to 15 meter of Homey they work great any further and they don’t work, the Quad switch is slightly better over 15 meters and it stops responding.

So I guess I have 2 questions, what caused Homey to crash, is it likely to happen again and is the z-wave range that bad? I thought it was a lot better than that, although not having any mains z-wave devices I guess there is no mesh network in place.

Thanks again for your help.
David

**Comment by JohanBendz** [comment]
Hi @DavidRCT, hope things are working out better for you now.

Z-wave reach is directly connected to the number of wall powered units you have in your mesh. Only those route the traffic and the more the merrier.

Homey should not crash on you, but from time to time you might need to pull the plug and let it be for 11 minutes, this frees up any memory thieves and refreshes the system.

I'm closing the errand, if you have issues with the Philips Hue Zigbee app in the future please open a new errand.

Thx // Johan
