### ISSUE TITLE
Support for Lily XL

### ISSUE THREAD

**Issue by AH-audio** [sebbebebbe/com.philips.hue.zigbee#233]
Hello!

https://www.philips-hue.com/sv-se/p/hue-white-and-color-ambiance-lily-xl-spotlight-for-utomhusbruk/1746230P7

![IMG_2285](https://user-images.githubusercontent.com/38322181/93778973-bd1d6b00-fc26-11ea-9870-825567e94c70.png)

**Comment by JohanBendz** [comment]
Thx, will add it to the new version.

**Comment by JohanBendz** [comment]
Added to next firmware 5 version of the app.
