### ISSUE TITLE
[New-Device] Philips Hue White Runner spot

### ISSUE THREAD

**Issue by Allram** [sebbebebbe/com.philips.hue.zigbee#234]
A new product to integrate if you can 👍 

Link to product: https://www.philips-hue.com/en-gb/p/hue-white-ambiance-runner-single-spotlight-ext/5309031P8

ProductID: 5309031P9

White Ambiance.
![158068e9719442a4bc8aa9b900a5228e](https://user-images.githubusercontent.com/5573149/94271845-7ee3bc80-ff42-11ea-8fe5-0c02d342132a.jpg)

**Comment by JohanBendz** [comment]
Hi @Allram, thx for the request.

**Comment by JohanBendz** [comment]
Hi again @Allram, just wanna check with you. You say the product ID is ending with 9 but the product page show 8. What is correct?

**Comment by Allram** [comment]
> Hi again @Allram, just wanna check with you. You say the product ID is ending with 9 but the product page show 8. What is correct?

P9 is correct. I linked to the Extension lamp instead of the correct one.
https://www.philips-hue.com/en-gb/p/hue-white-ambiance-runner-single-spotlight-ext/5309031P9

**Comment by JohanBendz** [comment]
OK, added to next version
