### ISSUE TITLE
Philips Pendant added as basic ZigBee devices

### ISSUE THREAD

**Issue by shaarkys** [sebbebebbe/com.philips.hue.zigbee#235]
Hi,
when I'm adding Philips Pendant (LCP001, LCP002) I get error and it's added as Basic ZigBee device.
**Philips Hue ZigBee app version 2.0.6
Latest Homey experimental v5.0.0-rc.34**

Should be this one : https://zigbee.blakadder.com/Philips_LCP001.html

Based on details, it should be supported as "Hue Ensis Pendant (4090331P9)' - but seems the ProductID is different.
Also it's not possible to add one device, but only as two separated.

**Comment by shaarkys** [comment]
Node interview result for one of the light

>   "ids": {
>     "modelId": "LCP002",
>     "manufacturerName": "Philips"
>   },
>   "endpoints": {
>     "endpointDescriptors": [
>       {
>         "endpointId": 11,
>         "applicationProfileId": 49246,
>         "applicationDeviceId": 528,
>         "applicationDeviceVersion": 0,
>         "_reserved1": 2,
>         "inputClusters": [
>           0,
>           3,
>           4,
>           5,
>           6,
>           8,
>           4096,
>           768,
>           64513
>         ],
>         "outputClusters": [
>           25
>         ]
>       },
>       {
>         "endpointId": 242,
>         "applicationProfileId": 41440,
>         "applicationDeviceId": 97,
>         "applicationDeviceVersion": 0,
>         "_reserved1": 0,
>         "inputClusters": [
>           33
>         ],
>         "outputClusters": [
>           33
>         ]
>       }
>     ],
>     "endpoints": {
>       "11": {
>         "clusters": {
>           "basic": {
>             "attributes": [
>               {
>                 "id": 0,
>                 "name": "zclVersion",
>                 "value": 1
>               },
>               {
>                 "id": 1,
>                 "name": "appVersion",
>                 "value": 2
>               },
>               {
>                 "id": 2,
>                 "name": "stackVersion",
>                 "value": 1
>               },
>               {
>                 "id": 3,
>                 "name": "hwVersion",
>                 "value": 1
>               },
>               {
>                 "id": 4,
>                 "name": "manufacturerName",
>                 "value": "Philips"
>               },
>               {
>                 "id": 5,
>                 "name": "modelId",
>                 "value": "LCP002"
>               },
>               {
>                 "id": 6,
>                 "name": "dateCode",
>                 "value": "20191218"
>               },
>               {
>                 "id": 7,
>                 "name": "powerSource",
>                 "value": "mains"
>               },
>               {
>                 "id": 16384,
>                 "name": "swBuildId",
>                 "value": "1.50.2_r30933"
>               }
>             ],
>             "commandsGenerated": "UNSUP_GENERAL_COMMAND",
>             "commandsReceived": "UNSUP_GENERAL_COMMAND"
>           },
>           "identify": {
>             "attributes": [
>               {
>                 "id": 0
>               }
>             ],
>             "commandsGenerated": "UNSUP_GENERAL_COMMAND",
>             "commandsReceived": "UNSUP_GENERAL_COMMAND"
>           },
>           "groups": {
>             "attributes": [
>               {
>                 "id": 0,
>                 "name": "nameSupport",
>                 "value": {
>                   "type": "Buffer",
>                   "data": [
>                     0
>                   ]
>                 }
>               }
>             ],
>             "commandsGenerated": "UNSUP_GENERAL_COMMAND",
>             "commandsReceived": "UNSUP_GENERAL_COMMAND"
>           },
>           "scenes": {
>             "attributes": [
>               {
>                 "id": 0
>               },
>               {
>                 "id": 1
>               },
>               {
>                 "id": 2
>               },
>               {
>                 "id": 3
>               },
>               {
>                 "id": 4
>               }
>             ],
>             "commandsGenerated": "UNSUP_GENERAL_COMMAND",
>             "commandsReceived": "UNSUP_GENERAL_COMMAND"
>           },
>           "onOff": {
>             "attributes": [
>               {
>                 "id": 0,
>                 "name": "onOff",
>                 "value": true
>               },
>               {
>                 "id": 16384
>               },
>               {
>                 "id": 16385,
>                 "name": "onTime",
>                 "value": 0
>               },
>               {
>                 "id": 16386,
>                 "name": "offWaitTime",
>                 "value": 0
>               },
>               {
>                 "id": 16387
>               }
>             ],
>             "commandsGenerated": "UNSUP_GENERAL_COMMAND",
>             "commandsReceived": "UNSUP_GENERAL_COMMAND"
>           },
>           "levelControl": {
>             "attributes": [
>               {
>                 "id": 0,
>                 "name": "currentLevel",
>                 "value": 254
>               },
>               {
>                 "id": 1,
>                 "name": "remainingTime",
>                 "value": 0
>               },
>               {
>                 "id": 16384
>               }
>             ],
>             "commandsGenerated": "UNSUP_GENERAL_COMMAND",
>             "commandsReceived": "UNSUP_GENERAL_COMMAND"
>           },
>           "touchlink": {
>             "attributes": [],
>             "commandsGenerated": "UNSUP_GENERAL_COMMAND",
>             "commandsReceived": "UNSUP_GENERAL_COMMAND"
>           },
>           "colorControl": {
>             "attributes": [
>               {
>                 "id": 0,
>                 "name": "currentHue",
>                 "value": 32
>               },
>               {
>                 "id": 1,
>                 "name": "currentSaturation",
>                 "value": 140
>               },
>               {
>                 "id": 2
>               },
>               {
>                 "id": 3,
>                 "name": "currentX",
>                 "value": 29972
>               },
>               {
>                 "id": 4,
>                 "name": "currentY",
>                 "value": 26871
>               },
>               {
>                 "id": 7,
>                 "name": "colorTemperatureMireds",
>                 "value": 366
>               },
>               {
>                 "id": 8,
>                 "name": "colorMode",
>                 "value": "colorTemperatureMireds"
>               },
>               {
>                 "id": 16
>               },
>               {
>                 "id": 17
>               },
>               {
>                 "id": 18
>               },
>               {
>                 "id": 19
>               },
>               {
>                 "id": 21
>               },
>               {
>                 "id": 22
>               },
>               {
>                 "id": 23
>               },
>               {
>                 "id": 25
>               },
>               {
>                 "id": 26
>               },
>               {
>                 "id": 27
>               },
>               {
>                 "id": 48
>               },
>               {
>                 "id": 49
>               },
>               {
>                 "id": 50
>               },
>               {
>                 "id": 51
>               },
>               {
>                 "id": 52
>               }
>             ],
>             "commandsGenerated": "UNSUP_GENERAL_COMMAND",
>             "commandsReceived": "UNSUP_GENERAL_COMMAND"
>           }
>         },
>         "bindings": {
>           "ota": {
>             "attributes": [],
>             "commandsGenerated": "UNSUP_GENERAL_COMMAND",
>             "commandsReceived": "UNSUP_GENERAL_COMMAND"
>           }
>         }
>       },
>       "242": {
>         "clusters": {},
>         "bindings": {}
>       }
>     }
>   }
>

**Comment by shaarkys** [comment]
![obrazek](https://user-images.githubusercontent.com/14859895/94436600-edbc5200-019c-11eb-9a74-941f36f780e4.png)

**Comment by shaarkys** [comment]
![obrazek](https://user-images.githubusercontent.com/14859895/94436653-fca30480-019c-11eb-822a-deb3a97b483b.png)

**Comment by shaarkys** [comment]
Well, I got it fixed by myself basically by removing 4090331P9_x to appropriate ModelIDs where-ever I found it.
4090331P9_01 and 4090331P9_02 to LCP001 and LCP002, and removed 4090331P9 itself.
Yet I have no idea if this is right or not.

**Comment by JohanBendz** [comment]
Hi @shaarkys, thanks for the info. I will add LCP001 and LCP002 to the app. As you already have noticed that's the same devices as 4090331P9_x's (devices can have different names given when they were produced).

I see you deleted the device 4090331P9, did it interfere with your device or did you remove it anyway?

**Comment by shaarkys** [comment]
Hi @JohanBendz ,it did not interfere, I'm just lazy to figure out right source code structure (not developer...), so I simply deleted not needed devices to be able to get lights working quickly for me , and used search and replace :-)

**Comment by JohanBendz** [comment]
Added to next version of the app for firmware 5
