### ISSUE TITLE
Please add "last dim state" option to bulbs

### ISSUE THREAD

**Issue by Vincent75b** [sebbebebbe/com.philips.hue.zigbee#236]
About a year ago, Philips updated the firmware of the bulbs with the option to "remember last dim state".

The Hue bulbs have the annoying habit (Philips says its for safety) to "dim" to 100% after a power outage (or a visitor that tries to turn on a light by the switch). The added option gives the option to "remember" the last dim state. I noticed this only works one time, but it was enough.

Since Homey v5, I could finally toss the Hue hub. Thanks for that btw! ;-)  Unfortunately, I have the problem back with the bulbs going to 100%. 

Is it possible to integrate the option "remember last dim state" in Homey? Or maybe a workaround? For example, a trigger or status that can be used to see when a light is switched on to 100%?

I noticed the issue has been discussed many times on the forum, but I could not find an answer or reason why it can't be done. Sorry if I overlooked...

Thanks in advance!

**Comment by shaarkys** [comment]
I just noticed the same after power-outage - it would be great to have some solution for that ;-)

**Comment by JohanBendz** [comment]
Hi all, working on this :)

**Comment by JohanBendz** [comment]
Now added to live version.
