### ISSUE TITLE
Add Filament G125 (E27)

### ISSUE THREAD

**Issue by rvdeijk** [sebbebebbe/com.philips.hue.zigbee#238]
I would like to have the Filament G125 added to the Philips Hue Zigbee app inside Homey.
Right now it's added as a 'Unknown Zigbee device'/

Product ID: LWO003
Service ID: 257
Profile ID: 260

![Screenshot_20201006-125749_Homey](https://user-images.githubusercontent.com/35557458/95196440-5c6e6080-07d8-11eb-8f05-2ba757e279fd.jpg)

[meethue: Filament G125 website](https://www.philips-hue.com/nl-nl/p/hue-white-filament-1-pack-g125-e27-globe-met-zichtbare-gloeidraad/8719514279131)

**Comment by JohanBendz** [comment]
Thx, added to todo list :)

**Comment by JohanBendz** [comment]
Added to next release of the app (for firmware 5)

**Comment by rvdeijk** [comment]
Thx!!
