### ISSUE TITLE
Hue ligt status not correct

### ISSUE THREAD

**Issue by Reemster** [sebbebebbe/com.philips.hue.zigbee#24]
I have a lot that Homey say that the light is off (status) but the light is ON. So Homey don't trigger the flow for OFF, so the lights stay ON most of the time.

I already send a email about this, to Athom. But they told me that i must contact the maker of the Hue zigbee app.. I have also sometimes that the Hue bulp don't go OFF. I get a error when thats happen. See screenshot.

![hue light](https://user-images.githubusercontent.com/19860405/44356785-ab4dc480-a4b0-11e8-958e-5d6513363b96.jpg)
![huelight error](https://user-images.githubusercontent.com/19860405/44356787-abe65b00-a4b0-11e8-95fd-d4175eb14d23.jpg)

**Comment by sebbebebbe** [comment]
Since there isn´t any code that handles network routes in the app i made. I am sorry to say that i cannot fix the issue. :(
 
Athom has stated before that they need to rewrite the zigbee drivers.
