### ISSUE TITLE
Impress outdoor wall light small

### ISSUE THREAD

**Issue by EmielPijn** [sebbebebbe/com.philips.hue.zigbee#240]
A few months ago I asked you to add the Impress outdoor wall light small. Thank you very much for adding, but I cannot connect to the lamp. I get the message "no program is found for this device. The device has been added as a simple Zigbee device", see picture below(sorry, is Dutch). Would you like to take another look at this? Thanks!

![IMG_1471](https://user-images.githubusercontent.com/69204917/96506123-658b1300-1257-11eb-9a30-018606269a40.png)

![IMG_1472](https://user-images.githubusercontent.com/69204917/96506133-6a4fc700-1257-11eb-9835-33239b539cd1.png)

**Comment by JohanBendz** [comment]
Hi @EmielPijn, the device is added to the version of the app that works on firmware 5.
I understand if you do not want to install the experimental firmware 5 but sadly I am unable to update the old app (for firmware 3 and 4) after releasing the firmware 5 version (limitation in the app store).

**Comment by EmielPijn** [comment]
Hi Johan, thanks for your reply. I didn't know about the experimental firmware 5. I will test it.
