### ISSUE TITLE
Unknown Zigbee device (Lucca Outdoor Garden Light)

### ISSUE THREAD

**Issue by Chrissba** [sebbebebbe/com.philips.hue.zigbee#243]
Hi

I’m trying to connect a Lucca Outdoor Garden Light, but it will only show as unknown device.
I notice that the profile ID dos not match the one from your code, this is the info for my device:

Manufacturer ID:	Philips
Product ID: 		LWF001
Device ID: 		256
Profile ID: 		9246

Can you please add this Product ID?

Thanks,
Chriss

**Comment by JohanBendz** [comment]
Hi @Chrissba, can you please verify that this is the device you have: https://www.philips-hue.com/en-us/p/hue-white-lucca-outdoor-wall-light/1734630V0

**Comment by Chrissba** [comment]
Hi,
That is not the device, this is the one: https://www.philips-hue.com/en-gb/p/hue-white-lucca-outdoor-pedestal/1740293P0

**Comment by JohanBendz** [comment]
Hi @Chrissba and thanks for clarification. I have added the product ID to the app, will be supported after next update.
