### ISSUE TITLE
Hue motion sensor and holding time before no motion

### ISSUE THREAD

**Issue by dagengstrom** [sebbebebbe/com.philips.hue.zigbee#244]
Hi
I just installed Philips motion sensor and it works nice. 
I have some problem to understand these two parameters: Min report interval for motion and Max report interval for motion. How do this 2 parameters works? What I'm looking for is motion and a hold time i.e. motion hold for 180 second before no motion. Can I do that with the existing parameters?
Best Regards
Dag

**Comment by JohanBendz** [comment]
There was issues in firmware 4x, Rewritten in firmware 5 and should now work.
