### ISSUE TITLE
REQUEST - Philips Hue Being White

### ISSUE THREAD

**Issue by Jugge72** [sebbebebbe/com.philips.hue.zigbee#245]
Tillverkar ID: Philips
Produkt ID: 3261031P6
Enhets ID: 268

https://www.elgiganten.se/product/hem-och-hushall/lampor-och-belysning/lampor/191030/philips-hue-being-taklampa-3261031p6-vit

**Comment by JohanBendz** [comment]
Hej @Jugge72, this device is already supported by the app version for Homey firmware 5. I am unable to update the version for older firmwares. (Athom app store does not support it)

https://homey.app/sv-se/app/com.philips.hue.zigbee/Philips-Hue-ZigBee/test/
