### ISSUE TITLE
Philips hue bloom

### ISSUE THREAD

**Issue by leppis1** [sebbebebbe/com.philips.hue.zigbee#246]
Hi, i connect my new hue bloom to my homey pro whit philips hue zigbee app and it connected, but it says that it is unknown device and there is no app for that and only connect that "basic Zigbee device" so i only can get lights on or off, so is there any solutions for that? or due i have to bought philips hue bridge?
Manufacturer ID:Philips
Product ID: 929002375901

And i am very sorry for my bad english.

**Comment by JohanBendz** [comment]
Hi @leppis1
Do you run Homey firmware 4.2 or 5? Bloom is supported by the app byt only if you run firmware 5. 
I do see however that your product ID is not in the app, I will add it asap.

**Comment by leppis1** [comment]
Hi, my homey firmware version is 5.0.0-rc.38
Thanks if you can fix it soon.

**Comment by JohanBendz** [comment]
Great! I have added it to the code, will be in next update.
