### ISSUE TITLE
Request to add new LED strip plus

### ISSUE THREAD

**Issue by Emile86** [sebbebebbe/com.philips.hue.zigbee#248]
Hi,
I just bought 2m led strip plus but homey recognize it as standard zigbee device

Device info:

Product ID: LCL001
Device id: 269

![Screenshot_2020-11-14-16-18-04-256_app homey](https://user-images.githubusercontent.com/43245874/99150715-c101c280-2696-11eb-9b75-5bf69dc61058.jpg)

Thank you

**Comment by Emile86** [comment]
Bought today another one from other shop and result is same, not recognized by homey

**Comment by JohanBendz** [comment]
Hi @Emile86, the device is already supported by the version of the app that is for firmware 5.

**Comment by Emile86** [comment]
Oke, where can i find version for firmware 5?.
Thanks

**Comment by dirkg173** [comment]
https://homey.app/de-de/app/com.philips.hue.zigbee/Philips-Hue-ZigBee/test/

**Comment by Pieter87** [comment]
I'm having the exact same problems that Emile is describing. When trying to install the beta app gives me the following message: [incompatible_app_version].

**Comment by Emile86** [comment]
You have to upgrade Homey firmware to 5 (beta)

**Comment by Pieter87** [comment]
Thanks

**Comment by Pieter87** [comment]
Unfortunately the ledstrip is still not recognized and installed as a simple zigbee device. (Homey v5.0.0-rc.43 and Philips Hue zigbee v2.0.12)

**Comment by JohanBendz** [comment]
Hi @Pieter87, can you please interview the device and post the output here?
https://developer.athom.com/tools/zigbee

**Comment by Pieter87** [comment]
I tried multiple interviews but every time I end up with a timeout error.

**Comment by JohanBendz** [comment]
Hi @Pieter87, there has been a few updates last 24 hours. Can you try update your Homey to latest update and see if you now can interview the device?

**Comment by Pieter87** [comment]
Hi @JohanBendz same result as before. (error: timeout)

**Comment by JohanBendz** [comment]
Hi again @Pieter87, still an issue with the latest firmware?
If so I suggest you contact Athom support (support@athom.com) since it's a Homey problem and not related to the Philips Hue app.

**Comment by Pieter87** [comment]
Hi @JohanBendz still no joy. I'll contact athom. Although I'm curious if @Emile86 was able to solve this problem.

**Comment by Emile86** [comment]
I have changed led strip for the older model which works with homey because i don't want to migrate to v5 till there is a stable v5.1 to be sure

**Comment by Pieter87** [comment]
Solved! With Philips Hue ZigBee v2.0.14 the strip is recognized! Thanks everyone for the help.
