### ISSUE TITLE
Adding a Hue Iris

### ISSUE THREAD

**Issue by rwdp** [sebbebebbe/com.philips.hue.zigbee#249]
Could you add the Philips Hue Iris, please? I added it as a Iris Living Colors (since I thought this is the same device). The app couldn't find the Hue version of it, so added it automatically as a generic zigbee device.

Device: https://www.philips-hue.com/nl-nl/p/hue-white-and-color-ambiance-iris-tafellamp/8719514264489

![IMG_3878](https://user-images.githubusercontent.com/75021163/100223511-e35bd180-2f1b-11eb-8c70-f65bae1f35cb.PNG)

**Comment by JohanBendz** [comment]
Hi @rwdp, thanks for your request. I will add this product id to the next release of the app for firmware 5. I am unable to update the older version of the app for firmware 4 as Athoms app store rules does not let me do that.

**Comment by rwdp** [comment]
Thanks! I just discovered that the Homey developers are busy with firmware 5.0 Do you have any idea when they will release it?

**Comment by JohanBendz** [comment]
Hi again. It's now added to the version for firmware 5.
No, only Athom knows when they will release it.

**Comment by rwdp** [comment]
Thanks for the update! I will wait (im)patiently then. ;)
