### ISSUE TITLE
Support for Philips Hue Beyond

### ISSUE THREAD

**Issue by rickardp** [sebbebebbe/com.philips.hue.zigbee#25]
Product ID is LLM001. Product link: https://www2.meethue.com/sv-se/p/hue-white-and-color-ambiance-beyond-bordslampa/7120231PH

Using it as a generic ZigBee device will only control half of its LEDs

**Comment by sebbebebbe** [comment]
This one has already been added. Will be included in upcoming release.

**Comment by rickardp** [comment]
That’s great, but I just wanted to double check. The product ID for the lamp is LLM001 as reported by the Homey (v2) app. I see the Beyond product defined under a different ID (HBL001) in the source code.

Also, the Beyond is supposed to have two LED modules, individually controllable, while the HBL001 only seems to inherit from the same base class as normal RGB bulbs. Or am I missing something?

**Comment by rickardp** [comment]
I added LLM001 as a copy of HBL001 and it seems to be able to control the top part of the lamp correctly.

I then saw https://github.com/athombv/homey/issues/2137

I guess this means the bottom part won’t work until the meshdriver is fixed?

**Comment by sebbebebbe** [comment]
Nice info.

Yes HBL001 is the grouping info ID for the two bulbs, according to the Hue Developer page, which in my opinion is not the best source of information.

Copied from Hue Developer page supported product:

Product Name | Number of light modules | Model ID luminaire group
Hue Beyond Table | 2 | HBL001

I am lacking a bunch of information regarding the Aurelle panels and Asana Wall light, which isn´t even mentioned on their developer pages.

Regarding your bottom part lamp, I am afraid it looks like you have to wait for an update.
