### ISSUE TITLE
Lightstrip plus

### ISSUE THREAD

**Issue by xabbakal** [sebbebebbe/com.philips.hue.zigbee#250]
Hi Johan, please add support for LCL01, see attached picture
Thanks!

![3EBAC94E-37F6-427B-A3C3-70781CA973DC](https://user-images.githubusercontent.com/35507542/100261971-ce973200-2f4b-11eb-8584-aac6dd7bbd59.png)

**Comment by JohanBendz** [comment]
Same as: https://github.com/JohanBendz/com.philips.hue.zigbee/issues/248
