### ISSUE TITLE
Lightstrip outdoor 5m

### ISSUE THREAD

**Issue by hylandk** [sebbebebbe/com.philips.hue.zigbee#251]
Can you please add lightstrip outdoor 5m
https://www.philips-hue.com/sv-se/p/hue-white-and-color-ambiance-lightstrip-for-utomhusbruk-5-meter/8718699709853

![CB49ECC5-1066-43C4-8BE1-96170DD4CE15](https://user-images.githubusercontent.com/75036006/100269462-dc05e980-2f56-11eb-99ed-2864f533a23c.png)

**Comment by solidsystem** [comment]
Hi, this is already in the experimental Homey v5 version of the app. I'm using it with that version. So I doubt it will get added to the older stable version. (But I'm not the developer of this app)

**Comment by JohanBendz** [comment]
Hi @hylandk. @solidsystem is correct, it's added to the firmware 5 version of the app and I am unable to update the old version of the app. (Athom rules for App store)
