### ISSUE TITLE
Philips Hue Play Light Bar

### ISSUE THREAD

**Issue by AllanMcK** [sebbebebbe/com.philips.hue.zigbee#252]
Hey guys,
The Philips Hue Play Light Bar does not appear to work. It’s only appearing as a Unknown Zigbee Device. 

https://www.philips-hue.com/en-au/p/hue-white-and-color-ambiance-play-light-bar-single-pack/7820130N7

![97430276-BF95-42A2-A19F-5F5CBCD41731](https://user-images.githubusercontent.com/75157869/100496243-9c354100-31a6-11eb-85f0-fde963f3f60e.png)

**Comment by JohanBendz** [comment]
Hi @AllanMcK , support for that device is added to the test version of the app, only available for Homey Firmware 5.

**Comment by AllanMcK** [comment]
Hi Johan,
Do you have a test version support for AU? I tried to install off a previous thread where you posted the link however was unsuccessful. 
Thanks!

**Comment by JohanBendz** [comment]
Hi @AllanMcK, https://homey.app/it-it/app/com.philips.hue.zigbee/Philips-Hue-ZigBee/test/
If you are unable to install this version it's because you don't run Homey firmware 5 (experimental).
