### ISSUE TITLE
adding Lily XL

### ISSUE THREAD

**Issue by MrV34** [sebbebebbe/com.philips.hue.zigbee#253]
support for lily xl would be nice.

https://www.philips-hue.com/sv-se/p/hue-white-and-color-ambiance-lily-xl-spotlight-for-utomhusbruk/1746230P7

Manufacturer ID : Philips
Product ID: 1746230P7
Device ID: 269
Profile ID: 260

/P

**Comment by JohanBendz** [comment]
Hi @MrV34, this device is already added to the firmware 5 version of the app.
https://homey.app/sv-se/app/com.philips.hue.zigbee/Philips-Hue-ZigBee/test/
