### ISSUE TITLE
Play Lightbar Not Adding

### ISSUE THREAD

**Issue by davidhalford** [sebbebebbe/com.philips.hue.zigbee#254]
Hi, I've just tried to add a Play Lightbar to Homey, which should work as the device is supported/selectable in the list. I can only add it as a generic Zigbee Device and only switch it on/off (that part works). I'm guessing maybe there is a new firmware/productID or something?

The product I'm trying to add: https://www.philips-hue.com/nl-nl/p/hue-white-and-color-ambiance-play-tafellamp--enkelpak/7820131P7 (but the black one, don't think that matters). It's basically the Play Light Bar Base Unit.

Zigbee info:
Producent ID: Philips
Product ID: 440400982841
Apparaat ID: 269
Profiel ID: 260

Please help me out, this i my first Hue light and I'd like it to work. If you need any more info, let me know!

**Comment by JohanBendz** [comment]
Hi @davidhalford, this device is already added to the version of the app that works on firmware 5.
Firmware 5 is however still in experimental so if you want to stay on a stable firmware I suggest you wait for the release of firmware 5. (I for one think firmware 5 works just great! but.. it's on experimental..)
