### ISSUE TITLE
Philips Hue Impress path

### ISSUE THREAD

**Issue by staleso** [sebbebebbe/com.philips.hue.zigbee#255]
Hi and thank you for your great work with the app! :) much appreciated.

I just upgradet to newest Firmware 5 rc47.

Trying to add Hue Impress, but ends up just with Basic Zigbee.
Philips 1745430P7.

Hope for any help :)

Br, Staale

**Comment by JohanBendz** [comment]
Hi @staleso, I see that this product ID is not in the app. I can add it but I would like to know a bit more about the device. Can you add a link to the device on Philips website or where you bought it? (I need to know if it's a pedestal light, wall light, path light or something else..)

**Comment by staleso** [comment]
Hi, thank you.

Maybe this link is useful:

https://www.philips-hue.com/en-gb/p/hue-white-and-colour-ambiance-impress-outdoor-pedestal-light/1743130P7

Reg, Staale

**Comment by JohanBendz** [comment]
OK, thanks! I'v now added it, will be in next update.

**Comment by staleso** [comment]
Hi, thanks for fixing!
The impress lamp works great, however, I also have the extension. Could it be they both need to be incorporated? Only difference I find is S/N.
- impress s/n 0657A7 (works)
- impress ext s/n 010D24 (not working)

Lamps look exactly the same. Thanks :)
