### ISSUE TITLE
Support for A67 E27

### ISSUE THREAD

**Issue by icaros1** [sebbebebbe/com.philips.hue.zigbee#259]
Hi
Would appreciate if you can add support for https://www.philips-hue.com/sv-se/p/hue-white-1-pack-a67-e27/8718699747992

Great work btw, thank you.
![Screenshot_20201211-165355_Homey](https://user-images.githubusercontent.com/75850843/101925776-8b3af580-3bd2-11eb-8455-0bce41c88fba.jpg)

**Comment by JohanBendz** [comment]
Hi @icaros1, already supported bu the app version for Firmware 5. I will update the 4.2 version of the app with support for it during next week.
