### ISSUE TITLE
Add Support new Aurelle Product-ID

### ISSUE THREAD

**Issue by martin82private** [sebbebebbe/com.philips.hue.zigbee#260]
Hi @JohanBendz Do you can add following aurelle square Product ID: 3216231P6 To the app ?
![6283BB9D-A634-4F84-A348-6A043EB4583D](https://user-images.githubusercontent.com/53186904/102005879-b6316080-3d1c-11eb-8efe-801370fa4838.png)
https://zigbee.blakadder.com/Philips_LTC014.html

Thanks

**Comment by JohanBendz** [comment]
Hi @martin82private, the device is added to the app. Please notify me if it does not work for you.

**Comment by martin82private** [comment]
Hi Johan thanks. In the meantime i downloaded tge source and added it by myself. But i want to change back to the official test version. Is it already added in thr 2.0.20 version? Regards
