### ISSUE TITLE
Add Support Hue P45 E14 Bulb

### ISSUE THREAD

**Issue by adrienbernard** [sebbebebbe/com.philips.hue.zigbee#261]
Hello guys,
I used some Philips Hue lights with my Homey, but last bulbs I bought wasn't fully supported on the app.
It has been added as Zigbee device without the option to control the brightness...
The model is this one: Hue P45 E14 Bulb [(Philips LWU001)](https://zigbee.blakadder.com/Philips_LWU001.html)
Could it be possible to add it on supported devices on the next app version ?
Thank you ! =)

**Comment by adrienbernard** [comment]
I forgot to tell you those informations:

Product ID: LWU001
Service ID: 257
Profile ID: 260

Thanks.

**Comment by JohanBendz** [comment]
Hi @adrienbernard, thanks for your request. Can you please share a link to Philips or a store where I can see this device so that I do not mixit up with some other one. (photo)

**Comment by adrienbernard** [comment]
Hello @JohanBendz,
Here you will find the link of the Philips Hue store: [https://www.philips-hue.com/en-gb/p/hue-white-1-pack-luster-p45-e14/8719514266889](https://www.philips-hue.com/en-gb/p/hue-white-1-pack-luster-p45-e14/8719514266889)
Thank you.

**Comment by JohanBendz** [comment]
Will be added to the firmware 5 version of the app
