### ISSUE TITLE
Hue Being - V2.0.18

### ISSUE THREAD

**Issue by Jugge72** [sebbebebbe/com.philips.hue.zigbee#262]
Homey 4.2. 
Device not supported in V2.0.18?
Adds as "unknown zigbee device"

Tillverkar ID: Philips
Produkt ID: 3261031P6
Enhets ID: 268

**Comment by JohanBendz** [comment]
Hi @Jugge72, and what is the profileId? 260?

**Comment by Jugge72** [comment]
Yes, profileid is 260.

**Comment by JohanBendz** [comment]
Added to the firmware 5 version of the app
