### ISSUE TITLE
Hue Phoenix downlight support

### ISSUE THREAD

**Issue by BertvanGoor** [sebbebebbe/com.philips.hue.zigbee#263]
Can you please add support for the Hue Phoenx downlight?

Producent ID: Philips
Product ID: HML006
Apparaat ID: 544
Profiel ID: 49246

**Comment by JohanBendz** [comment]
Hi @BertvanGoor, thanks for your request. I will add it to next release of the app.

**Comment by pshotton** [comment]
Yes please!

**Comment by JohanBendz** [comment]
Now added to the app for firmware 5, will be supported in next update
