### ISSUE TITLE
Support for Hue Welcome (new device id)

### ISSUE THREAD

**Issue by ei0haro** [sebbebebbe/com.philips.hue.zigbee#264]
The following product got new Device id and profile id

https://www.philips-hue.com/no-no/p/hvit-fargetone-welcome-utendors-flomlys/1743630P7

Manufacturer ID: 1743630P7
Device ID: 257
Profile ID: 260

![Hue Welcome](https://user-images.githubusercontent.com/22055290/102766052-d5b03500-437d-11eb-857f-4e58ffc1ecc7.jpg)

**Comment by JohanBendz** [comment]
Him this is added to the firmware 5 version of the app. I will look into updating the 4.2 version too.
