### ISSUE TITLE
New Product ID Iris Table Lamp

### ISSUE THREAD

**Issue by martin82private** [sebbebebbe/com.philips.hue.zigbee#265]
Hi Johan

please add following Product ID to the Iris Table Lamp: 929002376101

![image](https://user-images.githubusercontent.com/53186904/102785158-ca6d0180-439d-11eb-98fb-89b8f3fb312c.png)

i added the yellow one locally and it s working.

br
Martin

**Comment by JohanBendz** [comment]
OK, added to next update
