### ISSUE TITLE
New Product ID Aurelle Panel Square (small)

### ISSUE THREAD

**Issue by martin82private** [sebbebebbe/com.philips.hue.zigbee#266]
Hi Johan

please add following Product ID to Aurelle Panel Square:3216131P6

![image](https://user-images.githubusercontent.com/53186904/102875836-a1537c00-4444-11eb-8c21-6e95d9cf6192.png)

thanks
Regards Martin

**Comment by JohanBendz** [comment]
Added, will be supported in next update
