### ISSUE TITLE
Philiops Play Lightbar not detected as such (Added as generic Zigbee device)

### ISSUE THREAD

**Issue by mvletter** [sebbebebbe/com.philips.hue.zigbee#267]
I tried adding a Philips Play Lightbar to Homey via your app (which does support a lot of other Hue devices in the house (WoopWoop) but it's not detected as a Hue devices thus added as generic ZigBee device (which lacks the color options).

Manufacturer ID: Philips
Product ID: 440400982841
Device ID: 269
Profile ID:  260

Product Code: 8718696170717 (should be the same as the LCT024 you already support)

**Comment by JohanBendz** [comment]
Added to the firmware 5 version of the app. I'll look inte adding it to the firmware 4.2 version soon.
