### ISSUE TITLE
support for PHILIPS HUE 17463/30 / P7, PHILIPS HUE 56330/30 / P7, PHILIPS HUE 34357/31 / P6

### ISSUE THREAD

**Issue by FeKik** [sebbebebbe/com.philips.hue.zigbee#269]
I have not seen support for these lights. Is it going to be added anytime soon? 

PHILIPS HUE 56330/30 / P7
PHILIPS HUE 17463/30 / P7
PHILIPS HUE 34357/31 / P6

it is not on the list of supported products 

https://homey.app/en-us/app/com.philips.hue.zigbee/Philips-Hue-ZigBee/

 Thank you!

**Comment by JohanBendz** [comment]
Hi @FeKik
5633030P7 and 3435731P6 can be added if you send me the zigbee info for the devices and a link to Philips website where I can see them. (add as generic and look in the device's settings to get Zigbee info.)

1746330P7 is already added to the firmware 5 version of the app (https://homey.app/en-us/app/com.philips.hue.zigbee/Philips-Hue-ZigBee/test). I might add it to the firmware 4.2 version but it's not on top priority.

**Comment by FeKik** [comment]
I have not bought it yet, but I have it on my list for my house. I will have it in summer. I could send you the website though.

**Comment by JohanBendz** [comment]
Hi again, when you have the devices you want to add please create a new issue and I will help you asap.
