### ISSUE TITLE
Namron ZigBee light bulb E27 Dim

### ISSUE THREAD

**Issue by Holmen88** [sebbebebbe/com.philips.hue.zigbee#270]
![5F301360-4F14-40B3-9585-C56C927F76E3](https://user-images.githubusercontent.com/76704446/103237999-a5523300-4949-11eb-9f52-869c0eca141e.png)

Hi

I bought some light bulbs from Namron. Trying to control them through Homey Hub. Downloaded the Hue App but was only able to connect it as a generic device. Then it is possible to dim the bulbs. I was sent to this page to report it to you. It was supposed to work with the Homey App without having the Hue Bridge. Is that possible?

**Comment by JohanBendz** [comment]
Hi @Holmen88.
I will not add support for Namron device in this app.
Correct app for Namron devices is this one: https://homey.app/en-us/app/net.filllip-namron/namron/test/
