### ISSUE TITLE
Addition of Hue White Luster P45 E14

### ISSUE THREAD

**Issue by MagWide** [sebbebebbe/com.philips.hue.zigbee#271]
Hi,
would be grateful if you could add the buld Hue White Luster P45 E14 to your app, so it would be possible to dim it with a Homey.

Please find the product linked here:

https://www.philips-hue.com/en-gb/p/hue-white-1-pack-luster-p45-e14/8719514266889

And the data from form the HOMEY zigbee general app when paired,  in the attached picture below.

![Attachment](https://user-images.githubusercontent.com/76747142/103304679-8a46f800-4a09-11eb-8fdf-6cee9717547a.jpg)
 
Thanks, Magnus

**Comment by JohanBendz** [comment]
This is added to the firmware 5 version 2.0.22. I will look into adding this to the 4.2 version too.
