### ISSUE TITLE
Philips Ensis Pendant (black) not working and added as generic Zigbee device

### ISSUE THREAD

**Issue by cyberbozzo** [sebbebebbe/com.philips.hue.zigbee#272]
Dear All,

The Ensis Pendant Black (https://www.philips-hue.com/en-gb/p/hue-white-and-colour-ambiance-ensis-pendant-light/4090330P9) has become available a few weeks ago.
However, when I add the device to Homey by the Philips Hue Zigbee app, it's recognized twice (both sides of the light) as generic Zigbee device:
- 4090330P9_02 (Device ID: 269 & Profile ID: 260) > Down side
- 4090330P9_01 (Device ID: 269 & Profile ID: 260) > Top side

Am I doing something wrong? Or is this just because it's the black version of the product, another SKU or something like that?

Kind Regards,
Pieter

**Comment by JohanBendz** [comment]
Hi @cyberbozzo, yes.. it's a separate deviceId for this color. I have now added it to the app for firmware 5 and it will be supported on next update. Regarding the version for firmware 4.2 (I see you are using this) I have no scheduled update. I will try to squeeze one in during next week.

**Comment by JohanBendz** [comment]
A tip while waiting for the update.. if you have a Hue Switch Dimmer you can pair it with the Ensis Pendant separately. This way you will be able to dim the light using the remote. If you want the Ensis device in Homey too just make sure the Switch Dimmer is added to Homey before pairing it with the lights.

**Comment by cyberbozzo** [comment]
Dear Johan,

Tnx for your efforts!
In the meanwhile I'm controlling the device via Bluetooth, so no hurry. I've updated my homey to experimental firmware v5. You said that you've added support to the v5 version of your app, when will you release the update for v5 app?

Many thanks!
Pieter
