### ISSUE TITLE
New product ID? E14 Candle Bulb

### ISSUE THREAD

**Issue by ulvestuen** [sebbebebbe/com.philips.hue.zigbee#273]
Hi. 

When trying to add the Philips Hue white ambiance candle bulb E14 (with bluetooth support), it only adds to the Homey as a generic Zigbee device. Can it be that the specific bulb is not supported by the Heomey-app? Its Zigbee information is listed below: 

Product ID: LTE002
Device ID: 268
Profile ID: 260 

Product link: https://www.philips-hue.com/en-gb/p/hue-white-ambiance-single-bulb-e14/8718699726294 

Best regards, Idar

**Comment by JohanBendz** [comment]
Hi, this device is added to the firmware 5 version of the app. I will look into updating the 4.2 version too.
