### ISSUE TITLE
Support for Hue Discovery Flood Light needed 17435/30/P7

### ISSUE THREAD

**Issue by Stefans25** [sebbebebbe/com.philips.hue.zigbee#274]
Hi, 
can you please add the Hue Discovery Flood Light. I tried to add the device with v2.0.18 without success - only recognized as unknown Zigbee device. 
(https://www.philips-hue.com/de-de/p/hue-white---color-ambiance-discover-flutlicht/1743530P7)

Product ID: 1743530P7
Service ID: 269
Profile ID: 260

Thank you very much.
BR Stefan

**Comment by JohanBendz** [comment]
Thanks for the feedback, looks like new versions of this device (and other units) have new profile and device id's.
I am updating the code, lets hope this works :)
