### ISSUE TITLE
Support for Hue smart button needed

### ISSUE THREAD

**Issue by twanennatascha** [sebbebebbe/com.philips.hue.zigbee#275]
Hi,
can you please add the Hue Smart Button. I tried to add the device only recognized as unknown Zigbee device.

https://www.philips-hue.com/nl-nl/p/hue-smart-knop/8718699693985

Product ID: ROM001
Service ID: 2069
Profile ID: 260

Thank you!

Natascha

**Comment by JohanBendz** [comment]
Hi @twanennatascha, the device is already supported by the app for firmware 5. I will have a look at updating the firmware 4.2 version of the app too. Thanks for your request!

**Comment by dirkg173** [comment]
Hi @JohanBendz, the Smart Button has the same functions as the Dimmer Switch:
- On-button pressed
- Off-button pressed
- Dim buttons (Dim-up pressed / Dim-up hold / Dim-down pressed / Dim-down hold / Dim-button released)

I guess this is a mistake.
