### ISSUE TITLE
Hue Impress wall light only added as generic zigbee device

### ISSUE THREAD

**Issue by TeamhubDk** [sebbebebbe/com.philips.hue.zigbee#276]
Hi Johan,
Is it possible to check why this is not added correct into Homey.

Thanks.
Best regards,
Kim Lindorff

https://www.philips-hue.com/da-dk/p/hue-white-and-color-ambiance-impress-udendors-vaglampe/1742930P7#specifications

![6E9E8323-E8EA-4D44-A7A6-D7109A77E913](https://user-images.githubusercontent.com/77539717/104815433-d5884580-5814-11eb-9843-a425921f7909.png)

**Comment by JohanBendz** [comment]
Hi @TeamhubDk, looks like this unit have a new device and profile Id. I have added it to next release.

**Comment by TeamhubDk** [comment]
Thanks🙂
