### ISSUE TITLE
Request for new light Hue White Ambience BT E14 5,2watt

### ISSUE THREAD

**Issue by osram** [sebbebebbe/com.philips.hue.zigbee#277]
https://www.philips-hue.com/sv-se/p/hue-white-ambiance-enkel-ljuskalla-e14/8718699726294
![image](https://user-images.githubusercontent.com/2835901/104821890-4e03fc00-583f-11eb-97c5-914d9f8f91d8.png)

**Comment by JohanBendz** [comment]
Added to next release.
