### ISSUE TITLE
Hue Being ceiling light only added as generic zigbee device

### ISSUE THREAD

**Issue by PaulWillemen** [sebbebebbe/com.philips.hue.zigbee#278]
Hi,

Philips Hue Being chilling light is only added as generic zigbee device.
Is it possible to check why this is not added correct into Homey.

ProductID: 3261048P6
DeviceID: 268
ProfileID: 260

https://www.philips-hue.com/nl-nl/p/hue-white-ambiance-being-plafondlamp/3261030P6

Thanks for the support,
Paul

**Comment by JohanBendz** [comment]
Thanks for your request, added to next update.
