### ISSUE TITLE
Please add support for milliskin recessed spot light

### ISSUE THREAD

**Issue by PatrickvanderPlas** [sebbebebbe/com.philips.hue.zigbee#279]
![Screenshot_20210120-185304_Homey](https://user-images.githubusercontent.com/73231597/105214787-c117b600-5b50-11eb-82cb-983dee53e608.jpg)

https://www.philips-hue.com/nl-nl/p/hue-white-ambiance-milliskin--inbouwspot/5041131P7

**Comment by JohanBendz** [comment]
Added to next release

**Comment by PatrickvanderPlas** [comment]
Deleted the Light and added it again on app v2.0.25. Still being added as 'onbekende zigbee apparaat'. Am I too early? I cant find the product id in your code. Could you please check again? Thx
