### ISSUE TITLE
Support for Still

### ISSUE THREAD

**Issue by NdyGen** [sebbebebbe/com.philips.hue.zigbee#28]
Could you please add support for the Still light.

Using it as generic Zigbee does not controll brightness & color temperature. THNX!

https://www2.meethue.com/nl-nl/p/hue-white-ambiance-still-plafondlamp/3261348P7

**Comment by sebbebebbe** [comment]
Noted in the list.

**Comment by JohanBendz** [comment]
@NdyGen 
Can you please add below information to your request?
Manufacturer ID:
Product ID:
Device ID:
Profile ID:

(bump @NdyGen )

**Comment by mfapouw** [comment]
Not sure if it is better to open a new issue or add this comment. Please let me know if I need to open a new one.

Seems that there is a new version of the Hue Still:
https://www.philips-hue.com/nl-nl/p/hue-white-ambiance-still-plafondlamp/3261330P6

New IDs
ManufacturerID: Philips
ProductID: 3261330P6
DeviceID: 268
ProfileID: 260

![HUE_STILL](https://user-images.githubusercontent.com/37973694/96039787-832c3700-0e69-11eb-98ea-2a075aea20e9.PNG)

Hopefully this version can also be added. Thank you.

**Comment by JohanBendz** [comment]
Thx, added!
