### ISSUE TITLE
Iris Limited Edition - Gold

### ISSUE THREAD

**Issue by Raeghin** [sebbebebbe/com.philips.hue.zigbee#280]
Hi, can you please provide support for the Iris limited Edition - Gold?
https://www.philips-hue.com/nl-nl/p/hue-white-and-color-ambiance-iris-goudkleur-limited-edition/8719514264526

Manufacturer ID Philips
Product ID 929002376401
Device ID 269
Profile ID 260

Thank you in advance!

**Comment by JohanBendz** [comment]
Added to next release
