### ISSUE TITLE
Philips fugato 3 connecting problem Homey

### ISSUE THREAD

**Issue by Digibitsnl** [sebbebebbe/com.philips.hue.zigbee#281]
I have trouble connecting my new philips fugato 3 spotlight to Homey. In the app I can find the fugato 3 but my homey version 4.2.0 does not recognize it, and ad it as a common zigbee device. My homey has an app version 6.3.0.671.

The fugato is recognized as 5063331P7
App id 269
Profile id 260
Can you help????

**Comment by JohanBendz** [comment]
Added to next release.

**Comment by Digibitsnl** [comment]
After the last update, Homey installed the fugato 3, thank you for adding it. But only one of the three lamps is adjustable, or even goes on/of with Homey. The other two bulbs light on their brightest function.
