### ISSUE TITLE
Requests for adding Hue lamp E14

### ISSUE THREAD

**Issue by GerardH12** [sebbebebbe/com.philips.hue.zigbee#282]
Hi, is het possible to add the Philips e14 bulb LWU001?
![533A19EF-8E38-4EA9-92C6-A1313B130FE1](https://user-images.githubusercontent.com/77884746/105578500-f0ad0500-5d80-11eb-9cf1-e0dedbbdfda1.jpeg)

**Comment by JohanBendz** [comment]
Added to next release
