### ISSUE TITLE
Request forma new Hue lamp. 

### ISSUE THREAD

**Issue by marcelmarkes** [sebbebebbe/com.philips.hue.zigbee#283]
Hello is it possible to ad the Philips Hue ST72 (E27)

![7DA2F1DD-420F-4752-A28C-2CE75B21BA9D](https://user-images.githubusercontent.com/31585929/105614862-8ae66a80-5dcc-11eb-8350-e66b3570ab85.jpeg)
![EB6F51FB-C5D1-49DA-B811-CF964C5AB380](https://user-images.githubusercontent.com/31585929/105614866-8fab1e80-5dcc-11eb-8803-0b7b54196001.jpeg)

thanks

**Comment by JohanBendz** [comment]
Added to next release.

**Comment by marcelmarkes** [comment]
> Added to next release.

Thanks.  
Do you no when the next release wil be released
