### ISSUE TITLE
Milliskin support

### ISSUE THREAD

**Issue by PatrickvanderPlas** [sebbebebbe/com.philips.hue.zigbee#284]
See #279 

Updated the app to v2.0.25 but still 'onbekend zigbee apparaat'. I deleted the Light and added it again. Also I dont see the product id the code. Could you please check? Thx

**Comment by JohanBendz** [comment]
Hi @PatrickvanderPlas. Let me guess, your unit(s) have device id 5041131P9? Looks like there are several device id's for these lights, I will add more to next release.
