### ISSUE TITLE
Support for Philips Hue Centris 2-spot + panel

### ISSUE THREAD

**Issue by Blom1974** [sebbebebbe/com.philips.hue.zigbee#286]
Same as issue #285 except Model ID

Centris RGB 2-spot + panel
https://www.philips-hue.com/sv-se/p/hue-white-and-color-ambiance-centris-taklampa-med-2-spot/5061031P7

5061031P7_01 = Panel 1
5061031P7_02 = Spot 2
5061031P7_03 = Spot 3

**Comment by badschwii** [comment]
Same as #285 just another Model
Centris 4 (black)

5060730P7_01 = Panel
5060730P7_02 = Spot 1
5060730P7_03 = Spot 2
5060730P7_04 = Spot 3
5060730P7_05 = Spot 4

Thank you so much for adding these IDs.
I appreciate your work very much!

**Comment by JohanBendz** [comment]
Added to next release.
Thanks for your kind words :)
