### ISSUE TITLE
Philips Hue Zigbee - Milliskin spots

### ISSUE THREAD

**Issue by mortenlid** [sebbebebbe/com.philips.hue.zigbee#288]
I think i have tried everything, the milliskin spots/downlights wont appear in Homey. 
Can you fix it?

![EDB2EAA3-4697-4BAD-95EE-B11E72757676](https://user-images.githubusercontent.com/78114251/106057496-5afed600-60f0-11eb-8310-07bf1711c823.png)

**Comment by JohanBendz** [comment]
Hi @mortenlid, thanks for the feedback. Looks like there are several device id's for those (might be based on color or country etc.. ) I'll add this too!
