### ISSUE TITLE
Hue dimmer switch v2

### ISSUE THREAD

**Issue by Jzi85** [sebbebebbe/com.philips.hue.zigbee#289]
Is it possible to add support for the new dimmer switch?
![Screenshot_20210131-152143_Homey](https://user-images.githubusercontent.com/78308212/106387025-17e68080-63d8-11eb-8d26-c0f08a082bf4.jpg)

**Comment by JohanBendz** [comment]
Hi @Jzi85, it's on my todo list :)

**Comment by JohanBendz** [comment]
Now released, in the test version and soon in live version.
