### ISSUE TITLE
Hue motion sensor settings

### ISSUE THREAD

**Issue by fkey3** [sebbebebbe/com.philips.hue.zigbee#29]
Hi, I cant figure out how the motion sensor settings work or what they do.
I changed them but do not notice difference.
1 is this setting at homey? Or at the sensor?
2 min report interval lux (ms) miliseconds seems very short. If I check the insights I do not see updates that often
Thank, Frank
![04203f5d-9cb5-4ad2-9494-4d23bb388f11](https://user-images.githubusercontent.com/42219340/47245637-6edc0d80-d3fa-11e8-8b75-a097de409e1f.jpeg)

**Comment by marindal** [comment]
Hi.

How do you set the motion alarm timeout?
And is it possible to set when its gonna be active, based on the LUX in the room/daylight?

BR
M.Heldt

**Comment by fkey3** [comment]
@maheldt The forum (https://community.athom.com/) gives you many example for all 3 questions...

**Comment by marcus-karlsson** [comment]
Regading the ms (miliseconds) I think it is a type my experience is that it is s (seconds). Max 900 on lux means at least every 15 minutes the lux value is transmitted, similarly 3600s for temperature means at least every hour temperature value is sent. It can be shorter if there is a change in the values.

**Comment by fkey3** [comment]
Hi Marcus, thanks for your response.
My setting is at max=900 but when I look at insights, during the night, I do not see readings every 15 min. So it seems the setting is not working...

**Comment by marcus-karlsson** [comment]
@fkey3 
For me this seem to work but sometimes all reporting stops from the device. Then I have to restart Homey to get it working again. Are you sure values change during the night, my sensor bottoms out at 1lux. I do not think you can see the data points in insights then, I am not sure but I think insights compress the data by removing data points that show the same value. Looking at it from the other end wehen values change and the min interval is set to 300s I do not get data points more often than every 5 mintes between that when exporting the data I get a rounded off value to fill the gaps. 
"2019-02-15 16:38:00	10.333333333333332"
"2019-02-15 16:39:00	10"
"2019-02-15 16:40:00	10"
"2019-02-15 16:41:00	10"
"2019-02-15 16:42:00	10"
"2019-02-15 16:43:00	9.166666666666666"
"2019-02-15 16:44:00	9"
"2019-02-15 16:45:00	9"
"2019-02-15 16:46:00	9"
"2019-02-15 16:47:00	9"
"2019-02-15 16:48:00	7.333333333333333"
"2019-02-15 16:49:00	7"
"2019-02-15 16:50:00	7"
"2019-02-15 16:51:00	7"
"2019-02-15 16:52:00	7"
"2019-02-15 16:53:00	6.083333333333333"
"2019-02-15 16:54:00	6"
"2019-02-15 16:55:00	6"
"2019-02-15 16:56:00	6"
"2019-02-15 16:57:00	6"
"2019-02-15 16:58:00	5.083333333333333"

**Comment by fkey3** [comment]
How can I get the readings you show?
The reason why I started looking at the insights was that I came home a few times, the house in the dark. At the moment I entered the house (trigerred the motion) the lux also triggered the lights.
So I have the feeling lux is not reported even when it changes a lot.
For insights it could indeed be that the same values are ignored, did not think about that
![116b9354-ccaa-4704-bee0-03111e4b417e](https://user-images.githubusercontent.com/42219340/52903471-420bfb80-321e-11e9-9d9a-9fbcf959bde2.jpeg)

**Comment by marcus-karlsson** [comment]
@fkey3 
Click the download button arrowed in below screenshot...

![image](https://user-images.githubusercontent.com/47646332/52904212-40940080-3229-11e9-9248-1e9430749fce.png)

**Comment by fkey3** [comment]
Thanks, not at V2 yet so this is not availble for me ...
Gr Frank

**Comment by sebbebebbe** [comment]
This is the info from the ZigBee implementation from Athom.

 * @param {number} minInt - The minimal reporting interval in seconds (e.g. 10 (seconds))
 * @param {number} maxInt - The maximal reporting interval in seconds (e.g. 300 (seconds))

**Comment by sebbebebbe** [comment]
Also note that it only reports data that differs to the graphs.

**Comment by JohanBendz** [comment]
Hi @fkey3, I will close this issue. Please open a new one if you still have questions/problems.
