### ISSUE TITLE
Philips Hue Motion Sensors bug

### ISSUE THREAD

**Issue by mortenlid** [sebbebebbe/com.philips.hue.zigbee#290]
Hi.
The motion sensors from Philips Hue are very unstable. Sometimes the motion-alarm is active for hours, and wont turn of the lights when the motion-alarm is active. 
![8D1F0794-B581-46E6-AC96-046954F2BE88](https://user-images.githubusercontent.com/78114251/106723335-49915e80-6607-11eb-959f-53033029ed05.png)

**Comment by JohanBendz** [comment]
Hi @mortenlid, they driver for motion sensors are totally rewritten for sdk3 / firmware 5. I hope they work better for you when you have upgraded. I will not make any more updates to the version for firmware 4.2.
