### ISSUE TITLE
Philips Hue Ensis dosent work with White Ambience colors.

### ISSUE THREAD

**Issue by mortenlid** [sebbebebbe/com.philips.hue.zigbee#291]
Hi! My Philips Hue Ensis lamp dosent work with White Ambience colors, goes only to cold white. Have to adjust the colors to get the light i want.
Thank you for doing a great work with this app, hope you fix this. 

![F040D916-BED5-4EBB-88E4-C59113085DD7](https://user-images.githubusercontent.com/78114251/106793819-3d81bd00-6658-11eb-80d6-31835ea83e2c.png)
![0569F4C7-D332-43D8-B7D0-1D0FFD6A3E8C](https://user-images.githubusercontent.com/78114251/106793828-3fe41700-6658-11eb-8818-bc45c57c6d4f.png)

**Comment by JohanBendz** [comment]
Hi, this should be fixed in the version for firmware 5. Are you planning on updating?

**Comment by JohanBendz** [comment]
Hi @mortenlid, did updating to firmware 5 fix this issue?

**Comment by JohanBendz** [comment]
Get back to me if this problem persists.
