### ISSUE TITLE
Request for adding Hue Amaze pendant 4023331P6

### ISSUE THREAD

**Issue by rliedes** [sebbebebbe/com.philips.hue.zigbee#292]
Hi,

Could this Hue Amaze pendant be added to the app?

![Hue_amaze_homey](https://user-images.githubusercontent.com/78527651/106856171-c5061500-66c6-11eb-8487-c0e280c7f1dc.jpeg)

https://www.philips-hue.com/en-hk/p/hue-white-ambiance-amaze-suspension-light/4023331P6

Thank you very much!

**Comment by JohanBendz** [comment]
Hi @rliedes, added to next version of the app (firmware 5 only).
