### ISSUE TITLE
please add bloom device

### ISSUE THREAD

**Issue by jefmo** [sebbebebbe/com.philips.hue.zigbee#294]
Product ID: 929002376001
Apparaat ID: 269
profiel ID: 260

https://www.philips-hue.com/nl-nl/p/hue-white-and-color-ambiance-bloom-tafellamp/8718699771126 

Thanks

**Comment by jefmo** [comment]
https://www.philips-hue.com/nl-nl/p/hue-white-and-color-ambiance-bloom-tafellamp/8718699771126

**Comment by jefmo** [comment]
In

**Comment by JohanBendz** [comment]
Hi @jefmo, support added to next release of the app. (firmware 5 only)

**Comment by jefmo** [comment]
@JohanBendz thank you for adding the device.
