### ISSUE TITLE
When is a new update on this app released?

### ISSUE THREAD

**Issue by mortenlid** [sebbebebbe/com.philips.hue.zigbee#295]

**Comment by JohanBendz** [comment]
Hi again @mortenlid, is there anything special you are waiting for?

**Comment by mortenlid** [comment]
Hi :) Yes, waiting for support for the milliskin downlights and the bugs on motion sensors to be fixed.

**Comment by JohanBendz** [comment]
OK, I'll release an update with added Milliskin device id's this evening then :)
