### ISSUE TITLE
Support LWB001 and LWL001

### ISSUE THREAD

**Issue by hvandrie** [sebbebebbe/com.philips.hue.zigbee#297]
Could you add support for LWB001 LivingWhites E27 Bulbs and LWL001 LivingWhites Plug (dimmable), please.

**Comment by JohanBendz** [comment]
Hi  @hvandrie, can you please 1. interview the devices and send me the data. 2. add an url to where I can see the units. I need to add power usage and if they differ from what's already included a professional product photo of them.

**Comment by JohanBendz** [comment]
Please create a new issue and add interviews of the devices if you still want this added.
