### ISSUE TITLE
Lamps and Bulbs fall out of the network

### ISSUE THREAD

**Issue by mflydahl** [sebbebebbe/com.philips.hue.zigbee#298]
Hi

My Hue devices, especially my three Being lamps, but also other bulbs, sporadically falls out of the network, and won't react to any of my flows. One hour they work, one hour they don't. 

When I run a flow, they come up as unreachable. 

I've recently changed my Homey to a Homey Pro, upgraded to v5, and restored a backup. All is fine, except Hue-lamps.

On my old Homey I used the newest 5RC-version of the firmware. No problems there. 

I've tried to restart the app and the Homey many times. 

I've not tried to remove and include the devices again, and I really, really want to avoid that, because they're in alot of flows.

**Comment by JohanBendz** [comment]
Hi @mflydahl, strange behavior indeed. I have never heard about Hue lights act like that. Can you please send a crash report from the app and send a diagnostic report to Athom and give me the ID of both?

**Comment by mflydahl** [comment]
Diagnostic reports:

App:
f6fdfb54-2fa1-40e7-836f-c1768131f25e

Homey:
29FFA2

**Comment by JohanBendz** [comment]
Hi @mflydahl, I have looked through your report and reported the problems to Athom. There is sadly nothing I can do as the problem is not within the app. Athom wants you to start a support ticked with them, you do that here: https://support.athom.com/hc/en-us/requests/new
