### ISSUE TITLE
App update

### ISSUE THREAD

**Issue by PatrickvanderPlas** [sebbebebbe/com.philips.hue.zigbee#299]
When will you release an update? Waiting for milliskin support. Still on 2.0.26

**Comment by JohanBendz** [comment]
Hi @PatrickvanderPlas, Milliskin is supported in version 2.0.26. Are you unable to add them? If so, what zigbee info do yours have?

**Comment by PatrickvanderPlas** [comment]
Waiting for update for issue #284

**Comment by JohanBendz** [comment]
Added support for additional model id's to next release.
