### ISSUE TITLE
Bulbs stoped working

### ISSUE THREAD

**Issue by mariarosberg** [sebbebebbe/com.philips.hue.zigbee#300]
Hey Johan!
My bulbs stoped working all at once. Trying to do anything with the bulbs results in "request timeout".
Looking att when the latest update accured it fits with when the problem started!
I have the following models: Hue White LWB010 and White Ambiance E27 
(Just bought White Ambiance E14, don't dare to connect them untill this issue is ressolved!)

**Comment by JohanBendz** [comment]
Hi @mariarosberg, what Homey firmware is your Homey running? 4.2 or 5?
If your Homey is on firmware 5 and your have Philips Hue Zigbee App version 2.0.26 installed and the lights still is not working please send me a crash report from the app.

**Comment by mariarosberg** [comment]
Hi!

My Homey said it was updated and on 5 but i did a manual check to be
sure...and it updated to 5!🤯
Weird!

Maybe you should say something about the update fixing Zigbee on the page
for the app!?
It would have saved me A LOT of time trubleshooting!

Thank you for your quick response!

Den lör 20 feb. 2021 00:21Johan Bendz <notifications@github.com> skrev:

**Comment by JohanBendz** [comment]
Hi again, OK.. so all light works now?
Yes, I have requested from Athom to let us developers have some kind of notice text in app store that users could read. Today I have to update the app and have it reviewed before I can change the text you see in app store.
