### ISSUE TITLE
 Aurelle, round, Request device

### ISSUE THREAD

**Issue by Ron48780** [sebbebebbe/com.philips.hue.zigbee#302]
Hi, could you add hue Aurelle round?
ProductId= 3216431P6

https://www.philips-hue.com/nl-nl/p/hue-white-ambiance-aurelle-hue--rond--paneellamp/3216431P6

thanks in advance!

**Comment by JohanBendz** [comment]
Hi @Ron48780 , can you please do an interview and post the data? https://developer.athom.com/tools/zigbee

**Comment by Ron48780** [comment]
ok, first time im doing this......



  "ids": {
    "modelId": "3216431P6",
    "manufacturerName": "Philips"
  },
  "endpoints": {
    "endpointDescriptors": [
      {
        "endpointId": 11,
        "applicationProfileId": 260,
        "applicationDeviceId": 268,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          0,
          3,
          4,
          5,
          6,
          8,
          4096,
          768
        ],
        "outputClusters": [
          25
        ]
      },
      {
        "endpointId": 242,
        "applicationProfileId": 41440,
        "applicationDeviceId": 97,
        "applicationDeviceVersion": 0,
        "_reserved1": 0,
        "inputClusters": [],
        "outputClusters": [
          33
        ]
      }
    ],
    "endpoints": {
      "11": {
        "clusters": {
          "basic": {
            "attributes": [
              {
                "id": 0,
                "name": "zclVersion",
                "value": 2
              },
              {
                "id": 1,
                "name": "appVersion",
                "value": 2
              },
              {
                "id": 2,
                "name": "stackVersion",
                "value": 1
              },
              {
                "id": 3,
                "name": "hwVersion",
                "value": 0
              },
              {
                "id": 4,
                "name": "manufacturerName",
                "value": "Philips"
              },
              {
                "id": 5,
                "name": "modelId",
                "value": "3216431P6"
              },
              {
                "id": 6,
                "name": "dateCode",
                "value": "20200124"
              },
              {
                "id": 7,
                "name": "powerSource",
                "value": "mains"
              },
              {
                "id": 8,
                "name": "appProfileVersion",
                "value": 0
              },
              {
                "id": 9
              },
              {
                "id": 10
              },
              {
                "id": 11
              },
              {
                "id": 16384,
                "name": "swBuildId",
                "value": "1.65.9_hB3217DF4"
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "identify": {
            "attributes": [
              {
                "id": 0
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "groups": {
            "attributes": [
              {
                "id": 0,
                "name": "nameSupport",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0
                  ]
                }
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "scenes": {
            "attributes": [
              {
                "id": 0
              },
              {
                "id": 1
              },
              {
                "id": 2
              },
              {
                "id": 3
              },
              {
                "id": 4
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "onOff": {
            "attributes": [
              {
                "id": 0,
                "name": "onOff",
                "value": true
              },
              {
                "id": 16384
              },
              {
                "id": 16385,
                "name": "onTime",
                "value": 0
              },
              {
                "id": 16386,
                "name": "offWaitTime",
                "value": 0
              },
              {
                "id": 16387
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "levelControl": {
            "attributes": [
              {
                "id": 0,
                "name": "currentLevel",
                "value": 143
              },
              {
                "id": 1,
                "name": "remainingTime",
                "value": 0
              },
              {
                "id": 15
              },
              {
                "id": 16384
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "touchlink": {
            "attributes": [
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1,
                "reportingConfiguration": {
                  "status": "UNREPORTABLE_ATTRIBUTE",
                  "direction": "reported"
                }
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "colorControl": {
            "attributes": [
              {
                "id": 2
              },
              {
                "id": 3,
                "name": "currentX",
                "value": 32861
              },
              {
                "id": 4,
                "name": "currentY",
                "value": 27216
              },
              {
                "id": 7,
                "name": "colorTemperatureMireds",
                "value": 443
              },
              {
                "id": 8,
                "name": "colorMode",
                "value": "colorTemperatureMireds"
              },
              {
                "id": 15
              },
              {
                "id": 16
              },
              {
                "id": 17
              },
              {
                "id": 18
              },
              {
                "id": 19
              },
              {
                "id": 21
              },
              {
                "id": 22
              },
              {
                "id": 23
              },
              {
                "id": 25
              },
              {
                "id": 26
              },
              {
                "id": 27
              },
              {
                "id": 48
              },
              {
                "id": 49
              },
              {
                "id": 50
              },
              {
                "id": 51
              },
              {
                "id": 52
              },
              {
                "id": 54
              }
            ],
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        },
        "bindings": {
          "ota": {
            "attributes": [],
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        }
      },
      "242": {
        "clusters": {},
        "bindings": {}
      }
    }
  }

**Comment by JohanBendz** [comment]
Added to next release.
