### ISSUE TITLE
Support for Philips Hue GU10 - White and Color Ambiance

### ISSUE THREAD

**Issue by Hmvink** [sebbebebbe/com.philips.hue.zigbee#303]
Hi Johan,

can you please add support for the Philips Hue GU10 - White and Color Ambiance to the Homey Philips Hue Zigbee app?
Product ID: 5062131P7
Profile ID: 41440

A Service ID is not mentioned but the EAN code is 8718699629250

Kind regards,

Hans Maarten Vink

**Comment by JohanBendz** [comment]
Hue Argenta
https://www.philips-hue.com/sv-se/p/hue-white-and-color-ambiance-argenta-enkel-spotlight/5062131P7

**Comment by JohanBendz** [comment]
Added to next release
