### ISSUE TITLE
measure_battery status for the Philips motions sensors

### ISSUE THREAD

**Issue by joka222** [sebbebebbe/com.philips.hue.zigbee#308]
Would be nice if the measure_battery status for the Philips motions sensors would be integrated. THX Johan

**Comment by JohanBendz** [comment]
Hmm, I think motion and outdoor sensors should be OK but I see that the new Occupancy sensors does not get the info at start. I'll add that to the code. If you experience reporting issues with motion and outdoor sensors please let me know.
