### ISSUE TITLE
Hue Tap

### ISSUE THREAD

**Issue by marindal** [sebbebebbe/com.philips.hue.zigbee#31]
Hi.

Is it possible for you to add support for Hue Tap? 

BR
M.Heldt

**Comment by sebbebebbe** [comment]
Hi,

Hue tap uses another type of ZigBee "protocol" that does not work with Homey.

//Sebastian

**Comment by ghost** [comment]
Hi,
Some years have passed, the new Homey Pro (early 2023) is live. Is there any chance Good Ol' Hue Tap might work with it?

**Comment by sylvainia** [comment]
Nothing still ? 😢
I have four of them, they worked with my previous box (Jeedom), not anymore with my homey pro 2023 (but through the Hue bridge I would like to get rid of).
