### ISSUE TITLE
All Hue devices (lights) become unresponsive after cutting the power to some of the devices (lights) till the power is restored.

### ISSUE THREAD

**Issue by EricPiepers** [sebbebebbe/com.philips.hue.zigbee#312]
After physically switching off power on some lights all Hue devices (lights) become unresponsive (device can't be reached - the request took to long).
After physically switching on power to the devices (lights) switched off all Hue devices (lights) become responsive again.

So it seems that when you cut the power to one / some Hue lights all other become unresponsive.

The issue occurs since last update. It's  a little bit annoying so I hope the issue can be resolved.

Regards, Eric.

**Comment by JohanBendz** [comment]
Hi @EricPiepers, is this still an issue?
If the device that you cut power to acts as a router for the other lights they will become unavailable (but eventually find a new way to Homey).

When you say "switched off all Hue devices" do you mean that none is responsive or that a "group off" flow does not work?

**Comment by EricPiepers** [comment]
Hello Johan,

 

Yes, it is still an issue that persists even after restarting the app and rebooting Homey.

I have several Philips Hue in- & out-door lights connected to my Homey device.

 

I’m not aware if the lights to which the power is cut act as a router for the other devices. How can I check this?

 

When the power is cut to one light, all the other Hue lights become unresponsive both to individual (device) switch on/off and flow device switch on/off in Homey. Hence both: none is responsive and a “group on” flow does not work.

 

As soon as the lights to which the power was cut are powered on using a plain standard 230v light switch all lights become responsive again. 

 

I hope my answer clarifies some of the questions you had.

 

Kind regards, 

Eric Piepers

**Comment by JohanBendz** [comment]
Hmm, it does sound like you have mesh problems when those lights are powerless.
Best is to never power off a Hue device with a physical circuit breaker at all but always use a flow or the app to turn them off.

You can check in the Zigbee section of developer tools if the devices that are powered off are critical mesh/routing points for the rest of your lights.  https://developer.athom.com/tools/zigbee

To the far right in that website you will se routing, any device that other units connect through is considered a router and a power loss will make the rest of the devices unavailable. Sounds strange though that all device goes unresponsive..

If this continues I suggest contacting Athom Support.
