### ISSUE TITLE
Add Support for Argenta spots

### ISSUE THREAD

**Issue by Logic1978** [sebbebebbe/com.philips.hue.zigbee#313]
Hi Johan,

I love your app for Homey, everything works and at lot of issues I solved myself in versions prior to version 5 have been integrated into the App. Only 2 lights I still had to add myself, both Argenta. I have a 2-spot Argenta and several 4-spot Argenta that aren't standard in the App. Manually I have added them since they basically are GU10 white and colors, but I miss out on all future updates.

[https://www.philips-hue.com/nl-nl/p/hue-white-and-color-ambiance-argenta-2-lichts-spotbalk/5062248P7](url)

[https://www.philips-hue.com/nl-nl/p/hue-white-and-color-ambiance-argenta-4-lichts-spotbalk/5062448P7](url)

Thanks in advance and keep up the great work, the efforts are much appreciated.

Kind regards,
Marcel

**Comment by JohanBendz** [comment]
Thanks for your request, will be supported in next release.
