### ISSUE TITLE
Improved icons for Hue lights and accessories!

### ISSUE THREAD

**Issue by IvoDerksen** [sebbebebbe/com.philips.hue.zigbee#314]
Hello Johan,

I come bearing gifts!
[nl.philips.hue.zigbee.zip](https://github.com/JohanBendz/com.philips.hue.zigbee/files/6273072/nl.philips.hue.zigbee.zip)

I've updated some icons for the Philips Hue Series of Athom, and they referred me to you, share they said! 
The icons are named after their (known for me) driver. I hope it is as drag and drop as possible ;)

Kind regards,
Ivo

**Comment by JohanBendz** [comment]
Hi @IvoDerksen, nice indeed! Thanks! : )

**Comment by IvoDerksen** [comment]
Sorry i closed this one per accident.

**Comment by JohanBendz** [comment]
Hi there @IvoDerksen. No worries, it's been collecting dust for way to long!
Glad you made me aware I have not used them as I should. I'll get back to you on more icons!

**Comment by IvoDerksen** [comment]
I dont mind that at all!
Glad to help!
