### ISSUE TITLE
Add support for Philips Hue White A60 E27

### ISSUE THREAD

**Issue by runely** [sebbebebbe/com.philips.hue.zigbee#316]
Hi

I've bought `Outdoor Wall light Turaco` which includes a `Hue White A60 E27 9w 60mA 2700K` bulb:
**Product-ID**: `LWW003`
**Model**: `9290018216`

I've tried to include it with the following devices but it just adds it as a generic zigbee device:

- `Bulb 9W A60 E27 EUR White`, but this has other Product-ID (LWA001) than my bulb
- `Bulb A60 E27 White `, but this has other Product-ID (LWB000) than my bulb

Could you add support for this bulb?

**Comment by JohanBendz** [comment]
OK, added to next release.
