### ISSUE TITLE
Homey script example for HUE app

### ISSUE THREAD

**Issue by BOverdevest** [sebbebebbe/com.philips.hue.zigbee#317]
Hi Johan

Would it be possible to add to the documentation (wiki part ) a few examples of Homey script to control the HUE app. 
How to set it up, how to use APIget and APIput to turn on a light or check light status.
i'm really struggling here. (currently use a http fetch and put  directly on the HUE ip address.

**Comment by JohanBendz** [comment]
Hi there. perhaps you are thinking of the Hue Bridge app? This app does not talk to Hue using ip but Zigbee.

**Comment by BOverdevest** [comment]
oops, my bad...
