### ISSUE TITLE
Hue Smart Plug as Zigbee Router?

### ISSUE THREAD

**Issue by PimKoedijk** [sebbebebbe/com.philips.hue.zigbee#318]
Can I use a Hue Smart Plug as Zigbee Router? Somehow I can not connect the Hue Smart Plug into the Homey with this app. I'm also not able to add other Zigbee devices so maybe the problem is now in the Homey. So maybe I need to reset my Zigbee network and build it up again. But can I use the Hue Smart Plug as a router for the Zigbee network with this app?

**Comment by JohanBendz** [comment]
Hi @PimKoedijk. Yes, all Philips Hue devices that is grid powered acts as mesh "routers".

If you are unable to add any Zigbee devices even as Generic Zigbee you have a Homey issue.
