### ISSUE TITLE
App still supported?

### ISSUE THREAD

**Issue by RobVoogt** [sebbebebbe/com.philips.hue.zigbee#32]
Hello,

Is this app still supported? I send the developper via email a request for a new Hue spot but no reaction so far.

Regards,

Rob

**Comment by sebbebebbe** [comment]
@RobVoogt 
Hello,

Well yes and no. I haven´t had any time to make any changes this far. Im hoping there will be some time during the holidays to add support for more devices.

Sorry for keeping you hanging.

Regards,
Sebastian

**Comment by dkduck** [comment]
@sebbebebbe 

Hi Sebastian

If you want some help to get more devices added, I would gladly help, then it’s only the packing the app and send to Athom for release for you to do ( I don't how to do that) :-)

And awsome work you have done so far

Kind regards
Erik

**Comment by sebbebebbe** [comment]
@dkduck 

Hi Erik,

I would love some help with adding new devices.
Send me a mail on sebastian@hibbisoft.se and I will hook you up with some more info.

Regards,
Sebastian

**Comment by RobVoogt** [comment]
Hi Erik and Sabastian,

This is fantastic news, hopefully the new hue lamps/bulbs are supported in the near future. Keep us posted.

Regards,

Rob
