### ISSUE TITLE
Doesnt recognize Phillips Signe Floor Light 

### ISSUE THREAD

**Issue by JimvK** [sebbebebbe/com.philips.hue.zigbee#320]
I bought a new Philips Signe Floor Light and I'm trying to pair it with my 2016 Homey but it won't recognize it. It will only allow me to pair it as an unknown Zigby device.

**Comment by JohanBendz** [comment]
Hi @JimvK, when you add it as a generic Zigbee, what ProductId does it get?

**Comment by JimvK** [comment]
Dear Johan,

The product ID is 4080248P9 and the producer ID is Phillips

Best wishes
Jim

**Comment by JohanBendz** [comment]
Ok, thanks for the request. It's added to the next release.

**Comment by JimvK** [comment]
Thank you for your response very much for the service. Have a great weekend

**Comment by sjoerdmaessen** [comment]
Same issue, awesome to see it will be supported in the next release. Looking forward to the update. Just wanted tk say thank you.

**Comment by JimvK** [comment]
@JohanBendz is it possible to get notified when the new update has arrived? 

Best wishes
