### ISSUE TITLE
HUE Motion Sensor Frage

### ISSUE THREAD

**Issue by clipse2004** [sebbebebbe/com.philips.hue.zigbee#322]
Hi,
Hab grad erst gesehen dass das hier auf deutsch ist :D.
Du ich habe aktuell mit den Motion Sensoren und der Lux Übermittlung Probleme, teils meldet er das extrem spät. Das hat zur Folge, das manchmal kein Licht angeht weil er immer noch denkt es hätte zB. 30Lux ,aber tatsächlich ist es nur 1 (0) Lux.
Ich hab jetzt mal testweise den min Report Intervall auf 30 und den Max auf 60 gestellt. Hat aber nichts verändert.
Kannst du mir erklären wie diese beiden werden gemeint sind? Heißt das (also bezogen auf meine Werte) das er irgendwann zwischen 30 und 60 Sekunden, bei Lichtänderung erst meldet?
Die Sensoren wurden von mir schon desöfteren neu hinzu gefügt :/

ich danke dir

**Comment by JohanBendz** [comment]
Hi @clipse2004.
The values for reporting is "min", "max" and "change".

The "min" value defines how often the device can report. Even if something happens between reports the device will wait this long before reporting it.

The "max" value defines how seldom the device can report. Even if nothing have happened the device will report it's current status efter this long time.

The "change" value is not user settable, it's set at 1, eg every change in lux will trigger a report event.

I will have a look at if I somehow can make the reporting better.

**Comment by JohanBendz** [comment]
Closing, changes has been made in later updates.
