### ISSUE TITLE
Phillip Hue Adore Bathroom Ceiling Light - 3418411P6

### ISSUE THREAD

**Issue by oddinge73** [sebbebebbe/com.philips.hue.zigbee#325]
My Homey can't recognize Adore Bathroom mirror so it use standard ZigBee unit. As a conseqence, Im not able to change color, only dim. Is that a problem after homey update?

I have 3 other PH units, they works fine.

![image](https://user-images.githubusercontent.com/83422068/117491607-b1da3e00-af70-11eb-8194-be8d9cff3366.png)

![image](https://user-images.githubusercontent.com/83422068/117491650-c3234a80-af70-11eb-8ed0-24c3b0cdda44.png)

**Comment by JohanBendz** [comment]
When you add it as a generic Zigbee unit, what productId does it have?

**Comment by oddinge73** [comment]
Hello.
Product ID is 3418411P6.

It's a ceilinglamp for bathroom,  not Bathroom mirror

Regards
Odd Inge Jacobsen

**Comment by oddinge73** [comment]
Did you find this product? Are there need for an update to get this product in Phillips Hue app?

**Comment by JohanBendz** [comment]
Added to next release
