### ISSUE TITLE
Hue Remote unresponsive after periode of time +24 hrs

### ISSUE THREAD

**Issue by ghost** [sebbebebbe/com.philips.hue.zigbee#326]
Each 24 hours my remotes don't tend to work. If I reboot homey everything works again voor +/- 12 hours.
First I though it was the zigbee network. But yesterday I installed a Ikea hub. (I use Ikea tradfri as lights). And when the remotes were not responding I tried reaching the lamp via the homey portal this worked. Only remote didn't seem to do anything. After reboot everything works again. It looks like a sleeping mode or something can u help me?

**Comment by JohanBendz** [comment]
closing as there has been multiple updates since. If you still experince this please open a new issue.
