### ISSUE TITLE
Bulb A60 E27 Color & Ambiance - LCA001

### ISSUE THREAD

**Issue by joerithienpont** [sebbebebbe/com.philips.hue.zigbee#328]
As title says, I only see the bluetooth version?

**Comment by joerithienpont** [comment]
https://zigbee.blakadder.com/Philips_LCA001.html

**Comment by augustofinamore** [comment]
Same issue here: have 2 of these lamps, can't add them.

**Comment by JohanBendz** [comment]
Added to next release
