### ISSUE TITLE
Question: Hue Bridge as emulated service

### ISSUE THREAD

**Issue by eelco2k** [sebbebebbe/com.philips.hue.zigbee#33]
is this package working like a emulated Hue Bridge so that it is for example possible to "see" a Hue Bridge in your LAN network but then implemented in Athom Homey?

**Comment by sebbebebbe** [comment]
I am not really sure what you are asking. But it does not emulate a Hue Bridge. It uses Homey to send messages to ZigBee devices.

**Comment by eelco2k** [comment]
For example i'm using a Logitech Harmony. but for it to be able to control the lights it can only connect to Philips Hue Bridge to control the lights via the remote control. 
But i'm guessting it's a to big of a project to build a "philips hue bridge server" in homey so that compatible light switches (even from z-wave or other devices connected to homey" can be controlled via the philips hue bridge.. Much like the "homeKit/HomeyKit" implementation of Homey works..

**Comment by sebbebebbe** [comment]
It sounds like you would be looking for a Logitech Harmony app instead to link the features together.

**Comment by eelco2k** [comment]
that would be the logical way, yes. but unfortunatelly Logitech Harmony app has no API for controlling the lights.. only for "devices" and "activities". and those features are already build by a great developer of the homey Logitech Harmony Hub app. 

But i think it's to much work for such small feature on the logitech harmony to hack into it via an "emulated hue bridge".
