### ISSUE TITLE
Additional device ID 1746347P7 for Appear outdoor light

### ISSUE THREAD

**Issue by happytesting** [sebbebebbe/com.philips.hue.zigbee#331]
Hi, 

Please add the device ID for Appear outdoor wall lamp: 1746347P7

I see you already have the device, so just adding the ID, is there anything more you need from me? I guess its the missing ID that is enough since they come in as generic zigbee devices?

Cheers

https://www.dropbox.com/s/mgnpt81mxmc90lu/Sk%C3%A4rmavbild%202021-05-31%20kl.%2021.19.06.png?dl=0

**Comment by JohanBendz** [comment]
Added to next release.
