### ISSUE TITLE
Hue Amarant light bar for outdoor - 1746630P7

### ISSUE THREAD

**Issue by Muiske** [sebbebebbe/com.philips.hue.zigbee#332]
Please add support for the Philips Hue Amarant outdoor light.
[https://www.philips-hue.com/en-us/p/hue-white-and-color-ambiance-amarant-linear-outdoor-light/1746630V7#overview](url)

Product ID: 1746630P7

Let me now if you need more info.

BTW: the Nyro outdoor pedestal is working great with the app (i have 8 of them).

Thanks.

**Comment by JohanBendz** [comment]
Added to next release
