### ISSUE TITLE
2.0.36 still not published on homey app store

### ISSUE THREAD

**Issue by arovik85** [sebbebebbe/com.philips.hue.zigbee#333]
Hi.
One of my suggestions got merged into 2.0.36. but this version is still not available in the homey app store for me to do the update. When will it be available?

**Comment by arjanvdbos** [comment]
@JohanBendz This is an update I'm also looking forward to; is the update already under review or has it yet to be published?

**Comment by arovik85** [comment]
Any status on the release of this version?

**Comment by JohanBendz** [comment]
A new version is on it's way
