### ISSUE TITLE
Hue Signe Floor light - 4080248P9

### ISSUE THREAD

**Issue by paaccoo** [sebbebebbe/com.philips.hue.zigbee#338]
Hi, 
The Hue Signe Floor light is not recognized and added as generic ZigBee device.
Product ID = 4080248P9.

**Comment by packetninja** [comment]
I actually have the same issue with my Signe. Wanted to add to this thread. :-)

**Comment by cgroenen** [comment]
Yes, I also have this issue. When will version 2.0.36 be released?

**Comment by Martin1985as** [comment]
Is there any development on this?
I have the same issue and see there's no update since 9 months ago.

**Comment by JohanBendz** [comment]
Hi all.
Yes @Martin1985as, an update of the app is underway.

**Comment by JohanBendz** [comment]
Added to next release.
