### ISSUE TITLE
[Request] Add support of dimmer with Product ID = RWL020

### ISSUE THREAD

**Issue by radkoslav** [sebbebebbe/com.philips.hue.zigbee#34]
Hi.
I just bought 12 Phillips dimmers and paired them with homey using your app. However with one I run into issue that it was recognized as Unknown Zigbee Device.

After doing some research I found out that apart of supported RWL021 dimmer product IDs there is more exotic dimmer product ID = RWL020 (device ID and profile ID are same as well) - and the one not working is RWL020. By briefly checking your code I see only product id RWL021 is supported there.

Can you please add support of this product ID (RWL020) as well?

Thanks in advance.

**Comment by sebbebebbe** [comment]
Hi,

I have noted your request. Please be aware of that there are some issues related to the dimmers in the underlying ZigBee implementation. Mainly consisting of connection issues.

**Comment by sebbebebbe** [comment]
Has been added and will be included in the next release.
