### ISSUE TITLE
Philips Lily spots - LCS001

### ISSUE THREAD

**Issue by TomBraneworld** [sebbebebbe/com.philips.hue.zigbee#340]
I bought some new Philips Lily Outdoor Spots and they will not be recognized by the App. The reported Product-ID is 1741430P7. The older spots, on the other hand, have the Product-ID LCS001.

**Comment by matt20v** [comment]
Hey @TomBraneworld glad you have commented i am having the same issue, i have 3 working fine then i went to add two more and it either wont pair or it gets added as a generic zigbee 😢😢😢

@JohanBendz do you need any more details about the devices to help make them work again ? 

I am running app version 2.0.35

Homey os - 7.1.0

Thanks as always for your help !!

**Comment by matt20v** [comment]
@TomBraneworld not sure if your still not able to add your new devices but i found if i just try and add them as Lily XL it detected one and then just added it as a basic zigbee i went and added my 2nd new device as a normal Lily outdoor spot and it detected and then did the same thing added it as a generic zigbee not solved but i can at least use them now 👌🏽

Hope it might help🙌🏽

**Comment by TomBraneworld** [comment]
**@matt20v** thank you for the hints. The problem has already been solved by the Homey Update 7.1. With the new "Zigbee Lights" function, I can now address the spots with full functionality, even if they are not recognized by the Hue app.

**Comment by matt20v** [comment]
Hey @TomBraneworld 

Yes that’s it, its just the homey generic function taking over hopefully John when he has time will fix it so it is all in the right groups and the icons are the same  :-)!


Cheers Matt

**Comment by JohanBendz** [comment]
Added to next release.
