### ISSUE TITLE
Cannot add Hue dimmer switch

### ISSUE THREAD

**Issue by sanderjacobsen** [sebbebebbe/com.philips.hue.zigbee#341]
Hi guys, I'm can't add the Hue dimmer switch (https://www.bol.com/nl/nl/p/philips-hue-dimmer-switch-draadloze-schakelaar-slimme-verlichting-accessoire-wit-incl-batterij/9300000020528391/?s2a=). First I  press the reset button above the battery for 10 seconds untill the green light. After the green light I release the button. I see the green light is going out, thereafter blinking green and red light. After the blinking a "normal" blinking light.

Nothing happens in Homey. Did I miss something?

**Comment by tfsjohan** [comment]
Same here. Did you ever find a fix?

**Comment by sanderjacobsen** [comment]
> Same here. Did you ever find a fix?

Yes the solution was a Zigbee reset in Homey.
