### ISSUE TITLE
Philips Hue Centris 3-spot - 5060930P7_04 + panel - 5060930P7_01

### ISSUE THREAD

**Issue by packetninja** [sebbebebbe/com.philips.hue.zigbee#346]
I saw in #285 and #286 that support for the Centris 2/4 spot was added. I have a 3-spot and that is not supported. 

- I'm able (with much difficulty (resets through bluetooth) to get the panel and 3rd spot (start counting from panel, so most outside spot) added as basic zigbee device. 
- For one other spot is says "being added", but that is where is hangs (and it never gets added)
- I can't get the last spot to be discovered, even after numerous resets.

IDs:
panel: 5060930P7_01
3rd spot: 5060930P7_04

Logic would say the 1st and 2nd spot are IDs "_02" and "_03", but I can't confirm this.

I bought a 4 spot and 3 spot Centris at the same time. Much appreciated if you can help out here.

**Comment by packetninja** [comment]
I think I received a Centris that was previously connected to a bridge. Somehow that made it very hard to reset it without a bridge or remote. However, I got my remote this evening and managed to reset all of them. I can confirm that the other Spot IDs are indeed "_02" and "_03".

**Comment by JohanBendz** [comment]
All added to next release
