### ISSUE TITLE
E27 lamps: 806 lumen hue white,  A60 9W 60mA 2700k

### ISSUE THREAD

**Issue by Ipadrao** [sebbebebbe/com.philips.hue.zigbee#349]
I can't integrate philips hue E27 lamps!!
806 lumen hue white A60 9W 60mA 2700k

**Comment by JohanBendz** [comment]
Hi @Ipadrao, I need more information to be able to add support for a device. Please add it as a generic zigbee device and get back to med with modelID/ProductID.

**Comment by Ipadrao** [comment]
thank you @JohanBendz , but i have already managed to add this kind of devices. I should have deleted the issue, but I didn't remember. sorry

**Comment by JohanBendz** [comment]
Np, happy it works for you.
