### ISSUE TITLE
Add support for Aurelle LED panel (3216331P5)

### ISSUE THREAD

**Issue by kristofferpeterhansel** [sebbebebbe/com.philips.hue.zigbee#35]
It seems to be fairly new. And hard to actually find on the English  Phillips Hue pages. But I got one of these: https://www.p4c.philips.com/files/3/3216331p5/3216331p5_pss_.pdf. And figured I'd add it to the list of devices to support.

**Comment by sebbebebbe** [comment]
I will add it to my TODO-list.

**Comment by dkduck** [comment]
@kristofferpeterhansel 
Could you please provide:

deviceId and profileId

**Comment by kristofferpeterhansel** [comment]
Hey

Would this be something I could extract from the Athom dev tools? I was was looking to see if I could see the device though it. And so far I have not had much success. 

/Kristoffer Peterhänsel

**Comment by sebbebebbe** [comment]
Add it as a Generic device first and then check the device information for the device.
If you need more info on doing this we will help you.

**Comment by kristofferpeterhansel** [comment]
Hmm. Maybe I didn't get it correctly into pair mode then. I'll git it another go tonight

**Comment by kristofferpeterhansel** [comment]
Strange. Seems to not be working.

1) I put it into pairing mode with a dimmer switch (holding down first and third button from the top).
1) lamp flashes.
1) I click the add ZigBee button in the Homey app.
1) Lamp brightens the light (this happens no matter if I do step 3)
1) Nothing happens in Homey

A reset of the lamp does not seem to do anything either (holding down first button until lap blinks). 

Suggestions? Or is there a chance it is incompatible somehow. The included dimmer seems to be the same. So it can't be that different from the other offerings? 😕

**Comment by sebbebebbe** [comment]
Im not sure if you should go thorough with step 1. I usually do it like this.

Reset the bulb with a RWL021 hue dimmer switch. Keep the dimmer close to the bulb and then press on and off at the same time until the bulb flashes. Then i just go and att new zigbee device in homey.

It could also be that it is using ZigBee 3.0 after searching for some info on that particular lamp. And i don´t think that it will be possible to add to Homey in that case. Try contacting Athom support and ask if your particular device will be compatible.

**Comment by kristofferpeterhansel** [comment]
Oh. That is a new key combination I don't think I have tried. I'll give that a shot.

But yeah. I did come across references to ZigBee 3.0 too. But didn't find up with much info from either Philips or Athom about protocol versions - except that Philips started moving to ZigBee 3.0.

Still it seems all the basic infrastructure from Philips has not changed. It is the same bridges and remotes. And 3.0 is supposed to be compatible with Zigbee Light Link that seemed to be used before.

**Comment by kristofferpeterhansel** [comment]
Yay! It worked. Took a couple of attempts (think maybe the remote will sometimes end up behaving as when just holding down the on button?).

But here we go:
![screenshot 2018-11-27 at 22 58 15](https://user-images.githubusercontent.com/6907530/49114258-0ead7680-f298-11e8-85cc-450d50ea466c.png)

**Comment by sebbebebbe** [comment]
Nice thx it´s added to the todo-list.

**Comment by kristofferpeterhansel** [comment]
BTW. Initial testing of 1.4.3 beta seems to indicate it works
