### ISSUE TITLE
Support Homey Bridge

### ISSUE THREAD

**Issue by bashuis** [sebbebebbe/com.philips.hue.zigbee#352]
Hi,

Are there plans to support the new Homey Bridge?

Kind regards
Bas

**Comment by bashuis** [comment]
Any news?

**Comment by JohanBendz** [comment]
Hi @bashuis, as of right now Athom do not let me publish this app with support for the bridge as there is generic Zigbee support in the bridge already and have support for the Hue hub in the cloud. Perhaps that will change with time... I hope so..

**Comment by bashuis** [comment]
Thnx for the reply.

Is it possible to install an app on the bridge like on the Pro?

Then i can install your app manual.

**Comment by JohanBendz** [comment]
No, it's not. No apps are installed on the bridge, Homey is cloud based and the apps are installed in the cloud. Only Homey Pro can have apps installed in the local unit.

**Comment by marcelbodde** [comment]
So, i understatement, there will be no solution for it.
I have to spend money for the Hue bridge.

**Comment by JohanBendz** [comment]
@marcelbodde I will make the app Bridge compatible but it is really up to Athom to decide if they will let it support the Bridge. One CAN sideload the app on the Bridge by using the CLI installation but this require a computer to be running a docker container for the app... not very user friendly ;)

**Comment by marcelbodde** [comment]
Hey Johan,

Thanks for your answer.
I dont know what you mean by a donker container? Should this computer be always running?
Is there more information about setting up a donker container?

Greetz,

Marcel


________________________________

**Comment by JohanBendz** [comment]
Hi @marcelbodde, setting up a docker container running apps sideloaded is quite outside of this app :)
I suggest you create a new topic here: https://community.homey.app/c/questions-help/8
