### ISSUE TITLE
Adding HUE lights to Zigbee, makes zigbee network buggy & not responsive

### ISSUE THREAD

**Issue by sossienl** [sebbebebbe/com.philips.hue.zigbee#353]
I have had a steady Zigbee network for over several weeks now. I use 4 "routers" that are strategically placed in the house, all end devices (sensors) are connected fine.

Yesterday I tried to add 3 new HUE lights directly to my Zigbee network, so not using the HUE Bridge.
Adding the first one, was almost instant.
The second one took more than 10 tries, but eventually, it worked.
The third one didn't add, whatever I tried.

I also saw issues occurring with 2 sensors in the other room (Aqara sensors). 
I removed them and tried to add them again, but this was also unsuccessful.

When switching off the power on the newly added HUE devices **completely** (so no electricity), allowed me to add the 3rd HUE light and the two sensors, without any issue and instantly.

When switching on the lights again (power on), introduces new issues, Aqara motion sensors that do not report back anymore. The issue occurs when one of my original routers is meshing with one of the HUE lights and not directly reporting to Homey.

**Situation 1, where everything works GOOD:** 

Router A has ID 5 and routing is: 0 > 5

Sensor A has ID 25 and routing is 0 > 5 > 25
Sensor B has ID 33 and routing is: 0 > 5  > 33

HUE Light A has ID 29 and routing is: 0 > 29
HUE LIght B has ID 28 and routing is 0 > 29 > 28

**Situation 2, where it BREAKS :** 

**Router A has ID 5 and routing is: 0 > 29 > 5** (this happens automatically )

Sensor A has ID 25 and routing is 0 > 5 > 25
Sensor B has ID 33 and routing is: 0 > 5  > 33

HUE Light A has ID 29 and routing is: 0 > 29
HUE LIght B has ID 28 and routing is 0 > 29 > 28

**Comment by sossienl** [comment]
Issues also occur when for instance my Aqara motion sensor is routing directly through for instance HUE ID 29 (0 > 29 > 25).
Point being: I believe the Router functionality is not correctly working for these HUE lights.

**Comment by JohanBendz** [comment]
Hi @sossienl, thanks for the feedback.
Problem is that I have no ability to manage how Hue and Homey talks over Zigbee.. that's nothing I can fix from the app.
I will however talk to Athom about this and see if they can find out what is wrong and how to fix it.

**Comment by sossienl** [comment]
Thanks. Any update / input from Athom  on this?

**Comment by sossienl** [comment]
I believe nothing right?

**Comment by JohanBendz** [comment]
Hi @sossienl. The upcoming app version hopefully fix this. Athom has released an updated driver and it looks very promising.

**Comment by sossienl** [comment]
I’ll try later today. I hope they fixed it. My Hue network is full using the existing Philips gateway. So adding some directly would solve it, plus it would further stabilize the zigbee mesh (IF it works as expected)

**Comment by sossienl** [comment]
I've added two HUE lights and after that a new Aqara Sensor. Without an issue!
Also, routing seems to be working. Fantastic!
