### ISSUE TITLE
All devices times out

### ISSUE THREAD

**Issue by CheggenOnline** [sebbebebbe/com.philips.hue.zigbee#354]
Starting yesterday i cant reach any devices added through the app.

**Comment by CheggenOnline** [comment]
I have sent an diagnostics report

**Comment by CheggenOnline** [comment]
461271bb-f57c-4296-aee3-3b7c38bdb15e

**Comment by JohanBendz** [comment]
Hi Christian, I noticed on the forum your issue is fixed so I will close this case :)
