### ISSUE TITLE
Iris hue living color gen 4 … impossible appairing 

### ISSUE THREAD

**Issue by romfany** [sebbebebbe/com.philips.hue.zigbee#355]
Hello, 

i can’t appair my Last living color iris gold édition with my homeypro … the official app do This (meet hue Philips Bluetooth mode …) why Homey can’t ? :-(

**Comment by JohanBendz** [comment]
Hi @romfany, please have a look here if this can help: https://zigbee.blakadder.com/Philips_LLC010.html
