### ISSUE TITLE
Motion sensor Temperature compensation issue

### ISSUE THREAD

**Issue by f8006539** [sebbebebbe/com.philips.hue.zigbee#358]
The temperature compensation value isn't added to the temperature measurement of the motion sensor.

**Comment by red4evil** [comment]
![F87F5B93-9327-4338-B9E4-A2078457212C](https://user-images.githubusercontent.com/31590736/140637317-e1efc461-d45f-4f0a-965c-c0402673393c.jpeg)
![69309963-471D-49EE-8306-82E226AD1F7D](https://user-images.githubusercontent.com/31590736/140637319-6c8b1cfd-a6db-4e29-969b-d207b71d6bad.jpeg)
![88424155-36C5-403B-A22B-A641043A257F](https://user-images.githubusercontent.com/31590736/140637320-2e72aab6-d207-4750-9fac-48630e56df27.jpeg)
![CBFD3712-467D-479E-81D4-CC1BF285E5DD](https://user-images.githubusercontent.com/31590736/140637321-df14e90f-39d4-4e2e-a672-f59338b89d5e.jpeg)

**Comment by red4evil** [comment]
At this time adding the Device is not functioning properly. 
ptp, reboot of app and homy did not work.

**Comment by JohanBendz** [comment]
Hi @red4evil, is this still an issue?

**Comment by hwharwig** [comment]
Hi Johan, for me yes, just bought 3 sensors and they all give the same result "Unknown Zigbee Device". did some reboots, reset of zigbee network but same result. Any ideas? In the Zigbee advanced settings of the added unknown device it displays Product ID SML003.
(is there a difference in motion sensor and occupancy sensor? I tried both with same negative result)
App v2.0.35, Homey v7.2.1

**Comment by JohanBendz** [comment]
Hi @hwharwig, the new indoor sensor will be supported in next update of the app.

@red4evil, if you still have an issue with this device please open a new issue.

**Comment by JohanBendz** [comment]
@f8006539 Is your problem still an issue?

**Comment by nielslbeck** [comment]
I have 15 brand new motion sensors which all are added as "Basic Zigbee Device" 🤥

When will the updated version of your great app reach the store? When looking at https://homey.app/en-us/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/ it says the current version is 2.0.35 but when looking at the changelog I can see version 2.0.36 and 2.0.37 too 🤔 I currently have 2.0.35 installed on my Homey.

**Comment by JohanBendz** [comment]
Hi @nielslbeck, I have released a test version with support for the new unit. I got a few comments on issues from early testers so I might need to fix something but you are welcome to try it out, nothing in your Homey will break :) And you can revert to Live version without any issues if needed,

https://homey.app/en-gb/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/

**Comment by nielslbeck** [comment]
Great! Thank you for your fast reply.

I installed it yesterday and it seems to be working :-)

However, after a restart of the Homey there is a red warning triangle on all motion sensors. If I click into the sensor it says "Device is unavailable - device is unreachable". I don't know if the issues from the early testers are the same? 

If there is anything I can do to help you resolve the issue please let me know.

**Comment by HLamboo** [comment]
> Hi @nielslbeck, I have released a test version with support for the new unit. I got a few comments on issues from early testers so I might need to fix something but you are welcome to try it out, nothing in your Homey will break :) And you can revert to Live version without any issues if needed,
> 
> https://homey.app/en-gb/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/

Hello Johan, 

I tested this version for the Hue Indoor sensor. The sensor is recognized but the app makes a occupancy sensor of it, but I selected a Motion sensor. It would be nice that the app makes a motion sensor of it.

Thanks for sofar.

**Comment by JohanBendz** [comment]
Closing this issue, there is an update in the test version of the app and there will be an update of the Zigbee stack in the upcoming release that might help anyone still with problems.
