### ISSUE TITLE
Add support for Phoenix Wall Light

### ISSUE THREAD

**Issue by dhanjel** [sebbebebbe/com.philips.hue.zigbee#36]
I would love to see support for Phoenix Wall Light.
Right now it ends up as unknown zigbee device and can be powered on/off, but be able to dim it as well would be nice.

Hopefully not a lot of work since other Phoenix-devices already are included.

Let me know if testing is needed.

https://www2.meethue.com/en-gb/p/hue-white-ambiance-phoenix-wall-light/3115331PH

**Comment by sebbebebbe** [comment]
Added it to the TODO list.

**Comment by dkduck** [comment]
@dhanjel 

Could you please provide:

deviceId and profileId

**Comment by dhanjel** [comment]
Is it this?

HML004 / 49246

**Comment by dkduck** [comment]
@dhanjel 
Almost :-)

![5d364e56-aeab-4c1b-b77a-701b7aa75c51](https://user-images.githubusercontent.com/36172135/49032427-c9f8e100-f1ac-11e8-838b-505ced943925.jpeg)

**Comment by dhanjel** [comment]
@dkduck , Close, but no cigar :)

Product ID: HML004
Device ID: 544
Profile ID: 49246
