### ISSUE TITLE
Hue Calla Outdoor (short) - 1742030P7

### ISSUE THREAD

**Issue by Rubn86** [sebbebebbe/com.philips.hue.zigbee#361]
Hi,

I have recently bought new Hue Calla short lights, but they are not recognized in the app.
I think the product ID has changed, it is showing up as 1742030P7 whereas my older Calla are showing as LCF002, which are recognized.

Thanks!

**Comment by JohanBendz** [comment]
Added to next release.

**Comment by jajopajo** [comment]
Recently I have bought several Hue Calla Outdoor (short) and some have product ID 1742030P7 (these can be added), but others have different product ID 1742330P7 (these are not recognized).
