### ISSUE TITLE
White and Color Ambiance 6.5W 800 E27 (BT/Zigbee) - LCA004

### ISSUE THREAD

**Issue by Gamer978** [sebbebebbe/com.philips.hue.zigbee#363]
Hello,

I have issue adding bulbs Philips Hue White and Color Ambiance 6.5W 800 E27 (BT/Zigbee) to my Homey Pro.
When i select them and finish the pairing process an Error pops up saying the device is uknown, so it's added as a basic zigbee device.

I tryed adding 4 piececs with the process of being recognized as basic zigbee device is same and the following happens:

1) The "Power on behavior" in iOS BT Hue app disappears (tested on both iPhone 13 Pro and iPhone 7).
2) The bulbs pending update wont carry out, unless i reset the bulbs and remove them from homey and update them before adding to Homey again.
3) The bulbs reset color on each hard off via power switch, after i remove them from homey and install them again ONLY in Philips hue BT app they work properly. To be exact i can use "Power on behavior color" and it works even after 2 hrs of hard off (tested). After i add them to homey again, they cease to work properly. 

For additional info i am using v 2.0.35 "Philips Hue, without the bridge" in my Homey v. 7.2.0.
The model of all 4 bulbs is: LCA004

Any possible help from Johan Bendz as a developer in this issue is very welcome. 
For now i am not looking forward to get hue bridge this year :-p.

Thank you kindly in advance for making it down here.

**Comment by alexfost** [comment]
I also bought the Phillips Hue WHite and Color 800 with ID LCA004 and cant add the Device to Homey.

Could you add supprt to it? I would highly appreciate it!!

Interview result:


  "ids": {
    "modelId": "LCA004",
    "manufacturerName": "Signify Netherlands B.V."
  },
  "endpoints": {
    "endpointDescriptors": [
      {
        "endpointId": 11,
        "applicationProfileId": 260,
        "applicationDeviceId": 269,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          0,
          3,
          4,
          5,
          6,
          8,
          4096,
          64514,
          768,
          64513
        ],
        "outputClusters": [
          25
        ]
      },
      {
        "endpointId": 242,
        "applicationProfileId": 41440,
        "applicationDeviceId": 97,
        "applicationDeviceVersion": 0,
        "_reserved1": 0,
        "inputClusters": [],
        "outputClusters": [
          33
        ]
      }
    ],
    "endpoints": {
      "11": {
        "clusters": {
          "basic": {
            "attributes": [
              {
                "id": 0,
                "name": "zclVersion",
                "value": 2
              },
              {
                "id": 1,
                "name": "appVersion",
                "value": 2
              },
              {
                "id": 2,
                "name": "stackVersion",
                "value": 1
              },
              {
                "id": 3,
                "name": "hwVersion",
                "value": 1
              },
              {
                "id": 4,
                "name": "manufacturerName",
                "value": "Signify Netherlands B.V."
              },
              {
                "id": 5,
                "name": "modelId",
                "value": "LCA004"
              },
              {
                "id": 6,
                "name": "dateCode",
                "value": "20201117"
              },
              {
                "id": 7,
                "name": "powerSource",
                "value": "mains"
              },
              {
                "id": 8,
                "name": "appProfileVersion",
                "value": 0
              },
              {
                "id": 9
              },
              {
                "id": 10
              },
              {
                "id": 11
              },
              {
                "id": 16384,
                "name": "swBuildId",
                "value": "1.76.11"
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "identify": {
            "attributes": [
              {
                "id": 0
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "groups": {
            "attributes": [
              {
                "id": 0,
                "name": "nameSupport",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0
                  ]
                }
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "scenes": {
            "attributes": [
              {
                "id": 0
              },
              {
                "id": 1
              },
              {
                "id": 2
              },
              {
                "id": 3
              },
              {
                "id": 4
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "onOff": {
            "attributes": [
              {
                "id": 0,
                "name": "onOff",
                "value": true
              },
              {
                "id": 16384
              },
              {
                "id": 16385,
                "name": "onTime",
                "value": 0
              },
              {
                "id": 16386,
                "name": "offWaitTime",
                "value": 0
              },
              {
                "id": 16387
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "levelControl": {
            "attributes": [
              {
                "id": 0,
                "name": "currentLevel",
                "value": 254
              },
              {
                "id": 1,
                "name": "remainingTime",
                "value": 0
              },
              {
                "id": 15
              },
              {
                "id": 16384
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "touchlink": {
            "attributes": [
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1,
                "reportingConfiguration": {
                  "status": "UNREPORTABLE_ATTRIBUTE",
                  "direction": "reported"
                }
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "colorControl": {
            "attributes": [
              {
                "id": 0,
                "name": "currentHue",
                "value": 199
              },
              {
                "id": 1,
                "name": "currentSaturation",
                "value": 97
              },
              {
                "id": 2
              },
              {
                "id": 3,
                "name": "currentX",
                "value": 22178
              },
              {
                "id": 4,
                "name": "currentY",
                "value": 17875
              },
              {
                "id": 7,
                "name": "colorTemperatureMireds",
                "value": 189
              },
              {
                "id": 8,
                "name": "colorMode",
                "value": "currentXAndCurrentY"
              },
              {
                "id": 15
              },
              {
                "id": 16
              },
              {
                "id": 17
              },
              {
                "id": 18
              },
              {
                "id": 19
              },
              {
                "id": 21
              },
              {
                "id": 22
              },
              {
                "id": 23
              },
              {
                "id": 25
              },
              {
                "id": 26
              },
              {
                "id": 27
              },
              {
                "id": 48
              },
              {
                "id": 49
              },
              {
                "id": 50
              },
              {
                "id": 51
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND"
          }
        },
        "bindings": {
          "ota": {
            "attributes": [],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        }
      },
      "242": {
        "clusters": {},
        "bindings": {}
      }
    }
  }

**Comment by JohanBendz** [comment]
Added to next release.
