### ISSUE TITLE
Smart plug - LOM007

### ISSUE THREAD

**Issue by Krisstenswe** [sebbebebbe/com.philips.hue.zigbee#364]
Hi!

I have issues to add Philips Hue Smart Plug.
When I try and finish the pairing process an error pops up saying there is no app for this device, so it's added as a basic zigbee device.
![8B0DD1B8-6069-4644-B70B-0D2EF4D374EA](https://user-images.githubusercontent.com/33200170/144227655-ce31b684-0bce-4329-b3fa-e7812dbeedd5.png)

I have tried all the usual bits; restarted app, Homey, checked latest versions on everything, device close to Homey, and so on…

**Comment by Krisstenswe** [comment]
When I look on the devices in the Developer site, I can see that my earlier Philips Hue Smart plugs has ProductID "LOM001". The new Smart plugs I try to pair (I have bougt them now) has ProductID "LOM007". Maybe Philips changed the ProductID on the Smart plugs and since LOM007 can't be find in the app, then Homey pair it as a Basic Zigbee device..?

**Comment by varghexum** [comment]
> When I look on the devices in the Developer site, I can see that my earlier Philips Hue Smart plugs has ProductID "LOM001". The new Smart plugs I try to pair (I have bougt them now) has ProductID "LOM007". Maybe Philips changed the ProductID on the Smart plugs and since LOM007 can't be find in the app, then Homey pair it as a Basic Zigbee device..?

I have the same issue, the ProductID is LOM007.

**Comment by JohanBendz** [comment]
`"ids": {
    "modelId": "LOM007",
    "manufacturerName": "Signify Netherlands B.V."
  },
  "endpoints": {
    "endpointDescriptors": [
      {
        "endpointId": 11,
        "applicationProfileId": 260,
        "applicationDeviceId": 266,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          0,
          3,
          4,
          5,
          6,
          8,
          4096,
          64514
        ],
        "outputClusters": [
          25
        ]
      },
      {
        "endpointId": 242,
        "applicationProfileId": 41440,
        "applicationDeviceId": 97,
        "applicationDeviceVersion": 0,
        "_reserved1": 0,
        "inputClusters": [],
        "outputClusters": [
          33
        ]
      }
    ],
    "endpoints": {
      "11": {
        "clusters": {
          "basic": {
            "attributes": [
              {
                "id": 0,
                "name": "zclVersion",
                "value": 2
              },
              {
                "id": 1,
                "name": "appVersion",
                "value": 2
              },
              {
                "id": 2,
                "name": "stackVersion",
                "value": 1
              },
              {
                "id": 3,
                "name": "hwVersion",
                "value": 1
              },
              {
                "id": 4,
                "name": "manufacturerName",
                "value": "Signify Netherlands B.V."
              },
              {
                "id": 5,
                "name": "modelId",
                "value": "LOM007"
              },
              {
                "id": 6,
                "name": "dateCode",
                "value": "20201117"
              },
              {
                "id": 7,
                "name": "powerSource",
                "value": "mains"
              },
              {
                "id": 8,
                "name": "appProfileVersion",
                "value": 0
              },
              {
                "id": 9
              },
              {
                "id": 10
              },
              {
                "id": 11
              },
              {
                "id": 16384,
                "name": "swBuildId",
                "value": "1.76.11"
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "identify": {
            "attributes": [
              {
                "id": 0
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "groups": {
            "attributes": [
              {
                "id": 0,
                "name": "nameSupport",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0
                  ]
                }
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "scenes": {
            "attributes": [
              {
                "id": 0
              },
              {
                "id": 1
              },
              {
                "id": 2
              },
              {
                "id": 3
              },
              {
                "id": 4
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "onOff": {
            "attributes": [
              {
                "id": 0,
                "name": "onOff",
                "value": false
              },
              {
                "id": 16384
              },
              {
                "id": 16385,
                "name": "onTime",
                "value": 0
              },
              {
                "id": 16386,
                "name": "offWaitTime",
                "value": 0
              },
              {
                "id": 16387
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "levelControl": {
            "attributes": [
              {
                "id": 0,
                "name": "currentLevel",
                "value": 254
              },
              {
                "id": 1,
                "name": "remainingTime",
                "value": 0
              },
              {
                "id": 15
              },
              {
                "id": 16384
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "touchlink": {
            "attributes": [
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1,
                "reportingConfiguration": {
                  "status": "UNREPORTABLE_ATTRIBUTE",
                  "direction": "reported"
                }
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        },
        "bindings": {
          "ota": {
            "attributes": [],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        }
      },
      "242": {
        "clusters": {},
        "bindings": {}
      }
    }
  }`

**Comment by JohanBendz** [comment]
Added to next release.
