### ISSUE TITLE
Signify Netherlands BV	RDM001

### ISSUE THREAD

**Issue by Chopper6608HM** [sebbebebbe/com.philips.hue.zigbee#365]
Hoi JohanBenz , goedemorgen.
 is het mogelijk dat mijn nieuwe philips hue module (deze kan achter een enkele/ dubbele puls schakelaar geplaatsts worden ) toegevoegd kan worden aan hue without the bridge app, deze geeft nu steeds aan dat deze niet herkend word en als onbekent zigbee apparaat word toegevoegd. De gegevens die er bij staan  zijn: 
(Signify Netherlands BV | RDM001)
Ik had dit al overlegd met bas(Ahtom) en die stuurde me naar jou voor verzoek

Met vriendelijke groet john

**Comment by JohanBendz** [comment]
https://github.com/JohanBendz/com.philips.hue.zigbee/issues/315
