### ISSUE TITLE
ZTHS-100  is onbekend zigbee apparaat

### ISSUE THREAD

**Issue by Chopper6608HM** [sebbebebbe/com.philips.hue.zigbee#366]
Hoi johan , zou je deze ook  kunnen toevoegen aan hue zigbee zonder brug. De ZTHS-100
Bvd 

John kr

**Comment by JohanBendz** [comment]
Is this the product you have? https://www.trust.com/en/product/71247-zigbee-temperature-and-humidity-sensor-zths-100

If so I will not add it to this app, this app only manage Hue devices.

**Comment by Chopper6608HM** [comment]
Okee, bedankt . Heb hem gelijk maar gelijk  weggegooid want na elke keer proberen is hij kapot gegaan waarschijnlijk.ging steeds verkeerde waardws doorgeven.
Mvg chopper
