### ISSUE TITLE
simple Zigbee device much faster

### ISSUE THREAD

**Issue by Deroy2112** [sebbebebbe/com.philips.hue.zigbee#367]
Hello,

my hue zigbee lamps turn on and off much faster when they are included as a simple device at Homey without "Hue, without bridge app".
Can you test by removing a Hue lamp, deactivating the app and integrating the lamp as a simple Zigbee device.
Is this due to the code of the app or has this a technical reason ?

greets deroy

**Comment by Deroy2112** [comment]
Hey JohanBendz

I downloaded your code, installed the latest homey-zigbee driver 1.6.10 via npm install homey-zigbeedriver and installed the app via homey CLI.
The lights switch much faster, with no delay.
There are also no more problems switching many lights at the same time.

Could this be the reason ?

If so, is there a way to update the app on the homey store ?

greets deroy

**Comment by JohanBendz** [comment]
Hi  @Deroy2112, thanks for taking the time to help out! :)
Great find, I have verified what you say and it's really a big difference! Thanks a bunch for making me aware!!
I am about to release an update so this will be included.

(I will check with Athom what has been changed.)
