### ISSUE TITLE
Losing control of GU10 White Ambience BT

### ISSUE THREAD

**Issue by genotix** [sebbebebbe/com.philips.hue.zigbee#370]
Hi Johan,

After installing 5 of my original Warm White GU10’s twice today I have issues addressing them.

I installed the bulbs after factory resetting each. They were controllable. (On, Off, Brightness and Light warmth)
I have added an Ikea Trådfri Switch to control them.

All the bulbs worked fine until a few hours later. The bulb status displays correctly though. (On/Off/Color/Brightness)

For all of them I get either the error:
Apparaat is niet te bereiken.
Or
Appraat reageert niet, zorg ervoor dat deze van stroom is voorzien.

What I have tried:
1. Reset the bulbs (doesn’t resolve)
2. Reset the Hue app (doesn’t resolve)
3. Reset the Homey (doesn’t resolve)
4. Connect the bulbs to the iOS Hue app, give them a factory reset and reconnect them to my Homey. This lasts some hours it seems after losing the ability to control the bulb again.

Any ideas what could be done to fix this?

**Comment by JohanBendz** [comment]
Hi @genotix.
I see two diagnostics that I think are yours, is the product model LTG002 ?
If those are your diagnostics I can't see any issue within the app, no errors for any of the four units.

Have a look at developer tools, https://tools.developer.homey.app/tools/zigbee, are there any issues with the routes to your devices? Are they online? Press the refresh button (circular arrow in upper right part of the screen) and see if something change. If you can't find any issues I suggest you open a support ticket with Athom to have them see if they can help out.

**Comment by genotix** [comment]
One thing I did’t try was move my Athom Homey closer to the light bulbs.

I’m not sure why they initially did work and then stopped working. This still baffles me.

Please consider this a non-issue.
