### ISSUE TITLE
Low battery issue!? Even with brand new batteries 

### ISSUE THREAD

**Issue by Goliath2000** [sebbebebbe/com.philips.hue.zigbee#371]
Strange problem I have with Philips Hue, I have bought new batteries but still I get low battery warning. I have tried two brand new CR2450 but still get this low warning!
Anyone with same issue? Is this a bug?

item I’m using is Philips hue switch gen 2
Product ID RWL021

**Comment by Goliath2000** [comment]
Anyone looking at this?

**Comment by ITemplate** [comment]
I have the same issue with Smart Buttons, Hue Bridge app says 100%, but without the bridge it's always low. My motion sensors does seem to report correctly though.

**Comment by JohanBendz** [comment]
Should work better now
