### ISSUE TITLE
Can’t connect motion detector to Homey pro

### ISSUE THREAD

**Issue by mussemats** [sebbebebbe/com.philips.hue.zigbee#374]
Just bought me a Hue motion detector but the App in Homey says that there is no app to detect a Hue motiondetector so it connects it as a basic zigbee device.

**Comment by hwharwig** [comment]
Have the same problem with 3 Hue motion sensors.
Sorry @JohanBendz, added my comment in #358 since there I found the same screenshots as I have...

**Comment by JohanBendz** [comment]
The new outdoor sensor will be supported in next update of the app.

**Comment by mussemats** [comment]
Hi,
I think my is the indoor version but that will maybe also be affected by the update (I hope).

Regards, Mats

**Comment by ITemplate** [comment]
@mussemats I had the same issue - but try to add them as "Occupancy Sensor" (not Motion Sensor). At least this works for all my indoor motion sensors.
