### ISSUE TITLE
Aquara Vibration Sensor added as Philips bulb

### ISSUE THREAD

**Issue by arnljot** [sebbebebbe/com.philips.hue.zigbee#377]
When trying to pair an Aquara Vibration Sensor (DJT11LM) to my homey, I need to disable this app so that it doesn't add the sensor as a light bulb.

![Screenshot_20220118-203357_Homey](https://user-images.githubusercontent.com/851845/150010415-a6ed171c-c402-4790-beb8-80b9e24b219b.jpg)
![Screenshot_20220118-203406_Homey](https://user-images.githubusercontent.com/851845/150010444-3b749726-26c7-4b14-acba-e5200afdc715.jpg)
![Screenshot_20220118-203418_Homey](https://user-images.githubusercontent.com/851845/150010472-452b52d2-23cf-4a21-9c92-f888e0a32734.jpg)
![Screenshot_20220118-203434_Homey](https://user-images.githubusercontent.com/851845/150010481-6ea0fb21-5c9a-41f7-81bb-46adde67838c.jpg)

**Comment by arnljot** [comment]
Just to be safe, I've also added an issue to the other app too.
https://github.com/TedTolboom/com.xiaomi-mi-zigbee/issues/276

**Comment by JohanBendz** [comment]
Hi @arnljot, hahaha 😵‍💫  that should be impossible.. there is nothing i this apps code that could validate your unit if it is a genuine Aqara unit.

What version of the Hue app do you have installed? Tried reinstalling it? Tried the test version?

What happens if you disable both this and the Aqara app and add your units as a generic Zigbee unit? What Zigbee data does it then have?

**Comment by arnljot** [comment]
![Screenshot_20220119-005658_Homey](https://user-images.githubusercontent.com/851845/150037907-6ea48412-3586-4395-8d45-a52492fe6d04.jpg)

This is what it shows then. I notice that there's no manufacturer ID. I've got an idea that the manufacturer code should be 4447.

Either the device didn't give it, or there's a bug in Homey?

**Comment by arnljot** [comment]
The following are version numbers.

I haven't tried to reinstall anything, as I've got a lot of configuration.

![Screenshot_20220119-010659_Homey](https://user-images.githubusercontent.com/851845/150038805-012d66c6-9fb8-4bec-95de-2ba185479293.jpg)

**Comment by JohanBendz** [comment]
Hi again @arnljot, is this happening to just one device or multiple devices? If this is just one device I think it might be broken, every device should report ManufacturerName to Homey when added as a generic Zigbee unit.

I have triple checked the code of my app, there is nothing in it that should be able to add your device as an A19 light bulb.

I suggest starting a ticket with Athom and let them check what is going on, neither Ted nor I have the ability to see what happens in the inclusion part of the pairing as this is done using Athom's code.

**Comment by arnljot** [comment]
I think it's an athom problem, I agree. I'll check to see with another device if it fails to report manufacturer id. The device is sold by a reputable source in Norway, and sold in quantity. The shop hasn't had many reports of this, and they've emailed back with the same surprise as you :)

I'll contact Homey and see what they find out, thank you @JohanBendz
