### ISSUE TITLE
Lights are turned on and off by app

### ISSUE THREAD

**Issue by rarev** [sebbebebbe/com.philips.hue.zigbee#378]
I have 4 hue spots that are connected directly to homey. I also have a lot of other hue lights which are connected to the hue hub. I connected the 4 directly to solve a range problem with zigbee for an other zigbee battery powered device that is outside. These 4 lights are outside of my home. I also have a hue motion sensor outside, which is in the same 'room', but connected to the hue hub.

Now, the problem occurs with the 4 spots being turned on without a homey flow doing this. According to the homey app, the lights are being turned on by the "hue without bridge" app. How can I stop this?

**Comment by JohanBendz** [comment]
Hi @rarev, please restart the app and let the event occur where the lights are turned off, then send me a diagnostic report from the app with your nickname mentioned.

**Comment by JohanBendz** [comment]
Hi @rarev, I did not see any diagnostic report from you (or did I miss it), is this still an issue?

**Comment by p1457** [comment]
Hi @JohanBendz,
I am experiencing the same thing with one of the lights that i have connected direct to homey. According to the log the Light is turned on by the app and not by any Flow.
I will do as you asked rarev and restart the app and then send a diagnostic report next time the issue appears.
Thank you.
