### ISSUE TITLE
Smart plug not reconized

### ISSUE THREAD

**Issue by Chompiz** [sebbebebbe/com.philips.hue.zigbee#381]
Bought myself a Philips Smart Plug and when connecting it to my Homey it says Zigbee baseunit and not smart plug. Made a screenshot of the info regarding the unit. Just guessing that the id is new and thats why its not reconized correct
![Screenshot_2022-01-30-14-36-30-470_app homey](https://user-images.githubusercontent.com/98696248/151702011-c6b6e207-3629-4413-b174-6fb8498baa93.jpg)

**Comment by JohanBendz** [comment]
Hi @Chompiz, LOM007 is a new version of the same device. It will be supported in next update of the app.
