### ISSUE TITLE
Unabled to find Buckram - White Ambiance - GU10 - 4x

### ISSUE THREAD

**Issue by xfinx** [sebbebebbe/com.philips.hue.zigbee#382]
After resetting the lights with the remote I was able to add the individual lights as a generic zigbee device.
Product ID's
929003048301_01
929003048301_02
929003048301_03
929003048301_04

Is there a way to help me add them as buckram 4 spot device?
Do you need more info from me?

**Comment by JohanBendz** [comment]
Sorry for the delay, I have added these to the next update. They will be added as separate devices so that you can manage them individually, if you want to handle all four as one please use the app "Group".
