### ISSUE TITLE
Missing two Philips hue lamps

### ISSUE THREAD

**Issue by Goliath2000** [sebbebebbe/com.philips.hue.zigbee#383]
Hi
I miss following Philips hue amps. 
1. Philips Hue Enrave LED ceiling lamp black (can be in Small, Medium, Large and XL) for XL I get following product Id: 915005997101
2. Philips Hue White Ambiance Wellner. Get following product Id: 4440156P6

Hope these can be added to the list of supported lamps

**Comment by Goliath2000** [comment]
Any more info needed from me?

**Comment by Goliath2000** [comment]
No update on this?

**Comment by JohanBendz** [comment]
Sorry for late answer, both are under implementation..
https://github.com/JohanBendz/com.philips.hue.zigbee/issues/432
https://github.com/JohanBendz/com.philips.hue.zigbee/issues/508
