### ISSUE TITLE
Philips motion sensor Model 929003675 not recognized by app

### ISSUE THREAD

**Issue by Rumon** [sebbebebbe/com.philips.hue.zigbee#386]
This new motion sensor  is not recognized by homey added trough the App, homey cannot find a Homey app for this device, and installs it as an zigbee basic unit, is similar issue as #385 , I did send some Diagnostics Yesterday "motion Sensor not Detected" . 

Could you Please Add these newer Devices.

PS
Your change log mention a newer version ....39 But the current is still .35

**Comment by Svenjoelsson** [comment]
Having same issue, please assist to get this sorted.

**Comment by Delta-Q** [comment]
Having exactly the same issue. Can't use the new HUE motion sensor

**Comment by HLamboo** [comment]
I have the same issue. At first I installed a Hue outdoor motion sensor and that one is working fine. Now I bought an indoor motion sensor and that sensor is not recognized. From the outdoor sensor the ProducentID is "Philips"  with Product ID "SML002" and from the indoor sensor the ProducentID is "Signify Netherland B.V." with Product ID "SML003" . 

Can the change in ProducentID the cause of this issue?

**Comment by HLamboo** [comment]
Johan made a test version:

[ttps://homey.app/en-gb/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/](https://homey.app/en-gb/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/)

I tested this version for the Hue Indoor sensor. The sensor is recognized but the app makes a occupancy sensor of it, but I selected a Motion sensor. 
The occupancy sensor works a bit different than a motion sensor but now you can use the sensor.

**Comment by Delta-Q** [comment]
👍 keep up the good work

**Comment by Rumon** [comment]
Testing it with the motion sensor as this occupancy sensor and it works so far, thanks for making a Test version, i will update more if i have more test done.

**Comment by ghost** [comment]
I have the same problem with the motion sensor model 9290030675. When I add it the same response : This device is already added ! Is very strange because I 'dont have any other device in my Homey.
Could you find and fix the problem ?
Thanks a lot !

**Comment by mikkelnl** [comment]
> Johan made a test version:
> 
> [ttps://homey.app/en-gb/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/](https://homey.app/en-gb/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/)
> 
> I tested this version for the Hue Indoor sensor. The sensor is recognized but the app makes a occupancy sensor of it, but I selected a Motion sensor. The occupancy sensor works a bit different than a motion sensor but now you can use the sensor.

I have the exact same issue, but at least the motion sensor works now 👍
