### ISSUE TITLE
App often crashes since a few days.

### ISSUE THREAD

**Issue by tkroon89** [sebbebebbe/com.philips.hue.zigbee#389]
Hi Johan,

The app has crashed a couple of times in the last few days, without any clear reason. I haven't changed anything in Homey, and it hasn't happened before. 
To be specific: is was not the app itself that gave an indication that it crashed, but all of my devices had the red exclamation mark. After restarting the app, everything was fine.

Diagnostics report: ffcbc538-b0a0-492a-826c-1370c438fc43
Could you please check the log if there is any indication?

Kind regards from the Netherlands,

Thomas

**Comment by JohanBendz** [comment]
Hi @tkroon89, sorry for the late response.
I hope you don't have this issue any longer, the diagnostic did not show any action at all...

"---- stdout ----
[log] 2022-03-03 01:00:09 [PhilipsHueZigbeeApp] Philips Hue Zigbee app initiating...

---- stderr ----

"

So not much to work on..  If you still have this problem please get back and I'll put some effort into fixing your issue.
