### ISSUE TITLE
Problems with adding some hue devices

### ISSUE THREAD

**Issue by vims95** [sebbebebbe/com.philips.hue.zigbee#392]
Hi!

I have som issues regarding adding Filament G93 and G125 to Homey Pro. When adding, the light bulbs are recognized as "Basic Zigbee device". I have tried adding the light bulbs with your app, both version 2.0.37 and 2.0.39. I have also reported it to Homey. See following code from Homey: e27a04f7-4352-44c5-bda9-e0283fdd4097

**Comment by JohanBendz** [comment]
Hi @vims95, can you please post the Zigbee data you get from the units once you paired them as generic (Basic)  Zigbee units.

**Comment by vims95** [comment]
Here is the interview results
  "ids": {
    "modelId": "LTO001",
    "manufacturerName": "Signify Netherlands B.V."
  },
  "endpoints": {
    "endpointDescriptors": [
      {
        "endpointId": 11,
        "applicationProfileId": 260,
        "applicationDeviceId": 268,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          0,
          3,
          4,
          5,
          6,
          8,
          4096,
          64515,
          768
        ],
        "outputClusters": [
          25
        ]
      },
      {
        "endpointId": 242,
        "applicationProfileId": 41440,
        "applicationDeviceId": 97,
        "applicationDeviceVersion": 0,
        "_reserved1": 0,
        "inputClusters": [],
        "outputClusters": [
          33
        ]
      }
    ],
    "endpoints": {
      "11": {
        "clusters": {
          "basic": {
            "attributes": [
              {
                "id": 0,
                "name": "zclVersion",
                "value": 2
              },
              {
                "id": 1,
                "name": "appVersion",
                "value": 2
              },
              {
                "id": 2,
                "name": "stackVersion",
                "value": 1
              },
              {
                "id": 3,
                "name": "hwVersion",
                "value": 1
              },
              {
                "id": 4,
                "name": "manufacturerName",
                "value": "Signify Netherlands B.V."
              },
              {
                "id": 5,
                "name": "modelId",
                "value": "LTO001"
              },
              {
                "id": 6,
                "name": "dateCode",
                "value": "20211210"
              },
              {
                "id": 7,
                "name": "powerSource",
                "value": "mains"
              },
              {
                "id": 8,
                "name": "appProfileVersion",
                "value": 0
              },
              {
                "id": 9
              },
              {
                "id": 10
              },
              {
                "id": 11
              },
              {
                "id": 16384,
                "name": "swBuildId",
                "value": "1.93.7"
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "identify": {
            "attributes": [
              {
                "id": 0
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "groups": {
            "attributes": [
              {
                "id": 0,
                "name": "nameSupport",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0
                  ]
                }
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "scenes": {
            "attributes": [
              {
                "id": 0
              },
              {
                "id": 1
              },
              {
                "id": 2
              },
              {
                "id": 3
              },
              {
                "id": 4
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "onOff": {
            "attributes": [
              {
                "id": 0,
                "name": "onOff",
                "value": true
              },
              {
                "id": 16384
              },
              {
                "id": 16385,
                "name": "onTime",
                "value": 0
              },
              {
                "id": 16386,
                "name": "offWaitTime",
                "value": 0
              },
              {
                "id": 16387
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "levelControl": {
            "attributes": [
              {
                "id": 0,
                "name": "currentLevel",
                "value": 254
              },
              {
                "id": 1,
                "name": "remainingTime",
                "value": 0
              },
              {
                "id": 15
              },
              {
                "id": 16384
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "touchlink": {
            "attributes": [
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1,
                "reportingConfiguration": {
                  "status": "UNREPORTABLE_ATTRIBUTE",
                  "direction": "reported"
                }
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "colorControl": {
            "attributes": [
              {
                "id": 2
              },
              {
                "id": 3,
                "name": "currentX",
                "value": 29967
              },
              {
                "id": 4,
                "name": "currentY",
                "value": 26869
              },
              {
                "id": 7,
                "name": "colorTemperatureMireds",
                "value": 366
              },
              {
                "id": 8,
                "name": "colorMode",
                "value": "colorTemperatureMireds"
              },
              {
                "id": 15
              },
              {
                "id": 16
              },
              {
                "id": 17
              },
              {
                "id": 18
              },
              {
                "id": 19
              },
              {
                "id": 21
              },
              {
                "id": 22
              },
              {
                "id": 23
              },
              {
                "id": 25
              },
              {
                "id": 26
              },
              {
                "id": 27
              },
              {
                "id": 48
              },
              {
                "id": 49
              },
              {
                "id": 50
              },
              {
                "id": 51
              },
              {
                "id": 52
              },
              {
                "id": 54
              }
            ],
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        },
        "bindings": {
          "ota": {
            "attributes": [],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        }
      },
      "242": {
        "clusters": {},
        "bindings": {}
      }
    }
  }

**Comment by vims95** [comment]
Here is also two screen shots from the device data.

<img width="1058" alt="Skjermbilde 2022-04-01 kl  17 17 36" src="https://user-images.githubusercontent.com/43495738/161292752-2ccd76b7-2ca7-4c68-91b8-5a5e48c997f3.png">
<img width="814" alt="Skjermbilde 2022-04-01 kl  17 17 52" src="https://user-images.githubusercontent.com/43495738/161292771-60055caa-e4fc-4ddc-b05d-36c33ad2c487.png">

**Comment by JohanBendz** [comment]
Added to next update.
