### ISSUE TITLE
Hue Smart Plug problemen

### ISSUE THREAD

**Issue by GWGvB** [sebbebebbe/com.philips.hue.zigbee#393]
Beste Johan,
Vermoedelijk is de Firmware van de Hue Smart Plug vorig jaar veranderd.
Ik kan hem niet meer installeren in "Philips Hue without bridge" Homey geeft aan : "Onbekend Zigbee apparaat".
Via de Bridge kan wel geïnstalleerd worden. Echter met een Homey flow geeft de keten Homey-Bridge-SmartPlug een vertraging van 30 minuten bij de ZonOP en ZonOnder functies.
Zie bijlage. Hier heb ik een vraag aan Philips Hue gesteld
[Probleem Hue Smart Plug.pdf](https://github.com/JohanBendz/com.philips.hue.zigbee/files/8380705/Probleem.Hue.Smart.Plug.pdf)
Heeft u hier een oplossing voor?

Met Homey support heb ik uitgebreid gemailed en van alles uitgeprobeerd. Helaas.
Ik ben een beetje huiverig om de test app without Bridge te proberen en wacht liever tot de definitieve app uit is.
Werkt die versie met de "oude" en met de "nieuwe" Hue Firmware?
Ik weet niet of de oudere pluggen die nu goed werken ook beïnvloed worden.
Met vriendelijke groet,
Geert

**Comment by JohanBendz** [comment]
Hi @GWGvB, I have added support for the new units in the test version of the app.
You can try out the test version of the app without risking breaking anything. If it does not work to your liking you can revert to the Live version.
https://homey.app/sv-se/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/

**Comment by GWGvB** [comment]
Hi Johan, 
The test version of the app installed the new Smart Plugs without problem and did not affect the older Plugs as you indicated.
The old en new Smart Plugs have different product codes.
The problem with the 30 min delay was created by myself. I swith on/off an Arduino. In that program was an wrong time correction, which I discovered during the change to summertime.
All problems are solved now. Thank you for your effort and support!
Best regards,
Geert
