### ISSUE TITLE
Unable to pair Hue motion sensor

### ISSUE THREAD

**Issue by packetninja** [sebbebebbe/com.philips.hue.zigbee#394]
Hi,

A few weeks ago one of my motion sensors stopped working out of the blue. I deleted it and wanted to add it again, but whatever I did ... it just wouldn't pair. Eventually the "add dialog" times out. Given that all my other Hue devices work without issues, I assumed it was an hardware issue and sent it back.

I received a new one and tried to pair that, but unfortunately the same issue...

I would like to troubleshoot this in more detail, but honestly I'm a bit stuck. I opened a support case with Homey, but they throw their hands in the air and tell me to buy a Hue bridge so I can use their own app. Imho this goes against the reasons I bought a Homey for.

What can I do to further debug this and get some help to solve this issue?

**Comment by JohanBendz** [comment]
Hi @packetninja, try disabling the Hue app and pair the devices as a generic Zigbee device. If this fails the issue is with Homey and not with the app.

**Comment by larbut** [comment]
I can confirm that the Hue Motion Sensor does not pair with Homey.
It ends up as a "Simple Zigbee" unit, which is useless.
I've tried two different, brand new sensors, both failing to pair. Restarted Homey app, this app and Homey Pro, but still no proper pairing.

I don't have the Hue Bridge.

Any help appreciated.

**Comment by mikkelnl** [comment]
Having a similar (or same?) issue. Am trying to connect an Outdoor Sensor, which is not recognized and it'll be added as an 'Unknown Zigbee Device'...?

**Comment by PeterKawa** [comment]
I found this https://github.com/JohanBendz/com.philips.hue.zigbee/issues/386
Maybe it works.

Quote:
Johan made a test version:
https://homey.app/en-gb/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/

I tested this version for the Hue Indoor sensor. The sensor is recognized but the app makes a occupancy sensor of it, but I selected a Motion sensor.
The occupancy sensor works a bit different than a motion sensor but now you can use the sensor.

**Comment by jornhd** [comment]
Thank you! That solved the problem for me. 🙂

**Comment by PeterKawa** [comment]
YW!
