### ISSUE TITLE
Problem with pairing Filament G125 E27 bulb

### ISSUE THREAD

**Issue by ruben375** [sebbebebbe/com.philips.hue.zigbee#398]
I do not get my 3 filament g125 (it is version LT0001) paired with Homey. I get them paired the proprietary Philips Hue Bluetooth app paired, but not with homey. 

I switched the bulbs off (via physical switch) and on again. With no result. I have no philips hue bridge. What can I do to get them paired with Homey Pro?

In Homey Developer Tool I get the following error message if I search for Bluetooth devices - is this part of the problem?
![image](https://user-images.githubusercontent.com/96666343/164067426-83b0cc91-bc6e-470f-b386-31e6c3a16f40.png)

**Comment by JohanBendz** [comment]
Hi @ruben375, I hope this is not still an issue. If it is the problem lies within Homey and not the app. Please get back to me if this is still an issue.
