### ISSUE TITLE
Changing light temperature on color bulbs / lightstrips

### ISSUE THREAD

**Issue by nhassink** [sebbebebbe/com.philips.hue.zigbee#4]
There seems to be something wrong when changing the light temperature of a color hue bulb or hue lightstrip. When changing the temperature the light switches to a cool blue temperature no matter what light temperature you set.  

Expected behaviour would be that the light temperature changes from a cool blue (0%) to a warm white (100%)

**Comment by nhassink** [comment]
Is it possible that the color hue bulbs should be of type ZigBeeXYLightDevice instead of ZigBeeLightDevice as they are defined now?

**Comment by sebbebebbe** [comment]
Hi @nhassink this could be the case. I will add this issue to my TODO and have a look at it for the upcoming release.

**Comment by nhassink** [comment]
Ok great. Other than this the app is quite stable over here.

**Comment by sebbebebbe** [comment]
Hi @nhassink , does the light strip work as intended now? I changed all RGB bulbs to ZigBeeXYLIghtDevice but it does not seem to work that well with some of the light strips and bulbs. Warm white turns into light green. 

Would be nice to know if your devices are working correctly and what ID:s they have.

**Comment by nhassink** [comment]
I have just checked with the latest dev version (1.4.4) but as you mentioned the warm white is light green instead of light yellow

**Comment by sebbebebbe** [comment]
Awesome thanks for the info. I will change back all the color bulbs to ZigBeeLightDevice and try to identify which ones that should go as ZigBeeXYLightDevice.

**Comment by nhassink** [comment]
It seems that the color bulbs have this problem. The hue white ambiance Lights work correctly. Do you still need the id’s?

**Comment by sebbebebbe** [comment]
I would be interested in the id:s after i have changed back all to ZigBeeLightDevice. To see if there are any issues. There might come an update during the day.

**Comment by nhassink** [comment]
LCT001 - color e27 - turns to green
LTW012 - white ambiance e14 - works ok
LTW001 - white ambiance e27 - works ok
LST002 - color light strip - turns to green

**Comment by nhassink** [comment]
just read your post .. wil update the ids overview after testing with the new version

**Comment by sebbebebbe** [comment]
I have now changed all color lights to ZigBeeLightDevice and pushed it to dev branch.

**Comment by nhassink** [comment]
LCT001 - color e27 - works ok
LTW012 - white ambiance e14 - works ok
LTW001 - white ambiance e27 - works ok
LST002 - color light strip - works ok

**Comment by nhassink** [comment]
Did not test the white ambiance since you only changed the color lights. But all working ok over here now

**Comment by sebbebebbe** [comment]
Awesome! Thanks for help with testing
