### ISSUE TITLE
problem with pairing Philips Hue Signe Floor lamp

### ISSUE THREAD

**Issue by louise92** [sebbebebbe/com.philips.hue.zigbee#400]
Goodafternoon,

Unfortunately I'm not able to pair my new Philips Hue Signe floor lamp. 
In the app I select the Signe lamp, en immediatly after pairing the app said that it was not possible to pair. The lamp is added to my Homey, but I can not use the specific functions for the Signe.
I can not select 3 colours, only 1 for the lamp.

Can you please help me?

Louise

**Comment by jockeadn** [comment]
Hi,
I can not pair my Hue Signe at all. When will the updated app 2.0.36 that support Hue Signe be released?

Thanks, Jocke

**Comment by JohanBendz** [comment]
I'll have a look at this issue here: https://github.com/JohanBendz/com.philips.hue.zigbee/issues/428
