### ISSUE TITLE
The new Motion sensor is not recognized

### ISSUE THREAD

**Issue by oivsol** [sebbebebbe/com.philips.hue.zigbee#401]
Hello 
The new sensor (model 920030657)is not recognized in Homey. 
Homey reports that there is “no app for this device”.
It then adds this as a simple zigbee device. 
The previous version works fine. 
Are there any eta for this fix?

**Comment by dahne** [comment]
Having the same issue. Any ideas on how to fix this?

**Comment by JohanBendz** [comment]
Hi, sorry for the late reply.
Is this the outdoor or indoor model?
Can you please send an interview of the unit?

**Comment by oivsol** [comment]
Hello Johan. This is the indoor model. 
Not sure what you mean by interview?

**Comment by JohanBendz** [comment]
Hi again.
OK, thanks for a quick reply.

Interview is done by adding a device as a generic Zigbee device and then click the interview button to the right of the device in this list: https://tools.developer.homey.app/tools/zigbee

I think I will manage with the info I have, but an interview is always nice to have to be sure.

**Comment by Delta-Q** [comment]
I'm having the same problem with the 9290030675 model, identified as 'Signify Netherlands B.V.' , not 'Philips' as in the older versions

  "ids": {
    "modelId": "SML003",
    "manufacturerName": "Signify Netherlands B.V."
  },
  "endpoints": {
    "endpointDescriptors": [
      {
        "endpointId": 2,
        "applicationProfileId": 260,
        "applicationDeviceId": 263,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          0,
          1,
          3,
          1030,
          1024,
          1026
        ],
        "outputClusters": [
          25,
          0,
          3,
          6
        ]
      }
    ],
    "endpoints": {
      "2": {
        "clusters": {
          "basic": {
            "attributes": [
              {
                "id": 0,
                "name": "zclVersion",
                "value": 2
              },
              {
                "id": 1,
                "name": "appVersion",
                "value": 2
              },
              {
                "id": 2,
                "name": "stackVersion",
                "value": 1
              },
              {
                "id": 3,
                "name": "hwVersion",
                "value": 1
              },
              {
                "id": 4,
                "name": "manufacturerName",
                "value": "Signify Netherlands B.V."
              },
              {
                "id": 5,
                "name": "modelId",
                "value": "SML003"
              },
              {
                "id": 6,
                "name": "dateCode",
                "value": "20210830"
              },
              {
                "id": 7,
                "name": "powerSource",
                "value": "battery"
              },
              {
                "id": 8,
                "name": "appProfileVersion",
                "value": 0
              },
              {
                "id": 9
              },
              {
                "id": 10
              },
              {
                "id": 11
              },
              {
                "id": 16384,
                "name": "swBuildId",
                "value": "2.53.6"
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "powerConfiguration": {
            "attributes": [
              {
                "id": 32,
                "name": "batteryVoltage",
                "value": 30
              },
              {
                "id": 33,
                "name": "batteryPercentageRemaining",
                "value": 200
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "identify": {
            "attributes": [
              {
                "id": 0
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "occupancySensing": {
            "attributes": [
              {
                "id": 0,
                "name": "occupancy",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0
                  ]
                }
              },
              {
                "id": 1,
                "name": "occupancySensorType",
                "value": "pir"
              },
              {
                "id": 16,
                "name": "pirOccupiedToUnoccupiedDelay",
                "value": 0
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "illuminanceMeasurement": {
            "attributes": [
              {
                "id": 0,
                "name": "measuredValue",
                "value": 18575
              },
              {
                "id": 1,
                "name": "minMeasuredValue",
                "value": 1
              },
              {
                "id": 2,
                "name": "maxMeasuredValue",
                "value": 65534
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "temperatureMeasurement": {
            "attributes": [
              {
                "id": 0,
                "name": "measuredValue",
                "value": 2056
              },
              {
                "id": 1,
                "name": "minMeasuredValue",
                "value": -27315
              },
              {
                "id": 2,
                "name": "maxMeasuredValue",
                "value": 32767
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        },
        "bindings": {
          "basic": {
            "attributes": [
              {
                "id": 0,
                "name": "zclVersion",
                "value": 2
              },
              {
                "id": 1,
                "name": "appVersion",
                "value": 2
              },
              {
                "id": 2,
                "name": "stackVersion",
                "value": 1
              },
              {
                "id": 3,
                "name": "hwVersion",
                "value": 1
              },
              {
                "id": 4,
                "name": "manufacturerName",
                "value": "Signify Netherlands B.V."
              },
              {
                "id": 5,
                "name": "modelId",
                "value": "SML003"
              },
              {
                "id": 6,
                "name": "dateCode",
                "value": "20210830"
              },
              {
                "id": 7,
                "name": "powerSource",
                "value": "battery"
              },
              {
                "id": 8,
                "name": "appProfileVersion",
                "value": 0
              },
              {
                "id": 9
              },
              {
                "id": 10
              },
              {
                "id": 11
              },
              {
                "id": 16384,
                "name": "swBuildId",
                "value": "2.53.6"
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "identify": {
            "attributes": [
              {
                "id": 0
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "ota": {
            "attributes": [],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "onOff": {
            "attributes": [],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        }
      }
    }
  }

**Comment by JohanBendz** [comment]
OK, thanks for the info guys, Well be added to next release.

**Comment by oivsol** [comment]
Thanks 👍

**Comment by Delta-Q** [comment]
Thanks

**Comment by dahne** [comment]
Thanks 🙏
Any idea on when on when next release will go?
