### ISSUE TITLE
White Ambiance E27 1100 (LTA009)

### ISSUE THREAD

**Issue by Thorarin** [sebbebebbe/com.philips.hue.zigbee#405]
I bought [this White Ambiance bulb](https://www.philips-hue.com/nl-nl/p/hue-white-ambiance-1-pack-e27/8719514291119) today (as best as I can tell without product specs on the website), which is not yet recognized by your app. Its Zigbee model ID is LTA009.

As I also mentioned in #379, I'd make a PR, but at this point I'm not yet familiar enough with Zigbee to do it right, I think 🙂

Here is the interview result: [LTA009 interview.txt](https://github.com/JohanBendz/com.philips.hue.zigbee/files/8838144/LTA009.interview.txt)

Some other product specs:

**Brightness:**
1055 lm @ 4000K
806 lm @ 2700K
**Color temperature:** 2200K - 6500K
**Power draw:** up to 8 W
**Standby power:** 0.5 W max

PS: this might be a duplicate of #397. I'm uncertain as I don't see "G1X" mentioned anywhere and the OP of that issue didn't give a lot of information.

**Comment by JohanBendz** [comment]
Hi @Thorarin, sorry for the delay, I hope you have been able to use the bulb as a generic unit so far.

I have now added support for this bulb to the next update. It will not have the exact power draw match, I'll fix this later.
