### ISSUE TITLE
Battery state Dimmer switch

### ISSUE THREAD

**Issue by eeckelaertyannick** [sebbebebbe/com.philips.hue.zigbee#408]
Would be great to have a battery state of the dimmer switch,

**Comment by GibStorm** [comment]
+1

Really missing this functionality.

**Comment by eeckelaertyannick** [comment]
@JohanBendz any News on this? Thx! :)

**Comment by JohanBendz** [comment]
Gen 1/2 should be working in latest version, Gen 3 is not acting as nice.. working on it. closing this issue.
