### ISSUE TITLE
Using scenes like in the hue app

### ISSUE THREAD

**Issue by eeckelaertyannick** [sebbebebbe/com.philips.hue.zigbee#410]
Would be great to use scenes like in the hue app, ore changing Color's ,

**Comment by eeckelaertyannick** [comment]
Dit you see this question Johan? Thx

**Comment by JohanBendz** [comment]
Hi, it would... only Athom/Homey does not support scenes. Might change. I considered building a "scenes" functionality myself but it would be huge to maintain..

**Comment by eeckelaertyannick** [comment]
Ok ;)Met vriendelijke groet,Yannick EeckelaertOp 9 okt. 2022 om 20:39 heeft Johan Bendz ***@***.***> het volgende geschreven:﻿
Hi, it would... only Athom/Homey does not support scenes. Might change. I considered building a "scenes" functionality myself but it would be huge to maintain..
