### ISSUE TITLE
Hue W/O bridge question: Battery device is not responding, how to fix?

### ISSUE THREAD

**Issue by MisterOlsen** [sebbebebbe/com.philips.hue.zigbee#413]
Dear Johan / Other.

I just bought my Homey, and first tried with hue bridge connected sensors, but the delay drained me :)
I then changed to directly added with hue without bridge, and everything worked perfectly, until I rebooted the Homey.
Now half of the sensors saying, Battery device is not responding, wake up the device before communicating.

Can you explain how to ? it's HUE indoor and outdoor sensors that is having the problem SML002,SML003 and SML004

Kind regards, Thomas.

**Comment by JohanBendz** [comment]
Hi, is this still an issue?

**Comment by JohanBendz** [comment]
Please get back to me if this is still an issue.
