### ISSUE TITLE
Sync box

### ISSUE THREAD

**Issue by eeckelaertyannick** [sebbebebbe/com.philips.hue.zigbee#415]
Hi @JohanBendz maybe strange question. I just moved to your app from the hue app that athom. In this way I have direct loyal use en no extra hue hub. But I want to buy en use the sync box, can you add support for this ore is it not possible. I know this is maybe a stupid question but like to know it.

Thx!

**Comment by JohanBendz** [comment]
Hi @eeckelaertyannick, sorry for the very late answer. If you don't still have this considerations perhaps someone have so I'll give a straight answer :)

No, I will not add support for the Sync box as there are no way to do it without using the Hue hub. If I added the ability to control it you would still need the Hue hub and this app is for those that does not want to use it.. so.. :)

**Comment by eeckelaertyannick** [comment]
Ok :) thx! For the answer Met vriendelijke groet,Yannick EeckelaertOp 9 okt. 2022 om 20:35 heeft Johan Bendz ***@***.***> het volgende geschreven:﻿
Hi @eeckelaertyannick, sorry for the very late answer. If you don't still have this considerations perhaps someone have so I'll give a straight answer :)
No, I will not add support for the Sync box as there are no way to do it without using the Hue hub. If I added the ability to control it you would still need the Hue hub and this app is for those that does not want to use it.. so.. :)
