### ISSUE TITLE
Philips Hue White & Color Ambiance GU10 LED - DIM LvL

### ISSUE THREAD

**Issue by Urknall78** [sebbebebbe/com.philips.hue.zigbee#419]
Hi, i try to conect my Philips Hue White & Color Ambiance GU10 LED from HUE-Bridge direct to Homey with your App.
I setup a ADV-Flow with the Philips Switch. ON/OFF is working fine. But i can not use dimm function.
I set a logic parameter so if i press UP or down the Variable is changeing 10 Percent up or down. This still works.
Then i use the THAN set DIM to LOGIK-Variable.
But nothing happend.
When i use the same over the HUE-APP its still working.
So whats wrong?
What is the Best way to set the DIM LVL for the Spots?

Can you help?
![HUE-Flow-DIM-LVL](https://user-images.githubusercontent.com/14349743/184710168-aed8855b-e687-4734-885c-9809b2808c58.png)

**Comment by Urknall78** [comment]
Does anyone know a solution?

**Comment by JohanBendz** [comment]
Hi @Urknall78, I don't have the GU10 myself but I have tested the advanced flow you use in my setup using other lights and it works for me. I would rather use the card "set relative dim level" to move the light to brighter/darker but there might be a reason you use a logic value that I don't know.

**Comment by JohanBendz** [comment]
Please get back to me if this is still an issue.
