### ISSUE TITLE
Add support for Hue light strip outdoor

### ISSUE THREAD

**Issue by xabbakal** [sebbebebbe/com.philips.hue.zigbee#42]
Hi
I would appreciate if you could add support for Philips Hue Outdoor light strip. Dimmable and color support. The app cannot recognise it and it finds it as "unknown zigbee device"

Product ID LST003
Device ID 528
Profile ID 49246
Product information: https://www2.meethue.com/en-us/p/hue-white-and-color-ambiance-lightstrip-outdoor-197-inch/046677530938

Thanks in advance!

**Comment by sebbebebbe** [comment]
Perfect! Just the info i need.

Adding it to the list for next release.

**Comment by xabbakal** [comment]
Thanks for quick reply!

**Comment by sfredrikj** [comment]
> Perfect! Just the info i need.
> 
> Adding it to the list for next release.

Would this support this version as well?
8718696804773
https://www.philips.ie/c-p/8718696804773/hue-white-and-color-ambiance-lightstrip-outdoor-2-metre

Edit: I just had a look in zigbee developer tools, and this version of the outdoor lightstrip also has modelId "LST003". So I guess it will be supported.

**Comment by ghost** [comment]
Is the Hue Lightstrip Outdoor supported yet or not?

**Comment by sebbebebbe** [comment]
Sorry for the very late answer. but yes it has been released.

**Comment by xabbakal** [comment]
Thanks!
