### ISSUE TITLE
Hue motion sensor is detected as occupancy

### ISSUE THREAD

**Issue by ronald2404** [sebbebebbe/com.philips.hue.zigbee#420]
First of all thanks for writing the app, great work!
I have an Hue motion sensor (SML003) but it is detected as an occupancy sensor. 
Because of this it seems that my lights are not going on when an motion flow is triggered. It usually only goes on once and if you walk-in with a minute or so it doesn't go on again although motion is detected, thats why I think it is related to wrong product type detected..

Thanks and Regards
Ronald

**Comment by ronald2404** [comment]
v.2.0.39 in use Homey 8.05

**Comment by JohanBendz** [comment]
Hi @ronald2404, the new units are by Philips design Occupancy sensors that reports "start of movement" and "end of movement". The old driver reacted to the "start of movement" signal but was unable to listen to "end of movement" and therefor used a timer to reset the device, the new driver use the "end of motion" signal that the device sends to Homey.

I have seen several comments regarding this, the wish to have the "old" way implemented for the new units. I'll consider implementing it.. but there are many other requests to deliver on too... so.. no promises.

**Comment by ronald2404** [comment]
Hi Johan,

Thanks for your response.
I would like to let you know that current implementation is not working
after each reboot of homey i needed  add the device.
Now I have the regular app with hub and it works fine.

Regards
Ronald

Op zo 9 okt. 2022 om 20:29 schreef Johan Bendz ***@***.***>:

**Comment by JohanBendz** [comment]
Hi @ronald2404, thanks for the feedback. Sorry to hear you had issues with the driver. I'll give the driver some love and hopefully fix that problem..
