### ISSUE TITLE
Unable to connect hue being

### ISSUE THREAD

**Issue by Robkve** [sebbebebbe/com.philips.hue.zigbee#421]
Unable to connect to Being Lamp. Reset a few times and removed paired dimmer. 
Does not pair with the lamp. No issue connecting to dimmer.

**Comment by JohanBendz** [comment]
Not even pairing as generic zigbee? If so this is a Homey issue. Try replacing the power adapter (make sure it can provide min 2.1 Amp). If this does not help please get back to me, Athom support can also help if you make sure you tell them the units are not pairing as generic Zigbee.

**Comment by JohanBendz** [comment]
Closing this issue, please get back if the problem has not been solved.
