### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by eddiegonzales** [sebbebebbe/com.philips.hue.zigbee#422]
I have been running fine with a Hue hub. And chose to go for this solution, to turn off the Hub. But within 24 hours of moving them to this app i lost connection to all my 3 Hue product. Dimmer, Motion Sensor and a Bulp. Is there something to do or do i need to go back to the Hub solution again?

**Comment by JohanBendz** [comment]
Hi there.
Hope this is not still an issue, but if it is please send me a crash report from the app.
Normally this kind of issues is not related to the app but to Homey itself, a Homey restart, change of the Homey power adapter or re-pairing of the units without prior deletion of them often helps.

**Comment by JohanBendz** [comment]
Any news? Please get back to me if the issue persist.
