### ISSUE TITLE
I get Philips Hue outdoor sensor model: 9290030674 not registered on the philips hue without bridge app.

### ISSUE THREAD

**Issue by Krekrev** [sebbebebbe/com.philips.hue.zigbee#426]
I have installed the Hue without the bridge app on my homey Pro.
I have tried to register / connect both possibilities of outdoor sensors.
Both times I got the same message that no Homey app was found for this device and that it has been added as an unknown zigbee device.
As a result, the sensor does not detect any movement.
I have a Philips Hue outdoor sensor model: 9290030674

**Comment by JohanBendz** [comment]
Hi, please try the test version of the app: https://homey.app/sv-se/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/
