### ISSUE TITLE
Request to add LWA017 Hue Bulp 1100 lumen White to Hue app 

### ISSUE THREAD

**Issue by HGrundeman** [sebbebebbe/com.philips.hue.zigbee#429]
Hi Johan,

Is it possible to add this Hue-lamp to the app. The Zigbee interview gives:

  "ids": {
    "modelId": "LWA017",
    "manufacturerName": "Signify Netherlands B.V."
  },
  "endpoints": {
    "endpointDescriptors": [
      {
        "endpointId": 11,
        "applicationProfileId": 260,
        "applicationDeviceId": 257,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          0,
          3,
          4,
          5,
          6,
          8,
          4096,
          64514
        ],
        "outputClusters": [
          25
        ]
      },
      {
        "endpointId": 242,
        "applicationProfileId": 41440,
        "applicationDeviceId": 97,
        "applicationDeviceVersion": 0,
        "_reserved1": 0,
        "inputClusters": [],
        "outputClusters": [
          33
        ]
      }
    ],
    "endpoints": {
      "11": {
        "clusters": {
          "basic": {
            "attributes": [
              {
                "id": 0,
                "name": "zclVersion",
                "value": 2
              },
              {
                "id": 1,
                "name": "appVersion",
                "value": 2
              },
              {
                "id": 2,
                "name": "stackVersion",
                "value": 1
              },
              {
                "id": 3,
                "name": "hwVersion",
                "value": 1
              },
              {
                "id": 4,
                "name": "manufacturerName",
                "value": "Signify Netherlands B.V."
              },
              {
                "id": 5,
                "name": "modelId",
                "value": "LWA017"
              },
              {
                "id": 6,
                "name": "dateCode",
                "value": "20201012"
              },
              {
                "id": 7,
                "name": "powerSource",
                "value": "mains"
              },
              {
                "id": 8,
                "name": "appProfileVersion",
                "value": 0
              },
              {
                "id": 9
              },
              {
                "id": 10
              },
              {
                "id": 11
              },
              {
                "id": 16384,
                "name": "swBuildId",
                "value": "1.76.10"
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "identify": {
            "attributes": [
              {
                "id": 0
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "groups": {
            "attributes": [
              {
                "id": 0,
                "name": "nameSupport",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0
                  ]
                }
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ]
          },
          "scenes": {},
          "onOff": {},
          "levelControl": {},
          "touchlink": {}
        },
        "bindings": {
          "ota": {}
        }
      },
      "242": {
        "clusters": {},
        "bindings": {}
      }
    }
  }

Thanks in advance.
Rgds Hans.

**Comment by JohanBendz** [comment]
Thanks for the request, added to next update.
