### ISSUE TITLE
Homey 2.0 support?

### ISSUE THREAD

**Issue by luvis** [sebbebebbe/com.philips.hue.zigbee#43]
Hi, I just found this amazing app, I've been using the "main" hue app with the need of a bridge and it's painfully slow. I just updated homey to the v2 firmware and tried resetting,deleting from hue and adding a hue dimmer switch directly through this app but it doesn't seem to be working. It gets added but it doesn't work. So I'm wondering if it's because of the update to 2.0 or if I've done something wrong. Thanks!

**Comment by sebbebebbe** [comment]
Homey v2.0 is not yet supported. It will be updated at some point in time.

**Comment by luvis** [comment]
Ah, ok. Thanks for the hard work! Maybe difficult to answer but I really would like to use your app, would you recommend me to downgrade again or is v2 in the near future pipeline? No pressure, just asking.

**Comment by sebbebebbe** [comment]
Sadly I do not have any info on when to expect a release.
Im not sure if you even can downgrade, atleast without resetting your Homey completely.

**Comment by luvis** [comment]
Yeah I realized that.. Bummer. I'm surprised there's no backup in homey. I'll wait patiently 👍 Thanks for the response!

**Comment by sebbebebbe** [comment]
Hi, there have been reports of Homey 2.0 not setting up the ZigBee network correctly. Have you tried the app after rebooting or "pulling the plug"?

There has not been any changes made to the ZigBee implementation from version 1.5.* and 2.0rc2 so in theory it should just work fine.

**Comment by luvis** [comment]
Of course I hadn't 😅 Works perfectly after pulling the plug. Thanks!
