### ISSUE TITLE
Smart Plug recognised as unknow device

### ISSUE THREAD

**Issue by henkbart** [sebbebebbe/com.philips.hue.zigbee#430]
Hello,
Today i add to Philips Hue Smart Plug.
When adding i got the message that there is no Homey App for this and he installed them as Unknow devices.
I can Turn them on/off but i can not program them in Homey.

App version = 2.0.35
Homey version = 8.1.0

Would be nice if you can look at this

Henk

**Comment by JohanBendz** [comment]
Hi  @henkbart, try this version: https://homey.app/sv-se/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/
