### ISSUE TITLE
Request support HUe Motion Sensor  SML003

### ISSUE THREAD

**Issue by vtilgenkamp** [sebbebebbe/com.philips.hue.zigbee#434]
Hello Johan,

The people from Athom suggested me to send you a request for supporting the |(latest version?) Hue Motion Sensor.
I understood that not all versions are supported currently. Pictures attacthed with the details of this version.
Currently the app shows the Motion sensor as an unknown Zigbee device and its not functioning.
Would be great if this version would be supported in the future. Many thanks in advance. Vincent

SML003
![Image](https://user-images.githubusercontent.com/121048435/208474702-522f0154-a9a0-4419-b134-f5b77bd64956.jpeg)
![Image](https://user-images.githubusercontent.com/121048435/208474742-e7ba94f9-b397-44ae-9e7a-9efb9cc16d43.jpeg)
![Image](https://user-images.githubusercontent.com/121048435/208474787-b59b559b-fb72-4d4c-b630-ce977ec72f69.jpeg)
![Image](https://user-images.githubusercontent.com/121048435/208474827-30b3f89c-1db0-4741-a22f-9f47b020c5d2.jpeg)

**Comment by JohanBendz** [comment]
Hi @vtilgenkamp, sorry for the late answer.
The device is supported by the test version of the app:
https://homey.app/en-us/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/
