### ISSUE TITLE
Philips Hue without the Bridge, motion sensor

### ISSUE THREAD

**Issue by GWGvB** [sebbebebbe/com.philips.hue.zigbee#435]
Dear Johan,
The Homey app indicates the motion sensor cannot be reached. There is a warning sign.  “Equiment is not available”.
However the motion sensor switches correctly and additional data (temperature etc) is can be seen in the graphics of Homey-insights.
The problem was started earlier 6 month ago after Homey update 7.4.2. (or 7.4.3.) (I did not react to that)
With update -Philips Hue, without the bridge version 2.0.42- the app worked again perfectly and showed temperature etc. for 22 days.
With Homey update 8.1.1. today the problem is back.
I contacted Homey, but they point to the app owner.
Please can you help in this problem?
Homey suggested a weak signal issue, but that is not the case, I tested that.
Best regards
Geert

**Comment by GWGvB** [comment]
Dear Johan,
In addition to above  message.

The problem with the motion sensor happens after a Homey update.
Homey indicated, that possible the Zigbee chip did not awake properly after a Homey update. So they gave me the advice to install a clean firmware in the recovery mode.
First attempt went wrong on the download, but than the sensor worked well for all aspects.
Second attempt was successful, but the warning sign “Equipment is not available” was given again.
After trying to look deeper into the system we discovered, that:
- SML001 (switching) worked always,
- SML003 (temperature data and light data) caused the warning sign,
- the battery data has not updated for over one year.
Somehow in this process your app -Philips Hue, without the bridge version 2.0.42- disappeared in my flow system and I had to install it again.
Hereafter the motion sensor worked perfectly again.

My conclusion is now, that after a Homey update something could happen to the Zigbee and the problem can be corrected by installing your app again.
Future will confirm this hopely.
I reported this to Homey.

Best regards
Geert

**Comment by Gouss1969** [comment]
Hello Johan

I confirm the problem : the sensor is not recognized with the « without Hue bridge app ».

The only pairing mode is through the Homey Zigbee pairing. And it doesn’t work very Well.

on the other side, i see that my current version is V2.0.35 on my Homey but on Homey app site as well. Whereas you the last version you developed is the V2.0.42.
Why this gap ?

thanks for your support and reply.

regards

Franck

**Comment by JohanBendz** [comment]
Hi @Gouss1969, there is a test version of the app. If you have not already tried it, please do.
https://homey.app/en-us/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/

**Comment by JohanBendz** [comment]
Thanks for the feedback @GWGvB, keep me informed if this happens again.
