### ISSUE TITLE
CH-SmartPlugs LOM006

### ISSUE THREAD

**Issue by Deroy2112** [sebbebebbe/com.philips.hue.zigbee#436]
Hello

My CH-SmartPlugs are only recognized as "Simple Zigbee Device".

productID: LOM006

Could this be added in the next update ?

https://zigbee.blakadder.com/Philips_LOM006.html
https://user-images.githubusercontent.com/81692934/209543901-3694fa88-6d27-45c8-8021-0fe4d3b4b36b.png

Greets

**Comment by JohanBendz** [comment]
Added to next release
