### ISSUE TITLE
6th Gen 2021 A60 E27 Bulbs White & Color

### ISSUE THREAD

**Issue by Deroy2112** [sebbebebbe/com.philips.hue.zigbee#437]
my 2021 version A60 E27 hue white & color 1600 lumens are added as "Simple Zigbee device".

https://zigbee.blakadder.com/Philips_LCA004.html
https://zigbee.blakadder.com/Philips_LCA006.html
https://zigbee.blakadder.com/Philips_LCA008.html

6th generation 2021 A60 E27 models have
LCA004, LCA006, LCA008
800 lumens, 1100 lumens and 1600 lumens.
6.5 W, 11 W, 15 W

Greets Deroy 

Just saw that LCA004, LCA006 are already integrated. LCA008 is missing.

**Comment by raymondbh** [comment]
LCA004 is added under the LCA001, but not working.

**Comment by JohanBendz** [comment]
LCA008 added to next release. If LCA004 does not work, please start a new issue and send a diagnostic report.
