### ISSUE TITLE
Sudden crashes and high RAM usage

### ISSUE THREAD

**Issue by tkroon89** [sebbebebbe/com.philips.hue.zigbee#438]
Hi Johan,

In the past few days I experienced multiple crashes. The app itself kept running, but the devices failed and showed the red triangle.

Two diagnostic reports:
0f769776-28c4-447f-83e6-f487d45538f1
3cab91e1-03e4-4e8b-bcd3-8c370509d29c

Also the RAM usage tripled. I haven't changed anything, nor have I added new devices.

<img width="1255" alt="Scherm­afbeelding 2022-12-28 om 07 30 37" src="https://user-images.githubusercontent.com/60198451/209768913-78c028e5-2d0b-47c0-a368-5c23aad12466.png">

**Comment by JohanBendz** [comment]
Hi @tkroon89.
Both diagnostics are clean, no info at all.
Do you see this behavior still?
About to release a new version (soon...) so if there is a problem it would be great to have it sorted :)

**Comment by tkroon89** [comment]
Hi Johan,

I created a flow which restarted the app every four hours, and checks every minute if a sensor's value results in an error, which also triggers a restart of the app. Now I included a push notification to my phone so I know if and when it (still?) happens. I'll keep you posted!

**Comment by tkroon89** [comment]
Hi Johan,

I have not seen any significant RAM-increases or crashes in the past two weeks. Thank you anyway!

Thomas

**Comment by JohanBendz** [comment]
Hi @tkroon89, good to hear! Create a new issue if it comes back.
