### ISSUE TITLE
Hue plug added as generic zigbee device

### ISSUE THREAD

**Issue by dbuekenh** [sebbebebbe/com.philips.hue.zigbee#440]
Hi,
I just bougth 2 hue plugs, updated them via bluetooth to the latest firmware. Added them to the homey, but they are recognised as generic zigbee devices.

Many thanks to have a look to this, let me know if i can help.

![image](https://user-images.githubusercontent.com/47578509/210020374-87d24435-14b6-4033-95b7-a588eefd8328.png)

![image](https://user-images.githubusercontent.com/47578509/210020395-abb1e3c4-8267-4444-a4c6-651144fd7899.jpeg)

![image](https://user-images.githubusercontent.com/47578509/210020402-2b57731a-6226-427c-ae7b-c6e8dba68dcc.jpeg)

Rgds Dirk

**Comment by JohanBendz** [comment]
@dbuekenh, it's supported in the test version of the app. (add /test to the apps URL to see a test version of any app that has one)

Test version can be found here: https://homey.app/en-us/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/

**Comment by dbuekenh** [comment]
Dear Johan,

Many thanks for all your efforts!
Looking forward to test it.
Rgds Dirk

Verstuurd vanaf mijn iPhone
