### ISSUE TITLE
HUE Signe floor lamp

### ISSUE THREAD

**Issue by jockeadn** [sebbebebbe/com.philips.hue.zigbee#441]
Hi!
I wrote some time ago about using your Homey app "HUE without the bridge". I still can not pair my HUE Signe floor lamp. I also see the app is still in v2.35. Will the issue be solved (will be happy to sponsor your app) or do I have to buy a bridge?
V/R, Joakim

**Comment by JohanBendz** [comment]
Has been added to the app
