### ISSUE TITLE
Cant add hue outdoor Sensor 

### ISSUE THREAD

**Issue by theminsksparrow** [sebbebebbe/com.philips.hue.zigbee#444]
Hej!

I have an homey eary 2016 fully updated.
Just bought an hue outdoor Sensor.
When i try to add it to homey it just say tjat it cant fond The app and installs it as a unknown zigbee device.
I have tryed restart The app and homey powerless for 15 min. Nothing works.

Help!

**Comment by AadatHome** [comment]
Good morning Johan,

Have the same but then for the indoor Sensor (from philps to signify).
See that there have been made amendments for this issue in  V2.0.38.
The odd thing is that I see that the latest version is V2.0,42, while I can only download V02.0.35.
Where can I find the latest (beta?) to download ?
Thanks

**Comment by JohanBendz** [comment]
Hi guys,
Add /test to the apps url to install the test version of the app. This should solve your issues.
https://homey.app/en-us/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/

**Comment by theminsksparrow** [comment]
Worked like a charm! 👍

Den mån 13 feb. 2023 09:38Johan Bendz ***@***.***> skrev:
