### ISSUE TITLE
Hue without the bridge buffrar sen den 9-10  feb

### ISSUE THREAD

**Issue by adaswe** [sebbebebbe/com.philips.hue.zigbee#447]
Hej Johan 
Homeyappen på min homey har startat att buffra över 80MB sen den 9-10 februari. 
Jag var bortrest då så ingen ändring har gjorts från min sida då det började. När ramminnet fylls pausas appen( Se printscreen)

Jag har avaktiverat flöden i homey det senaste dygnet men buffringen kvarstår. (Se printscreen)

Vid omstart  av homey + app så visas enheterna som vanligt men det går inte att styra enskilda enheter (av/på). Jag får ingen felfunktion från homey eller appen, men ingenting händer.

Var skall jag fortsätta med felsökningen? Är jag ensam om problemet?

**Comment by adaswe** [comment]
![Uploading B21384BC-39B9-41D6-B87C-A8880249830C.jpeg…]()

**Comment by adaswe** [comment]
![9423952C-CDC4-4F05-A347-BFD98F005CE0](https://user-images.githubusercontent.com/17740556/222218138-8da5ca59-c4e8-4517-86ac-4930a1b2a537.png)

**Comment by adaswe** [comment]
![Uploading B104F674-E25A-4B2A-812D-711A04BA916A.jpeg…]()

**Comment by adaswe** [comment]
![63F316EC-0F0C-43C4-80B0-0BF42091CA8F](https://user-images.githubusercontent.com/17740556/222218563-6ee40962-ebe5-447e-9217-4cf69d1acf71.jpeg)

**Comment by JohanBendz** [comment]
Hej där @adaswe .
Hmm, appen har inte uppdaterats sedan 27 november så det är inget nytt i appen som orsakar det. Bör antingen vara nått i Homey OS eller någon enhet / din Homey som spökar.
Skicka över en diagnostikrapport från appen.

**Comment by adaswe** [comment]
Hej Johan.
Köpte en ”ny” och har låtit den köra samma inställningar som den tidigare mha en säkerhetskopia.
Samma symptom som den gamla.

137214a6-3280-4b9e-9c4e-ff04d39a52fd

En fråga på appen, går det att önska en funktion i appen för att sätta enskilda hue-enheter i parningsmode. Jag nollställde zigbee nätverket och har svårigheter att para dem i appen igen.
Jag har kastat ut hue-hubben och enheterna vill nödvändigtvis inte gå i parningsmode genom toggling. 

Tack för det arbetet du lägger ner på denna grymma appen

**Comment by JohanBendz** [comment]
Hej @adaswe, har du fortsatt minnesproblem eller fungerar appen bättre nu?
Angående parningen så finns det inget jag kan göra i appen, Athom har ju under året släppt bättre stöd för "repair" som kan vara till hjälp men generellt så är svårigheter att para enheter ett problem. Bra batterier, bra strömagg på Homey och tålamod hjälper.. att trycka på para knappen, på enheter som har en, var tredje sekund under parningen hjälper ibland.

**Comment by adaswe** [comment]
Hej Johan.
Du gör ett grymt jobb, tack för att du återkopplar!

Nej jag köpte en till homey till och fördelade antalet zigbee enheter jämt på de två.
Vet inte riktigt vad problemet var men mest troligt så hade jag för många enheter.
Nu senast krashade den ena homeyns zigbee nätverk så jag gav upp.
Men den andra  fungerar utan den massiva minnes uppbyggnaden.

Jag parade det mesta genom hue appen och gatewayen.

Kind Regards //Mikael


18 okt. 2023 kl. 11:52 skrev Johan Bendz ***@***.***>:

﻿

Hej @adaswe<https://github.com/adaswe>, har du fortsatt minnesproblem eller fungerar appen bättre nu?
Angående parningen så finns det inget jag kan göra i appen, Athom har ju under året släppt bättre stöd för "repair" som kan vara till hjälp men generellt så är svårigheter att para enheter ett problem. Bra batterier, bra strömagg på Homey och tålamod hjälper.. att trycka på para knappen, på enheter som har en, var tredje sekund under parningen hjälper ibland.

**Comment by JohanBendz** [comment]
Stänger ärendet, om samma problem kvarstår/uppstår så skapa nytt ärende med färska loggar.
