### ISSUE TITLE
Philips Hue motion sensor model 9290030675

### ISSUE THREAD

**Issue by bellringer2** [sebbebebbe/com.philips.hue.zigbee#448]
When I try to add this to my Homey Pro I am getting "could not find Homey app for this device it has been added as unknown zigbee device".

App and Homey pro are both up to date. 

I restarted the app and the Homey pro but it still goes wrong.

Any ideas what I'm doing wrong?

**Comment by Designburo** [comment]
I have the same! Looks like there is no support for this model. Please add?

**Comment by WoodGrove** [comment]
I have the same issue, please add support for this model.

Update: It works using the beta version (v2.0.42)
