### ISSUE TITLE
hue Occupancy sensor

### ISSUE THREAD

**Issue by robindelange** [sebbebebbe/com.philips.hue.zigbee#450]
i have the issue after migrating to the HP23, I tried to migrate a SML001 occupancy sensor. it migrates fine and HP sees it but after that it does nothing, after a while the red alert is showing again. tried several times but nothing works

**Comment by JohanBendz** [comment]
@robindelange, can you please restart the app, add the device again, wait for it to fail and send me a crash report from the app?

**Comment by robindelange** [comment]
Johan, thank you for your help.  I had 2 sensors that didn't work. one of them I removed completely and re add again and this works. why it doesn't work when I repair the sensor I don't know. I think im gonna repair the other today, and repair my flows after that with the script off Martijn poppen.

the thing is that the app or the device doesn't fail. when you repair it, homey sees it, the devices its led shows its connected but then it don't update any values

i made an crash report for you, so maybe you can see why it doesn't work if I repair the device without it removing it completely

41efecd8-112d-4f64-a1ec-1bc166382757

kind regards

Robin de Lange

**Comment by robindelange** [comment]
Johan, the last issue above seems to be a athom issue and they fixed it allready, sorry for that. 

but after my homey restarts or updates, the motion sensor gives the red error again. when It starts up all the devices in your app works great, only the motion sensor give error. after a app restart the motion sensor works also again.

i don't know if this is an athom problem or a app problem because the rest of the devices in the app work great

thanks for the help! 

kind regards 
Robin

**Comment by RonaldNeed** [comment]
Hi Johan,
I think I have the same issue as [robindelange]
If my Homey 2023 restarts or updates, the motion sensors SML002 (Occupancy Sensor)  gives a red error (exclamation mark). All other devices starting without a problem. Including the SML001 Motion Sensors. After I restarts the APP v2.0.42, the motion sensors SML002 (Occupancy Sensor) are  working again.
Regards, Ronald

**Comment by JohanBendz** [comment]
Sensors will have a "stay alive" feature starting next release, lets hope this works.
