### ISSUE TITLE
Hue motion sensor

### ISSUE THREAD

**Issue by HenryMD18** [sebbebebbe/com.philips.hue.zigbee#451]
Hello Johan,

Could you add the New motion sensor from Philips Hue.

Are you already busy with it, or would you like me to interview the device?

Thank you for all your work.

Greetings Henry

**Comment by JohanBendz** [comment]
Hi @HenryMD18, I need a bit more information to add support for any device. But first, make sure you have tested this version: https://homey.app/en-us/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/

**Comment by HenryMD18** [comment]
Hello Johan, thank you for the fast response. It works! I searched the homey community forum but didn t see the experimental app. Thanks again! Greetings Henry

**Comment by HenryMD18** [comment]
Hello Johan, the sensor works but last night After the update they stopped. I tried to repair them in the app, that doesn t work. Then I removed the devices and connected them. Now they work again.
I rebooted the pro to see what happens, then they stopped  working again.
I hope that this helps so can make you app better.
Thank you, greetings Henry

**Comment by martin82private** [comment]
Hi Johan, same issue with my homey pro 23 (today i have 10rc93 installed) , if i restart homey some of the motion sensor have a red triangle. Via developer portal i can ping them, also the flows are working (presence trigger). After several restarts of the app the red triangle will be gone.

**Comment by bergwfoto** [comment]
Hi Johan, same issue for me. (10.0.0-rc.110 installed) After release update I have to remove and reconnect all Hue motion sensors in my network. When trying to repair nothing happens.

**Comment by rvdeijk** [comment]
@bergwfoto @martin82private @HenryMD18 
Don't forget to add the diagnostic report from the app settings panel.

**Comment by JohanBendz** [comment]
Upcoming version hopefully fix the "dropping out" issues with sensors

**Comment by bergwfoto** [comment]
Hello Johan,
This fix would very welome.

One more question
Is the Philips hue gradient ledstrip already supported ?
When not how can I help you to get it on the list.
I know how to write homey apps. (Javascipt and Typescript).

Met vriendelijke groet,
Willem van den Berg
 fotoscan
   your memories memorizable

            Laan van Insulinde 3  |  2103 TA Heemstede   |  The Netherlands
            +31 (0)23 205 20 34<tel:+31%2023%20205%2020%2034>  |  www.fotoscan.nl<https://www.fotoscan.nl/>        |  ***@***.******@***.***>

Op 29 feb. 2024 om 00:41 heeft Johan Bendz ***@***.***> het volgende geschreven:

﻿

Upcoming version hopefully fix the "dropping out" issues with sensors
