### ISSUE TITLE
Ensis Pendant does not connect

### ISSUE THREAD

**Issue by fjkresin** [sebbebebbe/com.philips.hue.zigbee#455]
I use the app a few days now; it easily found & connected an Iris v4 and two Lightstrips v4. However, my new Ensis will not be recongnized and only connects as two regular Zigbee devices; which means I cannot use the specific cards you provided. I have tried resetting with the Hue app & registering a few times, so far not successful.

**Comment by JohanBendz** [comment]
Been a while, a few Ensis types are added to the test version of the app. If your version is not please get back with interview data.
