### ISSUE TITLE
Slow response

### ISSUE THREAD

**Issue by Mombasa-h8x** [sebbebebbe/com.philips.hue.zigbee#458]
Hi I have a strange problem. In picture 1, you can see a Philips Hue light bulb that responds quite slowly, taking around 0.7 seconds. However, in picture 2, the response is much faster, only taking 0.1 seconds. Interestingly, all my Philips Hue light bulbs exhibit this slow response, except for the fast one, which is a new Edison light bulb. Homey is located 2 meters away from the light bulbs without any obstructions. Regardless of the distance, the response time for all the Philips Hue bulbs is consistently around 0.6 to 0.7 seconds. I am using the Philips Hue (no bridge) application. I'm wondering if anyone else has experienced this behavior as well.

Picture 1
![IMG_0141](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/36369009/23473e58-8f10-44f9-befa-713ffca49335)

Picture 2
![IMG_0142](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/36369009/eb666eaf-6aa8-4014-b439-d9a2c6cb5448)

Slow light bulb
![IMG_0143](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/36369009/d20b9c39-81b0-4346-a2f3-cb04136b2433)

Fast light bulb
![IMG_0144](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/36369009/db9e5145-aef8-4258-88b1-d57974a25a6c)

What i notice is that the fast light bulb has a different class and driver could that be the reason?

**Comment by JohanBendz** [comment]
Hi there. Looks like the fast one does not use the app but the generic Zigbee driver from Athom/Homey. I see it use a never zb_sw_build_id, I'll check if this makes any difference. 0,7 seconds do look a bit slow, I just tested lights here and have 0,3 seconds on all of them.

**Comment by Mombasa-h8x** [comment]
Hi Johan,

Thank you for your swift response, i just noticed that there was an beta version available. After installing the beta version the response times went from 0.7s to 0.2s.

**Comment by JohanBendz** [comment]
Good to hear! Hmm.. I really should push a new live version...

**Comment by Mombasa-h8x** [comment]
Don’t know how difficult and time consuming it is, but does it make sense to update the drivers to the latest version? 

And btw I really appreciate the amount of work you did in making this great app!!

**Comment by JohanBendz** [comment]
Probably not worth the effort, one have to remove the device from Homey and add it to Hue Hub where it can be updated. If there is an update.. and then re-pair it to Homey and fix any broken flows..

Thanks! Always nice to hear!
