### ISSUE TITLE
Hue Tap Dial Switch

### ISSUE THREAD

**Issue by Sweethomey** [sebbebebbe/com.philips.hue.zigbee#459]
Pleace put  the Hue Tap Dial Switch in your App. THX

**Comment by tojo1271** [comment]
Yes please, that would be great! Thanks.

**Comment by jacc08** [comment]
I would like to ask this as well. Thnx alot in advance!

**Comment by jerevirt** [comment]
+1

**Comment by git-jb1975** [comment]
Yes Please. This is the only reason I have to keep my Hue bridge.  Thanks in advance.

**Comment by vanderwees** [comment]
I would like to support this. I can help develop this, if needed.

**Comment by vanderwees** [comment]
I saw in the changelog, this device is added. However it does not seem to be functional on the new Homey Pro (Early 2023)

**Comment by JohanBendz** [comment]
Hi @vanderwees, did you try this version?
https://homey.app/en-gb/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/

**Comment by vanderwees** [comment]
Sorry, yes it is working using the test version. First rotate right fast was missing, but that is also fixed. Thank you.
