### ISSUE TITLE
Addition to making flows

### ISSUE THREAD

**Issue by Hotshot079** [sebbebebbe/com.philips.hue.zigbee#460]
Hi,

I found something that may improve the experience and possibilities for some people.
If you want to pick an "if" flow card you have a wide range of options.
However, if you want to add an "and" flow card, there are only two available options: "motion sensor is on " and "battery warning is on"
Wouldn't it be amazing to have additional "and" flow cards which use the capabilities of the device such as:
- and the temperature is above/below a certain "value"
- and the brightness is above/below a certain "value" (for turnin on the lights when it is dark outside during the day, which happens way to often in the Netherlands unfortunately)

**Comment by JohanBendz** [comment]
Hi there.
Hmm, the idea is to only have cards for a specific device that concerns the device itself. If you need a "and" card for something that is not part of the device, say outdoor temperature or cloud levels, you should use a "and" card from a device or app that have this feature. Or am I not understanding your request? :)

If you mean the values of a device you can always use "logic" to check a value.

**Comment by Hotshot079** [comment]
Hi,

Apologies for the delayed response.

This specific sensor, the Philips Hue Motion Sensor, is not only capable of measuring movement but also capable of measuring lux values and temperature values. Currently, you can only use the lux and temperature values to start a flow, but there is no option to use those values as an "and" flow card. Unfortunately, the following flow is not possible:

If the motion sensor turns on, **_and the lux value is below X,_** then turn on light X.

It would be an excellent addition to the product and the app to be able to use the lux and temperature values as an "and" cards as well.

I have te following visualisations: (sorry im Dutch, so my homey is in Dutch as well)
![Flow](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/133372460/f96970c4-d043-4a10-be46-2f9e3cd0ee64)
![Options](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/133372460/c67f99dd-527d-4ca0-b607-ad1c2485a0b9)

**Comment by JohanBendz** [comment]
Hi @Hotshot079, sorry for the late answer.
Hmm, I see your point!
Until further I suggest using a logic card to check the devices values in the AND section.

**Comment by JohanBendz** [comment]
Luminance and Temperature Conditional cards added to next release. :)
