### ISSUE TITLE
Motion sensor data

### ISSUE THREAD

**Issue by SerrII** [sebbebebbe/com.philips.hue.zigbee#461]
hey @JohanBendz i have a problem with my motion sensors. These have not updated the brightness and temperature values ​​for about 2 months. Can you help me?

**Comment by jeroenski** [comment]
Had the same problem. just remove the sensor from yhe Homey and if you add them again it wil be working ( for some time)
With the outdoorsensor it will work great also for longer time.

Greetings jeroen

**Comment by RonaldTermaat** [comment]
I have the same problem. Removing them and add them again is not a pretty way of solving this issue. Because then you also have to repair all the flows. It would be nice if this could be fixed. It works when I use the Hue Bridge, so I suppose it could work without the bridge as well.

**Comment by JohanBendz** [comment]
Hi @SerrII, is this still an issue?

**Comment by SerrII** [comment]
@JohanBendz Yes the problem still exists

**Comment by JohanBendz** [comment]
New version out, hopefully works better. If not, please start a new issue and add a diagnostic report code from the app.
