### ISSUE TITLE
Add support for Philips hue model 8719514288232 (LWA017)

### ISSUE THREAD

**Issue by MBalajka** [sebbebebbe/com.philips.hue.zigbee#464]
Hi,

would be possible to add support for Philips hue model 8719514288232 ? LWA017 should be already implemented, but its missing in list.

<html>
<body>

Key | Value
-- | --
zb_product_id | "LWA017"
zb_manufacturer_name | "Signify Netherlands B.V."
zb_receive_when_idle | "✓"
zb_device_type | "router"
zb_ieee_address | "00:17:88:01:0c:33:b9:3f"
zb_sw_build_id | "1.76.10"

</body>
</html>

Thanks

**Comment by JohanBendz** [comment]
Hi @MBalajka, are you using the test version of the app?

**Comment by MBalajka** [comment]
Hi @JohanBendz,
No. Its version V2.0.35 from app store.

**Comment by JohanBendz** [comment]
@MBalajka try the test version, https://homey.app/en-gb/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/

**Comment by MBalajka** [comment]
@JohanBendz it works, thank you. Only now I found time to test it.
One nice thing that would be nice to have would be the ability to see the total kwh consumption (energy).
