### ISSUE TITLE
Can t add Hue outdoor motion Sensor to homey pro

### ISSUE THREAD

**Issue by ricoxdela** [sebbebebbe/com.philips.hue.zigbee#465]
Hi
Can t add Hue outdoor motion Sensor to homey pro ...See error message "no app available for this device" ...
Anything I ce misses to Make it Right ?
Thanks for helping
Sincerely

![Screenshot_2023-06-11-16-43-53-82_4bbfc4a7dd885a2bb189f300112a7ed4](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/136157639/65754369-81ac-4e43-9c0f-2db0430b57f4)

**Comment by romhug** [comment]
Hi. I have the same Issue. SML-004 (9290030674) Outdoor sensor cannot be added. It would be awesome if you can add support for this device. Thank you so much.

**Comment by wsu-runner** [comment]
I was able to add after updating to the test version of the app here: https://homey.app/en-us/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/

**Comment by JohanBendz** [comment]
Hi @ricoxdela and @romhug, the device is supported in the test version of the app (soon supported in the live version too).

**Comment by romhug** [comment]
Hi Johan

Thank you so much! Have a great day!

**Comment by ricoxdela** [comment]
Thanks Johan that works now
