### ISSUE TITLE
Philips hue Outdoor sensor is not working 

### ISSUE THREAD

**Issue by Stjernemix** [sebbebebbe/com.philips.hue.zigbee#466]
Hello.. 😊

I can't connect my Philips Hue Outdoor sensor to this app. Why not??? I'm doing something wrong?? 
Homey pro 23 will only take it as an unnamed zigbee devices.  🤔😫 help me..

Thanks in advance

Regards Chris Tved

**Comment by wsu-runner** [comment]
I was able to add after updating to the test version of the app here: https://homey.app/en-us/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/

**Comment by Stjernemix** [comment]
Hello..
Oohh thank you.. ☺️


Sendt fra Outlook til Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Stjernemix** [comment]
Hello again. 
I can't get my nous zigbee plug to work White power metering i use tuya zigbee app. Is there a test version like the Philips hue app??? 

Tanks in advance

Regeres Chris Tved

**Comment by JohanBendz** [comment]
Hi @Stjernemix, is nous zigbee plug a Tuya unit? If so yes there is, keep that discussion in the Tuya app git. Closing this thread.
