### ISSUE TITLE
Philips Hue Wall Switch

### ISSUE THREAD

**Issue by nemecmic88** [sebbebebbe/com.philips.hue.zigbee#472]
Hello, I have Phillips Hue Wall Switch and I use Phillips Hue, without the bridge. Please, can you add this device to the application Phillips Hue, without the bridge?

**Comment by rvdeijk** [comment]
@nemecmic88 can you already add it as a generic/unknown zigbee device? If so, then interview the device at [Developer page](https://tools.developer.homey.app/tools/zigbee) and paste the interview code here as a comment.

**Comment by Gand41f** [comment]
I think this is related to this: https://github.com/JohanBendz/com.philips.hue.zigbee/issues/315

Unfortunately it seems not to be possible at the moment to create a drive due to the lack of support of a feature from Athom.

**Comment by JohanBendz** [comment]
Device added to test version
