### ISSUE TITLE
Philips Hue motion unavailable after restart

### ISSUE THREAD

**Issue by bergwfoto** [sebbebebbe/com.philips.hue.zigbee#473]
Hello Johan, 
I am running Homey Pro (Early 2023) version 10.0.0 rc. 118
and the test version v2.0.42 of the Hue App.
The official version did not work with the motion sensors.

Each time I reboot Homey Pro all Philips motion sensors (indoor and outdoor) are unavailable after the reboot.
I have to manually restart the "Philips Hue, without the. Bridge" App to make them available and working again. 

Btw: this also happened with earlier versions.

Please can you fix.
Thanks in advance.

Regards, 
Willem

**Comment by JohanBendz** [comment]
Hi @bergwfoto, not sure what I can do to fix this.. can you provide a diagnostic report?

**Comment by bergwfoto** [comment]
Hello Johan
This is the report id.
cda2f246-8aad-4104-8429-0125c6f9695a

Please let me know.
I have also reported to Athom, they say that this must be fixed by the developer of the App.

Let me know.
Thanks in advance.

Met vriendelijke groet,
Willem van den Berg
 fotoscan
   your memories memorizable

            Laan van Insulinde 3  |  2103 TA Heemstede   |  The Netherlands
            +31 (0)23 205 20 34<tel:+31%2023%20205%2020%2034>  |  www.fotoscan.nl<https://www.fotoscan.nl/>        |  ***@***.******@***.***>

Op 4 jul. 2023 om 20:57 heeft Johan Bendz ***@***.***> het volgende geschreven:

﻿

Hi @bergwfoto<https://github.com/bergwfoto>, not sure what I can do to fix this.. can you provide a diagnostic report?

**Comment by bergwfoto** [comment]
I got an update from your App v.2.0.44 yesterday and Athom and this night. 
After both updates there are still sensors not connecting after reboot.
See below.

![HueMotionSensor](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/83172418/79bc3f28-7bd4-4336-9e1a-8b604cd0be1e)
