### ISSUE TITLE
Continues Appcrash

### ISSUE THREAD

**Issue by Ziglar1** [sebbebebbe/com.philips.hue.zigbee#48]
The app keeps crashing withing seconds of starting or restarting the app.  Had to pull all bulbs from their sockets to turn then off.

**Comment by sebbebebbe** [comment]
Hi thanks for the info. I have gotten some error-reports.

Have you tried removing one of the RGB bulbs and then adding it again?

**Comment by Ziglar1** [comment]
The app crashes before that Is possible.

**Comment by sebbebebbe** [comment]
This should now be solved, packages where missing in that version.
