### ISSUE TITLE
Philips Hue Lily spots not recognized - Homey: Unkown Zigbee device

### ISSUE THREAD

**Issue by ericsteffann-fontys** [sebbebebbe/com.philips.hue.zigbee#480]
Hi,

I have tried to add Lily spots. Unfortunately only 1 spot is recognized by Homey as a Philips Hue Lily spot. The others aren't. It it possible to add these to the system?

Spot 1
Lily 86020031
440400978991
S/N: 0A80E3

Spot 2
906600
440400978991
S/N: 9BF659

Spot 3
Lily 86020031
40400978991
S/N: B1D688

Spot 4
906600
440400978991
S/N EFA5C4

**Comment by JohanBendz** [comment]
Hi, sorry for the late answer. I would need an interview of the devices to make sure I add them correctly.

https://tools.developer.homey.app/tools/zigbee
(.../action - interview)

**Comment by ericsteffann-fontys** [comment]
@JohanBendz No worries!
Here are the interviews of the unrecognized ones:


**Spot 1**
`  "ids": {
    "modelId": "1741530P7",
    "manufacturerName": "Philips"
  },
  "endpoints": {
    "ieeeAddress": "00:17:88:01:0b:ed:43:02",
    "networkAddress": 6364,
    "modelId": `"1741530P7",`
    "manufacturerName": "Philips",
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 6364,
        "_reserved": 28,
        "endpointId": 11,
        "applicationProfileId": 260,
        "applicationDeviceId": 269,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          0,
          3,
          4,
          5,
          6,
          8,
          4096,
          768,
          64513
        ],
        "outputClusters": [
          25
        ]
      },
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 6364,
        "_reserved": 10,
        "endpointId": 242,
        "applicationProfileId": 41440,
        "applicationDeviceId": 97,
        "applicationDeviceVersion": 0,
        "_reserved1": 0,
        "inputClusters": [],
        "outputClusters": [
          33
        ]
      }
    ],
    "deviceType": "router",
    "receiveWhenIdle": true,
    "swBuildId": "1.82.10",
    "capabilities": {
      "alternatePANCoordinator": false,
      "deviceType": true,
      "powerSourceMains": true,
      "receiveWhenIdle": true,
      "security": false,
      "allocateAddress": true
    },
    "extendedEndpointDescriptors": {
      "11": {
        "clusters": {
          "basic": {
            "attributes": [
              {
                "id": 0,
                "name": "zclVersion",
                "value": 2
              },
              {
                "id": 1,
                "name": "appVersion",
                "value": 2
              },
              {
                "id": 2,
                "name": "stackVersion",
                "value": 1
              },
              {
                "id": 3,
                "name": "hwVersion",
                "value": 0
              },
              {
                "id": 4,
                "name": "manufacturerName",
                "value": "Philips"
              },
              {
                "id": 5,
                "name": "modelId",
                "value": "1741530P7"
              },
              {
                "id": 6,
                "name": "dateCode",
                "value": "20210305"
              },
              {
                "id": 7,
                "name": "powerSource",
                "value": "mains"
              },
              {
                "id": 8,
                "name": "appProfileVersion",
                "value": 0
              },
              {
                "id": 9
              },
              {
                "id": 10
              },
              {
                "id": 11
              },
              {
                "id": 16384,
                "name": "swBuildId",
                "value": "1.82.10"
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "identify": {
            "attributes": [
              {
                "id": 0,
                "name": "identifyTime",
                "value": 0
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "groups": {
            "attributes": [
              {
                "id": 0,
                "name": "nameSupport",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0
                  ]
                }
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "scenes": {
            "attributes": [
              {
                "id": 0
              },
              {
                "id": 1
              },
              {
                "id": 2
              },
              {
                "id": 3
              },
              {
                "id": 4
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "onOff": {
            "attributes": [
              {
                "id": 0,
                "name": "onOff",
                "value": true
              },
              {
                "id": 16384
              },
              {
                "id": 16385,
                "name": "onTime",
                "value": 0
              },
              {
                "id": 16386,
                "name": "offWaitTime",
                "value": 0
              },
              {
                "id": 16387
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "levelControl": {
            "attributes": [
              {
                "id": 0,
                "name": "currentLevel",
                "value": 254
              },
              {
                "id": 1,
                "name": "remainingTime",
                "value": 0
              },
              {
                "id": 15
              },
              {
                "id": 16384
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "touchlink": {
            "attributes": [
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1,
                "reportingConfiguration": {
                  "status": "UNREPORTABLE_ATTRIBUTE",
                  "direction": "reported"
                }
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "colorControl": {
            "attributes": [
              {
                "id": 0,
                "name": "currentHue",
                "value": 32
              },
              {
                "id": 1,
                "name": "currentSaturation",
                "value": 140
              },
              {
                "id": 2
              },
              {
                "id": 3,
                "name": "currentX",
                "value": 29973
              },
              {
                "id": 4,
                "name": "currentY",
                "value": 26871
              },
              {
                "id": 7,
                "name": "colorTemperatureMireds",
                "value": 366
              },
              {
                "id": 8,
                "name": "colorMode",
                "value": "colorTemperatureMireds"
              },
              {
                "id": 15
              },
              {
                "id": 16
              },
              {
                "id": 17
              },
              {
                "id": 18
              },
              {
                "id": 19
              },
              {
                "id": 21
              },
              {
                "id": 22
              },
              {
                "id": 23
              },
              {
                "id": 25
              },
              {
                "id": 26
              },
              {
                "id": 27
              },
              {
                "id": 48
              },
              {
                "id": 49
              },
              {
                "id": 50
              },
              {
                "id": 51
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        },
        "bindings": {
          "ota": {}
        }
      },
      "242": {
        "clusters": {},
        "bindings": {}
      }
    }
  }
`


**Spot 2**
`  "ids": {
    "modelId": "1741530P7",
    "manufacturerName": "Philips"
  },
  "endpoints": {
    "ieeeAddress": "00:17:88:01:09:ee:10:08",
    "networkAddress": 55326,
    "modelId": "1741530P7",
    "manufacturerName": "Philips",
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 55326,
        "_reserved": 28,
        "endpointId": 11,
        "applicationProfileId": 260,
        "applicationDeviceId": 269,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          0,
          3,
          4,
          5,
          6,
          8,
          4096,
          768,
          64513
        ],
        "outputClusters": [
          25
        ]
      },
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 55326,
        "_reserved": 10,
        "endpointId": 242,
        "applicationProfileId": 41440,
        "applicationDeviceId": 97,
        "applicationDeviceVersion": 0,
        "_reserved1": 0,
        "inputClusters": [],
        "outputClusters": [
          33
        ]
      }
    ],
    "deviceType": "router",
    "receiveWhenIdle": true,
    "swBuildId": "1.56.7_r29434",
    "capabilities": {
      "alternatePANCoordinator": false,
      "deviceType": true,
      "powerSourceMains": true,
      "receiveWhenIdle": true,
      "security": false,
      "allocateAddress": true
    },
    "extendedEndpointDescriptors": {
      "11": {
        "clusters": {
          "basic": {
            "attributes": [
              {
                "id": 0,
                "name": "zclVersion",
                "value": 2
              },
              {
                "id": 1,
                "name": "appVersion",
                "value": 2
              },
              {
                "id": 2,
                "name": "stackVersion",
                "value": 1
              },
              {
                "id": 3,
                "name": "hwVersion",
                "value": 0
              },
              {
                "id": 4,
                "name": "manufacturerName",
                "value": "Philips"
              },
              {
                "id": 5,
                "name": "modelId",
                "value": "1741530P7"
              },
              {
                "id": 6,
                "name": "dateCode",
                "value": "20190529"
              },
              {
                "id": 7,
                "name": "powerSource",
                "value": "mains"
              },
              {
                "id": 8,
                "name": "appProfileVersion",
                "value": 0
              },
              {
                "id": 9
              },
              {
                "id": 10
              },
              {
                "id": 11
              },
              {
                "id": 16384,
                "name": "swBuildId",
                "value": "1.56.7_r29434"
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "identify": {
            "attributes": [
              {
                "id": 0,
                "name": "identifyTime",
                "value": 0
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "groups": {
            "attributes": [
              {
                "id": 0,
                "name": "nameSupport",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0
                  ]
                }
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "scenes": {
            "attributes": [
              {
                "id": 0
              },
              {
                "id": 1
              },
              {
                "id": 2
              },
              {
                "id": 3
              },
              {
                "id": 4
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "onOff": {
            "attributes": [
              {
                "id": 0,
                "name": "onOff",
                "value": true
              },
              {
                "id": 16384
              },
              {
                "id": 16385,
                "name": "onTime",
                "value": 0
              },
              {
                "id": 16386,
                "name": "offWaitTime",
                "value": 0
              },
              {
                "id": 16387
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "levelControl": {
            "attributes": [
              {
                "id": 0,
                "name": "currentLevel",
                "value": 254
              },
              {
                "id": 1,
                "name": "remainingTime",
                "value": 0
              },
              {
                "id": 15
              },
              {
                "id": 16384
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "touchlink": {
            "attributes": [
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1,
                "reportingConfiguration": {
                  "status": "UNREPORTABLE_ATTRIBUTE",
                  "direction": "reported"
                }
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "colorControl": {
            "attributes": [
              {
                "id": 0,
                "name": "currentHue",
                "value": 32
              },
              {
                "id": 1,
                "name": "currentSaturation",
                "value": 140
              },
              {
                "id": 2
              },
              {
                "id": 3,
                "name": "currentX",
                "value": 29972
              },
              {
                "id": 4,
                "name": "currentY",
                "value": 26871
              },
              {
                "id": 7,
                "name": "colorTemperatureMireds",
                "value": 366
              },
              {
                "id": 8,
                "name": "colorMode",
                "value": "colorTemperatureMireds"
              },
              {
                "id": 15
              },
              {
                "id": 16
              },
              {
                "id": 17
              },
              {
                "id": 18
              },
              {
                "id": 19
              },
              {
                "id": 21
              },
              {
                "id": 22
              },
              {
                "id": 23
              },
              {
                "id": 25
              },
              {
                "id": 26
              },
              {
                "id": 27
              },
              {
                "id": 48
              },
              {
                "id": 49
              },
              {
                "id": 50
              },
              {
                "id": 51
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        },
        "bindings": {
          "ota": {}
        }
      },
      "242": {
        "clusters": {},
        "bindings": {}
      }
    }
  }`


**Spot 3**
`  "ids": {
    "modelId": "1741530P7",
    "manufacturerName": "Philips"
  },
  "endpoints": {
    "ieeeAddress": "00:17:88:01:0b:ed:29:10",
    "networkAddress": 13642,
    "modelId": "1741530P7",
    "manufacturerName": "Philips",
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 13642,
        "_reserved": 28,
        "endpointId": 11,
        "applicationProfileId": 260,
        "applicationDeviceId": 269,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          0,
          3,
          4,
          5,
          6,
          8,
          4096,
          768,
          64513
        ],
        "outputClusters": [
          25
        ]
      },
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 13642,
        "_reserved": 10,
        "endpointId": 242,
        "applicationProfileId": 41440,
        "applicationDeviceId": 97,
        "applicationDeviceVersion": 0,
        "_reserved1": 0,
        "inputClusters": [],
        "outputClusters": [
          33
        ]
      }
    ],
    "deviceType": "router",
    "receiveWhenIdle": true,
    "swBuildId": "1.82.10",
    "capabilities": {
      "alternatePANCoordinator": false,
      "deviceType": true,
      "powerSourceMains": true,
      "receiveWhenIdle": true,
      "security": false,
      "allocateAddress": true
    },
    "extendedEndpointDescriptors": {
      "11": {
        "clusters": {
          "basic": {
            "attributes": [
              {
                "id": 0,
                "name": "zclVersion",
                "value": 2
              },
              {
                "id": 1,
                "name": "appVersion",
                "value": 2
              },
              {
                "id": 2,
                "name": "stackVersion",
                "value": 1
              },
              {
                "id": 3,
                "name": "hwVersion",
                "value": 0
              },
              {
                "id": 4,
                "name": "manufacturerName",
                "value": "Philips"
              },
              {
                "id": 5,
                "name": "modelId",
                "value": "1741530P7"
              },
              {
                "id": 6,
                "name": "dateCode",
                "value": "20210305"
              },
              {
                "id": 7,
                "name": "powerSource",
                "value": "mains"
              },
              {
                "id": 8,
                "name": "appProfileVersion",
                "value": 0
              },
              {
                "id": 9
              },
              {
                "id": 10
              },
              {
                "id": 11
              },
              {
                "id": 16384,
                "name": "swBuildId",
                "value": "1.82.10"
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "identify": {
            "attributes": [
              {
                "id": 0,
                "name": "identifyTime",
                "value": 0
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "groups": {
            "attributes": [
              {
                "id": 0,
                "name": "nameSupport",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0
                  ]
                }
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "scenes": {
            "attributes": [
              {
                "id": 0
              },
              {
                "id": 1
              },
              {
                "id": 2
              },
              {
                "id": 3
              },
              {
                "id": 4
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "onOff": {
            "attributes": [
              {
                "id": 0,
                "name": "onOff",
                "value": true
              },
              {
                "id": 16384
              },
              {
                "id": 16385,
                "name": "onTime",
                "value": 0
              },
              {
                "id": 16386,
                "name": "offWaitTime",
                "value": 0
              },
              {
                "id": 16387
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "levelControl": {
            "attributes": [
              {
                "id": 0,
                "name": "currentLevel",
                "value": 254
              },
              {
                "id": 1,
                "name": "remainingTime",
                "value": 0
              },
              {
                "id": 15
              },
              {
                "id": 16384
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "touchlink": {
            "attributes": [
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 1,
                "reportingConfiguration": {
                  "status": "UNREPORTABLE_ATTRIBUTE",
                  "direction": "reported"
                }
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "colorControl": {
            "attributes": [
              {
                "id": 0,
                "name": "currentHue",
                "value": 32
              },
              {
                "id": 1,
                "name": "currentSaturation",
                "value": 140
              },
              {
                "id": 2
              },
              {
                "id": 3,
                "name": "currentX",
                "value": 29973
              },
              {
                "id": 4,
                "name": "currentY",
                "value": 26871
              },
              {
                "id": 7,
                "name": "colorTemperatureMireds",
                "value": 366
              },
              {
                "id": 8,
                "name": "colorMode",
                "value": "colorTemperatureMireds"
              },
              {
                "id": 15
              },
              {
                "id": 16
              },
              {
                "id": 17
              },
              {
                "id": 18
              },
              {
                "id": 19
              },
              {
                "id": 21
              },
              {
                "id": 22
              },
              {
                "id": 23
              },
              {
                "id": 25
              },
              {
                "id": 26
              },
              {
                "id": 27
              },
              {
                "id": 48
              },
              {
                "id": 49
              },
              {
                "id": 50
              },
              {
                "id": 51
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        },
        "bindings": {
          "ota": {}
        }
      },
      "242": {
        "clusters": {},
        "bindings": {}
      }
    }
  }`

**Comment by JohanBendz** [comment]
Hi @ericsteffann-fontys, this has been in the test version for some time. Hope it works for you, if not please let me know. (you will have to pair each light individually, if you have not already)

**Comment by JohanLindstam** [comment]
Hi. I just tried to add the base 3-unit package Hue Lily to my Homey Pro.
I keep getting two lights to be added, though not recognized. The third (keeps varying which of the individuals) cant be detected.
Is there possibly an update needed with newer Lilys?
