### ISSUE TITLE
Philips Outdoor Sensor sensitivity

### ISSUE THREAD

**Issue by Evert1976** [sebbebebbe/com.philips.hue.zigbee#482]
SInce I added my Philips Outdoor Motion sensor directly to Homey instead of the Philips Bridge, the motion sensor is constantly triggering motion even if I set the sensitivity to Low.  Any one an idea how to prevent this?

**Comment by Evert1976** [comment]
The strange thing is.. I have 2 outdoor sensors. One is working fine. The one who is working fine has product id SML002 and firmware 6.1.1.27575 and the one who is constanly triggering motion has a product id of SML004 an firmware 2.53.6

**Comment by rvdeijk** [comment]
@Evert1976 You could also ask this question to the community forum:
https://community.homey.app/t/app-pro-philips-hue-zigbee-without-the-bridge/29734

> Known issues
> Motion sensors (in- and outdoor): If your sensor is not working after an upgrade removing and re-pairing your sensor might be needed. Please note there is also an alternative driver for motion sensors.

**Comment by Evert1976** [comment]
You are right! I put the question over there.
