### ISSUE TITLE
Dimmer switches and motion sensor problems

### ISSUE THREAD

**Issue by Olimol1** [sebbebebbe/com.philips.hue.zigbee#485]
Hi JohanBendz

Thanks for a great app!

I'm using Homey Pro 2023 version 10.0.0-rc.133 with Philips Hue, without the bridge version 2.0.46.

I'm experiencing two problems:

1. I have added a Hue Dimmer Switch 3th gen (model 9290023986) into Homey via your app. When I want to make a flow where I use "Hue (Long release)" to turn off lights it looks like that the flow also is assigned to the"on/off (short press)". I think it's a error in the app.

2. I have added two motion sensor to Homey:
- 1x Philips Hue Motion sensor (model 9290030675)
- 1x Philips Hue Outdoor motion sensor (model 9290030674)
But after a couple hours the sensors says that they are not accessible (timeout). But the sensors is actually working. But it varies a lot how fast they turn on the lights. Som times it takes only 0,5 sec and sometimes it takes 5 sec. Is this a problem you know about?

**Comment by jorisoft** [comment]
How did you manage to install the Hue outdoor Motion Sensor ? Ich was unable to bind it, it says there is no up to connect to and leave an entry with a name of "unknown zigbee device"..... Any idea ?

**Comment by Olimol1** [comment]
Hi

You need to install this: https://homey.app/da-dk/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/

Be aware of this is the beta/test version of the next version of "Philips Hue without the bridge".

But it works with the Hue Outdoor Sensor.

I hope it helps :-)

Best regards

Oliver

Sendt fra min iPhone

Den 28. jul. 2023 kl. 20.39 skrev jorisoft ***@***.***>:

﻿

How did you manage to install the Hue outdoor Motion Sensor ? Ich was unable to bind it, it says there is no up to connect to and leave an entry with a name of "unknown zigbee device"..... Any idea ?

**Comment by jorisoft** [comment]
Thank you very much it works !

 

Best Oliver

 

Von: Olimol1 ***@***.***> 
Gesendet: Samstag, 29. Juli 2023 09:27
An: JohanBendz/com.philips.hue.zigbee ***@***.***>
Cc: Oliver Renz (Jorisoft GmbH) ***@***.***>; Comment ***@***.***>
Betreff: Re: [JohanBendz/com.philips.hue.zigbee] Dimmer switches and motion sensor problems (Issue #485)

 

Hi 

You need to install this: https://homey.app/da-dk/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/ 

Be aware of this is the beta/test version of the next version of "Philips Hue without the bridge". 

But it works with the Hue Outdoor Sensor. 

I hope it helps :-) 

Best regards 

Oliver 

Sendt fra min iPhone 

Den 28. jul. 2023 kl. 20.39 skrev jorisoft ***@***.*** <mailto:***@***.***> >: 

﻿ 

How did you manage to install the Hue outdoor Motion Sensor ? Ich was unable to bind it, it says there is no up to connect to and leave an entry with a name of "unknown zigbee device"..... Any idea ?
