### ISSUE TITLE
Missing Hue Attract Outdoor wall light

### ISSUE THREAD

**Issue by Nettopp** [sebbebebbe/com.philips.hue.zigbee#487]
Hi, it would be great if you could add support for this lamp: 
https://www.philips-hue.com/en-gb/p/hue-white-and-colour-ambiance-attract-outdoor-wall-light/1746130P7

**Comment by JohanBendz** [comment]
I need an interview to do that. Can you please provide one?

How to interview a device:

Add the device as a generic Zigbee device in Homey
Navigate to https://developer.athom.com/tools/zigbee.
Interview the device, the button for this is to the right of the device in the list of Zigbee units.
Click the copy button/icon to capture the device information.
Paste the copied information above.

**Comment by JohanBendz** [comment]
Without interview I can't add it.. if you still want this addad, please start a new issue with the requested information.
