### ISSUE TITLE
Philips Hue Enrave without bridge is missing in app

### ISSUE THREAD

**Issue by Easton8805** [sebbebebbe/com.philips.hue.zigbee#488]
Hello, I use Homey app Philips Hue, without the bridge and I really miss in the list of lamps ENRAVE model. I am unfortunately not able to pair my ceiling lamps :-( Please, could you help and add ENRAVE lamp into the app? Very appreciated.

**Comment by JohanBendz** [comment]
Hi @Easton8805, I need an interview of the device.
https://tools.developer.homey.app/tools/zigbee
(.../action - interview)

**Comment by Easton8805** [comment]
Hello,

I activate interview for one Enrave light, if it is sufficient.


Best Regards / S pozdravem,
Lukas Zvolanek.


------ Original Message ------
From "Johan Bendz" ***@***.***>
To "JohanBendz/com.philips.hue.zigbee" 
***@***.***>
Cc "Easton8805" ***@***.***>; "Mention" 
***@***.***>
Date 18.10.2023 11:43:27
Subject Re: [JohanBendz/com.philips.hue.zigbee] Philips Hue Enrave 
without bridge is missing in app (Issue #488)
