### ISSUE TITLE
Crashes after update

### ISSUE THREAD

**Issue by villaalstergren** [sebbebebbe/com.philips.hue.zigbee#49]
This has work really good until now. 
Now it just says it s crashed, I've tired to restart the app and restart homey and unplugged homey but same result!

Crash report: 8ad2b1bd-3191-4b80-956f-d6c344e56b16

**Comment by jimmyendt** [comment]
I have the same issue and tried the same! Now my whole house is dark..

Hope you can help !

**Comment by sebbebebbe** [comment]
New version in deployment, will publish as soon as Athom has approvedd it.

**Comment by jimmyendt** [comment]
Thank you so much, hope it will work again !

**Comment by sebbebebbe** [comment]
Should be published now. Please let me know if it works. Otherwise try to downgrade to 1.3.

**Comment by jimmyendt** [comment]
1.4.1 also crashes

Crashreport:
9be685a4-7f2f-4225-92c6-951950eb7be5

I will downgrade to 1.3

**Comment by villaalstergren** [comment]
How do I downgrade,  I only see uninstall?..

**Comment by andreasbeck** [comment]
Still no update, 1.4.1 still crashes, still an angry wife :-)

**Comment by sebbebebbe** [comment]
New version available. Please let me know if it works.
