### ISSUE TITLE
No functional flow cards for Ensis light?

### ISSUE THREAD

**Issue by Eivind100** [sebbebebbe/com.philips.hue.zigbee#491]
Hello!

I have connected my new phillips hue Ensis light to homey pro 2023.

I am new to hue and homey.

I wanted to make a flow with a motion sensor that I have got. However there do not seem to be any flowcards with the Ensis light? Maybe I am mistanken, but I could not find any. I am talking simple cards like "turn on light" or so.

Could it be because it has registered as an unknown device? Or is there no such functionality without gjetting the bridge and official app?

The light itself is easily controlled in the app. Very Nice.

Thx in advance for any answer

**Comment by JohanBendz** [comment]
Hi @Eivind100, sorry for the late answer. Hope you already learnt that support for this device is already in the test version of the app.
