### ISSUE TITLE
Smart Button Battery Low

### ISSUE THREAD

**Issue by Yann843** [sebbebebbe/com.philips.hue.zigbee#492]
Hello,
I'm new to the Homey community and I started by putting all my Philips hue equipment on my Homey box and for the moment. I only have one problem. 
I have 5 smart buttons and all of them have low battery. I changed the batteries and the problem is still there. Is there a way to get the true status of the battery please?
Can you tell me if I need any other additional information so that you can understand my problem?
For information, I tried to re-equip, restart the box and it's still the same 
Thanks for your help

**Comment by JohanBendz** [comment]
Hi @Yann843, in next update this device will also have measure battery functionality, your will have to repair or re-pair the device(s) to add the feature.
