### ISSUE TITLE
On homey version 2.0.35. In changelog 2.0.45

### ISSUE THREAD

**Issue by Ronm10** [sebbebebbe/com.philips.hue.zigbee#498]
Hi I have a question. I have the tap and dial and would like to use 2.0.45 but cannot get it on homey and in the community store I cannot get it at the moment. It looks like there is a problem. 

When wil version 45 be available on homey

Thanks 
Ron

**Comment by JohanBendz** [comment]
Try this: https://homey.app/en-gb/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/
