### ISSUE TITLE
Add support for Philips Hue Tap Dial Switch

### ISSUE THREAD

**Issue by Mikkelkuster** [sebbebebbe/com.philips.hue.zigbee#499]
Pls add support for the new Hue Tap Dial Switch - as I see it, its not compatible with any other Hue products

Thanks - and thanks for your hard work!
![image](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/146445331/55756336-9730-4921-ae0a-9b62115ea8d5)

**Comment by jacc08** [comment]
Changelog states it was added in 2.0.45 but I can't seem to find it.

**Comment by JohanBendz** [comment]
Hi, try this version: https://homey.app/en-gb/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/

**Comment by Mikkelkuster** [comment]
Super - thanks!
