### ISSUE TITLE
Cannot add Hue white 

### ISSUE THREAD

**Issue by Vincent75b** [sebbebebbe/com.philips.hue.zigbee#5]
Thanks for this plugin! Waited a long time for this...

The Hue dimmer could be added without problems, but I can't connect the Hue White lightbulb. I did reset the remote (was paired) and even tried a new buld straight out of the box, but no success.

Noticed on the Github page that there are multiple types of this lamp (LW...). Unfortuntaly, I cannot find which version I have, not on the box and using google. Philips model number  is 9290011370a. 

Further specs (printed on the bulb): 806 Lumen, A60, 9W, 54mA. Sold sogether with dimmer.

**Comment by sebbebebbe** [comment]
Hi @Vincent75b,

Add the bulb as a generic zigbee device and then klick the properties icon on the device and send me the data. I can then add the bulb to the definition if missing.

**Comment by Vincent75b** [comment]
Hi S, for some reason, I got it to work a few weeks after the post (same procedure). Maybe an update fixed it? (I could not find the dates of the updates).
So, you can close this issue ;-)
Thanks again for the plugin!

**Comment by sebbebebbe** [comment]
Thanks for an answer on this and not just another.

I solved it and forever silence :)
