### ISSUE TITLE
Hi my app is always crashing

### ISSUE THREAD

**Issue by felho001** [sebbebebbe/com.philips.hue.zigbee#500]
the app always crashing and I need restart because the devices not available and the restart always fix it. Here is the diagnostic report: 543e13e5-2a1b-4ae4-bbfa-6100d35fbc58

**Comment by Theppan** [comment]
I experies the same. Crashes continously.

**Comment by JohanBendz** [comment]
Hi @felho001 and @Theppan, is this still an issue? If it it, please try the latest test version and send me a diagnostic report and post the id here.
