### ISSUE TITLE
Hue as a deafault zigbee device

### ISSUE THREAD

**Issue by cautje** [sebbebebbe/com.philips.hue.zigbee#501]
Hello, i have added 2 new Hue bulps.
Kan these be addes to the Homey app?

THX!

![image](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/19371264/eead0100-69f8-4c87-b21a-305bca43538f)

**Comment by JohanBendz** [comment]
Hi @cautje, try this version: https://homey.app/en-gb/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/
