### ISSUE TITLE
SML004 Philips Hue Outdoor Sensor (model 9290030674)

### ISSUE THREAD

**Issue by reneeteunissen-nl** [sebbebebbe/com.philips.hue.zigbee#503]
Hi,

I'm trying to connect my outdoor SML004 but it is not detected as one. What might go wrong? This is a native Philips device thats works propely using home-assistant. 

Kind regards
Renee Teunissen

63bf0318-d513-4264-a808-2f147441e4ff

![renee teunissen_at_gmail com_Hue_SM004](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/95658050/295ab25f-2840-4c60-a1e0-838d2b419bd7)

**Comment by reneeteunissen-nl** [comment]
In your code, it looks like the device on photo SM002. can it be the same device?

**Comment by JohanBendz** [comment]
Hi there @reneeteunissen-nl, try this version: https://homey.app/en-gb/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/

**Comment by reneeteunissen-nl** [comment]
Hoi Johan,

Thank you! Its detected and shows movement and so on in de dialog.
