### ISSUE TITLE
New Philips device: Door Secure Sensors.

### ISSUE THREAD

**Issue by Markroadrace** [sebbebebbe/com.philips.hue.zigbee#504]
Hi!,
Philips started a new line, Security. Part of that are the Philips Door Secure Sensors, https://www.philips-hue.com/nl-nl/p/hue-secure-contact-sensor/8719514487345
Is it possible to add the new Philips Door Secure Sensors so that we can start a flow in Homey when they open? 

Thanks
Mark

**Comment by WeekendEric** [comment]
I second the wish of adding Philips Hue Secure Contact Sensor.

Thanks 
Helge

**Comment by JohanBendz** [comment]
Hi @Markroadrace / @WeekendEric
I need an interview to do that. Can you please provide one?

How to interview a device:

Add the device as a generic Zigbee device in Homey
Navigate to https://developer.athom.com/tools/zigbee.
Interview the device, the button for this is to the right of the device in the list of Zigbee units.
Click the copy button/icon to capture the device information.
Paste the copied information above.

**Comment by nickdekorte** [comment]
"ids": {
    "modelId": "SOC001",
    "manufacturerName": "Signify Netherlands B.V."
  },
  "endpoints": {
    "ieeeAddress": "00:17:88:01:0d:81:8c:f4",
    "networkAddress": 9805,
    "modelId": "SOC001",
    "manufacturerName": "Signify Netherlands B.V.",
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 9805,
        "_reserved": 24,
        "endpointId": 2,
        "applicationProfileId": 260,
        "applicationDeviceId": 2128,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          0,
          1,
          3,
          64518
        ],
        "outputClusters": [
          25,
          0,
          3,
          6
        ]
      }
    ],
    "deviceType": "enddevice",
    "receiveWhenIdle": false,
    "swBuildId": "2.67.9",
    "capabilities": {
      "alternatePANCoordinator": false,
      "deviceType": false,
      "powerSourceMains": false,
      "receiveWhenIdle": false,
      "security": false,
      "allocateAddress": true
    },
    "extendedEndpointDescriptors": {
      "2": {
        "clusters": {
          "basic": {
            "attributes": [
              {
                "id": 0,
                "name": "zclVersion",
                "value": 8
              },
              {
                "id": 1,
                "name": "appVersion",
                "value": 2
              },
              {
                "id": 2,
                "name": "stackVersion",
                "value": 1
              },
              {
                "id": 3,
                "name": "hwVersion",
                "value": 1
              },
              {
                "id": 4,
                "name": "manufacturerName",
                "value": "Signify Netherlands B.V."
              },
              {
                "id": 5,
                "name": "modelId",
                "value": "SOC001"
              },
              {
                "id": 6,
                "name": "dateCode",
                "value": "20221201"
              },
              {
                "id": 7,
                "name": "powerSource",
                "value": "battery"
              },
              {
                "id": 8,
                "name": "appProfileVersion",
                "value": 0
              },
              {
                "id": 9
              },
              {
                "id": 10
              },
              {
                "id": 11
              },
              {
                "id": 16384,
                "name": "swBuildId",
                "value": "2.67.9"
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 3
              }
            ],
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "powerConfiguration": {
            "attributes": [
              {
                "id": 32,
                "name": "batteryVoltage",
                "value": 29
              },
              {
                "id": 33,
                "name": "batteryPercentageRemaining",
                "value": 200
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 2
              }
            ],
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "identify": {
            "attributes": [
              {
                "id": 0,
                "name": "identifyTime",
                "value": 0
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 2
              }
            ],
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        },
        "bindings": {
          "basic": {
            "attributes": [
              {
                "id": 0,
                "name": "zclVersion",
                "value": 8
              },
              {
                "id": 1,
                "name": "appVersion",
                "value": 2
              },
              {
                "id": 2,
                "name": "stackVersion",
                "value": 1
              },
              {
                "id": 3,
                "name": "hwVersion",
                "value": 1
              },
              {
                "id": 4,
                "name": "manufacturerName",
                "value": "Signify Netherlands B.V."
              },
              {
                "id": 5,
                "name": "modelId",
                "value": "SOC001"
              },
              {
                "id": 6,
                "name": "dateCode",
                "value": "20221201"
              },
              {
                "id": 7,
                "name": "powerSource",
                "value": "battery"
              },
              {
                "id": 8,
                "name": "appProfileVersion",
                "value": 0
              },
              {
                "id": 9
              },
              {
                "id": 10
              },
              {
                "id": 11
              },
              {
                "id": 16384,
                "name": "swBuildId",
                "value": "2.67.9"
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 3
              }
            ],
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "identify": {
            "attributes": [
              {
                "id": 0,
                "name": "identifyTime",
                "value": 0
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 2
              }
            ],
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "ota": {},
          "onOff": {
            "attributes": [],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          }
        }
      }
    }
  }

**Comment by nickdekorte** [comment]
@JohanBendz here you go!

**Comment by MrBeefDev** [comment]
+1 would love functionality on these door sensors.

**Comment by nickdekorte** [comment]
Bump

**Comment by NLCULC** [comment]
Yes please, I would like this as well.

**Comment by betsim** [comment]
+1
