### ISSUE TITLE
Where can I find Power-on behaviour?

### ISSUE THREAD

**Issue by galapiat** [sebbebebbe/com.philips.hue.zigbee#505]
Hi
The scenario could be this one
- all Philips hue lights are off
- there is a power shutdown
- the power is re-establish
- all the lights are on!

Is there any way find Power-on behaviour?
With 3 options
- Return to previous state (that is for me the most important and should be the defaut)
When your light becomes powered, it will restore to the previous state. If your light was off before the power cut, it will stay off. If your light was on, it will restore to the previous colour/brightness.
- Switch on to previous state
When your light becomes powered, it will switch on and restore to the previous colour/brightness. This option is similar to Return to previous state, but the difference is that this will always switch on the light, even if your light was off before the power cut.
- Custom
You can select a custom colour/brightness for your light. When your light becomes powered, it will switch on to your custom colour/brightness.

Many thanks

**Comment by JohanBendz** [comment]
This is supported in the test version of the app.
