### ISSUE TITLE
Being Ceiling Light issue

### ISSUE THREAD

**Issue by Xybertecnic** [sebbebebbe/com.philips.hue.zigbee#509]
Hi, I am trying to add a Being Ceiling light, and it adds fine, but after adding I always get a message that the light is not available, any idea why?

![2023-10-24_113613](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/131592989/66a3f0b3-5126-4cac-a35e-ee0cc8cad376)
![2023-10-24_113815](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/131592989/0becb51d-06f0-4488-af1c-e53f3a551c05)

**Comment by RonaldNeed** [comment]
Workaround: (works for me) After adding and restarting the App and "Being Ceiling" is working.

**Comment by Xybertecnic** [comment]
I actually tried to restart the app, but it didn't change anything for me unfortunately

**Comment by RonaldNeed** [comment]
Just to be sure. Did you restart the "Philips Hue, without the bridge" only?

**Comment by Xybertecnic** [comment]
> Just to be sure. Did you restart the "Philips Hue, without the bridge" only?

have restarted only the app and also homey itself, no difference

**Comment by JohanBendz** [comment]
Hi @Xybertecnic, is this still an issue? If so please restart the app and try to use the device, then send me a diagnostic report.

**Comment by Xybertecnic** [comment]
Just removed it from hue and added it directly to Homey and the issue seems gone, so I guess it is solved, thanks
