### ISSUE TITLE
LST001 crashes due to import syntax

### ISSUE THREAD

**Issue by pardeike** [sebbebebbe/com.philips.hue.zigbee#51]
Hi,

I tested LST001/driver.js with the following change and it does not crash anymore:

```js
// import { ZigBeeXYLightDevice } from "homey-meshdriver";
const ZigBeeXYLightDevice = require('homey-meshdriver').ZigBeeXYLightDevice;
```

**Comment by pardeike** [comment]
Also, 
it seems that my LST001 has the cold-warm color setting but of course it does not support it because its a simple rgb color stripe.

**Comment by sebbebebbe** [comment]
Hi thanks for the info! Greatly appreciated!

New beta version will be available shortly.

**Comment by pardeike** [comment]
Thanks for the fast feedback!
