### ISSUE TITLE
Impossibly to associate a light hue e27 color and ambiance 

### ISSUE THREAD

**Issue by gicro** [sebbebebbe/com.philips.hue.zigbee#510]
Hi,
i think to ask you an upgrade a hue light devices in list application.
Because I cannot associate a light color and ambiance from Philipe hue.
This is a id device : LCA004
May be, it is a new product ? The application know not this id ?
Thank fir your help
(I am sorry for my English)
Best regard
Gilles

**Comment by JohanBendz** [comment]
Try this version: https://homey.app/en-gb/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/
