### ISSUE TITLE
Philips Hue Tap Dial Switch conect to homey 

### ISSUE THREAD

**Issue by kubakotlik** [sebbebebbe/com.philips.hue.zigbee#511]
Hello , I would like to connect a Philips Hue Tap Dial Switch to my home (for 2023) unfortunately there is no support for it yet, will there ever be support for this driver ? thank you for the answer

**Comment by wojogun** [comment]
when looking to the changlog it should have been added already.

> 2.0.4510. Juli 2023
> Added support for Tap Dial Switch

but u r right, i can't add it either. only options are Dimmer Swith Gen 1+2, Dimmer Swith Gen 3 and Smart Button

Unfortunatly the current Homey "Philips Hue, without the bridge"-App Release is still v2.0.35

**Comment by jacc08** [comment]
With the test version the tap dial is working

**Comment by kubakotlik** [comment]
how do I install the test version in homey pro  2023?

**Comment by JohanBendz** [comment]
Test version: https://homey.app/en-gb/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/
