### ISSUE TITLE
Friend of Hue

### ISSUE THREAD

**Issue by Xybertecnic** [sebbebebbe/com.philips.hue.zigbee#513]
Any chance in adding support for Friends of Hue switches?

**Comment by JohanBendz** [comment]
Not planned. what devices are you looking to have added?

**Comment by Xybertecnic** [comment]
I have the Gira friends of Hue switches in my house which are now directly connected to the lights via the Hue hub

**Comment by JohanBendz** [comment]
Hi @Xybertecnic, as those products use Battery-Less technology I am unable to add them to Homey. This platform simply does not support them. If this changes I'l have a look at it.

**Comment by Stavorinus** [comment]
I was wondering, because it's zigbee green power right it's a hard one to do. But the homey pro 2023 supports the zigbee 3.0 specs so it should be possible right?
