### ISSUE TITLE
Outdoor Sensor

### ISSUE THREAD

**Issue by magnuse87** [sebbebebbe/com.philips.hue.zigbee#515]
When trying to add the Hue Outdoor sensor I am getting an error that says no app can be found for the device. I have tried both the motion sensor and the occupancy sensor with no luck. The sensor flashes green indicating a successful pairing, but is added as a generic zigbee device.

**Comment by phred73** [comment]
For you guys who doesn’t get luminescence & temperature readings, have you tried interviewing the unit on developer pages? I did and my unit is now fully functional (as it seems). 
https://tools.developer.homey.app/tools/zigbee

**Comment by dunstarn** [comment]
Did you find a solution for this problem? It was the same for me, then I deleted the app (Philips Hue, without the bridge) and tried to reinstall it. But now I can't install it. "Timeout after 10000ms", "Disconnected", Homey offline" or "Ping timeout"... I've tried to install some random apps and succeeded so I don't think there is any problem with my HP23.

**Comment by magnuse87** [comment]
Yes I did. I realized that the stable version was quite old. If you add "/test" to the end of the url on the homey app store you can install the latest beta. After I did that I was able to include the outdoor sensor. It has been stable for a few days now so it seems that did the trick. This is however the only hue sensor I have, so you might have troubles with other sensors.
