### ISSUE TITLE
Is it possible to replicate the "Use serial number" feature to add challenging lights?

### ISSUE THREAD

**Issue by AndrewFarley** [sebbebebbe/com.philips.hue.zigbee#518]
I have a few Philips Hue devices which refuse to add to Homey and I'd prefer to not have to use a Hue Hub.  These devices similarly do not auto-add to the Hue Hub and require that I search for them using their "serial number".  Only then do they add to the Hue Hub properly.  Is there an equivalent in Homey either via Zigbee directly or via this App?

I'm imagining you adding a new item to the list of available items you support as a new icon, and when you click it, it asks the user for the serial number(s) to scan for (like the Hue app does) and then it tries to force-add those.

I'm having basically this issue: https://github.com/JohanBendz/com.philips.hue.zigbee/issues/207

**Comment by JohanBendz** [comment]
No, Athom have control over the pairing progress and this is not something the app can change. Good idea though, bring it to Athoms attention.
