### ISSUE TITLE
Crash after adding SML001 motion sensor

### ISSUE THREAD

**Issue by pardeike** [sebbebebbe/com.philips.hue.zigbee#52]
Here is my console log from running 1.4.3:
<https://gist.github.com/pardeike/3ecb015bdf6f11eaf40bb7cb6327f4a3>

That's after adding a motion sensor SML001 to my Homey 2.0.0rc8 - it never triggers.

**Comment by pardeike** [comment]
After installing 2.0.0rc9, the motion sensor is again working in bridge mode but adding it via this app still does not show any values at all.

**Comment by sebbebebbe** [comment]
Should be solved with v2.0.5-rc3

**Comment by pardeike** [comment]
Confirmed. Thank you
