### ISSUE TITLE
Smart Plug not recognized

### ISSUE THREAD

**Issue by aslakrin** [sebbebebbe/com.philips.hue.zigbee#520]
It still works since I can turn it on and off, but it's via the generic device widget/interface.

See attached for screenshot of vendor, mac etc.

![Screenshot_20231124_160516_Homey](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/901730/dfd66417-f073-4a9c-85fd-bf2d0aa97bae)

**Comment by JohanBendz** [comment]
Hi, this is supported in the latest test version. (add /test to the app's url)
