### ISSUE TITLE
Problem med installation

### ISSUE THREAD

**Issue by dunstarn** [sebbebebbe/com.philips.hue.zigbee#521]
Hej Johan och andra.

Jag köpte häromdan en Philips Hue Outdoor Sensor och installerade följaktligen "Philips Hue, without the bridge" och installerade enligt instruktioner. Där stötte jag på patrull. Ett meddelande dök upp med texten 
"Det verkar som om du inte har någon app installerad för den här enheten..." och lade därefter till min sensor som "Zigbee-enhet". 

Jag tänkte att det kanske var något fel vid installation av appen då det stod "Timeout after 10000ms" men ändå dök den upp bland mina appar. Jag avinstallerade appen och skulle installera den på nytt. Nu är det lögn i helvete att installera den. Jag har säkert försökt över 200 gånger utan att få in den igen.
"Timeout after 10000ms", "Ping timeout", "Disconnected", "Homey offline" är felmeddelanden som dyker upp.

Jag testade att installera några random appar och det fungerade direkt. Så jag vill ändå inte tro att problemet enbart ligger i min HP23. Jag har förvisso detta problemet med exempelvis "Chronograph"-appen också, men som sagt... andra appar installeras utan problem.

Jag har otaligt många gånger testat att starta om min HP23, kopplat upp den enbart över ethernet, dragit ur strömmen under drygt 10 minuter, men inget hjälper... 

Någon idé?

Tack,
mvh Johan.

**Comment by JohanBendz** [comment]
Hej Johan, hoppas det här löste sig för dig. Den enheten har bara stöd i test versionen av appen. (lägg till /test efter appens url). Det kommer en större uppdatering inom kort. Ledsen för sent svar men det haglar in ärenden på alla sätt och tiden är begränsad.. :(
