### ISSUE TITLE
Hue Sensors Homey

### ISSUE THREAD

**Issue by eddimello** [sebbebebbe/com.philips.hue.zigbee#523]
JohanBendz
<img width="422" alt="Scherm­afbeelding 2023-12-02 om 12 30 42" src="https://github.com/JohanBendz/com.philips.hue.zigbee/assets/152695275/5bb23402-b825-4b5b-af06-7fbfabbc7368">
,

I installed 2 HUE sensors and they work well, butt one small problem.

I changed the batteries butt the level indicator still keep saying its 1%.

I used this battery everywhere and also in other sensors with no problem.

Just changed to other batteries again with no result. Why doesn't he see the exact battery level?

Thanks

**Comment by JohanBendz** [comment]
Thanks for the info, looks like a few devices of different kind have this issue. I'll look into it.

**Comment by eddimello** [comment]
Thanks Johan

**Comment by JohanBendz** [comment]
Please try the new version. If problem persists, please start a new issue and include a diagnostic report from the app.
