### ISSUE TITLE
Hue Motion Sensor stops working after include / repair

### ISSUE THREAD

**Issue by notbuch** [sebbebebbe/com.philips.hue.zigbee#528]
Homey Pro 2023: After repair or include process the motion sensor have correct history but homey show them as buggy after a few hours (even tho the sensor stays right next to homey):

histroy ok screenshot #1 (even apears in the developer tools as working and routet correctly)

![image](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/85675943/ba506a27-fc93-4df0-ab7f-92bc1e6331ee)

But this bug leads to not being able to use it in flows:

![image](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/85675943/6f3d2100-4317-49a3-8dd8-1cca5a4e19e7)

![image](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/85675943/2e5b2ddc-aee6-480a-bd54-db8b023cf6fc)

**Comment by notbuch** [comment]
sorry, some other hue devices have the same issue: like the 4 buttons dimmer. on / of works suprisingly. but dimming don't. So some of the commands are interpreted, others not (there is a battery alert but it's new battery):
![image](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/85675943/37513c99-e96c-4b93-81ac-fcb0f71a7913)

I pressed the diagnotic button 34869be3-df23-480e-8725-74ecc6ccdd68

**Comment by JohanBendz** [comment]
New version is out, hopefully works better.
