### ISSUE TITLE
Hue Outdoor motion sensor

### ISSUE THREAD

**Issue by PeterK58** [sebbebebbe/com.philips.hue.zigbee#529]
Hi, within the (Homey) app the hue outdoor sensor is installed as a "Unknown Zigbee Device" and does not work. I have tried several times , no succes.

**Comment by hansrika** [comment]
Hi. The same thing happened to me. I installed the TEST-version and that found the outdoor sensor and it works.
It was found as an "Outdoor Occupancy sensor" instead of an "Outdoor sensor". I don't know the difference.

Hopefully the normal version will be updated.

**Comment by PeterK58** [comment]
Hi Hansrika,
My version of "Phillips Hue, Hue Whithout the bride" is 2.0.35 on Homey pro Early 2023.
Where do i find this "TEST-version" ?

**Comment by PeterK58** [comment]
Hi, Hansrika,
I found the "test version", installed it,  It appears as "Outdoor Occupancy sensor" and the Motionsesor works just fine !

https://homey.app/nl-nl/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/
