### ISSUE TITLE
Temperature setting

### ISSUE THREAD

**Issue by Jugge72** [sebbebebbe/com.philips.hue.zigbee#53]
Hi, my lightstrip came up green after last update 1.4.3. think it's something wrong with temperature settings.
With temperature setting at 65% (warmwhite), it goes green.
Worked ok with 1.4.2

**Comment by sebbebebbe** [comment]
Hi yes, I noticed this issue a few days back on my RGB bulb aswell. I will make a new release with a fix for it when i have the time.

It is my highest priority right now. FYI
