### ISSUE TITLE
Add new device ID of E14 White luster (LWU002)

### ISSUE THREAD

**Issue by rvdeijk** [sebbebebbe/com.philips.hue.zigbee#530]
@JohanBendz 
Homey forum: https://community.homey.app/t/app-pro-philips-hue-zigbee-without-the-bridge/29734/885?u=rvdeijk

Could you add the E14 Hue white luster (LWU002): Philips website: https://www.philips-hue.com/nl-nl/p/hue-white-kogellamp---e14-slimme-lamp/8719514356696#overview

I think it’s another ID of the Bulb E14 P45 White.

Zigbee interview code:
`"ids": {
    "modelId": "LWU002",
    "manufacturerName": "Signify Netherlands B.V."
  },
  "endpoints": {
    "ieeeAddress": "00:17:88:01:0d:b7:8c:cf",
    "networkAddress": 11793,
    "modelId": "LWU002",
    "manufacturerName": "Signify Netherlands B.V.",
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 11793,
        "_reserved": 30,
        "endpointId": 11,
        "applicationProfileId": 260,
        "applicationDeviceId": 257,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          0,
          3,
          4,
          5,
          6,
          8,
          4096,
          64515,
          64514,
          64516
        ],
        "outputClusters": [
          25
        ]
      },
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 11793,
        "_reserved": 10,
        "endpointId": 242,
        "applicationProfileId": 41440,
        "applicationDeviceId": 97,
        "applicationDeviceVersion": 0,
        "_reserved1": 0,
        "inputClusters": [],
        "outputClusters": [
          33
        ]
      }
    ],
    "deviceType": "router",
    "receiveWhenIdle": true,
    "swBuildId": "1.104.2",
    "capabilities": {
      "alternatePANCoordinator": false,
      "deviceType": true,
      "powerSourceMains": true,
      "receiveWhenIdle": true,
      "security": false,
      "allocateAddress": true
    },
    "extendedEndpointDescriptors": {
      "11": {
        "clusters": {
          "basic": {
            "attributes": [
              {
                "id": 0,
                "name": "zclVersion",
                "value": 8
              },
              {
                "id": 1,
                "name": "appVersion",
                "value": 2
              },
              {
                "id": 2,
                "name": "stackVersion",
                "value": 1
              },
              {
                "id": 3,
                "name": "hwVersion",
                "value": 1
              },
              {
                "id": 4,
                "name": "manufacturerName",
                "value": "Signify Netherlands B.V."
              },
              {
                "id": 5,
                "name": "modelId",
                "value": "LWU002"
              },
              {
                "id": 6,
                "name": "dateCode",
                "value": "20230403"
              },
              {
                "id": 7,
                "name": "powerSource",
                "value": "mains"
              },
              {
                "id": 8,
                "name": "appProfileVersion",
                "value": 0
              },
              {
                "id": 9
              },
              {
                "id": 10
              },
              {
                "id": 11
              },
              {
                "id": 16384,
                "name": "swBuildId",
                "value": "1.104.2"
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 3
              }
            ],
            "commandsGenerated": "UNSUP_GENERAL_COMMAND",
            "commandsReceived": "UNSUP_GENERAL_COMMAND"
          },
          "identify": {
            "attributes": [
              {
                "id": 0,
                "name": "identifyTime",
                "value": 0
              },
              {
                "id": 65533,
                "name": "clusterRevision",
                "value": 2
              }
            ]
          },
          "groups": {},
          "scenes": {},
          "onOff": {},
          "levelControl": {},
          "touchlink": {}
        },
        "bindings": {
          "ota": {}
        }
      },
      "242": {
        "clusters": {},
        "bindings": {}
      }
    }
  }`

**Comment by JohanBendz** [comment]
Added to next version.

**Comment by rvdeijk** [comment]
> Added to next version.
@JohanBendz 
To which version? Cause 2.0.48 does not have the support yet.
