### ISSUE TITLE
PHILIPS Hue without the bridge don't work with outdoir sensor

### ISSUE THREAD

**Issue by BJORNSJ** [sebbebebbe/com.philips.hue.zigbee#531]
Hello Johan
There must be a serious bug in the software for Philips Hue outdoor sensor (Philips Hue without the bridge) . Installation looks great but it must be mixed up with another product. 
Functionality after install looks like any zigbee lamp not a sensor! See attached screen shots. 
![Screenshot_20231210_164052_app homey](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/153444867/a4e5670c-2875-4e71-a3da-f60ab44ded0c)
![Screenshot_20231210_164106_app homey](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/153444867/35f84038-b16e-47da-b318-66c3aef9ceab)

![Screenshot_20231210_161559_app homey](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/153444867/52f8ae3c-62da-4b0e-9ac7-4779526953e3)

Thanks in advance! 
Björn bjorn@sjostrom.com

**Comment by JohanBendz** [comment]
Hi @BJORNSJ 
This icon means the device is added as a generic Zigbee unit, NOT using the driver in the app.
![image](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/34488771/b7a2867f-b3bf-4d4e-8e48-56eb684c7266)
Try the test version of the app (add /test to the url)
