### ISSUE TITLE
HUE DIMMER (RWL021) keeps reporting empty battery

### ISSUE THREAD

**Issue by shaarkys** [sebbebebbe/com.philips.hue.zigbee#532]
Hi, 
after repair (which I found later was caused by empty battery), I keep getting battery empty, even it's not (replaced twice and even measured voltage) .
Tried to perform interview and it reports also battery state full but app keep reporting empty. 
Any idea why ?

Diag : a86f3f95-4fd0-4e0c-a7ff-24f2b1008552

![obrazek](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/14859895/8bec3c8c-dda2-4f86-b660-741af4dda844)

Another one still reports battery OK ... ?

![obrazek](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/14859895/71ad9d8c-8cef-43cc-ba5e-b4ab4905d8b3)

**Comment by JohanBendz** [comment]
Thanks for the info, looks like a few devices of different kind have this issue. I'll look into it.

**Comment by andyp2234** [comment]
My hue v3 dimmer shows up but can't do anything with it

**Comment by JohanBendz** [comment]
Should be fixed in upcoming release.
