### ISSUE TITLE
2.0.48 - Hue Wall Rocker Switch

### ISSUE THREAD

**Issue by joeyv2** [sebbebebbe/com.philips.hue.zigbee#535]
Hi

- Adding the module and setting dual pushbutton
-  Create flow 1 for button 1
- Create flow 2 for button 2
When pressing a button launches the 2 flows at the same time

**Comment by jeroendew** [comment]
Same here with the dual rocker type

**Comment by christiaandewit** [comment]
Me three. Dual push button starts both flows at once. 
Is there an estimated release date for an updated test release (or even a new stable version)?

**Comment by JarnoGr** [comment]
For me the same. No matter which button is pushed, both are activated

**Comment by christiaandewit** [comment]
It seems like they had the same problem in Home Assistent. Maybe the solution on this website works for Homey too: [https://rudd-o.com/linux-and-free-software/how-to-use-the-philips-hue-wall-switch-module-with-push-button-wall-switches-in-home-assistant](https://rudd-o.com/linux-and-free-software/how-to-use-the-philips-hue-wall-switch-module-with-push-button-wall-switches-in-home-assistant)

**Comment by JohanBendz** [comment]
Fixed in next release, devices may have to be paired again

**Comment by christiaandewit** [comment]
@JohanBendz that’s great! When is the next release planned to be published?
