### ISSUE TITLE
Outdoor Occupancy sensor LED indicator lights up even though inactivated

### ISSUE THREAD

**Issue by hansrika** [sebbebebbe/com.philips.hue.zigbee#536]
Hi and thanks for your app!

Hue Outdoor Occupancy sensor with firmware 2.53.6 and "Philips Hue, without the bridge" version 2.0.48 activates the "LED indicator" and blinks red when detecting motion, even though I have inactivated it in the app advanced settings.

I don't want it to blink red when detecting motion.

It doesn't happen every time motion is detected and it was first noticed after a day or so.

Is this fixable?

Kind regards,

/H

**Comment by JohanBendz** [comment]
Hi @hansrika, please send a diagnostic report when you notice this next time.
