### ISSUE TITLE
Add support for tap dial switch

### ISSUE THREAD

**Issue by tomasmriz** [sebbebebbe/com.philips.hue.zigbee#537]
Hi, 

would it be possible to add support for Hue tap dial switch.

https://www.philips-hue.com/en-us/p/hue-tap-dial-switch/046677578800#overview

thanks a lot.

Tomas

**Comment by jeroendew** [comment]
It's already supported in the test version https://homey.app/nl-nl/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/
