### ISSUE TITLE
Philips Hue outdoor sensor is not recognized in the Homey Pro 2023.

### ISSUE THREAD

**Issue by HRHX11** [sebbebebbe/com.philips.hue.zigbee#538]
Hi,

Philips Hue outdoor sensor is not recognized in the Homey Pro 2023.
The Philips Hue without the Bridge app has been installed.
During Installation the following notification:
Add a Zigbee device.
.....
Unknown Zigbee device. No app has been installed yet. 
That's why it's been added as an unknown device.

Installation as a Zigbee device: The same result.

Is there a Solution?

**Comment by JohanBendz** [comment]
https://homey.app/sv-se/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test

**Comment by HRHX11** [comment]
Hi,
Installation was succesful.

Thanks
