### ISSUE TITLE
add support for hue white ambience filament e27 g125

### ISSUE THREAD

**Issue by Godart-gouda** [sebbebebbe/com.philips.hue.zigbee#539]
I can not find the right pick for my new Philips hue white ambience e27 g125. Both picks the filament g125 e27 and bulb white ambience e27 give me an unknown zigbee device that does control the light but which i can not use in a flow
EAN code 8719514301542 product number 929002478101

**Comment by JohanBendz** [comment]
Already in the test version, will be in live soon.
