### ISSUE TITLE
Dial switch unstable.

### ISSUE THREAD

**Issue by git-jb1975** [sebbebebbe/com.philips.hue.zigbee#541]
With the version 2.0.48 sometimes the dial switch is not working anymore. I have repair it and reconnect to homey with the reset button. After that everything is working again. (also the flows.) This happend with earlier versions with the dial switch but maybe can you fix this before you make it final. thanks!!

**Comment by JohanBendz** [comment]
Hi @git-jb1975. if you still experience this please get back to me with a diagnostic report id.
