### ISSUE TITLE
Missing support 

### ISSUE THREAD

**Issue by Kballe** [sebbebebbe/com.philips.hue.zigbee#543]
Dear @JohanBendz 

I’m missing support for the latest versions of the Motion Sensor Product id:SML003 - model 9290030675, Outdoor motion sensor Product id: SML003 - model 9290030674 

Are you able to add support ?

best regards

Kristian Balle

**Comment by PalRist** [comment]
Same issue here! Would be great if you could add support

**Comment by JohanBendz** [comment]
@PalRist / @Kballe Use this version: https://homey.app/en-us/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/
