### ISSUE TITLE
Hue Dimmer v3 installs in Homey Pro 2023 

### ISSUE THREAD

**Issue by andyp2234** [sebbebebbe/com.philips.hue.zigbee#544]
install Hue Dimmer v3 into homey Pro 2023 through Philips Hue without the bridge but can't do anything with it

**Comment by AllSeeingGoatWizard** [comment]
I have the same issue. Connected fine but the app says that nothing can be done with the device. 

Using the latest 2.0.48

**Comment by JohanBendz** [comment]
@andyp2234 / @AllSeeingGoatWizard, please send me a diagnostic report from the app after using the device. Get back with the report id.

**Comment by JohanBendz** [comment]
A new version is soon out, this works for me but hopefully the fix makes it work also for you.
