### ISSUE TITLE
Hue Outdoor Sensor not possible to add

### ISSUE THREAD

**Issue by Ab101090** [sebbebebbe/com.philips.hue.zigbee#545]
When adding a Hue Outdoor motion sensor I get message saying no app for homey, added as a general Zigbee device. Tried both versions of the sensor available (occupancy and motion) in the app when added. Any suggestions?

**Comment by RiBo68-1** [comment]
Same issue with both the Outlook sensor AND the new indoor sensor.

**Comment by RiBo68-1** [comment]
> Same issue with both the Outlook sensor AND the new indoor sensor.

It seems that the official app store version is (very) old in comparison to updates. Installing the latest (experimental) version solved all problems. 
Why is the app store so far behind?

**Comment by Erikmol41** [comment]
Welke versie heb ik dan nodig..en waar kan ik die vinden ?

**Comment by RiBo68-1** [comment]
Ik heb de testversie geïnstalleerd. Deze werkt vooralsnog probleemloos.
https://homey.app/nl-nl/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/

**Comment by Erikmol41** [comment]
Bij mij werkt hij nu ook naar behoren 🎉

**Comment by Ab101090** [comment]
Hi,
See this was marked as completed and tried to add again. Reset the sensor
and trying to add with both versions of the sensor that shows in the app,
but get error saying there is no app installed for this unit and that its
added as a general Zigbee device.

tir. 27. feb. 2024 kl. 00:20 skrev Johan Bendz ***@***.***>:
