### ISSUE TITLE
Support Hue wall switch

### ISSUE THREAD

**Issue by pvkerkum** [sebbebebbe/com.philips.hue.zigbee#547]
Hi,
Great app. 
All my Hue lights are much more stable than via Hue bridge.
Only missing support for the wall switch, is that correct and maybe coming?

Thanks,
Paul

**Comment by christiaandewit** [comment]
Hi Paul, the test version of this app has support for the wall switch (and some other devices). However, some bugs have been reported. I too am waiting for them to be fixed. Too bad I don't have the skills to fix them myself...

**Comment by MisterRenHoek** [comment]
Hej, there is a new version of the Hue Wall Switch: RDM004.
Can you please add the new ID?
Unfortunately I can't get an interview to run.
Thanks

**Comment by JohanBendz** [comment]
Hi all. Added to test version but there are some issues I have to fix.
@MisterRenHoek, I really do need an interview.. Looking at other platforms I don't think just adding the code will work.
Try pushing the pair button on the device every other second while it's being interviewed.

**Comment by ReneV1971** [comment]
I am new here but have the same issue with RDM004. I only want to let you know, that if I ad the RDM004 to the hue bridge, the switch still is not found by Homey Pro. Homey connects to the bridge but the RDM004 is not found. Also my new Outdoor sensor wasn’t found by your app. However, connecting the Outdoor sensor to the hue bridge solved this problem. It’s strange that the same work around doesn’t work with the RDM004. Same is true when accessing these sensors by using apple’s home kit or google, the outdoor sensor is found by the apps, but the wall switch isn’t.

**Comment by christiaandewit** [comment]
@ReneV1971, as you can read in the post above yours, the RDM004 isn’t supported yet. The results of interviewing the new device are needed, so you could help getting your device supported if you know how to collect the required information.

**Comment by JohanBendz** [comment]
RDM004 added to the current Live version, if you have issues please get back to me.
