### ISSUE TITLE
Philips hue Outdoor Sensor not working with Homey pro 2023

### ISSUE THREAD

**Issue by Mako1231a** [sebbebebbe/com.philips.hue.zigbee#548]
![IMG_0638](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/155478060/5f38f0cc-95df-4455-bb7c-3d20df50b4c8)
![IMG_0639](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/155478060/798daf4f-35cc-44f5-b0b3-fb92c23c5b6c)

**Comment by Erikmol41** [comment]
Ik heb het zelfde probleem 
De binnen sensoren werken priema 5x 
Maar krijg mijn buiten sensor niet goed gekoppeld 😭

**Comment by Erikmol41** [comment]
Met de nieuwe versie beta werkt het nu wel....bedankt

**Comment by Platvoetje** [comment]
Hoe krijg ik de bèta versie in homey want bij mij werkt het ook niet

**Comment by Erikmol41** [comment]
https://homey.app/nl-nl/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/

**Comment by Platvoetje** [comment]
It works!

Thanks

Op vr 12 jan 2024 om 14:14 schreef Erikmol41 ***@***.***>

**Comment by Friedhofsblond** [comment]
Hello, I think the settings are swapped.
With the LED indicator on movement I know.
I also believe in motion sensitivity.
(Outdoor SML004)
![hue3333](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/69040858/f98b6805-eb31-478a-b2f9-809781daf980)

**Comment by Mako1231a** [comment]
> https://homey.app/nl-nl/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/

Hello. 
Now it’s working, everything is okay 👍
