### ISSUE TITLE
Support for Hue Amaze Pendant

### ISSUE THREAD

**Issue by rvmuilekom69** [sebbebebbe/com.philips.hue.zigbee#55]
Hi,
Can you please add support for the Philips Hue Amaze Pendant? (Dimmable and 4 color modes)

Fabrikant ID: Philips
Product ID: LTP002
Apparaat ID: 544
Profiel ID: 49246

https://www2.meethue.com/nl-nl/p/hue-white-ambiance-amaze-hanglamp/4023331P7

Thanks for your work and this great app!

Regards,
Ron

**Comment by sebbebebbe** [comment]
Added to the list. Thx for the request.
