### ISSUE TITLE
Add support for Hue contact door and window switch 

### ISSUE THREAD

**Issue by Wietze1970** [sebbebebbe/com.philips.hue.zigbee#551]
Part of hue security 

This switch can be really helpful for flows on climate and lightning . Would love to include these in my flow's

**Comment by JohanBendz** [comment]
Hi @Wietze1970, please get back with a device interview. Not much I can do without one.
https://community.homey.app/t/app-pro-philips-hue-zigbee-without-the-bridge/29734
