### ISSUE TITLE
Beweging sensoren tijdelijk uitschakelen

### ISSUE THREAD

**Issue by Erikmol41** [sebbebebbe/com.philips.hue.zigbee#552]
is het mogelijk om de beweging sensoren tijdelijk uit te schakelen in een flow
bijvoorbeeld als ik een knop indruk dat de sensor 30 uit gaat ?

dit gaat wel als ik de sensor via de hue hub heb aangesloten maar niet via de hue zonder hub....

**Comment by JohanBendz** [comment]
Hi @Erikmol41, it's not a feature I have in the app right now. You can solve it in a flow but I see the use case for a device generic function. I will look into it.

**Comment by Erikmol41** [comment]
in middels gelukt om de sensor tijdelijk uit te schakelen via een flo en na een ....min weer in te schakelen 
![Homey badkar flo](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/147942818/3e4f64c2-d8af-44d2-bb7f-f31812b7aa49)


bedankt voor je mooie app

bedankt Erik een gelukkige

 Homey pro gebruiker

**Comment by JohanBendz** [comment]
Sensor suppression for Occupancy models added to next release.
