### ISSUE TITLE
Hue wall switch doesn't work after some time (ex. after night).

### ISSUE THREAD

**Issue by mmixxu** [sebbebebbe/com.philips.hue.zigbee#553]
After night nothing happens if I push hue wall switch. If I change device default mode and save, it will work again some time. Test version of app (2.0.48).

**Comment by mmixxu** [comment]
I have 2 hue wall switch and if I pair both with homey with this app, the first paired doesn't work anymore

**Comment by JohanBendz** [comment]
The next version of the app vill solve this, units will have to be paired again.
