### ISSUE TITLE
Hue Smart Plug Swiss edition not properly working with homey pro App „hue without the Bridge“

### ISSUE THREAD

**Issue by Marcelhomes** [sebbebebbe/com.philips.hue.zigbee#555]
Hue Smart Plug Swiss Edition (Product No. 28066300) is online detected as „unknown ZigBee device“. Can someone add it to the List of supported devices?

**Comment by JohanBendz** [comment]
Hi @Marcelhomes, I need the Zigbee info for the device to be able to add it. Best is to interview the device and add the log here.
https://tools.developer.homey.app/tools/zigbee
(Interview is found when clicking the Action dots)

**Comment by JohanBendz** [comment]
Please start a new issue when you have an interview to share. Not able to help without it.
