### ISSUE TITLE
Hue white luster e14

### ISSUE THREAD

**Issue by gvanhartevelt** [sebbebebbe/com.philips.hue.zigbee#556]
Ik kan de lamp 9290024406a Hue white luster e14 niet vinden om te koppelen aan Homey pro 2023 met de app, kan deze toegevoegd worden?![image](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/156919996/25ccb4a7-dc50-4f8a-b780-353a7a52b718)
![image](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/156919996/ebaf4ad3-5c3c-47bf-b3e3-c79473a06327)![image](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/156919996/ecc8f487-523d-49d3-9369-dab58ec46211)![image](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/156919996/401ef0d3-8c47-428b-9caa-d18beb2b1fd2)

**Comment by JohanBendz** [comment]
Hi @gvanhartevelt, please try this version: https://homey.app/en-us/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/
