### ISSUE TITLE
New device unavailable, after delete already added.

### ISSUE THREAD

**Issue by benbeek** [sebbebebbe/com.philips.hue.zigbee#557]
I tried to add a Philips Hue Impress outdoor lamp from Homey.
Devide was found and added with this app.
But the device was stated as "not available" in Homey.
Deleted the device from Homey.
Tried to add the device again with your app, but your app blocked this because "device already added".
Reset of the Hue lamp with the Hue app on my phone did not help.
Uninstalling your app did not help.
So this feels like a bug.
Can you tell me what to do to add the lamp again, or do something with this bug?

**Comment by JohanBendz** [comment]
Hi @benbeek, is this still a problem? Normally Zigbee fix problems like this on it's own over some time..

**Comment by benbeek** [comment]
Problem was persistent. Uninstalled your app en bought a Hue bridge. That worked.
