### ISSUE TITLE
Hue motion sensor every day disconnects 

### ISSUE THREAD

**Issue by rrobinss** [sebbebebbe/com.philips.hue.zigbee#558]
Hi!

Since 2 weeks my hue motion sensor disconnects every day, I dan repair the devices. After that it’s working for a day.

can you look what the problem is? thanks!!!

**Comment by JohanBendz** [comment]
Hi @rrobinss, I'm working on a potential fix. Will be in next update.

**Comment by WueBumbum** [comment]
Hello, I may have the same issue with two Motion Sensors, but not every day just after one or two weeks. Repair is not working for me. I have to delete the device and add it again.

**Comment by joco73** [comment]
Same as this https://github.com/JohanBendz/com.philips.hue.zigbee/issues/594 ?
