### ISSUE TITLE
Filament A60 definition not recognised 

### ISSUE THREAD

**Issue by tondenbraber** [sebbebebbe/com.philips.hue.zigbee#559]
Hi,

When trying to add the Filament A60 it always ends up with using the 'unknown Zigbee device' definition. It works also but it would be nice if it just used the correct definition.

thanks,
Ton

**Comment by JohanBendz** [comment]
Hi @tondenbraber, I need more information. What is the device's Zigbee info when you have it added as a generic/unknown device?
Looks like this:
![image](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/34488771/60c841e1-6c36-43c1-82c6-e21d6a33ba31)

**Comment by tondenbraber** [comment]
Hi Johan,

Thanks for reaching out. Here you go!

Kind regards,
Ton

On 26 Feb 2024 at 23:35 +0100, Johan Bendz ***@***.***>, wrote:
	Hi @tondenbraber, I need more information. What is the device's Zigbee info when you have it added as a generic/unknown device?
Looks like this:
image.png (view on web)

**Comment by JohanBendz** [comment]
Hi @tondenbraber, should there have been an image attached? :)

**Comment by tondenbraber** [comment]
Hi Johan,

Yes, it should…but I’ll try again!

Regards,
Ton

**Comment by JohanBendz** [comment]
@tondenbraber Still no image. Try uploading the image to github directly.

**Comment by tondenbraber** [comment]
Here you go, hope this works!
![A60_Zigbee](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/157276485/7ef28f31-9f73-4ae7-937a-7670a9aea9e2)

**Comment by JohanBendz** [comment]
Hi @tondenbraber, this should be supported by the latest version on app store. Please try it and get back to me if it does not work.
