### ISSUE TITLE
Philips Hue motion sensor

### ISSUE THREAD

**Issue by AllSeeingGoatWizard** [sebbebebbe/com.philips.hue.zigbee#560]
I'm having issues installing Hue indoor motion sensor to my Homey Pro 2023. The app does not recongize it as a motion sensor but a generic on/off device.

Is there a trick to it that I am missing ?

**Comment by AllSeeingGoatWizard** [comment]
I was able to add the motion sensor after updating to 2.0.48.

**Comment by osteinhauer** [comment]
same here, update to latest test version resolves the issue
