### ISSUE TITLE
Smart Button

### ISSUE THREAD

**Issue by FSUShanks** [sebbebebbe/com.philips.hue.zigbee#561]
Hello Johan

I hope you are well.

I have installed the app and am trying to pair the smart button but I keep getting an error;

"Zigbee is starting. please wait a minute and try again"

I try again but stuck in the cycle of this message, can you help. thank you.

**Comment by JohanBendz** [comment]
Hi @FSUShanks, is this still a problem?

**Comment by JohanBendz** [comment]
This is most surely not an app issue, get back to me with a diagnostic report from the app if you think it is. (remember to @mention me)
