### ISSUE TITLE
Hue Sensor ( Zigbee Could not start ) 

### ISSUE THREAD

**Issue by Olarsen96** [sebbebebbe/com.philips.hue.zigbee#562]
Can someone please help? I have several sensors from Philips Hue. I used the trial version for a long time without problemsc, then drt stopped working. then switched back to regular philips hue app in homey. but it's so slow.. So I thought I'd try to switch back. but when I want to add the sensor, it just says "Zigbee could not start" .. What can I do? have been trying for a long time now

**Comment by JohanBendz** [comment]
Hi @Olarsen96, is this still a problem?

**Comment by JohanBendz** [comment]
If this is still a problem, please get back to me. Given your description I think this is a Homey issue and not related to the app itself.
