### ISSUE TITLE
Lightstrip Plus v4 (LCL001 & LCL006)

### ISSUE THREAD

**Issue by ackerk** [sebbebebbe/com.philips.hue.zigbee#563]
Hi,

My first Lighstrip Plus v4 installed without any issues and was perfectly recognized:

![image](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/79246760/e29a2c7d-7ef9-49e7-9924-84211dd041c0)

I recently bought a few more, but when trying to install them, they were recognized as generic Zigbee devices:

![image](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/79246760/c7d1efc7-8c2b-45b2-93e5-07885d5dcab9)

Didn't understand why, untill I noticed that the initial one has a deviceid LCL001, while the new ones have a deviceid LCL006. Could that be reason?

Because I also noticed only LCL001 is mentioned with v4 Lightsrip devices:

![image](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/79246760/23ae556b-b59d-48fd-802f-c6b45eb29a17)

Thanks in advance!

Wkr,

Kris.

**Comment by JohanBendz** [comment]
Hi @ackerk.
I'll add it to the older driver, do get back to me if this does not work.
Will be in next update.

**Comment by ackerk** [comment]
Only today had some time to look into it. Works like a charm. Many thx for the quick fix! Highly appreciated!
