### ISSUE TITLE
Support for Lily and Motion sensor

### ISSUE THREAD

**Issue by JohanLindstam** [sebbebebbe/com.philips.hue.zigbee#564]
Hi
Neither of these were recognized when added though supported.
I suppose the hardware has been updated and need renewed support in the app.
Can you please help?
Hope the data in the images helps.

![IMG_4351](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/161557977/97f0e9ce-0af4-490d-b9dd-db3c67e2d271)
![IMG_4349](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/161557977/5cfd0d9c-096d-4654-9a63-86124673740f)

**Comment by JohanBendz** [comment]
Hi @JohanLindstam, both supported in the test version of the app. Soon in live.
