### ISSUE TITLE
Outdoor sensor error

### ISSUE THREAD

**Issue by slevin1987** [sebbebebbe/com.philips.hue.zigbee#565]
Can't exclude Outdoor Sensor from the new Climate list in the Homey app. Got the error "invalid_setting_type".

(indoor sensors can be excluded however)

**Comment by slevin1987** [comment]
On experimental version off your without the bridge app.

**Comment by JohanBendz** [comment]
Hi @slevin1987, both in and outdoor works for me. Please try restarting the app, homey or repairing the device.
