### ISSUE TITLE
Motion sensor indoor in error after restart of Homey Pro 2023

### ISSUE THREAD

**Issue by phemels** [sebbebebbe/com.philips.hue.zigbee#566]
When I restart my, Homey Pro then my two HUE motion sensors indoor have a red triangle and stop working.
You see that they detect movement in de “log” of the sensor, but the flow doesn’t start.
After I restart your plugin, they work fine again!
I have the latest test version running, on my Homey Pro 2023.
The sensors are brand new. SML003, version 2.53.6

I hope there is a fix, because it’s also after a power fail :(

**Comment by JohanBendz** [comment]
A potential fix is on it's way.

**Comment by phemels** [comment]
Hi Johan,

Great any idea when its implemented?


Met vriendelijke groet,

Paul.
www.pahedomotica.nl
www.alarmsysteemwebshop.nl


Op ma 4 mrt 2024 om 23:23 schreef Johan Bendz ***@***.***>
