### ISSUE TITLE
Filament Bulb ST64 E27 not recognized

### ISSUE THREAD

**Issue by stayallive** [sebbebebbe/com.philips.hue.zigbee#569]
![afbeelding](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/1090754/07cd8a21-acfb-4855-a918-bc6ae1f2fef5)

![afbeelding](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/1090754/45e7b0c8-8bf1-4840-a7f4-3f293eff5fc6)

> https://zigbee.blakadder.com/Philips_LTV002.html

Let me know how and if I can provide more information!

**Comment by JohanBendz** [comment]
Added to next release
