### ISSUE TITLE
Filament Bulb Candle E14 not recognized

### ISSUE THREAD

**Issue by stayallive** [sebbebebbe/com.philips.hue.zigbee#570]
![afbeelding](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/1090754/10f13a10-2aaf-45c3-8227-a8e70ff554af)

![afbeelding](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/1090754/66514697-ff8a-4d7e-abfc-b90a61e16cc6)

> https://zigbee.blakadder.com/Philips_LTE005.html

Let me know how and if I can provide more information!

**Comment by JohanBendz** [comment]
Added to next release.
