### ISSUE TITLE
unable to add sensor

### ISSUE THREAD

**Issue by Olarsen96** [sebbebebbe/com.philips.hue.zigbee#574]
Trying to add Occupancy Sensor. hold down the button for 10 seconds and it says that the sensor is being added, then a message appeared about "The device stopped responding and could not be added" what can I do? worked before with test version. but can't find it anymore
![IMG_6915](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/144847614/6c72096e-1e3b-42b2-93ca-8c375b84ec8e)
![IMG_6916](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/144847614/c5def11f-15de-46c0-91be-5ab92ea00fd6)

**Comment by JohanBendz** [comment]
Sounds like a pairing issue, which occurs before the app is involved in the process. Check the device battery, inspect the Homey power adapter, and look for interfering Wi-Fi. Click the setup button on the device every other second during the pairing process.
