### ISSUE TITLE
Big problem with the Wall Switch

### ISSUE THREAD

**Issue by joeyv12** [sebbebebbe/com.philips.hue.zigbee#575]
Hi,

I found out that we could add the wall switch to this app, what is wonderful to me, cause I have 28 of them in my house.
No i added all of them and now i see that all the secondary devices (button 2) have be messed up.

Example: So button 2 (which normally put on the light in the living room, now switches on the lights)
In the flows you still see that it must toggle the living room, but nop the device changed to another device.

**Comment by JohanBendz** [comment]
Hi @joeyv12. Yeah.. sorry about that.. I'm working on a fix, 
https://github.com/JohanBendz/com.philips.hue.zigbee/issues/568
