### ISSUE TITLE
Occupancy sensor loses connection

### ISSUE THREAD

**Issue by robinheghan** [sebbebebbe/com.philips.hue.zigbee#576]
Hi. I’ve got five occupancy sensors from Hue connected to the Homey Pro 2023 through this app.

three time the past week I’ve lost connection with the sensors, requiring a repair action to get them back online.

it seems to happen after the Homey Pro restarts (power loss or software update).

please let me know if you need more information.

**Comment by christian-persson** [comment]
I also have two occupancy sensors that I used for many years without problems with my Homey 2019. One month ago, or something like that they started to disconnect. I have to delete and re-add them, then they works for 1-5 days. I have alot of (around 20) other zigbee devices and also other hue devices that works without problems.

**Comment by JohanBendz** [comment]
Hi @robinheghan and @christian-persson, it looks like there are some generic Homey Zigbee problems and has been since early Mars. If you send me a diagnostic report I can have a look at your setups. get back to me with the report ID's.
I take it you use the latest version? 2.0.51

**Comment by robinheghan** [comment]
Yes, I’m using the latest version.

a820000f-bf90-4c9d-8b3e-e4b58d225ff2

**Comment by christian-persson** [comment]
2.0.51

631190a7-a95d-4c09-ae0b-e866dd8ae471

**Comment by flymanster** [comment]
Same here, I have one outdoor occupancy sensor and since last week homey pro 2023 reports error and had to repair few times or remove and add again

Version 2.0.51

**Comment by robinheghan** [comment]
It happened again after my Homey updated to the latest version. Here’s a fresh diagnostic: f8f6c77a-8bd3-4c4e-9769-7bf40dca61c4

**Comment by robinheghan** [comment]
Just saw this in the latest release notes. I guess there's nothing to do but wait, then.

![Skjermbilde 2024-03-26 kl  08 39 40](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/854889/7d45b4a0-0f32-475c-a8ca-c496c3477cd9)

**Comment by JohanBendz** [comment]
Thanks for posting that image @robinheghan, I said so before but it's better to have the info from Athom directly :)
All recent diagnostic reports show the same, Homey Zigbee fails and this is not related to the app but rather the Zigbee stack/chip.

**Comment by Davidogo** [comment]
> I also have two occupancy sensors that I used for many years without problems with my Homey 2019. One month ago, or something like that they started to disconnect. I have to delete and re-add them, then they works for 1-5 days. I have alot of (around 20) other zigbee devices and also other hue devices that works without problems.

I have also the same problem. Do you have an solution ?

**Comment by 3FINGER** [comment]
I have just like Davidogo. Homey 2019 2 sensors that I had for many years. And they lose connection. I have changed the battery and added removed etc. Good to know it's not my fault. Fingers crossed for a good solution. Have a good day

**Comment by 3FINGER** [comment]
These Zigbee problems, does it also apply to HP PRO 2019(early 2019)? Because when I remove and plug in my philips SML002, it works for 4-5 days. Then it disconnects. I have 2, but I have to have a ladder to reach one, so I've only tried to plug it in 2 times. But then I have one that I can reach and easily take down and remove and plug in. I have removed this 4-5 times I think. And it's the same result every time. Have 14 Zigbees connected to my HP PRO 2019 (early 2019) it is only the SML002 that disconnects. I have outside lights and car engine heaters (flow) that control these so I depend on them working. Should I buy a Philips Hue Bridge to ensure this works? As I understand it, it is the HP 2023 that has problems with Zigbee? Or does this also apply to HP PRO 2019?
Have a good day everyone

**Comment by christian-persson** [comment]
After the last firmware 10.0.11 i re-added my two motion sensors and both of them have worked for four days now. Let's cross our fingers :)

**Comment by 3FINGER** [comment]
> After the last firmware 10.0.11 i re-added my two motion sensors and both of them have worked for four days now. Let's cross our fingers :)

My 2 have been working for a little while now. Had to add one that dropped 16 days ago. 1 has been almost 2 months. run one on each driver. Think one shows battery left and the other doesn't (100%) all the time. I hope it turns out well for both of us now. :)

**Comment by JohanBendz** [comment]
https://github.com/JohanBendz/com.philips.hue.zigbee/issues/615
