### ISSUE TITLE
Multi spot support with "simultaneous" pairing (when one already paired)

### ISSUE THREAD

**Issue by mvletter** [sebbebebbe/com.philips.hue.zigbee#58]
Using beta v1.4.3

First off: great work so far! Added the first Hue Ambiance Spot (GU10) from a set of 2 Philips runners went great. Long pressed the 1 and 0 button close to the lamp. Switched of the light and switched it of again using the main switch (not the remote) and the device paired. 

When I tried to add a second lamp I get: 
"Something went wrong whilst adding your device, please try again later.
If you do not manage to pair the device with Homey, try resetting it first."

It’s almost like it still “sees” the first lamp and tries to pair that one again (both lamps switch on at the same time because they are both on the hall). 

I removed the already paired lamp from the socket to add the other one which worked.

**Comment by sebbebebbe** [comment]
Ok so it works as you should or are you still having issues?
