### ISSUE TITLE
Motion Sensor loses connection every day, had to manually restart the app

### ISSUE THREAD

**Issue by haadeess** [sebbebebbe/com.philips.hue.zigbee#589]
![Screenshot_2024-04-18-06-49-46-02](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/119533669/38d67626-34ff-42a7-a95f-8a2ddac598be)

a8956aec-b8c2-420d-88b8-8a5680617052

**Comment by haadeess** [comment]
5day in row without problems. hopefully it will stay that way

**Comment by haadeess** [comment]
It happened again.... 5days good, this morning the same issue

**Comment by magnuse87** [comment]
I have the same issue with my Outdoor Motion Sensor. If I access it through homey script or read the insights it seems to be reporting fine. So it seems to be the flow cards and UI in the app that isn't working. Restarting the app does not help. I am running v. 2.0.51

**Comment by magnuse87** [comment]
Correction - restaring the app actually helped now, but it hasen't earlier.

**Comment by marcopolitiek** [comment]
same with me, last 3 weeks problems started with the hue outdoor SLM002 motion detector, reinstalled 3 times and after 1 or 2 days connection lost, tried to install as occupancy sensor same deal. is there something wrong in the update from march 5th?

**Comment by joco73** [comment]
Same issues as this: https://github.com/JohanBendz/com.philips.hue.zigbee/issues/594 ?

**Comment by marcopolitiek** [comment]
Yes exactly the same

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JohanBendz** [comment]
https://github.com/JohanBendz/com.philips.hue.zigbee/issues/615
