### ISSUE TITLE
Philips Hue White ambiance LTW010: Cold to warm not working

### ISSUE THREAD

**Issue by mariarosberg** [sebbebebbe/com.philips.hue.zigbee#59]
Hi!
When turning the main power source off and then on the bulb activates in warm mode.
If i ever the slightly touch the controller for cold to warm it switches to the coldest setting and the controller for cold to warm does not work at all.

FYI: The controller for the dimmer works as it should.

Sincerely hope for at fix very soon!
Maria

**Comment by sebbebebbe** [comment]
Hi,

It might have to do with another issue I am looking at. But to clarify, what do you mean with controller?
What bulb are you having issues with? ID?

If you mean main power source as in the same as pulling the plug to the bulb it will always light up max. I believe this has changed when using the bridge or you might need to update firmware in bulbs. Not sure as i do not use a bridge myself.

Thanks for the report.

**Comment by mariarosberg** [comment]
...are you Swedish?
I wrote the model ID in the description and since I'm using your app I
thought it was obvious that I don't have a bridge!?

The problem was not that it lit up in max when I "pull the plug" it was
that the warm light, once shifted to cold or cooler can not be activated
again in any other way than to "pull the plugg".

The controller/regulator of how cool or warm the light should be is not
working. If I regulate it even a tiny bit I goes straight to the coldest
light and gets stuck there...unless I "pull the plug" and it starts up with
the warmest light.
The only thing working is the controller/regulator for the brightness of
the bulb!
/Maria


Den tors 17 jan. 2019 21:57 skrev Sebastian Johansson <
notifications@github.com>:

**Comment by sebbebebbe** [comment]
Yes I am........
Sorry, missed your ID in the title. Why I am asking if you used the bridge is that i have had a number of error reports from people using the bridge and contacting med on e-mail. Now that we have gotten that out of the way.

I have currently made a change where colors should work better with alla ColorDevices using the app. However i have not seen or heard anything that you describe. Does other bulbs work when this problem occurs?

What version of the app and Homey are you using?

**Comment by mariarosberg** [comment]
Ok, trist att de inte vet vad det är för app de använder ...för din app är
väl inte kompatibel med brygga!?

Nej, inget problem med andra lampor under tiden jag upplever mitt problem.

Problemet har inte plötsligt uppstått utan var så från början.

App: Homey (preview) 0.8.5.115
(har ju faktiskt inte testat med den gamla appen)

Homey: 1.5.13

Kanske inte någon annan som använt lampan med samma id? Stod att den var
oprövad i din beskrivning.

Ok, får kolla om det blivit någon förändring efter din tweak imorn.

Tack för dina snabba svar!
/Maria

Den tis 22 jan. 2019 22:04 skrev Sebastian Johansson <
notifications@github.com>:

**Comment by sebbebebbe** [comment]
Nej det stämmer det är direktkoppling utan brygga som gäller.

Min ändring kommer dessvärre inte ut förräns jag släpper en uppdatering för appen. Kommer troligtvis i början av februari.

Skriver ändå upp på listan att testa LTW010, kan vara så att jag har en sådan liggandes där hemma.

**Comment by mariarosberg** [comment]
Okej, kanon, tack för appen och tack på förhand!
/Maria

Den ons 23 jan. 2019 08:11 skrev Sebastian Johansson <
notifications@github.com>:
