### ISSUE TITLE
Phillips hue outdoor motion stop working

### ISSUE THREAD

**Issue by indicusdk** [sebbebebbe/com.philips.hue.zigbee#594]
Hi, 
i have a homey pro early 19 and i having issusues with the hue outdoor motion sensors, when i add them to homey they work as the shoud but after some days they just dont registrate any movement, if i remove and add them again its the same storey, they work for some days, think best results is for almost a week before they stop working, theres no errors in homey and when i click into the sensors everything seams just fine but when i see the log i can see when they have registrated movement last.

hope you have a soloution.

**Comment by j3l-scripts** [comment]
Same problem, thing worked for years. Tried replacing batteries and changing place for connectivity. But keeps losing connection after time.

**Comment by joco73** [comment]
I see the same problem. It has worked perfectly for years and the last couple of months it drops out after a couple of days/a week. Re add finds it but say it already exists so I need to drop it and add from start - finds it perfectly but then I need to fix my flows.
So something seem to have happened, either to the Homey early 19 code or this App.
I can not give details if it stopped at an update om homey or of the app.

**Comment by JohanBendz** [comment]
https://github.com/JohanBendz/com.philips.hue.zigbee/issues/615
