### ISSUE TITLE
Hue Sensors dropping connection  and going in pairing mode

### ISSUE THREAD

**Issue by Berightbackin5** [sebbebebbe/com.philips.hue.zigbee#606]
There is an odd issue on the Homey hue app that whenever a sensor is connected it will drop it connection with Homey.
The sensor would go on its own in pairing mode.

I 've seen this in outdoor sensor but as well in the indoor motion sensor.

What stands out is that the sensors that drop connection are the sensors that are usually connected via a router and not directly connected to Homey. I don’t know if this can be useful information to you. I have to admit though that the connection has been dropped directly after being added and right in front of Homey a couple of times too.

So that observation may not be consistent.

Also especially with the outdoor sensor. It will drop connectivity in matter of minutes after re-adding.

I tried many times to add it , and took the necessary steps via Athom but the sensor keeps going back to pairing mode whenever moment arise of low activity.

These sensors had maintain a connection for years in the passed so they were fully functional until the beginning of this year.

Is there a possibility for you to check if there is any issue on your side of the application?

The sensors I am currently using are SML002 and SML001.

Kind regards.

**Comment by JohanBendz** [comment]
Hi @Berightbackin5, I have been working with this issue for years and also rewritten the code to use a more stable reporting, sadly this is not enough for all. The connectivity issu is a Homey one, I have reached out to Athom for co-operation in fixing this but as I understand it there are issues with the core Zigbee driver/chip that I can't fix in the app.

**Comment by JohanBendz** [comment]
https://github.com/JohanBendz/com.philips.hue.zigbee/issues/615

**Comment by techydude** [comment]
https://github.com/JohanBendz/com.philips.hue.zigbee/issues/615#issuecomment-2508963185
