### ISSUE TITLE
pairing lightstrip plus

### ISSUE THREAD

**Issue by ronwell74** [sebbebebbe/com.philips.hue.zigbee#611]
Hi 
can you help me with how to slove, I have recently gone from homey 2018 to a homey 2023. I have managed to pair all my hue lights and dimmers over to the new homey, except for one light strip plus, I have the old homey 2018 powered off. I have tried multiple times to put the stip into pairing mode using a dimmer but it will not blink. is there another way I can force it into pairing mode.
thank you.

**Comment by JohanBendz** [comment]
Hi @ronwell74.
If the device have support for bluetooth you an also reset it from the Hue app and then add it to Homey.
You can also try using the web interface instead of the Homey app, sometimes this works better. 
https://my.homey.app/

**Comment by ronwell74** [comment]
thanks, the light strip is the older model before bluetooth, adding it from
the web app doesn't work because the issue is getting it into pairing mode
so that it can be added
