### ISSUE TITLE
Zigbee (Hue) device has left the Network. 

### ISSUE THREAD

**Issue by HemboLive** [sebbebebbe/com.philips.hue.zigbee#612]
Hey there. I have the issue that my Hue devices (mostly motion sensor) “left the network”.

I is about 2-3 times a day. Then I had to repair the device to get it to work. 

Sad because I bought homey to go away from so much bridges like Phillips hue’s. 

I use v2.0.51 of the app and homey is up to date with stock stable firmeware

thank you. 
![IMG_7013](https://github.com/user-attachments/assets/77f73bc1-1500-4621-8f66-4f9bca669b8c)

**Comment by JohanBendz** [comment]
Hi @HemboLive
This is often related to:
1. A bad or weak Homey power adapter. Try switching to a stronger one (minimum 2.1A).
2. Wi-Fi interference. Check if your Wi-Fi or a nearby Wi-Fi network is using interfering channels (Google "Zigbee Wi-Fi channels").

**Comment by JohanBendz** [comment]
more info here: https://community.homey.app/t/advanced-zigbee-troubleshooting-on-homey/115930
