### ISSUE TITLE
Regular disconected outdoor motion sensor

### ISSUE THREAD

**Issue by Sybrandv8** [sebbebebbe/com.philips.hue.zigbee#613]
After years of well functioning now my outdoor motion sensors are disconnected for the third time after deleting and connecting again. I read some other threads with the same issues but couldn’t recognize the solution. There is nothing like an error code or warning. The app shows juiste the latest static info from weakest ago. Is there an update or solution ?

homey pro early 2016 version 12.0.1
Diagnostic:9a596c80-f474-4e4a-bc0a-a4e4b6e3e415

**Comment by JohanBendz** [comment]
Hi @Sybrandv8, sadly there is no errors or anything else to troubleshoot. Have a look here to see if there is anything you can do to fix the issue: https://community.homey.app/t/advanced-zigbee-troubleshooting-on-homey/115930
