### ISSUE TITLE
My Hue 4 button switches stopped working

### ISSUE THREAD

**Issue by pardeike** [sebbebebbe/com.philips.hue.zigbee#62]
Hi,

Homey 2018, v2.0.1 and two hue switches that worked before on 2.0. Both have stopped completely from reporting button presses. I do not use a hue bridge. 

I even unpaired one of them and re-paired it. It does pair and does show up as a device but no flows are triggered. My hue lamps all work fine.

Anything more I can help with?
/Andreas

**Comment by sebbebebbe** [comment]
Hi,

Thank you for your report. Im not sure it is something that i can fix yet. But i have had a few reports of it not working properly.

My priority for next release is Motion sensor and dimmer switch. I cannot tell you when this will become a reality though.

**Comment by pardeike** [comment]
Thanks for the quick reply. I just find it strange that both stopped together at once. They worked just fine under Homey 2.0 from the very first beginning of v2. Maybe I clone this repo myself and find out why.

**Comment by sebbebebbe** [comment]
@pardeike Hi, do you have the means of testing this issue on Homey v2.0.5-rc.2 ?

**Comment by pardeike** [comment]
Sure. I’m on beta and 2.0.5rc2 installed like an hour ago. Tell me what I should do or am I suppose to test with the current version of your plugin?

**Comment by pardeike** [comment]
Just to be thorough, I unpaired one of my 4-button hue controllers by resetting it for more than 10s and paired it on 2.0.5rc2. Pairing works but pressing the buttons do not trigger any flows I made for the device.

**Comment by sebbebebbe** [comment]
Ok ill have a look. Thx for the info so far

**Comment by sebbebebbe** [comment]
I just tested adding a Hue Dimmer Switch to Homey v2.0.5-rc3 and tried triggering flows on all dimmer events and it worked fine. Please report issue if it continues to support@athom.com.

**Comment by pardeike** [comment]
I can do that. One last question: the two buttons I have have been connected to a hue bridge before. Could that be a problem?

**Comment by pardeike** [comment]
I do reset them so the light turns green then alternates between orange and green and they pair fine. Just tried to unpair both and only one unpaired fine, the other had to be force removed. 

Anyway, I will create a case with athom referring to this Issue

**Comment by sebbebebbe** [comment]
Hmm could be, but I am not sure how you reset a Dimmer Switch like you do with the bulbs.

**Comment by pardeike** [comment]
Actually: while preparing a clean state for my report to athom I removed BOTH no -functional switches, restarted Homey and tried to add a switch that was failing before regardless how many times I removed and added it again. 

Now it works. Must be some problem that only was solvable by removing all switches.
