### ISSUE TITLE
No support för Philips hue outdoor sensor

### ISSUE THREAD

**Issue by Kazapirskis** [sebbebebbe/com.philips.hue.zigbee#63]
In Homey app.

**Comment by sebbebebbe** [comment]
When initial issues with indoor sensor is solved with Athom support I will add support for the outdoor version.

**Comment by 6zXo8aMn2TRXOs** [comment]
Have you got device ID and so on, or should I pair mine as a general zigbee to help you with that?

**Comment by JohanBendz** [comment]
@rindlerblabla It is always a good idea to add that information to a request!
I help Sebastian with adding devices and finding that info and good images are the most of the work, coding is quickly done unless one meet challenges.

**Comment by 6zXo8aMn2TRXOs** [comment]
@JohanBendz Just thought maybe Sebastian already had the information since the issue was closed. Wasn't me who opened it. Anyway:

Product ID: SML002
Device ID: 2128
Profile ID: 49246

**Comment by 6zXo8aMn2TRXOs** [comment]
Sebastian, would you mind opening the issue again, so if someone with technical skills (not like me, hehe) could see the request easier, so the sensor could be added?

**Comment by sebbebebbe** [comment]
Sorry this one should be open, i have added it to our list for devices to be implemented. The motionsensor issue has been solved as of Homey v2.0.5-rc3

**Comment by Kazapirskis** [comment]
Sounds Good

**Comment by 6zXo8aMn2TRXOs** [comment]
Could be closed with #76.
