### ISSUE TITLE
Hue Dimmer Switch

### ISSUE THREAD

**Issue by Lindansaren** [sebbebebbe/com.philips.hue.zigbee#64]
Hi. My dimmer switches has stopped working when I updated from 2.0 to 2.02.

They are visible and possible to add, but they are not activating my flows as earlier.

**Comment by sebbebebbe** [comment]
I am aware of the problem and looking into solving the issue. I am having the same issues with my setup.

**Comment by sebbebebbe** [comment]
I just tested adding a Hue Dimmer Switch to Homey v2.0.5-rc3 and tried triggering flows on all dimmer events and it worked fine. Please report issue to support@athom.com.

**Comment by Vincent75b** [comment]
Unfortunately, dimmers still stop working after 1 day after reinclusion :-(
Have had this problem from before V2, now on update V1.4.4 and V2.0.5rc5
Would be fantastic if this could be fixed!

**Comment by sebbebebbe** [comment]
Please report to support@athom.com since I cannot make any changes in their Core which handles the device communication.

**Comment by Vincent75b** [comment]
Hi!

Ok, I will!

Do you have some info that I could use for the report? Just to make clear
what exactly the problem is, and Athom will not blame it on your app
instekend of the Homey core...

Regards, Vincent

**Comment by sebbebebbe** [comment]
Describe the issue that it adds fine but stops working after a day and that the app does not have any  functionality that changes over time.

They have access to this repo aswell so they can see how they are added.

**Comment by pardeike** [comment]
Removing all my switches, rebooting and re-adding worked for me. They stopped working after the 2.0.5 update (no other changes).

**Comment by Vincent75b** [comment]
Answer from Athom:

Dankjewel voor de extra informatie. Dit probleem wordt veroorzaakt door de
Zigbee implementatie in Homey. We zijn van plan deze een grote update te
geven. Hoewel dit even kan duren, is het de bedoeling dat hiermee dit soort
problemen worden verholpen. Het is moeilijk te voorspellen wanneer precies
dit af zal zijn, maar het staat hoog op onze prioriteitenlijst, gezien het
al lang speelt. Onze excuses voor het ongemak.

Guess its going to take another while :-(

**Comment by pardeike** [comment]
At least it’s acknowledged

**Comment by geurti64** [comment]
Here it worked until last update 2.0.5
The motion started working for the first time and the switch stopped.
Should I tell Athom about it?
