### ISSUE TITLE
Hue motion not send motion

### ISSUE THREAD

**Issue by jtyrvain** [sebbebebbe/com.philips.hue.zigbee#7]
I have 5 Philips Hue Motion sensors. Always one of those 5 stop sending motion.

**Comment by jtyrvain** [comment]
I try to reset all, and add only 3, but same problem. Little time all 3 works, but later 1-2 stops working.

**Comment by mickeman** [comment]
I have the same problem, motion/temp/luminance all stop working after random time.
Sometimes works for only 10 minutes sometimes works a few hours.
I have 2 hue motion sensors and 6 Ikea Trådfri lamps + 2 hue dimmer switch and everything else seems to work ok.
I have also tried hold the setup switch for 10 seconds.
Re-installed the hue app on homey.
Removed the sensor from homey and done the pairing again.

**Comment by mickeman** [comment]
Ok, so i got tired of not having the motionsensor working reliable and bought the Hue bridge.
One difference is that the sensor doesn´t light red now when detecting motion.
A theory is thats why it´s not working as it should when connected directly to Homey.
The sensor "thinks" it got communication problems everytime it sends.

**Comment by Mich007** [comment]
Hi, I'm having the same problem with the HUE motion sensor. Connected directly to Homey, the red led blinks long (=problem reaching the bridge/homey) when motion detected or no detection at all. Connected motion sensor to the hue bridge and the sensor works fine, I would like to us it directly on homey as response is a lot quicker and I have more possibilities. Could you look into this?

**Comment by Ikon79** [comment]
Hi, i have the same problem, i have three motion sensor, i can only get one of them to work. All paired fine, but only one working. And can’t remove the two that doesn’t work

**Comment by PerHag** [comment]
Hi, I have same problem. 
I have one Hue Motions sensor, and I use countdown + Better logic. 
It works some time, then it doesn’t work any longer. (like 10 minutes or 10 alarms)

Now try a clean Flow, = only use Hue motion sensor
Flow 1, if motion alarm turn on then turn light on
Flow 2, if motion alarm turned off, then turn light off.
After 10-15 minutes = same problem.
I found out that after it not work any longer. Then Motion sensor don’t react on motion (the red light on motion sensor do not lights up), Homey reports Motion alarms = No.
after another 10-15 minutes when the motions sensor has rested, the Hue motion sensor react on motion (red light in 2-3 seconds), still Homey report Motion alarms = No.

Any idea if it is the Hue motion sensor that is the problem or if it is something else?

Nice, after another 20 minutes, Hue motion sensor stat working again.

An 30 cycles with on/off, I start wave frantically, and Hue Motion Sensor give up again, no red light, Homey reports motions alarm = yes continuously.

**Comment by sebbebebbe** [comment]
Hi guys, thanks for the detailed information.

I am afraid that this is an issue with the ZigBee implementation somehow. I have a one motion sensor in my ZigBee network without any issues. Although I have had alot of reports of it not working properly. I will have another look at it when I have the time.

Again, thanks

**Comment by Mich007** [comment]
> Hi, I have same problem.
> I have one Hue Motions sensor, and I use countdown + Better logic.
> It works some time, then it doesn’t work any longer. (like 10 minutes or 10 alarms)
> 
> Now try a clean Flow, = only use Hue motion sensor
> Flow 1, if motion alarm turn on then turn light on
> Flow 2, if motion alarm turned off, then turn light off.
> After 10-15 minutes = same problem.
> I found out that after it not work any longer. Then Motion sensor don’t react on motion (the red light on motion sensor do not lights up), Homey reports Motion alarms = No.
> after another 10-15 minutes when the motions sensor has rested, the Hue motion sensor react on motion (red light in 2-3 seconds), still Homey report Motion alarms = No.
> 
> Any idea if it is the Hue motion sensor that is the problem or if it is something else?
> 
> Nice, after another 20 minutes, Hue motion sensor stat working again.
> 
> An 30 cycles with on/off, I start wave frantically, and Hue Motion Sensor give up again, no red light, Homey reports motions alarm = yes continuously.

Hi PerHag,

The red light on the Hue motion sensor indicates there is a problem reaching the bridge (Homey).
See: https://www2.meethue.com/en-us/support/motion-sensor/top/where-is-the-led-indicator-of-the-hue-motion-sensor-located-and-what-does-it-indicate

I've been in contact with Athom support about this some 4 month ago. They told me that they are aware of some bugs in the Zigbee stack and fixing these bugs is on the to-do list. But they couldn't give me any indication on timeline.
I switched to the NeoCool (Z-wave) motion sensors and these work fine. Not the preferred solution, buying more hardware, but I wanted a good working sensor without having to wait for software fixes with no schedule.

**Comment by PerHag** [comment]
Hi,  thanks for information.
I will look for a Zwave motion sensor, I agree wating is not fun 

//Per

**Comment by PerHag** [comment]
Hi, 
One question, which app and device do you use too install neocool in homey?

Edit: Hmm sorry,  I find the app, ny mistake

//Per
