### ISSUE TITLE
[Request]: make light level from SML001 available for flow conditions

### ISSUE THREAD

**Issue by pardeike** [sebbebebbe/com.philips.hue.zigbee#72]
Hi,
Is there a way to use that sensor for outdoor (through window) light level measuring so I can turn on for example the hall light when my door sensor triggers - but only if it’s rather dark outside? The hue motion sensor has a lux value but it seems I cannot write tests against it. 

/Andreas

PS: I guess I could write a HomeyScript for it but I rather want to see if a simple solution exists.

**Comment by sebbebebbe** [comment]
You should be able to use the lux setting in a flows "And"-part. I use it in a flow with the "Better Logic"-app. Math.js expression, using the tag Luminance < 35.

Hope that helps

**Comment by pardeike** [comment]
Using Better Logic and a math expression works like a charm.
