### ISSUE TITLE
Support for Hue White and Color Ambiance A60 E27

### ISSUE THREAD

**Issue by rdorf** [sebbebebbe/com.philips.hue.zigbee#73]

**Comment by sebbebebbe** [comment]
Any more info for this type of bulb?

Please add as Generic Device and select properties to show Model id and add information to this issue.

**Comment by JustThe2ofUs** [comment]
Would wish the same support. 
I installed Hue White Ambiance Ceiling lamp „Cher“ but it’s not possible to get it paired :((

**Comment by JohanBendz** [comment]
@JustThe2ofUs Support for Cher Ceiling is added to next release of the app.

**Comment by JustThe2ofUs** [comment]
Hell YEAH! Great, thx.

**Comment by JustThe2ofUs** [comment]
Is it rude to ask if there’s an estimated date for the update? (I did a reset to the remote control so I cannot change the lights color from ww back to cw anymore...) 😱😁🤫

**Comment by sebbebebbe** [comment]
Not rude at all. Ill try submit something during the day.

**Comment by JustThe2ofUs** [comment]
Thx mate so much!
