### ISSUE TITLE
Support for Hue White Welcome Outdoor Floodlight 

### ISSUE THREAD

**Issue by 6zXo8aMn2TRXOs** [sebbebebbe/com.philips.hue.zigbee#74]
https://www2.meethue.com/en-us/p/hue-white-welcome-outdoor-floodlight/1743630V7

Product ID: 1743630P7
Device ID: 256
Profile ID: 49246

Thanks in advance!

**Comment by sebbebebbe** [comment]
I have added it to our list.

**Comment by 6zXo8aMn2TRXOs** [comment]
Fixed with #75.
