### ISSUE TITLE
Temperature offset setting?

### ISSUE THREAD

**Issue by 6zXo8aMn2TRXOs** [sebbebebbe/com.philips.hue.zigbee#78]
Would it be possible to add temperature offset settings to the indoor and outdoor motion sensors? The values are way lower, but still relative, to the real ones.

How Xiaomi Aqara app solves it can be found here (I think) https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/master/app.json .

And as you (and @johanbendz ha!) know I don't know nothing about coding so I will not copy paste! Hehe.

**Comment by sebbebebbe** [comment]
Nice feature request! Added it to our internal todo list.

**Comment by 6zXo8aMn2TRXOs** [comment]
Closed with #81.
