### ISSUE TITLE
Add support for Impress (wall and pedestals)

### ISSUE THREAD

**Issue by henrikrox** [sebbebebbe/com.philips.hue.zigbee#83]
Hi, great app, would love support for these items

Impress wall light
https://www2.meethue.com/en-gb/p/hue-white-and-colour-ambience-impress-outdoor-wall-light/1743030P7

Impress pedestal
https://www2.meethue.com/en-gb/p/hue-white-and-colour-ambience-hue-outdoor-pedestal-light/1743130P7

Calla bollard
https://www2.meethue.com/en-us/p/hue-white-and-color-ambiance-calla-outdoor-pathway-light/1742130V7

Let me know if i can be of any help (i have all the lights)

**Comment by JohanBendz** [comment]
@henrikrox Hi there, if you could add your devices as general zigbee units and copy/paste the device info for each item that would help a lot! (Device id/product id/etc)

**Comment by henrikrox** [comment]
@JohanBendz hi sorry for the late response, im on vacation atm, but the first thing i will do when i get back is to what you told me. 

Really impressed by the impress lights in the hue app (no pun intended).

**Comment by JohanBendz** [comment]
@henrikrox Friendly reminder :)

**Comment by henrikrox** [comment]
@JohanBendz sorry for late response, i had issues with two of my pedestals, and they are being replaced as we speak, should have them in the coming week. Will update here then.

It seems its severla product IDs when i spoke to Hue on the phone

Wall lamp: 
ID: 1743030P7 (the one i have)
ID: 1742930P7 (smaller version, same lumen/funcionality)

Bollard: 
ID: 1745430P7
ID: 1743430P7
ID: 1743130P7

These 3 bollards, are exacly the same, its just that one of them comes with a power cord. I asked Philips why theres two identical models, they didnt know why. 

There is also
1743230P7 which is the tall variant ( i dont have that, but lumen output is the same)

Anyways enough rambling, will update this week or next week

**Comment by henrikrox** [comment]
![IMG_4119](https://user-images.githubusercontent.com/6884716/58213432-63cfbf80-7cf2-11e9-8994-750123c473cc.jpg)
![IMG_4117](https://user-images.githubusercontent.com/6884716/58213434-6500ec80-7cf2-11e9-88a8-110710f110bd.jpg)

Here you are, one of them is the bollard, and one of them is the wall light

**Comment by henrikrox** [comment]
they both are the impress lights, the calla bollards i returned, i like the impress way more.

so this
https://www.amazon.co.uk/Philips-Ambiance-Impress-Lantern-Compatible/dp/B07KMG625T?th=1

and this
https://www2.meethue.com/en-gb/p/hue-white-and-colour-ambience-hue-outdoor-pedestal-light/1743130P7

**Comment by sebbebebbe** [comment]
Added to internal TODO-list

**Comment by henrikrox** [comment]
@sebbebebbe

Any progress on adding support here?

**Comment by sebbebebbe** [comment]
I haven´t had a look at it yet. I will eventually go through all requests.

**Comment by jaleks** [comment]
Any update? I just bought some impress and have no hue bridge. I guess I can’t add them before they are available in the app?

**Comment by HarryInia** [comment]
Now and then, I find my Philips Impress "OFF" or "ON" without recalling how this was triggered. 
In the activityreport I read that the lamp was switched  by the Philips Hue without the bridge app (see picture).  
<img width="368" alt="Screenshot 2024-10-31 at 20 55 10" src="https://github.com/user-attachments/assets/e065e85a-c420-4e2f-b5a7-310726efdc32">

What causes the Philips Hue without the bridge app to activate?
