### ISSUE TITLE
No homey app found while adding Hue spot GU10

### ISSUE THREAD

**Issue by ncickc** [sebbebebbe/com.philips.hue.zigbee#84]
I'm unable to add Philips HUE GU10 spots because of the message: 
'There is no homey app found for this device. The device is added as a simple Zigbee device.'

Tried both Hue apps / resetting / reinstalling but without luck. See below screenshot. 
Can you add support for this device please?

![Screenshot_20190401_154912_app homey](https://user-images.githubusercontent.com/29095341/55332857-78cc6700-5496-11e9-9f9a-5b4a79304ff9.jpg)

**Comment by JohanBendz** [comment]
@ncickc OK, that product ID is new for the product. We will have to add it to the device list.

**Comment by ncickc** [comment]
That would be great, thanks!

**Comment by JohanBendz** [comment]
https://github.com/sebbebebbe/com.philips.hue.zigbee/pull/87

**Comment by ncickc** [comment]
Any update or can you give a Timeline for this please?

**Comment by sebbebebbe** [comment]
I got a mail from Jasper with this aswell. What puzzles me is that the info in the screenshot above says "Zwave" and those will not be included in this app.

**Comment by ncickc** [comment]
This is indeed strange but it looks like a bug from homey where it says z-wave while I'm actually looking at the advanced device information of a Zigbee device. The same happens when I'm looking at the advanced device information of a Xioami motion sensor (also Zigbee). See also below:

![image](https://user-images.githubusercontent.com/29095341/63353082-7cd42500-c362-11e9-8fd2-e8210512c334.png)

Advanced device information of (correctly working) zigbee motion sensor:
![image](https://user-images.githubusercontent.com/29095341/63353144-97a69980-c362-11e9-827c-7809e1bb99c4.png)
