### ISSUE TITLE
Hue Fair Pendant

### ISSUE THREAD

**Issue by nicjans** [sebbebebbe/com.philips.hue.zigbee#86]
Hi! Please and support for hue fair pendant. 
:)

**Comment by JohanBendz** [comment]
Hi @nicjans, can you add it to Homey as a generic Zigbee device and get back to me with the unit info? If so I will add it in next release of the app.

The info I need;
Product ID: 
Device ID: 
Profile ID:

**Comment by nicjans** [comment]
The info I need;
Product ID:LTP003
Device ID:544
Profile ID:49246

**Comment by JohanBendz** [comment]
https://github.com/sebbebebbe/com.philips.hue.zigbee/pull/88

**Comment by Blacksmit82** [comment]
Not to push but any info on when it will be merged and released?

**Comment by sebbebebbe** [comment]
Sorry for the late answer, it has now been merged into dev and is ready for release. I do not have an ETA on the release yet.
