### ISSUE TITLE
Please add outdoor motion sensor support

### ISSUE THREAD

**Issue by imbaimbaimba** [sebbebebbe/com.philips.hue.zigbee#89]
Got an outdoor motion sensor for my outdoor light strip. Can you add support for it please?

**Comment by sebbebebbe** [comment]
I think @JohanBendz  already has added this. There will be an update coming shortly.

**Comment by imbaimbaimba** [comment]
Sounds great. Thank you.

**Comment by fjeldstad** [comment]
Any idea when 1.4.5 will be available? I’m eager to try out a couple of new outdoor lights and motion sensor...😬

**Comment by JohanBendz** [comment]
@Hihaj 1.4.5 is the beta version on the app store: https://apps.athom.com/app/com.philips.hue.zigbee

**Comment by sebbebebbe** [comment]
Since there has not been any issues with 1.4.5 I have now updated it to stable.
