### ISSUE TITLE
Color/dim cannot be set while bulbs are off

### ISSUE THREAD

**Issue by imbaimbaimba** [sebbebebbe/com.philips.hue.zigbee#90]
Alright so I am trying hard to get all my scenes etc set up in Homey, but I have trouble with handling lights. It seems that color/temperature and dim cannot be set while bulbs are off, which is very inconvenient. 

If I remember correctly, this was possible when using the Hue bridge, but I had to ditch it for this, to expand my zigbee mesh for various battery powered sensors etc. 

As far as I understand, setting a certain dim/tone is just a value being sent to the bulb which it should be able to remember? This would, I assume, also make it possible to add on-mode settings like the Hue app has to let it turn on at last settings, even if powered down.

Any possibilities to improve on this? :-)

**Comment by sebbebebbe** [comment]
Hi, we could eventually have a look at this but imo it should not be implemented in the app. I will consider it though.
