### ISSUE TITLE
LWW001: Hue Lucca Gartenleuchte is not recognized

### ISSUE THREAD

**Issue by Fred0022** [sebbebebbe/com.philips.hue.zigbee#91]
The lamp is only recognized as an unknown Zigbee device.
Data of the lamp
Hersteller-ID Philips
Produkt-ID LWW001
Geräte-ID 256
Profil-ID 49246

Request for implementation of this lamp in the Philips Hue Plugin. Many Thanks

**Comment by JohanBendz** [comment]
OK, thx @Fred0022. Unit added to list of things to add.

**Comment by sebbebebbe** [comment]
Will be included in next release
