### ISSUE TITLE
Support for Hue Discover Outdoor floodlight

### ISSUE THREAD

**Issue by fjeldstad** [sebbebebbe/com.philips.hue.zigbee#92]
The app currently does not recognize/support the Discover floodlight (https://www2.meethue.com/en-us/p/hue-white-and-color-ambiance-discover-outdoor-floodlight/1743530V7) - would be super nice if this was added.

**Comment by JohanBendz** [comment]
Thanks @Hihaj for your request.
Can you provide us with the following product information?
Product ID:
Device ID:
Profile ID:

**Comment by fjeldstad** [comment]
Product id: 1743530P7
Device id: 528
Profile id: 49246

Not sure what those mean but that’s what it says under ”advanced settings” for the generic Zigbee device it added.

**Comment by fjeldstad** [comment]
Anything else I can help with?

**Comment by sebbebebbe** [comment]
If you want to speed things up there are 2 things that can be done.
1. Find a fairly high resolution picture of the flood light with transparent background
2. Create or find an .svg or other vector-format icon for the device.

**Comment by fjeldstad** [comment]
If I’ve understood things correctly, Discover is physically identical to the Welcome floodlight that you’ve already got graphics for. So I think it would be reasonable to reuse those. (The difference between the products is that Welcome is white light only while Discover supports many colors.)

**Comment by sebbebebbe** [comment]
Ah perfect! I will add it to the top of the list.
