### ISSUE TITLE
Support Hue Econic light

### ISSUE THREAD

**Issue by steinter** [sebbebebbe/com.philips.hue.zigbee#93]
https://www2.meethue.com/en-us/p/hue-white-and-color-ambiance-econic-outdoor-wall-light/1743830V7

Product ID: 174383oP7
Device ID: 528
Profile ID: 49246

**Comment by JohanBendz** [comment]
Thanks @steinter for your request.
Added to our todo list.

**Comment by sebbebebbe** [comment]
Added to upcoming release

**Comment by JohanBendz** [comment]
@steinter Did you get this device to work in the app? I have reason to believe the Device ID and Profile ID you mentioned might be wrong for the device. Will fix asap if so.
