### ISSUE TITLE
Trying to add hue outdoor sensor - "no compatiable homey has been found, added as a basic zigbee device"

### ISSUE THREAD

**Issue by henrikrox** [sebbebebbe/com.philips.hue.zigbee#94]
Product ID: 1743430P7
Device ID: 528
Profile ID: 49246

Tried adding it within 1 cm in homey, pairing goes ok, but says no available apps

**Comment by 6zXo8aMn2TRXOs** [comment]
Guess it's your bollard that has been found. See https://github.com/sebbebebbe/com.philips.hue.zigbee/issues/83#issuecomment-493686334 (same product ID). Turn that off and re-pair the motion sensor and it should be found.

**Comment by henrikrox** [comment]
oh ye good point rindler, damn what a brainfart, i will try that

**Comment by henrikrox** [comment]
ye @rindlerblabla that worked, going to close it, thanks alot, cant believe i didnt thought of that, tried like for 2 hours :P
