### ISSUE TITLE
Hue outdoor - no new data

### ISSUE THREAD

**Issue by henrikrox** [sebbebebbe/com.philips.hue.zigbee#95]
Hi

So I have had the outdoor sensor connected for 2 days. Noticed yesterday it said 12+ hours since last update on movement and it was stuck on showing movement and then temperature was wrong by 10 degrees.

I deleted the device and reincluded it but same thing today, it works for the first hours then it never wakes up. Even if it’s movement or drop in temperature. 

![2F3DE44D-16FF-4F93-96EA-1878A3FA798C](https://user-images.githubusercontent.com/6884716/58371748-52fe9400-7f14-11e9-987b-bab05cafbe14.png)

**Comment by 6zXo8aMn2TRXOs** [comment]
Basically the same issue as #61. The app developer says the issue is in Homey core and Athom haven't done anything for a couple of months. Some users don't seem to have this issue, don't know why...

**Comment by henrikrox** [comment]
thanks again @rindlerblabla 

Ps; i need to learn how to search
Pps; sent a support ticket to athom about the issue asking for an update

**Comment by henrikrox** [comment]
just noticed that i started working again @rindlerblabla after homey daily restart (from flow) so i guess its pretty random
![IMG_4140](https://user-images.githubusercontent.com/6884716/58383190-ecd94600-7fd3-11e9-9986-8bb45f599dde.PNG)

**Comment by 6zXo8aMn2TRXOs** [comment]
@henrikrox Yes, and when updating Homey to a newer firmware you got values for some hours/days, but at least so far (since the major update to 2.0) you can be certain that the issue appears again, hehe.

**Comment by henrikrox** [comment]
A bit late of an update, but got a reply from Athom regarding this issue.

> The development team is aware of an issue in the Zigbee part of Homey which is causing this issue.
> 
> This issue will be resolved when the Zigbee part of Homey will be updated. Unfortunately I cannot give an exact date on when this update will be released.
> 
> Once the update is ready for release we will update our customers via our newsletter. If you are not subscribed to our newsletter I would like to suggest to do so. This way you will be notified when the update is available.
> 
> Sorry for the inconvenience!
> Best Regards,

Will close this issue, as there is already an open issue about it #61

**Comment by glupschis-home** [comment]
Thank you very much for this update.
How can I subscribe to your newsletter?


Von meinem iPhone gesendet

**Comment by wieooit** [comment]
I also have the same problem.
I don't use a hue bridge but connect directly to Homey.
And even a sensor next to my Homey looses its connection.
Please make it work again.

**Comment by sebbebebbe** [comment]
This is a known issue that Athom eventually/hopefully.
