### ISSUE TITLE
Please add conditions to sensor

### ISSUE THREAD

**Issue by mvanhelmont** [sebbebebbe/com.philips.hue.zigbee#96]
Please add conditions to sensor flow cards. So we can check light sensitive as a condition

Thanks

**Comment by 6zXo8aMn2TRXOs** [comment]
If I understand what you are searching for Homey has a built in function for that. Use the sensor value being changed as 'when' and Logic cards as 'and' condition. There you can choose a lux value below/above a certain value.

**Comment by mvanhelmont** [comment]
you right. totally overlooked

Thanks
