### ISSUE TITLE
Motion Sensor unstable / GU10 not recognized 

### ISSUE THREAD

**Issue by mypublicme** [sebbebebbe/com.philips.hue.zigbee#98]
Hi,

I also observe very unstable behavior of the Hue motion sensor. It stops working frequently...
I also have problems adding a normal Hue GU10 Spot. The app will only recognize it as an unknown zigbee device.

Are these issues you’re working on already.
Keep up the great work on this!!
Thx!

**Comment by mypublicme** [comment]
Motion Sensor: SML001
GU10 Spot: LWG001

**Comment by JohanBendz** [comment]
Hi @mypublicme, support for LWG001 is waiting for next release. #87

**Comment by 6zXo8aMn2TRXOs** [comment]
@mypublicme And regarding the motion sensor it's unfortunately a known issue in Homey core, see #61.

**Comment by sebbebebbe** [comment]
LWG001 has now been merged in to dev
