### ISSUE TITLE
Support for  LivingColors Aura

### ISSUE THREAD

**Issue by malmentm** [sebbebebbe/com.philips.hue.zigbee#99]
Can this be added?

**Comment by glupschis-home** [comment]
And also can added the Philips HUE Living Whites Plug? I have 8 of it. And I know some people have more of it.

**Comment by JohanBendz** [comment]
Hi @malmentm and @glupschis-home.
If you provide the information below we can add it to our todo list.
Product ID: 
Device ID: 
Profile ID:

**Comment by malmentm** [comment]
> Hi @malmentm and @glupschis-home.
> If you provide the information below we can add it to our todo list.
> Product ID:
> Device ID:
> Profile ID:

Where can i find it? Model is LLC014 for the Aura

**Comment by glupschis-home** [comment]
Hi malmentm,

I don*t know where i can find this informationens about the Philips HUE Living Whites Plug. Can you help me, please?

**Comment by malmentm** [comment]
@JohanBendz
Where can we find this information?

**Comment by JohanBendz** [comment]
@malmentm Hi there, if you have the device you can add it to Homey as a generic Zigbee device, if so you will then be able to find this information in the device's settings.

**Comment by malmentm** [comment]
@JohanBendz Here are the values for Living Colors Aura. 

Product ID: LLC014
Device ID: 512
Profile ID: 49246

**Comment by JohanBendz** [comment]
@malmentm Thanks, added to the to do list.

**Comment by sebbebebbe** [comment]
Will be included in next release
